[quote.epigraph, , Prov. 4:18]
____
The Path of the just is as a shining light that
shineth more and more unto the perfect day.
____

== Introduction.

"`The memory of the just is blessed,`" so we believe it is the duty of survivors
to gather up the fragments that remain that nothing be lost to future generations
that may be added to the cloud of witnesses of those whose dedicated lives and
exemplary conversation plainly shew that they were seeking a better inheritance,
"`a city which hath foundations, whose builder and maker is God;`" of whom it is written,
"`God is not ashamed to be called their God, for He hath prepared for them a city.`"

In this blessed number we have undoubted assurance that our beloved,
departed friend John G. Sargent may be included, and,
in undertaking a selection from his diary and correspondence,
it has been with no desire to magnify the creature,
being fully persuaded that by the grace of God he was what he was, and that,
by his remarkably watchful care to walk in strict obedience
and conformity to the heavenly gift,--the grace of God,
in all its manifestations,
both as related to his outward concerns and the growth of Divine life in his soul,
he became quick of understanding in the fear of the Lord, and, in no ordinary degree,
realized the preciousness of the promise to the pure in heart, "`They shall see God.`"
His great delight and care was to dwell in that pure and holy stillness,
that secret place of the Most High,
where an abiding under the shadow of the Almighty is known, and often would he testify,
in a precious sense of grateful adoration,
"`under whose shadow I have sat with great delight.`"

And now that he has, as we believe, been called from works to an everlasting reward,
our desire is to show forth his purity of life and conversation,
his deep and unabated love and dedication to the pure and unchangeable Truth,
and his unswerving labour to defend a cause so precious,
from the many deviations of our day.
That this tribute to his memory may be so blessed with the seal of Divine approbation,
as that it may carry home to many hearts the conviction, "`he being dead,
yet speaketh,`" is our earnest desire.

Our beloved friend was brought up and educated in the Society of Friends.
His parents removing to Paris when he was quite young,
the care and oversight of him during his school vacations
devolved very much on his paternal grandparents,
but more especially on one of his aunts, whose watchful and tender care over him,
he held in grateful remembrance through life,
esteeming it among the many blessings a kind and
ever-watchful Providence had bestowed upon him;
and it is believed, that the seed sown under her judicious care and counsel,
tended greatly to imbue his mind with a sense of
the superiority of living in the fear of the Lord,
to all earthly enjoyments and gratifications.

About the seventeenth year of his age he was apprenticed to a draper,
which engagement he appears to have filled with fidelity,
and to have gained the esteem of his master and mistress.
At the expiration of his apprenticeship he returned to Paris to his parents,
not liking the business he had learned in England.
He was for a short time employed in his father`'s business,
and afterwards on his own account;
he remained in Paris about nine years before he finally settled in England.
For a short period a change appears to have come over him,
and he became less inclined to the self-denying life
that appertains to our high and holy profession,
though, it is believed,
he never lost sight of that strict integrity that
was so conspicuous in his character in after life;
yet a somewhat downward course marked his career.

The dress was changed from that which betokened him as a Friend,
to that whereby he would only be known as a young man of the world, and,
as is always the case that one backward step makes way for another,
so we find the plain language was abandoned,
and the world`'s mode of speech and manners adopted,
some places of amusement were for a short time frequented,
and the Wesleyan chapel occasionally attended,
instead of the meeting at a room hired by Friends in England
for the use of those under our name in Paris.
But this course of life was but of short duration.
Infinite Goodness was pleased to follow him with the gentle
wooings and tender pleadings of heavenly love,
and under the precious influences thereof,
which enamoured his soul with a sense of Divine regard,
a desire was quickened in him to return again to
those pure testimonies which he had slighted,
and to which he ever afterwards adhered with faithful integrity and scrupulosity;
this was the greater cross, the motive being so little understood in France.
But at that period, and in after years,
he always found as care was observed to maintain
an appearance and deportment consistent therewith,
way was made for him, and that marvellously,
amongst those with whom he had to mingle in the way of business.

In returning again to the path of self-denial into which Truth ever leads its followers,
one of the first tests of his allegiance was to avoid the
salutation of raising the hat to persons in the street,
so much practised as a mark of worldly honour;
this was soon followed by an intimation not to append
the word "`Saint`" to the names of the streets;
and thus, in a city so marked for its frivolity and superstition,
with no one to look to for counsel or example,
as he gave up to be led along step by step,
hearkening unto and obeying that heavenly voice, which teaches as never man taught,
he became increasingly sensible of the preciousness of walking
by that Divine law which giveth understanding unto the simple,
and his conduct and appearance were brought more and more into harmony with the
purity which he had embraced as an humble follower of the meek and lowly Jesus,
whose doctrine it was his earnest desire to adorn in all things, and on all occasions.

It does not appear that he was long in the practice of frequenting the Wesleyan chapel,
but that he became a regular and diligent attender of the little meeting in Paris, where,
in consequence of their number being so small,
an influential English Friend whilst in Paris on a religious visit,
had encouraged the reading of a portion of Scripture,
and our dear friend was appointed the reader.
But this practice soon became a burden to his awakened mind,
and he has been heard to say,
that it not only unsettled and unfitted him for the
great object for which they had assembled,
the solemn purpose of worshipping the Almighty, in spirit and in truth,
but that he had not the same comfort in reading the Scriptures thus publicly,
that he had in a more private way.
This appears to have been about the year 1838,
and he ever afterwards maintained a steadfast testimony against
this departure from our fundamental principle of meeting together
for the solemn purpose of waiting upon the Lord,
the basis of true worship,
and was deeply grieved in later times at the letting fall of our
testimony to the spirituality of the Gospel (in this and other
innovations,) having proved for himself that reading is not worship.

Our dear friend continued to reside in Paris,
and carry on business there until about the year 1844, when,
after passing through many deep exercises and provings,
wherein his faithfulness was closely tested, He who had wrought marvellously for him,
was pleased to open a way for him to leave Paris and settle amongst Friends in England;
a privilege he greatly longed for and embraced with much thankfulness.
Deeply instructive was the very watchful care he manifested in his outward concerns,
to be faithful to the doctrine of his profession;
and truly it may be said that he realized the language,
"`the righteous shall hold on his way and he that
hath clean hands shall grow stronger and stronger.`"
Many were the sacrifices which he was called upon to make in such matters,
of which it may be well to mention, his feeling it required to decline,
in the line of his business, working for cotton mills,
when slave-grown produce was so largely used therein, and, consequently,
being compelled to go to mills at a greater distance where other material was used;
nor could he at any time feel easy to work for mills mainly
engaged in the manufacture of lace or other superfluities.

He had not been long in this country before his mind became bowed
down with a sense of the very sorrowful departures in "`doctrine,
practice and discipline,`" which he saw so rapidly gaining ground amongst us, and,
according to the measure bestowed,
he endeavoured to lift up his voice against the various innovations imposed upon a people,
who had been so preeminently raised up to show forth
the purity and spirituality of the Gospel dispensation.
Deeply did he feel this falling away, and,
after finding that the pleading and exercise of a tribulated remnant could prevail nothing,
he, with a few others like-minded,
believed the time was come to shake themselves from the
dust and loose themselves from the bands of their captivity.
He who had been pleased to show them the abomination of desolation,
condescended to fulfill his gracious promise, "`for the oppression of the poor,
for the sighing of the needy, now will I arise, saith the Lord,`" and to lead along,
step by step,
until a small company was gathered under a united concern for the
maintenance of the Christian principles and practices of our Society,
to the rejoicing of the heart of our dear exercised friend,
and the few others who were united with him in exercise and travail of
soul for the upholding of that pure Gospel dispensation which is unchangeable;
and from which so many in religious profession with us,
had been fast turning to the weak and beggarly elements,
which the Society had been raised up to bear an unmixed testimony against.
These Friends were constrained in the love of the Truth to cease to acknowledge London
Yearly Meeting and its subordinate meetings as representing the Society of Friends,
in consequence of its continued and increasing departures
from its original and the only true Foundation of the Church,
even the pure openings and leadings of the Spirit of Truth in the heart of man, and,
in obedience to apprehended duty,
for their own safety to withdraw from under the influence and control of that body.

Wherefore,
when the call was heard to come out and be separate and touch not the unclean thing,
ability was given to obey, and our dear friend in the integrity of his heart,
was among the foremost to encourage and strengthen
his friends to perseverance in this good work,
in full yet humble reliance on the promise, "`the God of heaven, He will prosper us;
therefore we, his servants will arise and build.`"
And although many and deep were the discouragements,
and great the opposition they met with, yet He who has ever been mindful of his covenant,
did graciously, from time to time manifest that He, the unslumbering Shepherd of Israel,
was near to strengthen for the work whereunto He was pleased to call,
and did not fail nor forsake them in the day of trouble.
And when it pleased Him to say "`it is enough,`" and to gather
this meek and humble follower unto his never-ending rest,
all was joy, peace, and praise, no fear,
and no doubt as to the rectitude of the course taken,
but manifesting to the great consolation of his survivors,
that he realized that blessed assurance, "`I have fought a good fight,
I have finished my course, I have kept the faith:
henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, shall give me at that day: and not to me only,
but to all them also that love his appearing.`"

In thus bringing into public view the character of
this faithful servant of the Most High,
the compilers can testify that it was not in a spirit of contention
that he withdrew from those who had wrought such sorrowful changes;
for he was not one inclined to controversy,
but it was in pure obedience to the law of the Lord,
and in a zealous care to keep in mind that whereto he had "`already
attained,`" and so closely to watch as that he might at all times
"`walk by the same rule and mind the same thing`";
and thus following the cloud by day, and the pillar of fire by night,
his spiritual understanding was more and more quickened,
his soul grieved at what he was given to discern,
and he made willing "`earnestly to contend for the faith once delivered to the saints.`"
Closely were his feelings proved and tried in thus coming away from some
whom he had looked up to and honoured for the work`'s sake.

But he knew the Voice that called must be obeyed,
having long known that obedience is better than sacrifice,
and that the God whom he served would not accept any offering
but that of perfect resignation to his pure and holy will.
And those on whom the responsibility of this work has devolved,
believe that it has been done under a sense of apprehended duty,
accompanied with sincere and earnest desires that
its tendency may be to open the eyes more fully,
of those who yet remain uneasy in that lapsed body,
to the necessity to come out and be separate,
if we would bear a clear and unflinching testimony in our generation for the Truth,
remembering how great is our responsibility in professing to be the followers of those
to whom the light of the knowledge of the glory of God was so graciously revealed;
but, alas, how are the mighty fallen, and the weapons of war perished!
Yea, may we not say, the Yearly Meeting has changed the doctrine,
laid waste the discipline and trampled upon the testimonies
given us as a distinct people to bear?
And the few who are left may be compared to a "`cottage in a vineyard,
a lodge in a garden of cucumbers, and as a besieged city.`"
