== Chapter VI.

[.chapter-synopsis]
* Letters to J. P. Crisp
* A. Evertsen
* E. Bell and Family
* One of his Sons
* W. Waring
* His Wife
* E. Watkins
* S. D. Otis
* Visit to Ackworth Meeting
* Continuation of Diary
* Accompanies W+++.+++ C. and L. D. Meader on a Religious Visit to Norway and the Vaudois Valleys.

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. Crisp.

[.signed-section-context-open]
Fritchley, 9th of 5th Month, 1878.

[.salutation]
My Dear Friend,

I have thy two letters, and intended replying to the first without delay:
it felt cordial and acceptable.
As thou remarks, sympathy and fellowship amongst brethren is sweet;--so it is,
and the more we are brought under trial, the more we value it.
Thy allusion to thy stay in London and not feeling any drawing to attend a meeting there,
tells in the direction of a testimony, a strong testimony;
but how sad a state of things this does delineate, and it is so,
that there can only be satisfaction in this respect (as
well as in many others) in being in the way of our duty,
if we do attend the meetings at all,
of the modern Friends (or such as have left Friends).
We were favoured in our meetings held here last week.
The Master condescends to be with us.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Anders Evertsen.

[.signed-section-context-open]
Fritchley, 11th of 5th Month, 1878.

[.salutation]
My Dear Friend,

It seems with me to send thee a few lines expressive of my sympathy with thee and thy
dear wife in your solitary situation as to companions in the fellowship of the Gospel.
To have friends with whom we have unity, and feel nearness in the Truth,
is a privilege of no common sort, and when this is not the case,
and our dear friends are widely separated from us, it is, nevertheless,
a favour when we can know that they think one upon another in the fear of the Lord.
This we, some of us, can do with you,
and we desire your strengthening and encouragement to press
onward in faithful dedication of heart and soul,
unto Him who hath called you to serve Him, in humility of mind and abasedness of spirit,
as our fathers in the pure Truth have done, to his praise and their own true peace.
Do not, my dear friends, be discouraged;
for may we not believe that you are set for a testimony by his (the Master`'s) holy hand,
where you are,
against unsoundness which exists and makes its way amongst a highly professing people.
Keep, then, on your armour wherewith He hath girded you, and stand for the Lord,
whose the battle is, and He is victorious, forever blessed be his holy Name--his power,
which is invincible.

With a salutation of endeared love to you both,
of whom we shall like to hear when way opens in your minds to write,

[.signed-section-closing]
I remain thy and your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Edward Bell And Family.

[.signed-section-closing]
Fritchley, 13th of 10th Month, 1878.

[.salutation]
My Dear Friends,

Since being with you and breaking bread with you in more ways than one,
my heart has saluted you in a measure, I believe I may say, of Gospel love.
It did feel very pleasant to me to be with you for a little season,
and very grateful to my feelings it was to receive such
cordial tokens of your friendship under your roof,
as were extended to me from the time I entered your door, till I left you,
myself to journey on in the way of my business, and you to be diligent to labour,
to gather in the fruits of the season from the field.

I trust our hearts have since that time felt grateful to the Giver of all good,
in acknowledgment that He is supremely good,
and that it is his right to rule in and for us, and to govern the least,
and from the least to the greatest, of his children,--to rule in each one of us.
And how shall we praise Him in this way but by obedience, each one of us,
to the smallest manifestation of his holy Spirit in and upon our minds.
This, if given up unto, will make us, even the least amongst us,
quick or swift to hear his voice and heartily to obey.

I do believe the more we grow in the Truth, the smaller we think ourselves, yea,
so small do we feel, and so despised too, by that which is contrary thereto,
and let none be discouraged in the feeling of their low estate,
even that they are "`poor in Manasseh and least in their fathers`' house.`"
Let such dwell in this safe retreat and be content with their lot,
in their feeling of littleness; for assuredly there is safety and peace,
though at times great poverty, therein.
Poverty is the best clothing for us sometimes,
and there is One who knows what is best for us,
though outwardly we be trodden down as the mire of the street,
and though we be accounted fools by most, and not only by the world`'s people,
but it may be more so by our own people, and religious professors.

Therefore it feels to me there is encouragement for such;
for the good thing grows best where there is something to keep it alive,
and after much harrowing and stirring of the soil:
and the Master is pleased to honour that which has
gone through the process and undergone much.
Therefore, let none despise the chastening of the Lord,
in whatever way he sees meet to try them, but put on the whole armour,
which is invincible tinder the greatest provings as well as in the smaller trials.
Let us go forward in faith and hope, and be very faithful;
this is the way to grow and the sure way to obtain a crown at last.
I have written in love, and feel that I can, and do greet you in the same, and remain,

[.signed-section-closing]
Your sincerely affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. Crisp.

[.signed-section-context-open]
4th of 1st Month, 1879.

[.salutation]
My Dear Friend,

I do feel brought into sympathy with thee in thy seemingly lonely position,
in one after the other of the Friends being removed,
to the privation of thy holding converse with them; this we may say as to the outward,
but let us remember that there is a place of communion,
a place of refuge above all privations, the secret place of the most High.
O what a privilege it is,
to be of the number of those who are so secreted as to desire a continuance there.
This state to enjoy I believe to be a foretaste of the heavenly city, the new Jerusalem.
Let us keep our eye steadfast thereupon; but not forgetting that seasons there must be,
whilst in these earthly tabernacles,
when it is also good for us to know the withdrawal or the
hiding for a time of the Sun of righteousness from us.
Then, let us have faith; then, let us put our trust in Him, our spiritual Moses,
and be patient and still in our minds; for assuredly,
He will return and we shall again rejoice in Him.

I believe thou wilt see for thyself, by that Light which is sufficient for any us,
the way wherein thou art to walk, so as to meet the approval of Him,
whose time is the best time, and the right time to move,
for the upholding of the standard of Truth on the earth, and mayst thou, my dear friend,
be found faithful in thy lot, though it be to forsake all, even those if it must be so,
whom thou lovest and holdest dear in the Truth.
But we must each one of us serve the Lord in his way, not choosing for ourselves the way,
any more than the place, where we shall offer upon his holy altar the sacrifices.
He is pleased to call for,
from those who truly fear Him and are concerned to obey every dictate of his holy will.

[.signed-section-closing]
Thy friend,

[.signed-section-signature]
John G. Sargent.

--

1879+++.+++ 5th Month 2nd.--Jesse Darbyshire and Elizabeth Kelsall were married today,
at an appointed meeting at Fritchley.
A highly favoured season.
Heavenly good greatly manifested unto us in the precious
sense of his overshadowing and heavenly presence.
Blessed be his holy Name, He richly rewarded us in our meeting together,
and evidenced to us that He was indeed with us on this solemn occasion;
a day ever I trust to be remembered,
and holy help was vouchsafed to the Lord`'s unworthy servant,
enabling to testify for Him in a sense of the greatness
of his help and the strength afforded;
bless the Lord O my soul, and forget not all his benefits.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Gand, 11th of 5th Month, 1879.

[.salutation]
My Dear+++_______+++,

How has my heart yearned over thee since we met and since we parted +++[+++in London.]
My very soul does long that thou mayst be favoured to know and
distinguish whose is the living child and whose is the dead one,
that thou mayst have the true wisdom which our gracious Lord endues his obedient
children with--those whose delight it is to serve Him day and night faithfully,
even as Solomon did when he asked for wisdom before riches and honour, or anything else.
But this heavenly wisdom I allude to and desire for thee, cometh only from God,
as His gift, it is not attained to by ourselves, only as respects asking for it,
which will never be done aright whilst we are judging by our own outward observations--by
deciding which is the way we are to choose by outward observations of results,
whether these be tribulations and afflictions, or apparent decrease of our numbers,
those who are seeking to serve the God of our fathers
in the way that He shall choose for us,
not in the way that we shall choose for ourselves,
for this way doth never prosper as to the inward growth, or deepening in true religion.

No, my dear+++_______+++, the heart must be given up to serve the Lord;
and for this end there is no other way than by waiting upon
our God to know the way in which He would have us to go:
therefore do not, neither thou or thy dear+++_______+++,
be pondering in your hearts that this or that cannot be
the way of the Lord`'s chosen ones because of their numbers,
their afflictions, and because that some things are not even as they should be;
but endeavour to lay hold of this--that there are many hard
things to endure by the soldier of Jesus Christ,
and hardness must be endured unto the end, and for want thereof,
many have turned into another way,
than that designed for them by the holy Head of the Church.

Neither is it for any of us to decide that because of some differences in judgment,
some weaknesses remaining, or not as yet come out of,
that therefore such are not servants of the Most High God,
and that such have not been called to walk in this way or that way,
that they have taken at the starting point.
No, I believe it is an error to judge.
We are all called to be disciples of Christ--learners in his school.
And have we not all of us something yet to learn?
And who art thou, O man, that judgest?
Let every man be true to his own Master,
and let him serve Him faithfully in all that his Master requires of him;
but let all be very careful how they judge those who are standing for their God;
and rather let us desire to be judged only of Him, not even judging our own selves:
to our own Master, we must each of us, stand or fall.

Therefore, my dear+++_______+++,
do not look outward and judge by outwardly apparent results or effects,
for in this manner the world judges, and in thus doing how many are mistaken!
But judge ye with the judgment that the Lord gives, and only judge when He judges,
not of yourselves, as regards our deeply tribulated little company, (read the 21st chap.
Job, there is much in it) whose sole desire and intent
is to follow the Lord whithersoever He leadeth,
and to be true testimony-bearers in the way that He shall choose for us, yes,
of those precious testimonies He has delivered to
us to maintain for our own souls`' sakes,
for his Truth`'s sake; and for his Name, which is above every other name, upon the earth!
Therefore, fear Him, and tread softly all the way you go;
knowing that you may greatly err by condemning those who fear the Lord,
and stand for the ancient Testimony.

But we would not go into that which our Master does not lay upon
us--therefore beware how you take up with anything that you have
not seen in the silence of all flesh to be of the Lord.
I believe the Lord will always have true testimony-bearers left, though they be few;
but to go back to times past and take up by imitation a conformity to some outward things
which have not been adopted by the living testimony-bearers within our remembrance,
does seem to me to want the Master`'s requiring and seal upon them.
Let us keep fast hold of that which we have learned: let it not go;
this is the way to know more, and have more committed to us.

I have thought of you in connection with your contemplated move,
and view it as a serious step to take.--But the Lord is sufficient for all these things,
and will be the Leader of his people if they will follow Him in all things:
therefore look for the true leading,--the true signal for moving,--the cloud,
if you can observe it, must be lifted up by day,
and the pillar of fire by night if you journey forward
in the path the Lord would have you to take,
but beware of beholding a similitude of those things,
according to your own natural eye and understanding which, I do fear my dear+++_______+++,
has taken hold of you in no small degree.

I want to know how you now feel and what you are looking to,
for I do feel truly interested as thy father, and I trust,
in my measure also as one that the Lord has given some understanding
of the heavenly way-marks--the way of the kingdom,
in the way whereof there is true everlasting peace, and joy in the Holy Ghost.

With earnest desires for you both that you may be guided in the right way.

[.signed-section-closing]
I remain thy affectionate father,

[.signed-section-closing]
In dear love,

[.signed-section-signature]
John G. Sargent.

--

6th Month.--How precious it is to feel and know the merciful
lovingkindness of our heavenly Father extended to us.
In a feeling desire, whilst very unwell in the night, I asked of the Lord that,
if consistent with his holy will,
He would help me through this trying time of bodily suffering,
upon which the query seemed put to me, and what if it is not?
The words as quickly ran through my mind, "`Let me die the death of the righteous,
and let my latter end be like his.`"

7th Month 30th.--My 66th anniversary.
Awoke somewhat early and thought thereon.
Read after breakfast in course the thirteenth chapter of the Epistle to the Romans.
The Divine hand has I feel been with me, enabling me to give Him the praise,
which does in very deed belong unto Him; how much I have to be thankful for!
The day closed peacefully and thankfully in a sense
that the wing of mercy and love was spread over me.

8th Month 30th.--Left home for Harrowgate accompanied by my dear wife and Thos.
Davidson on a little visit, as I apprehended in Gospel love,
to hold a meeting with some young men, of Harrowgate, and Leeds.

31st.--First-day.
We met at G. W.`'s,
and were much favoured together under a feeling of
the heavenly wing being spread over us,
the Master`'s presence in our midst, to which sense I had to testify,
verifying the promise, "`Where two or three are met together in my name,
there am I in the midst of them;`" our meeting closed under a peaceful
and I trust grateful feeling that the Lord had been with us of a truth.
In our evening meeting I was favoured with ability to wrestle for the blessing,
and to hand out, to those with me something that I had received,
alluding to the little captive maid and her master for whom her desire was,
that he would go to the prophet and that he would heal him of his leprosy,--that we
must submit to the means prescribed however weak and incapable they may appear to us,
for our spiritual healing of whatever sort the malady may be.
The day closed in peaceful quiet and I trust thankfulness to the
Giver of all that is good for his gracious help so far,
on this little journey and visit of love.
Lodged again in Harrowgate.

9th Month 1st.--Left Harrowgate for Knaresboro`' and called upon W. and S. A. Needham,
thence to Wakefield, and were very kindly received by James Briggs and wife.
Before partaking of their hospitality, I was reminded,
that "`better is a dinner of herbs where love is,
than a stalled ox and hatred therewith,`" and gave expression thereto,
adding that our friends had provided more than this for us,
in their feeling of love towards us; after dinner before leaving the table,
had again to express what was with me.
We then returned home.

9th Month 17th.--Rose somewhat depressed,--why is it?
Shall I not, as well as others have done, pass through the sea of conflict and proving?
for this is not the place of rest for the Christian traveller Zionward.
We must look for help, if we would be helped,
to Him who alone can help the tribulated soul.

10th Month 23rd.--Our dear daughter C. D. S. was married in a solemn assembly at Fritchley,
to George Smith of Belper.
It was a highly favoured meeting; may it be remembered with thankfulness and trust by us,
and may they be blessed of the Lord through their pilgrimage here.

1880+++.+++ 1st Month 10th.--My dear wife and self left home today
for Ackworth to attend that meeting on the morrow,
my mind having felt drawn in Gospel love towards the children of the school.

11th.--Went to meeting at ten o`'clock; James Briggs of Wakefield first stood.
It felt to be a time of favour almost from the first of our sitting down,
evidencing that our holy Redeemer was with us.
I afterwards rose and felt helped to unburden my mind towards the dear young people;
after a time of silence I felt a pressure on my spirit to rise again,
and expressed a little.
Came away relieved, though I met with some opposition.
Left for home the next morning and reached it peacefully.

19th.--Left home on my business journey, going as far as King`'s Heath,
and was made truly welcome by our dear friends, W. C. and C. M`'Cheane.

20th.--First-day.
After breakfast and reading,
felt something to arise for communication and relieved my mind.
J+++.+++ H. D. and W. D. were present with us.
Attended the little meeting here this forenoon (seven of us there), a laborious time,
but was favoured with help late on and stood with the words, Labour not to be rich,
labour not (with our whole energies) for the bread which perisheth,
but labour rather for that bread and that water which endureth
and nourisheth up the soul unto everlasting life.
Wherefore doth the way of the wicked prosper?
It is that they shall be destroyed forever.
David knew not this till he went into the sanctuary, then understood he their end.

We must follow the Captain of our salvation, Jesus Christ our Lord and Saviour.
"`Fear not, little flock,
it is your Father`'s good pleasure to give you the kingdom;`" they,
the disciples of Christ were few, and they are few now, for "`wide is the gate,
and broad is the way, that leadeth to destruction, and many there be which go in thereat:
because strait is the gate, and narrow is the way, which leadeth unto life,
and few there be that find it,`" encouraging to go down into the valley of humility,
not to soar above into the tree of outward knowledge.
I was helped through this journey and favoured to reach
home with peace and I trust thankfulness of heart to Him,
who loadeth me with benefits.

5th Month 2nd.--In the afternoon meeting, stood with the words,
There is a silence comparable unto death, there is also a silence in which there is Life.
"`Be still and know that I am God.`"
In order to know God and commune with Him we must be still
in ourselves and feel that we are nothing and can do nothing,
but that as when He was with the disciples He said to the outward elements,
"`'` Peace be still,`' and there was a great calm,`" so now, He can still all within us,
but we must cooperate with Him and strive to get into the quiet,
ceasing from our own thoughts and imaginations by the help of the Divine power,
which can do all things for us.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Waring.

[.signed-section-context-open]
Fritchley, 16th of 6th Month, 1879.

[.salutation]
Dear Friend,

It is good I believe for us to bear one another in our remembrance,
and to communicate as ability may be given, even though we feel ourselves to be poor,
as to any store of that which is good;
but sometimes the mind being open to receive on our part,
strength may be given to do a good part,
all in the ability which our Heavenly Father bestows, often unexpectedly,
as well as undeservedly.
Thou alludes to the removal of our two dear friends W. H. and C. B. C.;
that though "`their vacancies were felt,
yet a solemnity prevailed quite equal to former occasions.`"
What a favour this condescension of our Heavenly Father feels to be,
who is graciously willing to make up to us all deficiencies; yea,
to do more for us than we can either ask or think.
If we know our own unworthiness, this must be the case,
(more than we can either ask or think.)

Is it not for the strengthening of those that remain?
Whereas we might well think that having lost that
which we could not of ourselves fill up,
there would be a void, or that wanting, so necessary for us.
It reminds me of the oil that was not stayed, until every vessel was filled;
it continued flowing until there was no other vessel to receive it.
It seems to me as though the language thereby spoken to us is, look not to numbers,
but to the strength of Him which is exhaustless:
this is the way for us to become strong in his Name and joyful in praise,
for that his mercies are forever and ever.

Thy feeling remarks respecting our dear family are very cordial to us.
We do indeed desire that the Shepherd of Israel may be mercifully pleased
to strive with them till they be brought in by his Almighty Power,
where they may feed in safety and peace,
and be daily receivers of that food which is convenient for them,
though in the cross to the natural part in them.
This must indeed be the experience, unto the mortification and subjection of the will,
if there be witnessed that true peace which is not
withheld from the Lord`'s dependent ones.

Thou wilt I believe,
be glad to know that some of us do feel encouraged in a sense of our heavenly Father`'s
goodness in granting us renewed ability to look upwards in hope and in believing trust,
that his favourable regard is unto us, in our weakness:
and a hope does at times arise in some degree of faith that He has a work for us to do,
whereby He will be glorified,
and whereby others will come and worship and be encouraged
also to enlist under the same Banner.
You also, we may trust, do feel and know the Rock which followed Israel of old,
to be your strength, in an increase, which is more unto those that love the Lord,
than the increase of corn, wine or oil, is to the natural man.
May we, my dear friend, be all of us encouraged (younger and older) to hold on our way,
in the Lamb`'s army, going forth conquering and to conquer in his Name, having on,
as we must do, if in his Name,
the invincible armour through which none of the enemy`'s
darts can penetrate to the hurt of his people.

In a measure, I believe, of that love which belongs to those who fear the Lord,
and is from the same God and Father of us all,
and by and through our Saviour Jesus Christ, do I salute thee as an elder brother,
and remain with love,

[.signed-section-closing]
Thy friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Dunkirk, 18th of 9th Month, 1879.

I cannot say that I feel to stand on high ground in anything.
An abiding in the valley and the remembrance in retrospect,
as well as passing along at the present time seems to show
the ruggedness of the road through life at times:
yet there are times, are there not?
when that which is beyond earth`'s concerns and cares lights
up the way a little for the help of the traveller Zionward;
were it not for this what should we do!
I have had my mind turned upon our position,
ourselves and family and our little company too:
and desires seem raised for the health of all,
that we may all be living to the praise of Him, who created man upright in the beginning;
and to all of us, in returning to that uprightness, through grace,
there will still be the forbidden thing to watch against and be preserved from,
whatever that may be;
or there will be to these a return into the transgression or transgressing nature,
into which all have fallen, or partaken of, through the sin of our first parents.
How vain and empty all things below seem to be! and yet grace beautifies
and changes as it were the element we live in;
but no doubt we are too careful or full of care: this I apprehend is my own case.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Courtrai, 26th of 9th Month, 1879.

With regard to +++_______+++`'s, offering, it will or may be seen undoubtedly,
what ground it springs from as time passes on, if he continues,
and "`two cannot walk together,`" (in this sense) "`except they be agreed.`"
His daily life and wherein is his dwelling, will bear witness for, or against;
if his abiding is in the outward, or if he has not got to that which is within the veil,
his offering, if he offers anything, will partake thereof also,
for the things of God knoweth no man, but the Spirit of God;
and the Spirit testifieth of its own, or beareth witness,
to that which is of itself in man, and he walketh answerably thereto.
This is speaking of things as they are in the main, though we do know indeed,
that "`the spirit is willing but the flesh is weak,`" and how often
has poor man to witness within himself that he cannot stand but
by faith in that which he has some knowledge of,
and that there is again and again something for him to learn,
and often the same lesson to learn over again!

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Anders And Sikke Evertsen.

[.signed-section-context-open]
Fritchley, 17th of 10th Month, 1879.

[.salutation]
My Dear Friends,

You are, dear friends, borne in remembrance by us and we desire to be remembered by you.
Were it not for the great space between us, of the watery deep,
I believe we would some of us make the effort to face it and come and see you.
We can readily understand the effort it must be to you when
health is not as it has been wont to be in times past.
How we, some of us, seem to be nearing the Port from which there will be no coming back!
May it be to you both and to such here, when called to give up our stewardship,
a happy release from time and time`'s trials,
to a happy eternity,--and of this we may be assured, if we be ready!
And does it not seem as if this being ready depends upon our being on the Watch,
the remaining days of our pilgrimage?
for I apprehend in order to be ready in that day, we have to endure,
(those who are of the blessed of the Lord and who
hold communion with Him now) unto the end!

Let us then be of good courage; and we are exhorted thereunto,
still fighting the good fight of faith, that we may receive the Crown which is laid up,
as an Apostle said, for all those who love His appearing: these are the blessed ones,
those who love His appearing; holding communion with Him;
"`sitting under his Shadow with great delight;`" feeding
on the Bread of Life which is the flesh of the Son of God;
and who drink his blood which satisfieth the longing soul,
and nourisheth it up unto everlasting Life.

Are we not assured of this, and do we not at seasons feel the force and truth thereof?
Then let us hold up the head, and drink of the everlasting Brook by the way.
Let us not be unduly and unprofitably cast down in our minds,
for that He that shall come, will come and will not tarry (only the appointed time),
and His time, my dear friends, is the best time,
though the desire of our hearts at times is,
that He would not be "`as a wayfaring man`" only, but that He would,
(as when He is pleased to make Himself known to us,
and as He is wont to do,) be with us always.

Be strong then, dear friends, and of good courage,
and when called upon to face the enemy, trust in the Lord Jehovah,
for in Him there is everlasting strength, (as we read,
do we not?) And our trust is exemplified by our faithfulness--being
faithful to Him in the gloomy night season,
as well as when the Sun of righteousness shines upon our heads, and upon our path;
and He does shine though there are seasons when we know it not,
even in the night as well as in the day, for with Him and in heavenly places,
though it be a dark season with us, there is no night at all.

You are, I do believe, appointed to be as the salt of the earth where you are sojourning,
even in a dark place of the earth, the Lord`'s earth;
and the earth is the Lord`'s and the fulness thereof.
O let us remember this,--and if we are the Lord`'s,
let us strive more and more to be his truly, his dedicated children,
doing that which he gives us to do, even in our own vineyards,
(for they must he kept) as also, if He willeth, in those of others.

I have written you a long letter though when I took the pen I seemed to have nothing,
You will I believe understand, at least, thereby, my love is towards you,
in that which is deeper than words only,
and I remain in sincere desire for your peace and welfare every way,

[.signed-section-closing]
Affectionately your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 21st of 10th Month, 1879.

[.salutation]
My Dear+++_______+++,

I was interested in reading how thou art engaged,
but I do not feel comfortable with the manner thou spends thy First-days,
no time (that I understand) given to worship by "`sitting alone and keeping silence.`"
How glad we should be to know of thy performing the solemn act of the worship
which is "`in spirit and in truth,`" and may be done in +++[+++every place]
and needs not the intervention of other men, it being an individual act,
and duty of man towards his Creator.
If thou wast to make it a rule to sit down in thy room, if for only half-an-hour,
and wait upon God, how it would rejoice our hearts,
and if done in a lively exercise and seeking state, wrestling for the blessing,
how thou wouldst (I believe and have no doubt) be truly blessed in thy inner man,
and grow in that which is good, whereas,
if our time is only given to worldly things and to ourselves,
there is no sowing to the spirit and reaping the everlasting life.

This, my dear son, is a solemn consideration, and should not be deferred to a future time.
How many are cut down in an unexpected moment,
and then where are they as pertains to that which never dies?
I think of thee as engaged in a way wherein something might happen to thee at
any time of a disastrous nature and even deprive thee of thy existence bodily.
Do think of this seriously.
Wait upon God, the God of thy fathers, and He will be thy rich reward,
giving thee that peace nothing in this world can give.

[.signed-section-closing]
With dear love, thy affectionate father,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

+++[+++The following Letter was addressed
to a little company of young men who were under discouragement.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fritchley, 1st of 1st Month, 1880.

[.salutation]
Dear Young Men,

Who are accustomed to draw together to wait upon God,
and to feel after his holy presence in your midst,
do not be turned aside by any false cries of Lo here, or Lo there,
is Christ! but continue your steadfastness and hearken
unto Him who hath called you by his own holy Spirit,
and not unto the reasonings of man or of men, whosoever they may be;
for the green pastures of Life where his sheep do feed are where
the Lord on high calls you and will lead you more and more into,
if you will be faithful, hearkening unto the voice of his Word within you, which will,
as you obey and follow Him, be a lamp unto your feet and a light unto your path,
as of old He has been unto his people of every generation.

Follow Him, and have you not heard Him saying unto you, "`This is the way,
walk ye in it?`"
O! do be faithful,
for by this your faithfulness and steadfastness unto Him is the alone sure way,
the way of everlasting life, whereunto ye are called.
In every age there have been temptations and tempters too,
which have been for the proving of the Lord`'s dedicated children.
O! let us be very watchful also, and not clothe ourselves in the armour of any,
though ever so valiant they may have been,
for many valiants have turned aside for want of keeping close with Him their Saviour,
who has brought them out of darkness into his marvellous light;
but that spiritual armour wherewith He has clothed
us and which we have tried as little David did,
let us go forth in, and still have faith,
and though Goliaths there may be in our day also,
yet if we use those weapons only the Lord entrusteth us with,
in humility and fear of departing from Him, we shall prevail.
In much nearness and true disinterested love for those who are convinced of the Truth,

I am your longing friend for your safe walking and true peace,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. W.

[.signed-section-context-open]
Lille, 29th of 1st Month, 1880.

[.salutation]
Dear Edward,

So J. F. is no more!
It brings thoughtfulness so many moving off the scene,
of about (a little younger or older) the age of some of us.
What a favour it feels,
to be enabled somewhat to realize the opening of the door
to the "`knock`" and the receiving the royal Guest,
and his supping with us, and we with Him; ever so small a measure of this,
in the reality of experience,
how good it is,--more than poor finite creatures can of themselves look for!
But it is true and the promise is yea and amen forever.
How few, we are to suppose, open to the knock; the many things,
lawful things absorbing the mind;
but the watch must be maintained if we would know these things;
and what a fund of experimental knowledge there is to come
at if we are willing and obedient to the learning,
and duly valuing the one thing needful; the one thing at a time; the measure dispensed;
but in this I expect, we often come short,
and do not dwell enough on what we have in possession

[.signed-section-closing]
Will now conclude, with love, thy friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel D. Otis.

[.signed-section-context-open]
Fritchley, 4th of 3rd Month, 1880.

[.salutation]
My Dear Friend,

It is pleasant to hear from our friends and to know how they and their`'s are situated,
thy family amongst the rest.
What a testimony for the Truth and to Truth`'s leadings, may be borne, by young and old,
if we are all of us found faithful to that Spirit which never errs, and speaks,
and hands to us for our occupancy, of its own.
To occupy well with what we are entrusted,
we do know is pleasing to our heavenly Lord and King.
What a cloud of witnesses there have been to this, and the comfort and help enjoyed,
and how this has been increased unto such!
Do we not know it?
Thou alludes to thy daughter S. G. being at the Women`'s hospital learning to be a nurse,
and her feeling to be in her place.
All must come to feeling if they would walk safely and honour the Master,
and by feeling we can all know, I believe undoubtedly, when we dishonour Him also.

It must feel to thee a favour to be raised up again,
that thou mayst yet further show forth his praise,
who called thee,--called thee to serve Him and to glorify his ever-excellent Name.
We may desire this for ourselves, that we may have this honour,
that of magnifying his power in the earth, whilst in these earthen vessels,
and wheresoever He is pleased to cast our lot.

Dear P. E. H. and S. C. G.! We may be thankful for
the help extended to them and their companion also,
on that long journey.
Our Lord is not a hard Master, and calls for nothing which He does not enable to perform.
I can believe this must be renewedly sealed upon the thankful mind of our dear friend,
and her companions also, and when returned again from that sphere of labour,
there may be poverty for a season; that wholesome and necessary state, permitted,
and ordered for the labourer, that strength in the abasedness of self may be known,
and gathered up for either further labour,
or the contentment which should he known in whatsoever state the Lord permits,
or appoints for us.

I could go along with thee in thy remarks respecting "`our children;`" it is
more and more my feeling that there is a state arrived at by some such,
in which we can do nothing (with them) no more than that of casting
out the evil spirit which could only be done by prayer and fasting,
as alluded to;
then we may commend them by prayer and a steadfast example in our own daily walk, which,
after all, may work out for them that which we desire--an heavenly inheritance;
and if so be the Lord will grant this to each one of mine,
O! how condescendingly merciful towards them and myself!
Well, my dear friend,
let us be increasingly of a prayerful spirit to answer
the design and good end of the Lord concerning us,
that we may walk to his praise the whole of the time
He allots to each one of us in these earthen vessels,
yea, that we may show forth his praise to the end of our days, that others, through us,
may extol Him in the heavens of his glory.

[.signed-section-closing]
I am thy friend,

[.signed-section-signature]
John G. Sargent.

--

6th Month 24th.--Fifth-day.
Left home in company with William C. and Lydia D. Meader +++[+++of New York State,
who were again in this country on a religious visit]
for Stavanger in Norway.
Had a favoured time before leaving,
when the language was revived in my mind and in our hearing, "`What ailed thee,
O thou sea, that thou fleddest?
thou Jordan, that thou wast driven back?
Ye mountains, that ye skipped like rams; and ye little hills, like lambs?`"
believing that to be for our encouragement,
and that as we had experienced this in time past, so,
if we who were going forth and those who remained
behind kept watchful and close to the Shepherd,
we should experience it still.
Arrived in Hull soon after 4 p.m. The Domino S. S.
left at about 1 p.m. and anchored a little way out.

// lint-disable invalid-characters ½
25th.--On board the Domino: a quiet sea: going at 9½ miles per hour:
not many vessels seen.
Wind rose up and blew a little strong in the after part of the day and at night.

26th.--Arose refreshed, and I trust thankful for favours received.
A strong wind blowing, about N.W. Sighted land at about 10 a.m. My two friends poorly,
William particularly so.
The reflection came to my mind in thinking of the great distance I am come on the sea,
What am I come for?
May I be watchful and know my Lord`'s will, and do it, whatever this may be!

Hull to Stavanger 410 miles (from town to town.) Arrived
at Stavanger between 6 and 7 p m. Anders Evertsen^
footnote:[Anders Evertsen was born in Norway.
His father who was master of a small coasting vessel fell overboard and was drowned,
leaving his mother with seven children in a very necessitous circumstances.
At the age of seventeen A. E. went to sea,
and by his good conduct and integrity rose to be master of a vessel
and continued to follow a sea-faring life for many years,
visiting England and most parts of the Continent.
He retired form this employment when not much past middle age.
Whilst residing at Stavanger he joined the Society of Friends,
being convinced of their principles.
He died in England, as the following testimony concerning him,
issued by Fritchley Monthly Meeting,
will show.
{footnote-paragraph-split}
"`In recording
the decease of our dear and valued friend,
Anders Evertsen of Stavanger, Norway, which took place on the 16th of 5th Month, 1883,
we can testify that by the grace of God he was what he was,
enabling him through obedience thereto, to bring forth fruit to the praise of the Giver,
the great and good Husbandman;
and in connection with the loss the Church militant has sustained thereby,
the language has arisen,
'`Gather up the fragments that remain that nothing be lost.`' He was very suddenly taken
from us to his everlasting rest (as we reverently believe) whilst on a visit,
accompanied by his wife, to their friends in England,
after having attended their Monthly and General Meetings.
{footnote-paragraph-split}
"`Of
our dear friend`'s early experience but little has been gathered;
but it appears that when about forty-one years of age he was united
in membership with the Society of Friends in Norway,
and continued with them until about the year 1869,
when his eyes were more fully opened than they had been,
to see the lapsed state of the professing Society and whither it was drifting;
and when favoured to see clearly that the time was come,
he with his dear wife withdrew therefrom.
It may be said he was firm and immovable in standing
for the testimony of Truth to the end of his days,
and though his life terminated so unexpectedly to his friends,
we have consolation in believing he was ready for the solemn change.
{footnote-paragraph-split}
"`Our
dear friend was entrusted with a gift in the ministry;
his communications were short but full;
and the evidence which accompanied his exercise was sufficient
to prove that what he offered he had not received from man,
neither was he taught it,
but by the revelation of Jesus Christ.
{footnote-paragraph-split}
"`It appeared
to be animating to him to mingle with the little company in England,
who, like himself,
had felt called away from the lapsed body which still retains the name of Friends,
and his heart yearned to encourage us in a sense of the love and
care of the Head of the church over this little body;
on one occasion quoting in one of our meetings '`a vineyard of red wine,
I the Lord do keep it, I will water it every moment, lest any hurt it,`' and added,
those who were steadfast to the end would come off victorious.
Very instructive to us was our dear friend`'s dedication as a fellow-helper
to such as were preserved from joining in with the spirit of innovation
and treading down of our testimonies,
who he believed were engaged in their Divine Master`'s service;
showing himself willing to spend and be spent for
the promotion of the cause of Truth and righteousness,
as can be testified by those from this land and America,
who were called to travel in Norway to declare the unchangeable riches of Christ,
labouring with much diligence to assist and cooperate with them,
in carrying out the service laid upon them.
{footnote-paragraph-split}
"`About
two hours before he was taken from us,
he said to his wife '`the Lord is with us.`'`"
{footnote-paragraph-split}
Signed on behalf
of the Meeting,
{footnote-paragraph-split}
Horatio Blake,
{footnote-paragraph-split}
Clerk.]
and Theodor Fugilie met us and conducted us to A. E`'s. Felt thankful for being
thus safely brought across the mighty deep and over a rough sea.
We were kindly welcomed by S. Evertsen.

27th.--At A. and S. E.`'s. Arose refreshed.
Dreamed a dream,--that a little parcel that had been left for me was given me:
it was not known who left it, or how it came where it was.
To my understanding it came from Heaven,
and on opening it I found a small one inside addressed to some one else,
which I was to give out.
It appeared there were or might be others in the packet, how many I did not perceive.
May I be watchful and faithful, and deliver what may be committed to me for others.

Meeting this a.m. at 10 in the Meetinghouse here.
"`My heart is not haughty, nor mine eyes lofty;
neither do I exercise myself in great matters, or in things too high for me.`"
Was led to stand with these words, and a concern on my mind to encourage to faithfulness:
for all good cometh from above and He hath given grace to every man,
whereby through faith all may be saved.
Said I was emboldened and encouraged to be faithful to my charge by a dream this night,
stating what it was,
and encouraged all to be faithful to their trust whatever it might be.
Both W. C. and L. D. M. were engaged in testimony, the former at considerable length.

28th.--Second-day.
It was intended to hold a meeting this evening at Hundvaag,
in the house of Gudmund Erland.
Left at about 3 p.m. About 25 minutes`' row in Isaac Klepzig`'s boat,
he and Rasmus Harrestad, and Ole Thorsen and Carl Nyman rowing.
Was helped again to apprehended duty:
laid before the people our need to sink low in our spirits and wait upon God,
not to look to the creature--that the most that any of us could do the one for the other,
is to point to Christ the Saviour.
Knelt at the close of the meeting,
after W. C. M. had been engaged at much length and his wife had also stood amongst us.

29th.--Stavanger.
In the afternoon called upon an aged woman, a member, 90 years old, Inger Strand.
It opened upon my mind to deliver,
how that the wise men followed the star in the east till it brought them to Christ,
and that they presented to him precious gifts of gold,
frankincense and myrrh,--so may we each one follow the inshining of the Light,
and offer to Him such as we have.

In the evening a few of the Friends came in, and we had a favoured time.
My mind was impressed with the language, "`Drink waters out of thine own cistern,
and running waters out of thine own well;`" my concern was
that each one of us might go to the Fountain ourselves and
drink of this living water for the sustenance of our souls;
not depending the one upon the other, not leaning upon a brother or a sister.

30th.--Fourth-day.
Left soon after 8 a.m. by boat, for the island of Renneso,
about two Norwegian miles (fourteen English): four men to row: about four hours going,
the wind being unfavourable, so that the sails were unavailable.

The meeting gathered slowly, a short notice unavoidably given.
Strength was given after a communication from W. C. M. The words arose,
"`Labour not for the meat which perisheth`" etc.,
directing to that spiritual food which each one has
to labour for every day to gather it afresh,
as the Israelites did the manna in the wilderness,
and sufficient would be given for the sustenance of our souls;
not to lean one upon another but to seek it for ourselves--to meet together for this end,
and also to be concerned to gather it at other times,
in the field or where our occupation may be.

Left soon after 7 o`'clock and were favoured to reach Stavanger
comfortably in a little more than two hours and a half,
the wind being in our favour and sails up.

7th Month 1st.--Meeting at A. E.`'s this a.m. Seven present with us.

3rd.--Seventh-day.
// lint-disable invalid-characters ö
Left Stavanger about 2.30 p.m. by the Steamer Kong Haakon for Sövde:
arrived at about 8 p.m. Grand rocky scenery, lofty mountains,
and snow on the highest of them.

4th.--Meeting at 11 a.m.: room nearly filled.
Was first to communicate; "`Ye believe in God, believe also in Me "`--+++[+++spoke of]
the necessity not only to believe that there is a God, but that there is a Saviour,
who died for us all, and is come again by his Holy Spirit in the hearts of all men,
and saves all who give heed to the Light that shines in them,
to bring them out of darkness,
that they may leave off doing evil and do that which is good,
whereby they are saved from sinning,
hearkening unto his voice that speaketh as never
man spake and teacheth as never man taught.
Felt it laid upon me to invite to this inward Light, and to walk therein.
Was strengthened in this offering: Sikke Evertsen interpreted.
W+++.+++ C. M. followed at considerable length, with evident help to preach the Way to all.

Afternoon meeting held at 4 o`'clock.
Not so large a company as this morning.
My mind was impressed with the language,
"`By this shall all men know that ye are my disciples,
if ye have love one to another;`" that our being known by others
to be the disciples of our Lord is to the glory of God.
Encouraged to be faithful to the talent, or talents received, to fear to offend Him,
by turning to that which we see in the Light is evil,--to say,
as our Saviour said when tempted by the enemy of our souls, "`Get thee behind me,
Satan.`"
Whilst writing this which was with me today, I feel the need there is for the ability,
which our Holy Redeemer giveth to them that ask Him,
to be enabled truly and experimentally to adopt the language.
L+++.+++ D. M. and W. C. M. stood before I did; the people were very quiet and attentive;
felt also constrained to kneel and supplicate, in the help I believe afforded,
that the Lord would bless this people,
that He would bless the crumbs that had been dropped and preserve us all.
One dear old man (Osmond Brekke) stood and spoke
at some length with much humility and fervour,
and though I did not understand his language, it was impressive,
and the solidity and seriousness of his countenance spoke much to me.

// lint-disable invalid-characters ö
6th.--Sövde.
We left this a.m. by steamer Hankelid about 6 o`'clock,
on our way to the Friends at Erfjord +++[+++which we]
reached between 10 and 11 a.m. Were landed by a boat
which came out to the steamer near to Haalandsosen,
on the right shore of the fjord.

A friend came out with his boat for us.
Claus Finnestad also came with him.
We were very kindly received, and taken to a comfortable house on the opposite bank.
Three brothers live here Lars, Neels, and Osmond; the latter only, married,
but no children.
This evening a meeting was appointed for the Friends to meet us here, at Osmond`'s,
to be held at 6 o`'clock, but they did not fully gather till about 7 o`'clock.
Was engaged, the words of the Psalmist having arisen with me with apprehended clearness,
"`I waited patiently for the Lord; and He inclined unto me, and heard my cry.
He brought me up also out of an horrible pit, out of the miry clay,
and set my feet upon a rock and established my goings.`"
The query was raised whether all of us were seeking the Lord as he did,
that we might find Him, for the promise is, "`Ask, and it shall be given you; seek,
and ye shall find; knock, and it shall be opened unto you:`" it felt hard getting along,
as if there was not much entrance.

Both of my companions were engaged.
// lint-disable invalid-characters ö
The name of the Island is Erö (as I understand),
the piece of water "`Erfjord,`" and the residence of Osmond and Sophia called "`Enerhaugen.`"
One large rock with trees growing on it, is opposite the house, divided off by a stream,
on which is a pretty large masted boat;
there are lofty mountains on one side of a wider expanse of water,
and another on the left,
with others beyond the island rock which is fronting us,--beautiful scenery,
causing admiration at the wonderful and mighty display of nature.
Held a meeting this p.m. at 4 o`'clock at Haalandsosen on the other
side of the fjord at the house of a Friend who has a family.

8th.--Fifth-day.
About to leave for Stavanger today; comfortably entertained here.

Erfjord.
May I never forget the lovingkindness and tender compassion, as well as mercy,
of my heavenly Father and Saviour, Jesus Christ, in his revelation to me this night,
whilst I lay upon my bed.
Truly this ought greatly to confirm faith in me: a remarkable vision for my good,
but not sufficiently alive thereto so as to receive it, according to his gracious intent,
in thus bestowing it upon me.
And further, his great condescension to me, how has it been displayed,
when desiring I might open my Bible, when dressed, at some portion suitable to my case,
he did condescend to answer my desire, and show me what was applicable thereto.
Surely this ought to convince me fully of the great and wonderful reality,
that there is One who is ever watchful over us,
and O! that this favour designed to be profitable to me,
may indeed have its full work within me, and establish me more than has ever yet been,
upon Him the invincible Rock.

We left this place this afternoon at about 2.30,
being rowed in the boat to the steamer Skjold,
// lint-disable invalid-characters ö
which took us on board on the other side of the rock, by which we went to Jaelsö,
a small boat taking us from this to the steamer Hankelid for Stavanger.
After waiting, perhaps nearly an hour,
this came up and we were favoured to reach Stavanger again towards 9 o`'clock;
feeling thankful I may say, I trust, for the help vouchsafed to us every way.

7th Month 9th.--Stavanger.
Arose refreshed and thankful in heart, I believe, for his goodness to me,
with a renewed feeling that it is good to feel after God, that we may find Him;
and our blessed Saviour has felt very near to me, preciously so, I can say,
to the sealing fresh instruction upon my mind.

The substance of what Anders Evertsen expressed in
our last sitting at Erfjord is--"`Dear Friends,
Be faithful! faithful to the first love,
and faithful to proclaim his glory who calls you
out from the darkness to his marvellous Light.
Set not your hope on man, because when the man perishes, your hope perishes;
but set your hope on the eternal, living God, then you will not be ashamed,
and when it shall please God, He will gather us all to his rest and peace,
where we shall no more go out.`"

We called upon the father and mother of the late Asbjorn Kloster who live at
// lint-disable invalid-characters ö
the meetinghouse and left this afternoon about 4 o`'clock by boat for Idsö,
one-and-a-half Norsk miles, or about eleven English.

// lint-disable invalid-characters ö
12th.--Left Idsö this morning at about 7 o`'clock.
Four to row and W. C. M. helping part of the way.
Very little rain, but what little wind there was, contrary.

Stavanger.
Arrived at about 9:30--about two hours and a half from Idso.
On leaving Idso,
an opportunity was afforded me to unburden my mind to Siri Idso (Svendong`'s
wife.) A concern had rested with me on awaking this morning,
the words being given "`Whatsoever thy hand findeth to do,
do it with thy might,`" that they should not give heed to the "`Lo! heres,`"
and "`Lo! theres,`" but keep close to the Shepherd`'s tent,
and not be turned from the faith once delivered to the saints, and to our fathers,
and to us; for that there are many under our profession who are running about,
ready to draw away to new things,
and over-turn that faith;--delivering this in substance,
dear Sikke Evertsen interpreting.
I came away relieved.

[.offset]
The following is an extract from a letter to his wife written about this time.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Stavanger, 14th of 7th Month, 1880.

I felt concerned at their not holding a meeting for
worship at Idso without reading the Scriptures,
and was helped to relieve my mind with them; kind S. E. interpreting for me.
Her heart seems in the work which she is so ready at.
It feels in the retrospect,
that our great Helper graciously condescends and is our Head in our gatherings.
We are not left to ourselves, but rather can we say,
self is swallowed up of that Power which prevails,
and before which nothing can stand to take the place thereof.
But there is a hidden exercise which avails much, and I cannot doubt this lives at home,
whilst we are here; and that she that tarries at home divides the spoil.
I know we have your feeling desires for our help and preservation as we go along.

--

14th.--Made visits this afternoon to+++_______+++ and+++_______+++. After a
time of seeking to get down to where nature is all silent,
at the first house, the words passed through my mind, "`There is a vein for the silver,
and a place for gold where they fine it`" believing we knew this,
and that it was precious to know it, also that "`there is a path which no fowl knoweth,
and which the vulture`'s eye hath not seen: the lion`'s whelps have not trodden it,
nor the fierce lion passed by it,`" that my desire was,
we might keep on the watch-tower and watch every day and every hour,
lest the enemy should enter in with his temptations and betray us,--that we may not
hearken to the voice of the stranger with his far-fetched presentations in human wisdom,
though he may appear as an angel of light to deceive us and draw us from the Truth,
but we think better things of you, dear friends, I said,
and that I desired myself to be on the watch--to this effect, and relieved my mind.

At the next place, where were four young people and their parents,
the words were "`Multitudes, multitudes, in the valley of decision:`" that the call was,
to be decided,
with full purpose of heart to serve the Lord--that He would not have half-hearted servants;
and I addressed the young people especially,
that they would listen to the still small voice in their
consciences and give up their lives unto the death,
and be faithful to all our Lord`'s requirings,
whether in doing or leaving undone,--that so they might grow stronger
in Him and "`come up to the help of the Lord against the mighty.`"
It felt a favour that a state or states were spoken to,
as a remark privately to me inferred.

15th.--Fifth-day.
Stavanger.
Left by Steamer and arrived at Naerstrand between 9 and 10 a.m. Left by boat,
arriving in about two and a half hours at Tendeland at 12:30. More
of a swell on the water than we had before found in the fjords.
Went to the house of Cecil Tendeland, a widow, and a member.
The meeting, held in the afternoon, was felt to be a favoured time.
We left Tendeland by boat at about 8 o`'clock.
We had about four miles to ride or walk.
Were helped forward with two conveyances as far as Espevig, where we took the boat,
Tollef Stolen and a woman from the house we had left, rowing us to Slogvig,
another inlet about three miles off.
This is a beautiful spot, mountainous rocks with beautiful verdure and water scenery.
Anders Slogvig and his wife Berthe, live here; no family.
He lately gave his farm to the Society; a large extent of ground.
They appear hardworking people.

We left Slogvig, rowed by Anders Slogvig,
at about 2:30 p.m. for an inlet where we arrived at about 5:30,
and were met with two carioles or spring carts, a pony to each,
by Elias and Soren Sorensen, by which,
Anders Evertsen and myself walking a little and W. C. M. all the way,
we arrived at Stakland at about a quarter past seven (about four miles).

17th.--Somewhat fatigued today after yesterday`'s
early rising and travelling by land and water.
Engaged a little both morning and afternoon in writing and reading,
and helped a little with raking up the hay.
In a sitting together in the evening, after L. D. M. had expressed something amongst us,
I did not feel easy in my mind though about to close the opportunity,
without giving expression to what had rested with me,
"`The cup which my Heavenly Father hath given me, shall I not drink it?`"
that that the children of God have to pass through deep baptisms and fiery ordeals;
that it is a favoured condition to know what it is
to stand as it were in the bottom of Jordan,
and be thus enabled to bring up stones of memorial from thence:
encouraged to be patient unto the end in enduring the afflicting
rod which is for everlasting peace and joy.

18th.--Stakland.
After breakfast read Ps. 107: After I had read and we had had a pause,
Sikke E. read it in their own language to those present of the house,
including Berthe Slogvig, who had walked over from Slogvig last evening.
A large meeting here in a comfortable Meetinghouse, nearly new; perhaps 150 present.
The words of the Psalmist came before my mind and were expressed early on in the meeting,
(a feeling of solemnity felt to me to cover us),
"`As the heart panteth after the water brooks, so panteth my soul after thee, O God!
My soul thirsteth for God, for the living God.`"
That was what we met for, professedly,
that we might be satisfied with the refreshing streams
of Life which give life to the soul,
and with the bread of Life which cometh down from heaven, that our souls might live.

Felt helped to enlarge somewhat and to invite to this; dear W. C. M. stood afterwards,
and pleaded earnestly with some present,--a mixed company.
I did not feel easy without rising on my feet again,
and testifying that "`The law of the Lord is perfect,
converting the soul,`" and pointing to this Divine Law written in the heart,
and to the Light (Christ) to walk therein; that He is the Light of the world;
that we must walk in the Light if we would be saved from sin;
that there is no salvation in sin;
that though an angel in appearance should preach any other doctrine, not to heed it;
that we must not lean upon a brother or confide in a friend and turn from the Light,
(or to that effect).

Came away feeling relieved: dear L. D. M. silent: a long meeting.
In the afternoon meeting, (4 o`'clock), my mind was impressed with the words,
whose adorning let it be that of the hidden man of the heart,
the ornament of a meek and quiet spirit; that though those enumerated by an Apostle,
"`the plaiting of the hair, gold and pearls,
and costly array`" might not be their besetment nor ours,
there may be other things which hinder a growth in grace;
and what is required of us is watchfulness in thought, word and deed.
Peace was my portion after giving expression to this and what further flowed therefrom,
having before doing so, felt much reluctance and disposed to reason it away,
as that these things were not their temptation, being poor people,
and not having means to indulge in these things named.

May I learn to be only the Lord`'s servant, both blind and deaf to the reasoner:
a quiet meeting:
much expression of feeling by the hand after we broke up our meetings as usual.
An aged widow, Inger Svinelie, living at Svinelie, was here at meeting with us,
and very feeling.
We drew into silence in the evening, when it was with me to say,
though we had outwardly closed the opportunity,
that I felt I had a few more words to say, "`If he smite thee on the one cheek,
turn to him the other also,`" inferring that humility
and love must be maintained and self denial.
Nothing outward led to this in my mind.

19th.--We left Stakland.
A short way by road and then by boat (at about 8 a.m.) Torbjorn Aarek and his son Erick,
rowed us perhaps an hour to the farm where they live (a little
way from the landing place) called Adraeg in Skjoldsogn.
Torbjorn`'s wife Inger and eldest daughter Berthe both afflicted.
They have two sons and two daughters.
We were driven by Torbjorn and Elias to Haugesund,
ten miles and a half along a good road, but very wet a part of the way,
to take the steamer for Bergen tomorrow at 3 or 3:30
a.m. Arrived at Haugesund in about three hours,
and left the luggage at the hotel.
Then went to Sikke Evertsen`'s brother`'s and took refreshment, and before leaving,
a comfortable tea.
Anders and I walked in afterwards to the hotel.

20th.--Haugesund.
By some mistake we were called about 1 a.m., for the first steamer,
instead of the one to leave at 3 or 3:30 a.m. so had a little more time to rest,
and proceeded at near 3 o`'clock, and waited in the boat taking us out,
till about 4 o`'clock, when we boarded the Steamer "`Tordenskjold`" coming from Hamburg,
which was to take us to Bergen, 64 English miles from Haugesund.
On arrival at Bergen we went to a lodging-house, where we were comfortably accommodated.
In the evening the principal one who professes with
Friends (not a member) came and took tea with us,
named Heine Heinesen, an optician.

21st.--Fourth-day.
Arose much refreshed, and thankful I trust for help vouchsafed, and a sense given me,
of which I feel unworthy, of his living presence,
the wing of his mercy being spread over me.
After breakfast walked out to steam-packet offices with Anders and Sikke.
Called this forenoon upon H. Heinesen, who was with us last evening.
As we were coming away without any silent opportunity,
my two friends having relieved their minds last evening,
I felt my peace consisted in our taking our seats again, so we sat down,
and I expressed what had rested with me since coming there.
In the afternoon we went across the water to Laxevaag on a small steam-boat,
to visit Paul Olsen.
His wife only was at home.

22nd.--Bergen.
Left this place this morning at about eight o`'clock
by steamship for Odde at the end of Hardanger Fjord;
expected to arrive at about 11 a.m. tomorrow.

23rd.--Sixth-day.
Odde and Roldal.
Arrived at Roldal in in the evening, about 30 English miles +++[+++from Odde.]
Four hours going to the first station (Seljestad) 14 miles on our way,
where we took refreshment and went on by the other conveyances.
Arrived at Roldal after about three hours more travelling
in three spring carts drawn by a small horse each,
going over the mountain Seljestad, 3394 feet above the sea, by a winding road,
down to the valley of Roldal.
Went to the house of Torjus H. and Martha Midhus.
They have eleven children, four of them in America.
Sat down in the evening, before going to rest for the night; Torjus and daughter present;
his wife and others away in the mountains; too far away to be convenient to come,
and leave the cattle.

26th.--Roldal.
Staying here today, as the steamer we propose returning to Bergen by,
does not leave Odde till 3 a.m.

27th.--Roldal.
We left this place this morning at about 20 minutes past eight o`'clock
in three conveyances (spring carts) accompanied by a man and two boys,
taking about eight hours, including some rest by the way,
and arrived at Odde between 4 and 5 p.m. ready for the steamer,
to arrive at 11:30 p.m. and sail at 3 a.m. tomorrow.
In taking leave of Torjus Midhus, I expressed through S. E.,
my desire for him that he might be faithful,
and that I felt the necessity of it for myself.
They are in a very different way of living here to what we are accustomed to meet with,--not
having some of those things we consider necessary for us in household conveniences,
but we did quite well, feeling contented, I can say, with such things as we had.

I felt thankful, in leaving this place,
whilst travelling along in one of the three spring carts by myself,
a boy on the road by the side, having to go up the mountain,
and joy of heart was my portion,
in the feeling that I knew of nothing I had passed over and not laid down,
which my Lord and Master commissioned me with;
and in a sense of his great goodness to me,
my heart was filled with gratitude to my good and gracious Helper,
who has proved to me more than I feel worthy of.
We halted more than once on the way for the horses to feed,
and on one of these occasions took refreshment ourselves on a bank by the road side.
Arrived in nice time,
and waited the arrival of the steamer "`Hordaland;`" went directly
on board and reached Bergen between seven and eight o`'clock.

30th.--Stavanger.
Have attained the 67th anniversary of my birth today.
How very much I have to be thankful for and to praise Him for,
who has not left nor forsaken me, but led me all my life long hitherto,
as far as I have been willing to be led and guided
by Him my Saviour and deliverer out of many temptations.
Have been much favoured whilst out on this journey
with fresh openings and lessons of instruction.
May I ever remember them to profit--and ask for more, in prayer believing.

8th Month 1st.--First-day.
Attended the meeting here this forenoon.
It fell to my lot to open my mouth first, I believed in the will of my Lord and Saviour;
"`He that dwelleth in the secret place of the Most High,
shall abide under the shadow of the Almighty;`" that
the place of the Most High is a secret habitation;
that it is the Lord`'s devoted children who dwell there;
that they that love the world are of the world`'s spirit, and know not this secret place.
Therefore, we must strive with the ability which our God giveth;
that He giveth a measure of grace to work with, and to profit thereby;
that we must be meek and lowly in heart,
and we shall have that peace which the world cannot give nor take away.

My two dear companions also bore testimony, and I felt I must again stand to be clear,
the words having revived with me--"`I will lay down my life for Thy sake,`"
that it must be by faithful obedience to the still small voice,
obedience to the little that is given,--giving attention thereto
and being faithful in whatever is required whether it be to do
or to leave undone,--that this is the only way to grow in the Truth,
and in the knowledge of God;
that to lay down our lives for his sake is a necessary resolve,
but that it can be only by going forward step by
step in faithfulness (or obedience) to Christ,
and working with the ability He gives us.

Met again at four p.m. A larger gathering I thought, than in the forenoon.
The words with me were "`Awake thou that sleepest, and arise from the dead,
and Christ shall give thee Light,`" (which after dear L. D. M. and W. C. M. had stood,
and to my feelings had been much helped amongst us,)
I gave expression to--rising with the words first,
"`A little more to what has been said,
for every message must be delivered that we may have peace`"--then
quoting the above I felt strength gradually arise--saying,
to this effect,
that it may be there are some here present who stand in need of this call,
to arise out of that sleep which is comparable to the sleep
of death--that Light is extended to every man,
woman and child,
to the child when arrived at a certain understanding to profit by--to walk therein,
in which they do not stumble--that my desire was that we
may all bring the solemn question home to ourselves,
whether this is our condition, that so none of us may escape.
That such, if there are any, who are in sin,
may be encouraged by the language of the Apostle,
"`You hath he quickened who were dead in trespasses and sins,`"--that
the invitation was to come to that quickening Spirit that they might live;
that the kingdom of heaven is at hand, it is near to us all;
not to think that the heavenly kingdom can only be
entered when the body is laid in the grave,
but that the kingdom,
and the blessedness thereof is to be entered and enjoyed in this life--that we
have to enter by the strait gate and narrow way which leadeth into Life,
and few there be which find it, because broad is the way that leadeth to destruction,
and many there be that go in thereat (by the wide gate),
that there must be no standing still,
for that such go back and not forward--with something
more and I sat down feeling sweet peace;
and the evidence was fully granted after breaking up our meeting,
that my prayer had been heard and answered--that
I might receive ability to do the Divine will,
whether to do or not to do, and came away clear;
and I can say with thankfulness of heart,
that in coming away from this meeting and afterwards,
my joy was "`full`" and the gracious promise was verified "`Ask, and ye shall receive,
that your joy may be full.`"

Many of the people came in to A. and S. E.`'s in the evening in a loving spirit,
probably from some words of farewell that had been expressed by dear W. C. M.,
thinking they might not see us again,
as we have no expectation of being at their meeting again.
W+++.+++ C. M. thought there might be as many as forty.
We dropped into a favoured silence and after dear
L+++.+++ D. M. had expressed what was with her,
I gave expression to what had been given me in our solemn silence,
"`I am come that ye ('`they`') might have life,
and that ye ('`they`') might have it more abundantly`" and
something more for the clearing of my mind at this time.
Dear W. C. M. afterwards was engaged amongst us.
Thus closed the day which I felt was indeed crowned
with peace;--and may it be remembered by me to profit,
increasing my trust in Him who has so condescended
to hear and answer me in the desire of my heart.
These people feel to us to be a seeking people,
and it may be said they have sought us in the desire of their hearts to know
an increase for themselves (so I can believe) and in the love of the Truth.
One female spoke amongst us this evening, and one also knelt and gave utterance,
it seemed to me, in true feeling.

8th Month 2nd.--A meeting was appointed to be held this evening in the,
Temperance Hall here, at the request of three members of the Society of Friends,
(or appointed by them) which was largely attended,
the three galleries being also partly occupied, and many of the Friends there.
William C. Meader was largely engaged.
After him I had to express what had rested on my mind since we sat down together,
"`Let me die the death of the righteous, and may my last end be like his!`"
And was led to say that the ability to do this was given to all of us,
all having a measure of that grace which saves from sin if we are obedient thereunto.
To die the death of the righteous we must live the life of the righteous;
that no doubt none of us would question this.

Let every one of us be very faithful to the "`Word nigh in the
heart and in the mouth,`" that "`Word which was in the beginning,
which was with God and which was God`" who teaches us by his holy Spirit,
and before we commit sin, tells us what is sin which is brought forth first by a thought,
then by words, and deeds; so there is no excuse for any of us,
and by giving heed to this we shall be safe,
with which I concluded after commending them and myself
to Him who inviteth all of us to come unto Him,
which is to be obedient to what He requires of us--to
obey his commands--the Law written in our hearts.
Dear L. D. M. followed soon after,
and W. C. M. with a few words more--so the meeting concluded,
and after much expression given us by shaking of hands we left the house,
returning to our dwelling with the reward of peace.

5th.--Fifth-day.
We left Stavanger for Egersund and stopped by the
way at Thime to visit a woman near there.

6th.--Egersund.
Arose by four a.m. to be ready for the steamer for
Flekkefjord +++[+++about 98 English miles from Stavanger.]

Left at about 6:30 and arrived at about 9:30. Gave a tract by W. Shewen,
in Norsk to a person on board, who made enquiries about Friends in Norway.
He was quite communicative and we had to part sooner than I would have wished:
went to lodgings--made enquiries respecting the way of continuing our route to Quinnesdal:
a small steamer was engaged to take us to Oie about 12 English miles, for 12 crowns,
+++[+++18 crowns £1 sterling]
to go direct without stopping by the way which was done in about two hours;
then we had to ride to Aamoth three miles.
We had to cross a stream in a boat to the inn, +++[+++at Aamoth]
which took a few minutes.
Two pony carts were soon found, no cushions; a man to each standing behind to drive.
Here we refreshed ourselves, and left at about 5:30 p.m. with two conveyances,
one a strong pony cart, the other a spring cart,--a man to drive the one,
a woman the other.

The road, most of the way, rough or hilly, about 10 miles perhaps.
It took us till about 9 o`'clock to reach Quinnesdal,
about three miles short of which we had to be ferried across a wide stream,
and our carriages left us.
The stream being shallow, we were ferried over at twice, to lessen the weight.
W+++.+++ C. M. walked all the way +++[+++from Aamoth]
their being no room for him to ride,
and he being quite satisfied to walk--said he walked as if he had hind`'s feet,
or to that effect: the horses walked most of the way.
W+++.+++ C. M. came up and joined us soon after.
The eldest of the Friends here, was seated on the opposite bank;
his name Tollag Torgrimsen.
The other that met us (a messenger having been sent over before us from Aamoth,
where we stayed awhile for refreshment,) named Lars Aslagsen Oxefjeld,
came over to us with the boat,
and walked in the water some way on account of its shallowness,
to move the boat in the deepest parts.
He is a son-in-law of Tollag Torgrimsen`'s. The members here are twelve in number,
and attenders twenty to thirty.

Their meetings on First-days are held at eleven and three, and on Fifth-days at eleven.

7th.--Quinnesdal.
Visited in the forenoon Tollag Torgrimsen and his wife: their young woman servant present.
Soon after dropping into silence the words were given me,
"`The nations are as a drop of a bucket,`" which
I believed it right to express and queried,
then what must we as individuals be in His sight?
We are of more value than many sparrows;
encouraging to faithfulness that we may live to His praise--watching
closely not to give heed to the Lo,
heres, or Lo, theres, whether secretly spoken by the enemy in our minds,
or by the voice of the stranger from without:
felt some openness with strength given and peace in declaring what came before me.

In the afternoon we went to two houses, and had a sitting with the Friends.
In the first we went to,
my mind was led to that passage of Scripture relating to Gideon
who said he was "`poor in Manasseh and least in his father`'s house.`"
This, it felt to me, was a favoured state, to feel poor and little,
whereby we grow in the true wisdom and the knowledge of God; that so,
He leadeth us up higher and teacheth us of his ways, or to that effect.
Our meal was then very acceptable and in peace we partook thereof.
In our pause at the close of it my mind was arrested
with those words of our Saviour to Peter,
"`Blessed art thou, Simon Barjona: for flesh and blood hath not revealed it unto thee,
but my Father which is in heaven;`" by which it opened to me,
that we have been blessed together with the blessing that
attaches to a visitation of our Lord`'s holy will,
and the doing of it; with a little more,
feeling the sweet peace that had accompanied our moving along +++[+++and being]
now nearly at the close of our work in this country.
Dear W. C. M. followed soon after,
alluding to the paying of the vow and quoting the passage;
"`He that goeth forth and weepeth bearing precious seed,
shall doubtless come again with rejoicing, bringing his sheaves with him.`"

8th.--First-day.
Meeting gathered at eleven a.m. Met again at three p.m. Had to
give up to what I believed was given me for the people.
After W. C. M. had spoken, I had to say--"`As the heavens are higher than the earth,
so are the Lord`'s ways higher than our ways,
and the Lord`'s thoughts than our thoughts.`"
Then what are we?
In the greatness of his love and mercy towards us,
he giveth unto each one of us a measure of his grace, sufficient for our need,
and requires obedience from us; that thereby we are saved from sin,
saying what came before me at the time--and till the spring dried up.
L+++.+++ D. M. then cast in what she had for them, and so closed our work amongst them,
gratitude filling my mind in being thus helped from day to day,
in the belief that my heavenly Master required nothing more of me at this time.

9th.--We left this place a little after six o`'clock.
Quite wet this morning.
Several of the people came out of their houses as
we passed along on our way to the ferry,
about three quarters of an hour`'s walk, and some came along with us.
After crossing the river, we got into the conveyance waiting for us,
and went forward on our way back to Stavanger and halted at Aamoth,
where we had stopped on our way out, and took a refreshing meal.
The rain fell most if not all the way and some of us were wet,
the accommodation being small.
In the afternoon about one o`'clock we left by boat rowed by a lad and Carl Tollagsen,
(of the house where we have been and who came over to Quinnesdal
with his wife to the meetings) to the small steamer engaged
to come and fetch us back to Flekkefjord today.

We arrived safely in the afternoon,
perhaps four o`'clock and found a steamer going to Stavanger
tomorrow having been detained here by the rain,
it being too wet to unload its cargo.
Thus we have again to admire that wonderful and condescending Hand who
cares for us,--and the rain which seemed so unfavourable for us,
turned to our advantage, making it easier for the remainder of our journey,
as otherwise we must have hired to go by road, a fatiguing long ride to Egersund,
and afterwards to go by rail to Stavanger.
Truly we may trust our great Benefactor and go on our way rejoicing.

Yesterday after breakfast I strolled away towards
the mountain where no human dwelling was,
and seated myself under the great rock, when, in solitude and away from man,
I felt the goodness of my heavenly Father,
and was enabled to partake of comfort in the contemplation of his power,
and his wonderful works in the creation, and in a feeling of how insignificant is man,
in comparison of the greatest works in the creation (for
magnitude) yet being endued with life and understanding,
he is much more in the Divine sight than any other of the Lord`'s works.
Remember, O my soul, these things for thy good,
and the praise and renown of thy great Creator, the Lord of the universe.

Had to wait here till the afternoon, when the steamship Trofast,
meaning "`Faithful,`" Captain Rasmussen, was expected to go for Stavanger,
with rye from the Baltic,
having been detained by the rain as it had some of
its cargo (rye) for this place to unload.
We went on board but did not get quite off till (I think) a little after six p.m.,
the Captain taking us without any charge,
except that we paid for provisions and something to the steward,
whom we felt interested in as a serious-minded man, and who was very open,
speaking English, and liking to be with us.
We were much favoured with fine weather, and did not feel very much motion of the ship,
though there was a little "`ground swell.`"

11th.--Stavanger.
Arrived this morning about nine o`'clock.
Having to cast anchor, etc., we did not land for a time,
but reached A. Evertsen`'s at about ten o`'clock.
A+++.+++ E. who is acquainted with the coast, having been a Captain,
says we passed the worst part of the coast of Norway: it is sometimes very rough:
the king, he told me, would not come by water to Stavanger, but by land on that account.
We have cause to be very thankful in an especial manner
for the help through this journey to Quinnesdal and back,
difficulties having been represented as to its accomplishment;
Anders and S. E. never having been here, and had been unwilling before to do so +++[+++but]
difficulties seemed to vanish and the way was made easy for us,
and though we travelled through rain on leaving the valley, and I was wet to the skin,
yet no cold was taken,
notwithstanding my susceptibility thereto in getting wet and continuing in wet clothes.

In the evening we held a meeting at A. E.`'s, about fifty perhaps present.
I felt I must say that our blessed Saviour left a legacy with his disciples,
"`Peace I leave with you, my peace I give unto you,`" John 14, 27,
and was enlarged amongst these dear, loving people.
W+++.+++ C. M. was also engaged lovingly amongst us.
After this,
a solemn feeling was over us and my belief was I
must kneel and ask for a blessing upon tbese people,
but finding dear L. D. M. was under exercise, I forebore awhile, when she knelt,
and asked that we who were about to leave them, might be favoured with a safe return,
(or to that effect) and was very feelingly engaged on this occasion.
Feeling that I must kneel as before impressed to do,
I gave up thereto and was favoured with the ability desired.
My prayer for this people,
was that the Lord would bless them with the dew of heaven above and of the earth beneath;
that He would increase the strength of those who had given up to serve him,
and for those who had not opened the door of their hearts to him,
that He would knock again and again, that all might be brought into the bundle of Life,
and be gathered into the everlasting rest; ascribing all honour and renown unto him,
I took my seat.
S+++.+++ E. interpreted for both of us in our prayers.
Dear W. C. M. then rose again and taking his farewell of them,
our last meeting together was concluded,
and after each one I think shaking hands affectionately with us, they left us.

12th.--Fifth-day.
We left Stavanger by the Domino at about eleven o`'clock
a.m. several of the dear people seeing us off,
and after repeated waving of handkerchiefs we saw them no more.
Fine warm weather for our voyage.

13th.--On board the Domino.
This morning between one and half-past, awoke, and these words impressed my mind,
and my thoughts turned with brokenness of spirit towards some very dear to me:
"`They shall hunger no more, neither thirst any more,
neither shall the sun light on them, nor any heat,`" Rev. 7, 16,
and the 17th verse I think also in part,
"`For the Lamb which is in the midst of the throne shall
feed them and shall lead them unto living fountains of waters:
and God shall wipe away all tears from their eyes.`"

14th.--Seventh-day.
Off the landing stage at Hull where the Ship`'s anchor was cast
I believe at about 12:30 a.m. after a quiet and fine passage.
Reached home in the afternoon and was favoured to find all in as
good health as usual,--a favour I desire to appreciate fully:
the good Hand has indeed been with us all through this journey.

8th Month 23rd.--Left home with our friends W. C. and L. D. Meader for the Vaudois Valleys,
near Turin.
Arrived at Calais about midnight, and left on Third-day for Paris.
My brother called in the evening.
Next morning we left Paris for Culoz,
arriving there about midnight--lodged at the Hotel Mimon and proceeded for Turin,
changing trains at Modane the frontier town where luggage is examined.
A few miles from this we passed through the Mont Cenis Tunnel, about eight miles long,
which was done in about twenty-four minutes.
Arrived at Turin in the evening.

27th--Left Turin after calling at G. P. Meille`'s at Via
Pio Quinto 15. Saw his father who does not speak English,
who gave us all the information needed for our going to La Tour (Torre Pellice).
Took tickets for Pinerolo.
Arrived there and proceeded by omnibus about two hours ride to La Tour.
M+++.+++ M. of this place soon kindly called upon us,
and arranged to call tomorrow morning and conduct us to a friend of hers,
to take up our quarters there at a moderate charge.

28th.--Called in the forenoon with M. M. upon the "`pasteurs`" Bartelemy Iron, Geo.
Appia, who married a niece of the late Joseph Sturge,
and upon John Daniel Charbonnier the "`procurateur.`"
Geo. Appia laid out the visits for the coming week in the different places in the Valleys.
In the afternoon we went with M. M. to the Orphanage.
W+++.+++ C. Meader addressed them, and on taking leave I expressed a little as it presented,
to do what they know is right that they might have peace.

29th.--La Tour.
Had a meeting at the College here; W. C. Meader addressed the people at some length.
William Meille interpreted for him.
Previously L. D. Meader knelt, this was not interpreted.
When W. C. M. concluded, I arose and expressed a little in French,
feeling best satisfied to do what I might be enabled to do rather than have it translated.
At seven o`'clock a meeting was held in a room at the village of "`St.`" Jean,
a large congregation.
The "`pasteur,`" Antoine Gay, was there and speaking to the people when we went in.
W+++.+++ C. M. soon stood after there was silence.
George Appia`'s son Henry interpreted, and did it,
I thought well,--to my satisfaction as far as I followed him.
After W. C. M. sat down I was helped to relieve my
mind in French,--in answer to my prayer that,
if anything was required of me I might be enabled to do it according to the Lord`'s will.
I felt my way more open and more ability than at the previous meeting.
It being very wet this evening we went into the "`pasteur`'s`"
house where we partook of some refreshment.
Again I can say I have been helped this day also.

30th.--Very wet today.
Only W. C. M. went to Rora over the mountain from
two to three hours walk to a meeting appointed there,
L+++.+++ D. M. feeling unequal to the undertaking,
it being too wet even to ride a donkey which she might have had,
and myself feeling unequal to the walk up the mountain,
and W. C. M. quite excusing me from accompanying him.
Geo. Appia went with him as interpreter.

31st.--W. G. M. returned this forenoon fatigued with his undertaking,
having found the journey to and from Rora more trying than anything he met with in Norway.
In the afternoon we rode to Villar a village about one hour`'s ride,
and went to the house of the "`pasteur`" Matthew Gay.
His son C. Gay interpreted for W. and L. D. M. I
stood twice and expressed what I had to say in French.
"`Fear not little flock for it is your Father`'s good pleasure
to give you the kingdom,`" was revived in my mind.
Endeavoured to lay it upon them,
the need to be really possessors of the heavenly kingdom,
to occupy with the talent or talents committed to
our trust that we may be possessors of that peace,
which the world can neither give to us, nor take away from us.
After Matthew Gay had expressed satisfaction with what had been said by the strangers,
and had given something of a summary of the matter and asked for a benediction,
the meeting concluded,--a poor people from the mountain and valley,
We were comfortably refreshed at the house, and L. D. M. and I returned to La Tour.
W+++.+++ C. M. was going a walk of about forty minutes to Bobbio
where a meeting was appointed for seven o`'clock,
to return afterwards to Villar with C. Gay, and then to walk back to La Tour tonight.
Have been helped again this day.
Cause for thankfulness of heart.

9th Month 1st. Went to "`St.`" Laurent in the hamlet of Angrona to a meeting
appointed for 10:30. The "`horse is a vain thing for safety`" was expressed
and something of our views of waiting upon God explained.
Dined with the "`pasteur`" Bonnet.
Left for him some books.

2nd.--Left La Tour by carriage to Saluzzo, there to take train to Savona,
where we lodged, and left this morning by the shores of the Mediterranean for Marseilles.

4th.--Left for Nismes.
// lint-disable invalid-characters é
Called at Jules Paradon`'s office, No. 10 in the avenue leading to the "`Marie Carrée.`"

5th.--Jules Paradon called and went with L. D. M. and myself to his house where the
meeting is held at 10:30 in their schoolroom,--Paul and Lea Fabore there and a few others.
L+++.+++ D. M. much helped therein: Jules interpreted.
W+++.+++ C. M. too poorly to come to meeting.
I relieved my mind in French.
The heavens declare the glory of God, etc., shewing that his voice speaks within us,
and we must cooperate therewith, and be faithful;
that this voice is as a voice behind us, saying, "`This is the way, walk ye in it,
when ye turn to the right-hand, and when ye turn to the left.`"

No further record is left by our dear friend of this journey,
// lint-disable invalid-characters é
but by letters received it appears they went from Nismes to Congenies and Fontanés.

In reference to the visit at Nismes he wrote, "`Help was extended at this place.
Dear L. D. M.`'s exercise was productive of much labour for her,
and the penny was earned by more than one of us, I may say.`"

They were favoured to arrive at Fritchley about the middle
of the month with a full testimony to the faithfulness of
Him who had required this arduous engagement at their hands.
