== Chapter VII.

[.chapter-synopsis]
* Visits to Ayton, Penketh, Rawden, Sibford, Wigton, Sidcot and Saffron Walden Schools
* Letters to J. Briggs and J. P. Crisp
* Visits to the Meetings of Chesterfield, Heanor, Monyash, Bakewell, Matlock, Mansfield and Nottingham
* Letter to J. Briggs
* Continuation of Diary
* Letters to M. Hall
* J. P. Crisp
* R. Hall
* To one of his Sons
* Death of L. E. Gilkes
* Death of M. Rickman
* Second Visit to America
* Letters to W. C. M`'Cheane
* To one of his Sons
* J. P. Crisp
* Mary M+++.+++ Otis
* J. Briggs
* M. and A. Walmsley
* H. S. Cope
* Last Illness and Decease

1880+++.+++ 11th Month 10th.--This day I laid before our Monthly Meeting
a concern that had rested on my mind to attend Ayton Meeting,
believing the pointing of the Master`'s finger was in that direction.
Had the full unity of my friends to undertake it, which felt an encouragement to me.
Jesse Darbyshire was named to accompany me, which felt acceptable.
Have cause to be thankful to my heavenly Caretaker for the
owning granted by his living presence on this occasion.

14th.--Attended the meeting at Ayton this forenoon, and felt the owning,
precious influence of the Lord`'s holy Spirit to be present soon after taking my seat,
being gathered into a holy solemnity by the Lord`'s condescending
lovingkindness and compassion towards us.
My mind was visited with the language,
"`With my spirit within me will I seek thee early;`" I rose and gave expression thereto,
calling upon the children of the school in an especial
manner to let this be the engagement of their minds,
now in the days of their youth;
"`they that seek me early shall find me,`" being also expressed,
as the promise which is known to be realized by those who truly seek the Lord.
Rose a second time with the language of Scripture, "`He that being often reproved,
hardeneth his neck,
shall suddenly be destroyed and that without remedy,`" reminding of what is also declared,
"`My Spirit shall not always strive with man,
for that he also is flesh,`" and encouraged to bow their necks to the holy yoke of Christ,
which yokes down the transgressing nature in man and woman,
and to let the hammer which breaks to pieces, and the fire which consumes, do its work.
We dined at the school, and I came away with a peaceful mind.
O that my soul may trust in the Lord, who hath done so wondrously for me,
laying low the mountains and enabling to come away with a thankful heart.

1881+++.+++ 1st Month 12th.--Our Monthly Meeting was held today,
at which I informed Friends that I apprehended the time was now come to
lay before them a further concern that rested with me to visit some of
the meetings of the "`larger Body`" where there are schools,
naming Penketh, Rawden and perhaps some others, if way opened.
I was liberated by my friends, and Jesse Darbyshire and Thomas Davidson were named,
one or the other to accompany me.

I was favoured to feel the Lord to be very near by the precious covering felt,
of his Holy Spirit, and was engaged in our meeting for worship with the words,
"`Comfort ye, comfort ye,
my people,`" which the Lord`'s children and servants are enabled to do,
to comfort one another in spirit.

29th.--Left home with T. Davidson as my companion
to attend the meeting tomorrow at Penketh.
Reached Warrington to lodge.

30th.--First-day.
We walked from Warrington to Penketh, about three miles,
and found the meeting was to be held at the school.
After a time of wading for the Life,
my mind was accosted with the words of our holy Redeemer, "`What I say unto you,
I say unto all, watch.`"
Was graciously helped by my divine Master and fully relieved my mind amongst them all,
(the scholars and others), and came away in the afternoon, feeling clear.

During the pause in the school dining room after we had dined,
I relieved my mind of a little that seemed to gather thereon,
relating to the cause of our observing these pauses
before and after our meals,--that we might feel within,
His owning of our desire after a sense of thankfulness to the Giver of all good,
for what He supplies us with.
After being comfortably entertained by the superintendents, J. T. drove us,
first to call upon P. D. and wife, and then to the station for the train,
to return to our homes tonight.
I can again say,
the Lord has graciously heard my prayer and qualified me so to testify for Him,
the Light, the Life, the Truth and the Way, as to cause me to feel I owe Him much.
Was drawn to supplicate for his blessing upon us all,
both together and separately near the close of our meeting for worship +++[+++at Fritchley.]

2nd Month 5th.--I left home accompanied by J. Darbyshire
to attend the meeting for worship at Rawden.
Reached Wakefield,
and were met by our friend J. Briggs and very kindly entertained by him and his wife.

6th.--First-day.
Proceeded to the meeting at Rawden.
Felt it a laborious time.
J+++.+++ B. spoke in testimony to the Word which is sharper than any two-edged sword etc.,
and C. B., the superintendent of the school also spoke;
after which I felt the time was come for me to stand,
and gave utterance to what had impressed my mind, "`I will extol Thee, O God, my king,
and I will praise thy Name forever and ever,`" alluding
to the favoured experience of being enabled to do so,
addressing the scholars particularly.
Felt my mind pretty much relieved,
but words again reviving I expected to have to express them,
"`He that being often reproved,
hardeneth his neck shall be suddenly destroyed and
that without remedy,`" and not feeling quite clear,
the meeting being broken up before I felt the weight sufficient to rise,
I felt best satisfied to request an opportunity at
the sitting down of the scholars to their dinner,
when I fully relieved my mind and believe I came away quite clear.
We dined with E. Latchmore.
After dinner, during our pause I felt much helped to communicate what came before me,
alluding to the strait gate and narrow way, and Truth felt to arise with power within me,
that I could rejoice that I had been so privileged by my dear Lord and Master;
so came away fully relieved.

In the afternoon we sat down together, eight in number, in Leeds, and,
after some time of inward dryness, and labour to get down to the living Spring, were,
I trust, sensible of the Master`'s condescension to us.

7th.--I returned home, and have truly cause to rejoice,
and to feel that I owe much to my Lord.
"`What shall I render unto the Lord for all his benefits towards me,`" is a language,
I have felt during this journey, I can adopt.

12th.--I left home, accompanied by J. Darbyshire, for Banbury,
to lodge and proceed next morning to Sibford, to attend the meeting there.

13th.--Was much helped in meeting, to the full relief of my mind,
laying close upon the young people, (the scholars of the school here) and others,
the necessity of obedience to the Light, Christ, who is our Saviour,
if we follow Him in the way of his requirings.
Was much enlarged at this time, and the meeting, I believe, ended well;
found openness with the friends after meeting.
Dined at the school with the superintendent and his wife,
and was again helped in testimony at the pause after the meal.
Called upon R. Routh, the late superintendent of the school,
who had left that office on account of his health.
Called also upon R. Lamb who gave us a sincere welcome,
and expressed his satisfaction with my coming amongst them.

14th.--Reached home safely,
with a renewed feeling that it is good to serve the best of Masters,
who rewards with abundance of peace.
Blessed be his Name forever!

19th.--I left home accompanied by T. Davidson for Wigton,
to attend the meeting there the next day, which we accomplished comfortably,
arriving in the evening.

20th.--Wigton.
Meeting at 10 o`'clock.
After some considerable time I rose with what I believed was given me for communication,
and felt much opened towards the young people of the school.
Was favoured to clear my mind,
and to come away fully relieved as to what I believed to be my duty at this time.
My old friend Richard Hall was absent; but we went to his home,
and dined with his kind wife and their two daughters and one son who were at home.
Called in the afternoon upon Joseph Hall at Park Gate,
and after expressing what seemed given to leave with him, I left for Cockermouth,
and was very kindly received and entertained by I. and H. Robinson, where I lodged.

21st.--I made a few calls and left in the forenoon for Liverpool
where I spent a short time with George Glover,
and proceeded in the evening to Manchester, to my son Frederic`'s.

22nd.--Was favoured to reach home this afternoon.
Again I have cause to return thanks unto Him who is the Author of all my blessings,
and who so bountifully helps me along from time to
time and brings me home in safety and peace.
Blessed and adored forever and ever be his holy Name!

3rd Month 12th.--I again left home--this time to attend the meeting for worship tomorrow,
at Sidcot.
W+++.+++ C. McCheane joined me at Birmingham and we proceeded together.

13th.--Attended meeting at eleven o`'clock.
There were 116 scholars (boys and girls) present.
Was helped, I believe to minister that which afforded relief to my mind, and,
after dining at the school,
came away in the afternoon and reached King`'s Heath at night.

14th.--Arrived at home, thankful, I trust, for the repeated lovingkindness of Him,
whom to serve is joy and peace.

19th.--Accompanied by my son-in-law George Smith, I left home for Saffron Walden, where,
in their meeting next day,
strength and ability were renewed to testify for the Truth to the relief of my mind.
Met with an open reception from some here; we dined at the school.
My visits to the public schools here concluded.

20th.--I proceeded to London for the Continent on business.

30th.--Leaving Osnabruck this forenoon I can again lift up my Ebenezer and say,
"`Hitherto the Lord hath helped me.`"
It is good to trust in my Lord and Saviour, who is the helper of his children.

31st.--Whilst pursuing my business, the words arose in my mind with understanding,
Verily there is a God in the earth.
Surely He answers prayer, and is with the sons of men, I can say, condescending to them.

4th Month 1st--Bless the Lord O my soul, and forever put thy trust in Him,
for He doeth wonderfully for thee.
He maketh a way through the darkness.

[.embedded-content-document.letter]
--

[.letter-heading]
To James Briggs.

[.signed-section-context-open]
Fritchley, 28th of 5th Month, 1881.

[.salutation]
My Dear Friend,

It did my heart good, I think I may say, to read thy letter lately received,
and I felt a response arise within me, but have been from home for a short time;
and now I feel unwilling not to send thee a little contribution,
such as my heart dictates, and I trust that living Principle in the heart,
which visits there in all of us,
and brings forth something like the raising up from the dead,
in those that cherish and follow its dictates.
O! my dear brother, this is what is wanting--can we not say, in all of us?
the more frequent raising into the newness and freshness of Life,
that we may answer the end wherefore we have been created.
That which is raised is not to die of itself, but the Life which quickens is there,
and we do well, each one of us, when we feel it not, to be passive,
lie still and wait for the fresh putting forth--which does come, which ever has come,
and ever will come to such as wait for it;
and it is a favour indeed to know that our dependence is solely upon Him,
who is everywhere, though we know it not,
nor at all times can feel that He is present with us.

Well, dear friend, it is encouraging to know how thou hast felt lately.
Put on strength, I would say, in the Name of the Lord.
Thou knowest not how much, if thou art faithful to the fresh discoveries of Truth,
thou mayst have to do for Him, as his instrument, in the hearts to be gathered;
we have to watch and mind the openings, and if these be to tread upon fresh ground,
let us not in any wise turn therefrom,
whilst obeying the injunction to take thy shoes from off thy feet,
not standing in thy own will in anything which takes from,
or lessens the dignity of true holiness,
or of Him whose commands are all of them to be obeyed
to the acknowledging of the Truth everywhere,
and in all, through obedience to the Word in ourselves.
Perhaps I may now conclude;--my pen has moved quickly
under a precious feeling which has prompted,
and I believe I can truly say, led the way.
With much love and in a feeling of good unity with thee,

[.signed-section-closing]
I remain thy friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Jane P. Crisp.

[.signed-section-context-open]
Fritchley, 4th of 6th Month, 1881.

[.salutation]
My Dear Friend,

In a little drawing, I believe, of that love which springs from the Fountain of love,
I put pen to paper to say as much,
as that I do desire thy encouragement in the way that is cast up before thee.
I want to tell thee how it will encourage our hearts
to know thou art strengthened in thy inner man,
to hold up the standard which it does seem is given thee in thy solitary place (comparatively),
and that thou canst testify where thou art,
that blessed are those that sow beside all waters.
May this be thy case, rightly allotted thee,
even in thy quiet habitation where the altar may be raised to the glory of God,
and where He may be exalted, and some be raised up, to proclaim his everlasting praise.

I do not want to urge thee to anything that the Lord doth not call for,
or command by his blessing;
and hath not his blessing rested upon some of his
children and called and chosen ones there?
Hath He not exalted the horn, and caused the oil to flow,
and a song of praise to arise from the heart?
Did we not feel his goodness, not as the morning dew only,
but as established and never to pass away! though there may be seasons,
and there are such when He so ordereth, when his goodness seems hid from us;
but He endureth and his Name is a strong tower,
whereinto the righteous runneth and is safe.

It feels to me that in whatever position we may be, in the Divine will,
whilst bearing testimony for Him in submission to his will,
that we are to stand ready to his call, to go forth when He calls,
hearkening unto the voice of his Word; and in looking at thy position,
I cannot see thee any more restrained,
when his living Word sounds within thee or thou hears
the command to go forth where thou art,
than hitherto, more than this, that thou wouldst feel after it,
rather than as a matter of course thing shew thyself amongst those who differ from thee;
but thou know`'st in whom thou hast believed, and may thy mountain stand strong.
With our united dear love, in that which draws the living closer and closer together,

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ G. S.

--

In pursuance of the draft of love I felt constraining me,
I laid before our Monthly Meeting, held at Belper, on the 8th of Sixth Month,
a feeling of duty to attend the meetings comprising Chesterfield
Monthly Meeting of the "`larger body,`" and,
on the 12th inst.
attended (accompanied by my dear wife who was liberated
by the Monthly Meeting to go with me) Matlock meeting,
which felt to be an exercising time,
but one that proved afterwards to be instructive to myself.
I was helped to deliver that which I believed was given me to speak amongst them,
and in this respect felt peaceful and relieved.

6th Month 19th.--Accompanied by my dear wife I attended Heanor meeting,
where help was renewedly extended to hand forth what felt
to be the counsel of my gracious Helper and Putter-forth.

26th.--We attended Chesterfield meeting and I had a very open time amongst them.

7th Month 3rd.--We attended the meetings at Monyash and Bakewell.
Both felt relieving meetings,
though the first was attended with what felt hard to nature
to have to do,--to keep our seats whilst one kneeled,
whom we could not own as a Friend; felt peaceful in so doing.

10th.--Went with my dear wife to Mansfield, and attended the morning meeting there.
Went in heaviness,
but returned with rejoicing that I had been enabled
to deliver what felt to arise for them.
I believed it to be an arousing testimony and call to them,
that they might not be living in a profession merely, nor only saying "`Lord,
Lord,`" but that they might come to Him truly;
a comparison therewith having arisen in my mind,
as that of attending a meeting once or twice on a First-day,
and once in the middle of the week,
without being at other times subject to the power of Truth, in thought, word, and deed,
though I believe not so expressed as to every word.
Reached home in the afternoon.

At our own meeting in the evening we were favoured
together with the ownings of Israel`'s Shepherd.
Felt helped to encourage to that which comforts the soul and rejoices the heart of man,
with the language also, "`Comfort ye, comfort ye, my people;`" demonstrating that,
to comfort one another,
it must be with the comfort wherewith we are ourselves
comforted,--that we must know this comforting within,
which springs from obedience in the Life,
to be enabled to comfort the Lord`'s children or people.

17th.--We attended the meeting at Nottingham, and I was helped therein,
so that I was again enabled to set my seal to the truth that the
Lord helpeth those that have no ability of their own to do anything
whereby his Name is extolled in them or by them;
but blessed be his power, which is enough for all occasions.
It feels to me I have proved this,
and the desire is raised in me that I may not forget
his benefits which are so often extended to me,
a little one, entirely dependent upon the Lord.
We were favoured to reach our home peacefully in the evening,
and now concluded such engagements as I apprehended, were,
in the drawings of Gospel love, laid upon me.

19th.--I left home on my Continental journey.

24th.--First-day.
Lille.
Sat down for worship in my bedroom at the hotel here.
Instruction has, today, been sealed upon my mind in the Life.
[.book-title]#Shewen`'s Meditations,# of which I read a little this morning, were productive of good,
and strengthening to me, confirming in the Truth,
in some things referred to in the part "`Concerning Christian Worship,`" also,
in that "`On Thoughts and Imaginations.`"

8th Month 4th.--Returned home, feeling thankful I trust,
for my heavenly Father`'s care over me as one of his poor little ones,
needing his watchful care: with Him surely we are rich, every one of us.

[.embedded-content-document.letter]
--

[.letter-heading]
To James Briggs.

[.signed-section-context-open]
Fritchley, 12th of 8th Month, 1881.

[.salutation]
My Dear Friend,

Thy letter brought us into fresh sympathy with thee; but tribulation, we are to believe,
worketh patience; patience, experience; and experience, hope.
Is not this a soother in difficulties?
But I look upon what has happened to thee as all one with
what the saints (may I not say) have to suffer,
and I have believed this very thing, the effect of thy testimony,
or the testimony given thee to bear that day,
is calculated further to show thee the fallacy in believing (for any who
do so believe) that these workers will come into the true patience,
and work His works only;
but something of their own (if they be workers for
Him at all) they will mix up therewith.

We had to believe,
and to find that they would not receive our testimony before we came out from them;
and they will not receive thine.
Is it not like beating the air to contend with them?
then perhaps the present will suffice to show thee where thou art, and where they are,
and that there is a distinct line between you.
One thing I will in freedom tell thee.
It does not seem to me that a meeting for worship is the place to answer again.
But if the Master gives us anything for the people, to lay it down and leave it there,
though I am quite willing to acknowledge this may sometimes seem hard to do:
the words have sometimes been with me "`Let the potsherds
strive with the potsherds of the earth.`"
I hope thou mayst now be able to leave them with a peaceful mind.
I have been from home lately, but was back before our Monthly Meeting.
We may acknowledge to help received, the favour amongst many favours continued,
of being owned together by Him, whom to know, and in whom to believe, is Life eternal.

[.signed-section-closing]
I remain thy friend affectionately,

[.signed-section-signature]
John G. Sargent.

--

23rd.--In the evening, during our sitting together,
I felt constrained to break the silence by giving utterance to the words,
"`Make straight paths to your feet,`" saying,
how can this be better done than by the prayer being raised,
"`Lead me in a plain path because of mine enemies;`" with some addition.

24th.--Opened for our reading after breakfast at the 26th and 27th Psalms, which I read,
the words quoted last evening, "`Lead me in a plain path`" etc.,
coming thus again before us.
Is there not cause to admire, and for thankfulness, for "`line upon line,
precept upon precept,
here a little and there a little`" being brought before us in merciful condescension,
for our help and encouragement on our way?

28th.--This day have been much favoured in both meetings,
after having felt silence my place in a few of our late meetings.
Is Israel a wandering sheep?
are the words which opened upon my mind in our forenoon meeting,
the view being given me of a wandering from the valley to the barren mountain, where,
finding no pasture, there is self-feeding and self-exaltation,
having departed from the green pastures of Life; such, finding they want something,
set about to feed themselves with what the nature of man finds,
and so they become exalted therein,
the enemy transforming himself into the appearance of an angel of Light,
and thus deceiving them,
their minds being filled with that which is of the chaffy
nature of the natural man and not the spiritual food.

In the evening, under a solemn feeling of the covering of good,
was constrained to bend the knee,
and to supplicate for all the children and people of God,
that they might be drawn nearer and nearer to our heavenly Father,
not from any merits of our own, for we have none,
but through and by our Lord and Saviour, Jesus Christ.

10th Month 9th.--This morning in meeting, the opening on my mind was instructive,
"`Whom the Lord loveth, He chasteneth,
and scourgeth every son whom He receiveth;`" "`his rod and his staff they comfort me.`"
In all his afflictive dispensations can we say this, with one of old,
his rod which chasteneth, and his staff which upholdeth in affliction and distress;
and further, it was opened to my understanding, and also expressed, "`I have been young,
but now am old, yet have I not seen the righteous forsaken,
nor his seed begging bread`"--how true this is! "`A
good tree cannot bring forth evil fruit,
nor a corrupt tree,
good fruit;`" so the seed of the righteous bringeth forth that which is righteous,
(spiritually, not merely or always in an outward or natural sense,
as conveyed to my mind) this signifying the begotten of the Lord in the seed
or through the seed sown by Him in the heart,--children raised up unto the Lord,
even by those to whom the glad tidings are committed and
by whom promulgated,--spiritual children begotten unto God,
through Christ Jesus our Lord.
Not all was expressed, but the substance in part or in the whole conveyed.

10th.--Our friend L. E. Gilkes continues very ill,
and the doctor gives no expectation of her recovery; she seems to be in a very quiet,
comfortable state of mind.

On the 12th of this month was held our Monthly Meeting,
and the following day our General Meeting; both of them, I feel I can say,
were favoured seasons,
and help was vouchsafed to testify to the goodness and mercy of God to us-ward.
In the Monthly Meeting I felt constrained to supplicate for us all,
those present and absent,
and in an especial manner for our friend in her afflicted state of body,
that she and we might be enabled to say, "`Thy will be done,`" on her account.
We had a good attendance on both days.
Several communications in the ministry went forth,
I trust to the help and encouragement of those assembled.
I felt much helped in the power of Truth to minister, and my prayer was,
I fully believed, answered, that I might be so favoured,
and if according to the Divine will,
that I might be instrumental to the help of some in handing forth what He,
the Head of the Church, might see meet for this end.

[.embedded-content-document.letter]
--

[.letter-heading]
To Mary Hall.

[.signed-section-context-open]
Fritchley, 19th of 10th Month, 1881.

[.salutation]
My Dear Friend,

The information received this morning of the departure
of one whom I have loved and honoured in the Truth,
was affecting to me and my wife,
and we do closely sympathize with thee and those nearly allied, in your loss;
but we do believe the change is his everlasting gain;
inasmuch as there is no more alloy to those who die in the Lord, no more pain,
but all is joy; tribulation hath ceased to such,
and the blessed promises so full and complete, to such as walk in the Spirit,
are realized.
O! this is a blessed state, and worth striving for, whilst time is allotted to us here,
and this is the only time we have!
I have felt the importance of this much of late;
and did not expect my dear friend and brother would have been called away first,
but the time is wisely hid from us, therefore the language is more imperative upon us,
"`Be ye also ready.`"
My thoughts have been much on what is appointed to take place tomorrow;
and I have endeavoured to know what would be best for me to do
as to undertaking the journey to be with you on the solemn occasion.
I am not feeling well, and have concluded not to undertake it,
but though absent outwardly,
I trust there will be that nearness in spirit which distance cannot separate.

With dear love to thee and thine, I am

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. C.

[.signed-section-context-open]
Fritchley, 29th of 10th Month, 1881.

[.salutation]
My Dear Friend,

We have had a letter from+++_______+++, so that the way is opened by himself for communication,
which will have attention.
I trust not to be behind-hand, should it feel to devolve upon me to write,
or should the way present for it by the drawings of Christian love.
It may be I want stirring up sometimes.
Those that are made use of in the Master`'s hand to communicate of that which is good,
are favoured, but our favours are forgotten sometimes; are they not?
this I write in allusion to what may be my own case.
It does feel as if there is a precious work going forward in the Divine will;
and that we may each one live to His honour and praise in the earth,
has to be renewedly the desire of our hearts.
But what havoc the tempter of mankind does make if
we follow the inclinations of our own hearts,
The young and inexperienced in the Lord`'s ways have to know this;
and many times before they have learned true Wisdom, these,
(and older ones too) have to be deeply humbled,
as a necessary part of their education in our blessed Master`'s school.

[.signed-section-closing]
I remain affectionately, thy friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

11th Month 15th.--I left home +++[+++on business]
for France and Belgium, and perhaps Germany,
but the latter depending partly upon my strength or state of health.

20th.--Gand.
Feeling very weakly in body.
The language seemed to be extended to me, "`Thou shalt spread forth thy sails again.`"
This seemed to hold out to me the expectation, that He who has been my Helper,
will be pleased to renew my bodily powers and will enable
yet to praise Him again in the way of his service;
at the same time, it has felt to me, I could utter the prayer, Do with me what Thou wilt;
not my will, but thine be done.

Spent the day (First-day) quietly, in my room chiefly, at the hotel,
and have much to be truly thankful for.
Had my sitting for waiting upon the Lord, and, I trust,
was enabled to worship Him in spirit and in truth.
I dined yesterday with one of my customers, and his wife and two of his family:
opportunity was given to explain the ground or reason of
Friends`' deviating from the world`'s ways and customs,
in what is so peculiar and strange to those, who, are either not called,
or are disobedient to the measure of grace bestowed
for their help and deliverance from all that is evil.
My explanations were well received and we parted very friendly.

12th Month 2nd.--I returned home, thankful, I trust really so, for the favour.
I may say, "`I was brought low,
and He helped me,`" and the language was heard in my inward ear,
"`Thou shalt again tune thy harp to my praise.`"
How precious it is to feel the divine regard extended at any time,
and how comforting in our low seasons!
Through favour I am enabled to trust in my Beloved,
and to look with joy to a glorious inheritance when it shall
please my Maker to take me away from this earth,
to leave the fleshly tabernacle behind,
to glorify Him in that body which it shall please Him to give me, yea,
to sing everlasting praises to his Name, who has done so much for me.

[.embedded-content-document.letter]
--

[.letter-heading]
To Rachel Hall.

[.signed-section-context-open]
Fritchley, 21st of 12th Month, 1881.

[.salutation]
My Dear Friend,

A few lines perhaps should have been penned sooner,
acknowledging the receipt of thine giving an account of thy dear
father`'s illness and dismissal from his earthly tenement.
Well, it does feel cause for gratitude to have a sense
of the goodness and mercy of God in Christ Jesus,
the gathering home from worldly cares, or troubles of any kind,
with which we are compassed;
and I can rejoice in the belief that this is his
(the dear departed one`'s) blessed experience;
and does not the reality make us also look forward
to the glorious entering upon such a change,
through the same unmerited mercy?
(all of free grace, all undeserved), if so be we are each one striving,
through redeeming love,
to fulfill our allotted portion of duty to so beneficent a Creator,
by hearkening to the voice of his Word within us, and being faithful thereto.

This, thy dear father, I can fully believe, was concerned to do,
and I felt him very near to my spirit in the best sense;
though some difference as to our outward walk (I mean as to the Society
we were brought up in) led to our being more separated perhaps,
than we should otherwise have been,
but the dear Master looks for faithfulness to his leadings and requirements,
and dedication to Him in all He requires, so that we have to have a care not to rest in,
or be absorbed in a looking out and enquiry of "`What shall this man do?`"
but mind our own business, and do, and finish, the work He gives each one to do;
then are we truly blessed in Him, and the blessing from Him will be ours forevermore.
So trust, my dear friend, in Him; do what He requires of thee, and gives thee to do,
and thou wilt be blessed, yea,
every one is blessed that feareth the Lord and watcheth in his fear.
Let each one press after the attainment of that crown which is at the end of the race,
by doing faithfully, whilst we can do it, that which our Lord and Master gives us to do.
I trust thy dear mother bears up under her loss, and that you too, all of the family,
will prove that the taking away of an earthly parent will
increase your confiding trust in our Heavenly One.
With dear love, I now conclude, and remain thy and your sincere friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 22nd of 12th Month, 1881.

[.salutation]
My Dear+++_______+++,

I often feel languid; perhaps later thou mayst have an improved account;
whilst nevertheless,
I feel how uncertain all is here,--a little longer and we are some of us gathered hence;
and it is one of the greatest of favours to feel
a confiding hope and trust for the future,
the change that is to come.
O! this is worth living for, if anything is so.
And to know a being guided by the pillar of a cloud by day
and of fire by night (the sure Guide) is necessary for us,
if we would live godly and righteously, in Christ Jesus our only Saviour,
for we cannot save ourselves only by Him, minding his holy law in our hearts,
that which condemns for evil (in a thought even);
and gives peace when we obey its righteous dictates, saying, in effect,
"`This is the way, walk in it.`"

I want thee, my dear son, to set thy foot on solid ground;
this ground of obedience to Truth in the heart;
without we do so we are not living to God, but to and for ourselves,
which comes short of the blessed inheritance, which stands in the holy will of God,
our great and good and merciful, as well as compassionate Redeemer,--ours,
if we are redeemed from evil, the evil of the world.
All that is not according to his will is evil,
therefore the need to know his will and do it.
Do my dear+++_______+++, turn thy thoughts and thy eyes to the holy land,
that which is higher than all sublunary things, higher in the very best sense;
in comparison of which, earthly things, earthly--mindedness,
is grovelling in things of nought.

Thou mayst see I want to draw thy thoughts from earth to heaven,
the true resting place of the righteous,
but not of the unrighteous or those who do not think upon God;
"`God is not in all their thoughts.`"
This my dear+++_______+++, is a forlorn condition to be in for any, whomsoever and wheresoever.
But I do trust better things of thee than this,
and that thou dost sometimes yield thy thoughts to heavenly impressions.
Dost thou look into [.book-title]#Shewen`'s Meditations,# that I gave thee?
there is real, substantial good shewn and pointed out to the reader, therein.
All may not be understood at once, but good is there,
and I hope thou wilt open it sometimes and read.
I carried it in my pocket when I was a young man,
and riding or walking to or from my business when living in Paris,
and it was blessed to me.

Do thou likewise, and may the God of all comfort, who comforted my inner man,
open to thy understanding some of the heavenly treasures, and comfort thee also.
Thy reading this valuable little book in small portions at a time,
need not hinder thy reading regularly thy Bible.
This do regularly, even ever so little at a time, for there is a blessing in it;
and God accepteth our works, if we are devoted to that which is right, even His will.
We may not derive sensible benefit, or instruction even, each time,
but the blessing is in it, if heart and mind is given up to the Lord.
The Scriptures teach us to be humble, and whatsoever we do,
to do all to the glory of God; if this be the case,
how much may be seen that proceeds from the human heart when not seeking his glory,
which is contrariwise, against the glory of Him who has a right to demand of us our time,
that it should not be spent in vanity;
this life is vain unless we choose God for our portion here below.

[.signed-section-closing]
With dear love, thy affectionate father,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

22nd.--Feeling low in body as to the strength of the natural man,
but the Lord`'s mercies and the over-shadowing wing of divine love is extended over me,
so I have indeed cause to rejoice and bless and praise
that Power which is over every other power,
and doeth all things well.

My aunt Jane Sargent this day attains her 93rd year.
Have felt helped in sitting by her side, to speak of His goodness and mercy,
and to express what opened to my understanding,--that it
is best not to limit time to ourselves because of age,
inasmuch as the Lord can take away, or lengthen life, to the aged as well as the younger,
and that we may leave all in his hands who doeth well.
In thus leaving events unknown to ourselves, with Him, we give Him his due,
to order for us, and so we acknowledge Him in this his prerogative for life or death,
as it shall please Him.

25th.--This morning at about twenty minutes to nine o`'clock
our dear friend Louisa E. Gilkes departed this life.
She passed quietly away after a long, gradual weakening of the poor body,
in the 67th year of her age.

On the 29th her remains were interred at Bakewell after a solemn,
owning time in our meeting, where the remains were taken in.
We were preciously favoured with the owning presence of Him,
who has promised "`where two or three are gathered in my Name,
there am I in the midst of them;`" this was in great condescension verified,
and I had to testify thereto,
giving expression that it had been felt that the
gathering arm of Israel`'s Shepherd was round about.
O! what a sweet evidence to me it felt that the Lord had accepted her,
and that her spirit was with the glorified ones;
a token also that He will receive us when our time comes to quit these mortal tabernacles.
What condescending love so to manifest Himself to us,--our
ever-living Lord and Saviour and blessed Redeemer!
A large company, for a country meeting, were assembled,
and several testimonies were borne in meeting.
At the grave I felt constrained to say, "`O death, where is thy sting?
O grave, where is thy victory?`"
the victory is gained through our Lord and Saviour, Jesus Christ.
There was no other utterance at the grave;
and the remains were lowered into their final resting-place.
Soon after, the company dispersed.

1882+++.+++ 1st Month 4th.--At our meeting today,
it felt required of me to give expression to what, at the latter part of our sitting,
arose in my mind, viz., the thermometer tells of heat,
but it does not communicate or give it,--a very just
comparison with the merely nominal professor,
who can speak of that which has been, is, and may be,
but "`the Lord on high is mightier than the noise
of many waters,`" encouraging to trust in Him,
and that He will give thee the desire of thine heart.
Dear M. Rickman was with us and stood pretty directly after, in testimony,
as I understood in unison therewith.

2nd Month 14th.--This morning,
our beloved friend Matilda Rickman departed this life after a short illness,
having been confined to bed only three days; her end was peace,
and a comfortable remembrance of her is left behind.

The interment took place at Bakewell;
we had a well attended meeting by our friends and some of M. R.`'s relatives present.
We were favoured therein,
the gracious Lord and Master solemnizing the occasion with his presence,
so that heartfelt praises did, I believe,
ascend unto Him who is the God of our salvation.
I had to bear testimony that it is "`not by works of righteousness which we have done,
but by his mercy He saveth us,
through the washing of regeneration and the renewing of the Holy Ghost.`"
Was enabled to stand in a feeling of the power of the Lord, my gracious Lord and Master,
and to fully relieve my mind after a second time of rising.
The remains of our departed friend, which were brought into the meetinghouse,
were afterwards carried to the grave, and soon lowered to their final resting-place.

3rd Month 23rd.--Was at Belper meeting.
The language was revived in me and by me, "`When I was a child, I spake as a child,
I thought as a child, but when I became a man, I put away childish things.`"
The opening was, that, as in the natural, so in the spiritual,
there is a growth from childhood to man`'s estate, and that when a child,
milk is used and meat when of more mature age;
that faithfulness must be abode in at all times, that our gracious Lord and Master,
(our Master if we be his servants) may be pleased to lead us up higher;
that obedience must keep pace with knowledge,
and so we make advances in the kingdom of grace; we must keep our ranks, each one of us,
the place allotted to us individually; for, as to the soldier of this world,
if he fall back, or is not obedient to orders, it is death to him, so, spiritually,
if we are not faithful to our great Captain who goes before, it may be death to us,
as regards the spiritual life bestowed upon us.
Encouraged all assembled to be faithful, I with you, and you with me,
whatever our individual callings may be, that the blessed reward may be ours.
I felt relieved when I sat down,
but a weight came over me which I felt to be a requiring
to cast off by supplicating our heavenly Father on our behalf,
for help and strength to do his will.
A preacher from some other congregation (Primitive Methodist I believe) sat with us;
he was unknown to me.

30th.--Was at Belper meeting.
Had a few words to drop amongst us, "`He that loveth father or mother more than Me,
is not worthy of Me: he that loveth son or daughter more than Me, is not worthy of Me.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To James Briggs.

[.signed-section-context-open]
Fritchley, 31st of 3rd Month, 1882.

[.salutation]
My Dear Friend,

Our love one for another must not always be measured by frequency of correspondence,
or I should, I think, be found deficient.
I have thought of thee from time to time, with, I trust,
thankfulness for thy wonted energy and desire to be faithful in Truth`'s cause;
and I doubt not thou hast from season to season to rejoice in a goodly measure
of experience that it is good to be employed by our blessed Lord and Master.

I do desire thy encouragement and my own preservation, and that of others,
with a hope that we shall each one know our armour kept clean and bright
to the honour of Him who so graciously permits us to be his servants.
Let us praise Him in the heights and in the depths;
in the former we shall do so if we be humble enough,
and in the latter by keeping very close to the good Shepherd who careth for his sheep,
and goeth before them when He putteth them forth to war in his great and glorious Name.
Let us then be faithful stewards of the gifts He hath bestowed upon us,
and mind our heavenly calling, for it is a heavenly, or holy one,
even to do His will at all times, which is living to his praise.

[.signed-section-closing]
With our united dear love, I am thy friend,

[.signed-section-signature]
John G. Sargent.

--

4th Month 1st.--In the night, on waking, I was favoured with the words upon my mind,
I will fill thy mouth with good things:
thy youth shall be renewed as the eagle`'s. What a favour to be thus condescended to,
and especially in my weakly state of health just now!
As I write, the words arise, "`Surely He crowneth the year with his goodness,
and his paths drop fatness!`"

18th.--Self and wife went to King`'s Heath to stay over the meeting there tomorrow,
which was a relieving time in dropping therein what
I believed given for our little company.

19th.--Left in the afternoon for Knight Thorpe to
attend the little meeting there the next day.
We were favoured together,
and felt much relieved in mind after delivering what
felt to be the commission on the occasion,
particularly to the dear children.
In the evening we were favoured to reach home with peaceful minds,
and with the feeling of how much we owe to our heavenly Helper.

At our Monthly Meeting in Fourth Month I was liberated by Friends, having their unity,
to pay a visit in the drawings of Gospel love,
to the smaller bodies of Friends in America, as way may open,
and other professing Friends and their meetings, if drawn thereto.
My dear wife was also liberated with the unity of the meeting to accompany me,
and it was directed that a minute should be prepared for our next meeting.

5th Month 3rd.--At our Monthly Meeting held at Leeds
the minute was brought in and signed by the clerk,
and the General Meeting held the following day, also signified its approval,
the clerk signing its minute.
It was a favoured time, strength being given for the day,
so that we can abundantly testify to the fulfilment of the gracious promise,
"`As thy day, so shall thy strength be.`"

13th.--Took leave of my dear home circle, and accompanied by my wife,
left for Liverpool this morning,
our sons P. and A. going with us to see us off by the steamship for New York.
It is cause for thankfulness that a peaceful quiet is the clothing of our minds,
and we trust our Heavenly Father is not only leading us forth,
but that He will graciously own us all through this
journey--desiring to do his will in all things.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
On board the Alaska, Nearing Queenstown, 14th of 5th Month, 1882.

[.salutation]
Beloved Friends, W. And C. McCheane,

Having a little time,
I thought of you with the inclination to send you a few lines letting
you know we have been favoured to arrive so far on our way after
a quiet night and not feeling much the motion of the vessel.
We have it seems, above seventy saloon passengers and may take more in at Queenstown.
It is a favour to feel peaceful and quiet, though without any great aboundings.
This is, perhaps, and I am willing to believe so, a safe allotment.
Our Divine Master and Lord will be sought unto by all, wheresoever and whosoever,
and if we were not empty sometimes,
as to a sense of the gracious outpouring of His Spirit upon us, we might be careless,
and not mindful to labour for that bread, which, as the manna of the Israelites formerly,
had to be gathered fresh every day.
Think of us, dear friends;
may we keep close to the Master who does cause to lie down in green pastures,
and leads beside still waters, which enables to testify,
that the Lord is good and does not forsake His children.

[.signed-section-closing]
Farewell, with our united dear love,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

14th.--After a quiet night, we arrived off Queenstown.

15th.--Had some comfortable conversation, in the openings of Truth I believe,
with two of our fellow-passengers,
in which I felt Truth to arise and help me to testify on its behalf;
for all to be faithful to what is made manifest within,--true to their profession,
as being the way to have the spiritual eye opened to see what further is required of us,
that so there may be no standing still, which leads to going backward instead of forward.

17th.--My dear C. and self sat down awhile this morning; we had a quiet retreat,
sheltered by one of the slung boats.

18th.--Again we can acknowledge that the Lord is good,
and that his favour is round about us as a shield;
his preservation is witnessed by sea and by land.
Thoughts turn to dear ones left behind, and also to some we are going on our way to meet,
if the Lord will.
Icebergs have been seen today in the distance,
the weather feeling as cold as in winter on a dry frosty day.
What cause for thankfulness, that we are getting along safely.

19th.--No aboundings, but trust I can say, I do trust in my Saviour.

20th.--Have felt comfort in reading from the memoir of Elizabeth Collins.
My heart is made glad in a sense that the Shepherd of Israel is watching over us;
forever blessed be his holy Name, who has done and is doing so much for us.
He careth for his sheep, most truly; not one of them, I feel I can acknowledge,
even the very least of them, is forgotten by Him, and may we not say these are,
if any difference, the most watched over;
He taketh them in his holy arms and carrieth them.
O! that we may acknowledge this with humble gratitude, more and more.

21st.--It has felt to be an instructive season this morning with some of our fellow-passengers,
when matter has flowed freely, utterance being given, unexpectedly to myself,
and our gracious Lord and Master praised, I do believe, thereby,
to the relief of my mind, and the comfort and encouragement I trust, of others.
We arrived at the dock, New York, in the afternoon of today,
and to our great comfort and feelings of thankfulness to Him who has so cared for us,
we perceived our dear,
kind friends Mahlon S. and Phebe A. Kirkbride were waiting our arrival,
having come that morning from Bristol to meet us.
Surely we can say our heavenly Pilot bringeth us
to our desired haven and careth for us when there.

We proceeded to Jersey City to take train for Aurora, State of New York,
thence to proceed to our dear friend Mary M. Otis`'.
At Aurora we were met by our kind friend W. C. Meader.
M+++.+++ S. Kirkbride, who accompanied us on our way, went with us to M. M. Otis`',
where we met with a true welcome.
In the evening we had a sitting with the family, when I believe, I can truly say,
the dear Lord and Master owned us together,
and counsel was given and handed forth to the relief of my mind.

23rd.--Today we proceeded across Cayuga lake to Elizabeth Mekeels`', at Ulysses,
where we met with a cordial welcome.
In the evening had an opportunity with the family, two young men,
brothers to E. M. living with her.
The language was revived and expressed, "`Not every one that saith Lord, Lord,
shall enter the kingdom of heaven,
but he that doeth the will of my Father which is
in heaven,`" addressing the young men particularly.

24th.--Meeting day here; a comfortable neat little meetinghouse.
Perhaps thirty Friends present this morning.
Was enlarged in testimony to the relief of my mind.
We visited the families, nine in number altogether; may say I felt helped through,
and had peace.

27th.--Met +++[+++at Poplar Ridge]
in a Select Meeting capacity.

28th.--First-day.
A large gathering of Friends and others met twice today.

29th.--The Yearly Meeting (at large) commenced.
Had two sittings.

30th.--Met in the afternoon.

31st.--The Select Meeting again met.
Had close words to utter in the openings of Truth.
"`Hew Agag to pieces,`" were the words given me and left amongst us.

A meeting for worship followed this forenoon and thus closed the Yearly Meeting.
It has felt to be a time in which we have been condescended to, and owned together.

6th Month 2nd.--After visiting the families on this side,
we left our dear and kind friend M. M. O. for Bristol, accompanied by M. S. Kirkbride,
to his house.

4th.--Attended meeting here; it felt to be a laborious time, but strength being given,
I rose and delivered what felt to me to be a close communication.

7th.--General Meeting at Fallsington concluded today, having attended all its sittings.
Was enabled to relieve my mind in what felt to be the requirings of Truth,
and peace was my portion.
Have felt it to be good to attend to the little pointings of Truth out of meeting,
amongst Friends in their houses, as well as in meetings.

Attended New England Annual Meeting held at Newport, Rhode Island.
Went to Lydia A. Gould`'s with Peleg Mitchel and wife.
This Annual Meeting concluded on the 14th with a meeting for worship.

14th.--We left Newport for Centreville.
Went to the house of Paulina Foster, where we lodged.

15th.--We left P. F.`'s, accompanied by her, for Providence, to call upon Apphia Chase;
had a sitting with this dear, aged friend.
Thence we went to Lynn, Rowland Hazard meeting us at Providence to go forward with us.
We went to William Oliver`'s.

16th.--Called on Nathan Page, and returned to W. O.`'s to lodge;
had a favoured opportunity with the family before rising from the breakfast table.

17th.--Left Lynn for Vermont,
meeting with Persis E. Hallock and Susan C. Gorham by the way.

18th.--Attended meeting at Lincoln, Vermont.
Was helped therein to the relief of my mind, both companies meeting together.

19th.--To Cleora Page`'s and Daniel Gove`'s. Had an opportunity,
P+++.+++ E. Hallock and S. C. Gorham being with us,
also the widow Varney and others,--it having been felt well
to invite some Friends of the two companies together,
with a view to their uniting in their meetings; this we trust will be effected,
though there seems to be a little that hinders,
to be removed in the minds of one or more,
but harmony and love was felt to be the covering of the spirits of all, I believe.

20th.--To David Knowles, whose wife is daughter of the late Joseph Hoag.

21st.--Proceeded to Pickering in Canada, to attend the Yearly Meeting there.
Arrived at Joseph Dale`'s in the forenoon, where we took up our abode for the time.

22nd.--The Select Meeting was held, which we attended.
The Yearly Meeting closed on the 27th, and on the 28th we left Pickering for Norwich,
and went to Jesse Stover`'s.

29th.--Attended the mid-week meeting at Norwich, to some satisfaction.
It felt most comfortable to visit Friends belonging to this meeting,
which I was helped to do, with the reward of peace.
Desires were raised within me to attend to the pointings of the Master`'s
finger and not leave anything undone which might feel required.
After some provings it felt most comfortable to my mind, and my dear wife`'s also,
to attend the First-day meeting here.

7th Month 2nd.--It felt relieving to my mind staying the meeting here this day;
finished also the visiting of families, going on our way to South Norwich,
which it felt best to do, William Stover and his wife accompanying us to Adam Spencer`'s.

5th.--We attended the meeting here, (South Norwich), today; a small gathering;
was helped in the meeting, though not feeling that free flow in communication,
which would have been more to my satisfaction inwardly.
It seems hard getting along sometimes.
The way in the mind of one individual of this meeting has
I apprehend seemed somewhat blocked up towards us,
and our little company in England,
it may be from error in judgment or want of more information,
but after some intercourse and better understanding respecting us,
I think some of the prejudice has now become removed.
I trust and believe, it has been good, our having come here and attended the meeting,
as well as made a call or two.

6th.--We left South Norwich this day for Salem, Ohio,--here we arrived on the 8th,
and found a comfortable home at Daniel Koll`'s.

9th.--Attended their meeting here and felt much helped to speak, in the authority,
I believed,
which the Master giveth to his servants who wait upon Him that they may feel his presence,
and know what is his will concerning them, whether it be to do or leave undone,
so that in all things He may be glorified and our
souls may know his enriching peace meted out to them.

12th.--Monthly Meeting here,
in which I had again to feel my Lord and Master graciously vouchsafed
his holy help and I felt peace in delivering matter as it arose.
"`There is a way (I had to say) which seemeth right unto a man,
but the end thereof are the ways of death,`"--that
it must be hard for the natural man to understand,
that the way which seemeth right unto a man, can be the way of death.

13th.--Left Salem for Pittsburg on our way to Chesterfield.
Attended meeting there,
and on the 15th arrived at Chesterfield and went to Joseph Doudna`'s.

16th.--Meeting at 10:30,
and an appointed meeting for Friends and any they liked to invite, in the afternoon.
Favoured seasons.

18th.--To Elisha and Lydia Holloway`'s at Plymouth.

19th.--Attended the meeting for worship here this forenoon.

22nd.--Proceeded on our way back to Salem, and attended meeting there on the 26th.

27th.--Left Salem for Cameron, New York.

30th.--Meeting at Stephen Aldrich`'s, at Cameron.

31st.--Left for Bath.

8th Month 1st.--Meeting at Jerome Hunt`'s, at Bath.

2nd.--Left this place this morning, and arrived at Lydia Haight`'s, at Grafton,
in the province of Ontario, Canada,
and the following day had a meeting at the house in the evening.

5th.--Had an appointed meeting at Cold Creek.

6th.--First-day.
To Thurlow meeting, and to Monthly Meeting at the same place on Fifth-day.

11th.--To Bloomfield, Levi Varney meeting us and taking us to his house.

13th.--At meeting here, and helped through.

16th.--Monthly Meeting; was helped to cast off my exercise

Truth rose into dominion and the Master ruled; came away with a peaceful mind.

17th.--An appointed meeting with Friends at their meetinghouse at Kingston;
a small gathering and not much refreshed.
Left for Farmersville,
at which place had a meeting on the 20th. Was favoured
with strength according to my need,
and bent the knee near the close of the meeting.

23rd.--Arrived at Westerley +++[+++Rhode Island]
this evening.

25th.--To Hopkinton; called at Daniel Wilbur`'s and dined,
after which a religious opportunity was had; and to Samuel Sheffield`'s to tea, himself,
wife and daughter present.

26th.--Called upon Ethan Foster and wife.

27th.--Meeting at eleven; favoured therein.

28th.--We attended the Monthly Meeting;
in that for worship I was strengthened to my full peace of mind,
to deliver matter as it was given.
E+++.+++ Foster stood afterwards.
We left this afternoon for Newport, and went to our friend L. A. Gould`'s.

30th.--Attended the meeting here, and was helped.

31st.--We went, accompanied by Levi Chase, to North Dartmouth,
meeting by appointment with Friends there and of New Bedford.
James Wilbur met us and took us to meeting.
Here L. C. first stood, and I, afterwards; not a very lively time.
L+++.+++ C. stood a second time, and I knelt,
asking for an increase of strength inwardly for those in this land.
We went to Jesse Tucker`'s to dine; had some open, free conversation with Isaac Wilbur,
on the state of the Society.

9th Month 1st.--Returned to Newport, which we reached before noon;
left Newport again in the evening for Bristol.

2nd.--Reached Bristol,
thankful I trust for the help vouchsafed hitherto and safe return here.

3rd.--First-day.
Meeting here; help extended, to my peace of mind.
Came away, I trust thankful, feeling cause indeed to trust in the Helper of Israel,
who is always near--never afar off, though He may hide his face for a little while.
Again, I may say, "`Return unto thy rest, O my soul,
for the Lord hath dealt bountifully with thee.`"
Our kind companion and helper, Rowland Hazard, came on here yesterday with our luggage;
he has been a faithful friend and companion to us, and now is at his home at Fallsington.

4th.--To Fallsington Select General Meeting.

6th.--Meeting for worship and concluding sitting of General Meeting;
this has been a favoured time,
to the strengthening and refreshing of our spirits together.

7th.--To Philadelphia, and to William Waring`'s, Colora, Maryland,
in the evening +++[+++accompanied by Daniel and Mary J. Koll and Hannah Brantingham].

8th.--Monthly Meeting at Little Britain, and returned to W. Waring`'s.

10th.--First-day.
A highly favoured time.
D+++.+++ K. livingly opened in testimony, and myself enlarged therein to my full relief of mind.
Truly help comes according to our need,
both to ministers and hearers,--forever blessed be his holy Name and Arm of power,
given to those who rely upon Him for everything!
Without Him we can do nothing, but with Him we can do all that He calls for.
After meeting accompanied by W. W. went to Gideon G. Smith`'s.

11th.--Held meeting at G. G. S.`'s, with him and his family;
afterwards we went forward with W. Waring to Darlington Cope`'s.

12th.--Had a favoured opportunity after breakfast, in the family,
when matter flowed freely, to the melting of my own spirit.
We left this afternoon for an appointed meeting with Friends at London Britain;
a dry and laborious time; thence to Benjamin Sharpless`' and stayed the night.

13th.--Went this morning in company with B. S. and
his wife and daughter to meet with Elizabeth L. Chambers;
a favoured meeting in which matter flowed to my relief of mind.
We went forward to Henry Albertson`'s at Wild Orchard near Philadelphia;
H+++.+++ A. met us and took us to his house.

14th.--Had a comfortable encouraging opportunity after breakfast,
and concluded to stop here till tomorrow morning.

15th.--Went into Philadelphia to Anna Hodgson`'s.
In the evening we called upon Martha Gould,
widow of Thos.
B+++.+++ Gould.
In an opportunity of silence, her son and daughter being also present,
truth opened the way, when plain things were spoken as utterance was given.

16th.--We left Philadelphia for Hatboro`', to Hannah C. Cope`'s.

17th.--To Horsham meeting; silence was kept as regards myself,
the authority to speak amongst them not being given me; the feeling with me was,
that there should be the labouring individually for
the meat which endureth unto everlasting life,
each one gathering for themselves the heavenly manna,
instead of looking to man to be fed with words.
My place was to keep silence throughout,
and no vocal offering was my portion here during our visit at either house,
but it felt with me to give expression, in taking leave,
to somewhat of that which was given me in meeting,
as respects our gathering for ourselves,
that which the divine Master lays at our command,
or for those who will work for themselves,
by waiting upon the Lord for the holy ability which proceeds from Him.

18th.--We left this morning, accompanied by R. Hazard, for Rancocas,
to see Spencer and Anna Haines, R. H. leaving us there.

19th.--This evening, at Samuel Haines`',
ability was given to express matter after an open time of conversation,
which I trust was in the ordering of Truth.

20th.--Went to the Monthly Meeting in Olive St+++.+++, Philadelphia.
Was much favoured therein; I understood afterwards,
to the encouragement of a tried but humbled state of one, for whom,
I felt love to spring up and remain with me.

24th.--To Fallsington meeting; a time of flatness;
near the close of the meeting Life arose, and with it,
way to speak of the lovingkindness of the Lord,
his many deliverances from temptation and the power of the enemy;
"`Greater is He that is in you,
than he that is in the world,`" was impressed upon my mind and utterance given thereupon.

25th.--We left on our way for Ulysses Quarterly Meeting, New York,
accompanied by P. A. Kirkbride and Mary Moon.

26th.--Arrived this morning; were met at the station by Charles Owen,
who took us to his house.
Attended the Select Meeting in the afternoon; a favoured time,
when Truth rose into dominion.

27th.--The Quarterly Meeting was held, and concluded as to the business of the meeting,

28th.--A meeting for worship, which closed the Quarterly Meeting.
This was a trying meeting;
no life felt throughout the much speaking +++[+++by some strangers present],
but towards the close, Life sprang up, to the comfort of my mind,
and I was enabled to minister in that ability which Truth gives the Lord`'s servants,
and the dominion thereof was felt over every other thing.
O! how poor and deserted was the feeling for a time,
but may we remember there is One who looks down upon us in our distresses,
and helps every soul which cries unto Him in secret, for help.

10th Month 1st.--At W. C. Meader`'s, Poplar Ridge; a company of Friends to tea,
and many came in to spend the evening as a last farewell.
A comforting time together in solemn silence ensued before we parted,
when utterance was given to what then rested on my mind.
Dear W. C. Meader had a tendering communication to drop amongst us,
and Gilbert Weaver knelt in solemn supplication.
Again may we not say, what shall we render unto the Lord for all his benefits towards us?
We parted one from another in peace and love, (so it felt) and thankfulness I trust,
for this renewed favour of the Master`'s presence having been with us on this occasion;
one of the many for which we owe so much.

2nd.--Left on our way for Elklands, to go this day as far as Canton.
Again the precious feeling of the Lord`'s presence was with us after Scripture reading.

3rd.--Joseph Snell took us to Samuel Battin`'s; thence to his own house.

4th.--Had a comfortable time before leaving.
Attended meeting; not a refreshing time to myself.

5th.--Left for Philadelphia.

8th.--Attended meeting here both morning and afternoon;
was favoured with best help to the relief of my mind;
Joseph E. Maule also said a little which was helpful to myself.
To my great relief of mind it now felt clear to me that I must go to Nantucket.
Again I have beheld the goodness of the Lord,
in his clearing up to me in a remarkable manner what
was my duty to perform,--this I had so much desired;
that I might not step into anything without my Guide.

How wonderful are the ways of our compassionate Lord and Saviour in his dealings with us;
we have indeed cause to bless his holy hand that worketh for us,
and bringeth about that which is good and what we stand in need of.

9th.--Went to Bristol, to our kind friends the Kirkbrides.

10th.--We went across the Delaware river, to Burlington for Rancocas, to A. Haines`',
to sit with them there in their meeting tomorrow.

11th.--Attended meeting this morning; and was helped, after much wading therein,
to stand and speak that which was given me, to my peace of mind,
and I believe to the encouragement of some.
Returned to Bristol in the afternoon.

12th.--We left Bristol for Fall River on our way to Nantucket,
and arrived on the island the following day; we went to Sarah Paddock`'s,
who received us kindly.

15th.--First-day.
Meetings morning and afternoon;
strength was given to testify and declare the truth as it is in Jesus,
the Saviour of all who follow Him.
In the afternoon was again helped and felt peaceful.

The subject of holding a public meeting on this island has occupied my mind;
may I be divinely directed as to taking that step.

16th.--It was concluded for Friends to meet with us at one of their houses this evening,
our minds feeling drawn to have a conference together; may best help attend us.
We met according to appointment,
and the subject of differences existing was brought forward,
with a desire that best Help might be granted to see the way out of them and unity restored,
but no way appearing at the present time,
or disposition on the part of some to take any other course than what they seemed to see,
nothing tangibly effectual was done.
May the remarks that were dropped and the exercise on the minds of some of us,
prevail to a change of mind on some points, after patiently waiting awhile.

The subject of holding a public meeting with such of the inhabitants
of Nantucket as may be disposed to attend still presses on my mind,
and feeling that it is the will of Him whom I desire faithfully to serve,
it was mentioned to Friends, and no objection arising in their minds,
printed notices were issued to have the meeting tomorrow.
Never having before called a public meeting, it felt a weighty undertaking for me,
but I was helped to give up thereto,
under a sense that hitherto my gracious Lord and Master has never failed me of
his good presence and strengthening power to do the thing that He calls for;
accordingly I submitted and put my trust in Him.

17th.--Feeling calm and peaceful in the prospect of the meeting this evening.
Was sustained and strengthened for the occasion; there might be sixty or more present.
I felt there was great cause for encouragement,
in that we were favoured with a holy solemnity,
and matter and utterance were given to the praise of his ever excellent Name.
We had a very attentive audience, and quietness was our favoured experience; I felt,
nevertheless, poor and stripped, yet peaceful in leaving the meetinghouse.
It was considered a good meeting.

18th.--We made arrangements to leave Nantucket this morning,
and had a very fine passage across to Woods Holl, where we landed, and proceeded to Lynn,
and were met by our kind friends James and William Oliver, Jr.,
who took us to William Oliver`'s, their father, where we received a true welcome.

19th.--We had a heavenly meeting this evening,
it being crowned with the blessed Master`'s presence; I was favoured with strength,
and marvellously (to my feelings) helped to preach the Gospel.

20th.--We left our friends here and went to Centreville, to visit John and Horace Foster.
I was again helped to relieve my mind in a season of ingathering to the Lord,
when help sufficient was vouchsafed to speak for their encouragement and
faithful walk in this day of conflict and trial as a little body +++[+++of Friends.]
Comfort is my portion in the retrospect.
We left them in the afternoon for Newport.

21st.--Arrived at Newport and went to L. A. Gould`'s.

22nd.--A small company at meeting; help was given and I came away relieved.

23rd.--We left Newport and arrived the next day at Bristol at our home
there (temporarily) with our dear kind friends M. S. and P. A. K.

25th.--Went to Fallsington to attend the Monthly Meeting held there this day;
was favoured in meeting, the comfortable ownings of the good Shepherd being felt.
We remained at Fallsington, taking up our abode with T. and E. Leigh,
which felt comfortable and agreeable to our minds.

26th.--Attended the meeting and a funeral here,
in which I was helped to cast off my mite before a large gathering;
it felt to be a solemn time.
The remains were carried into the meetinghouse,
the face and upper part of the corpse being exposed to view,
which was at the close of the meeting covered with
the part of the coffin belonging to it.
This is the custom at interments here.
There ensued at the grave a time of silence and offerings.
In the afternoon we accompanied our friends M. S.
and P. A. K. to their hospitable home at Bristol.
Had a comfortable sitting this evening before leaving for Salem on our way for Iowa,
by the 10 p.m. train.
This had been on my mind some time before,--to visit the few friends at Viola, Iowa,
and any other service for my Lord and Saviour which He may be pleased to call for.
It had seemed a very great undertaking in looking forward to this journey,
so far (about 1100 miles), and so few there to visit,
but a spring of love has seemed to flow towards the
family of young people at William Hampton`'s;
and the feeling that my Lord and Master calls for my giving up thereto should be enough,
so have given up to it; encouraged by Friends to do so.
We left accordingly, accompanied by our dear friend Rowland Hazard,
who freely gives up to go with us.

28th.--Arrived at Salem,
and were taken by dear D. Koll to his hospitable and welcome home.

29th.--First-day.
A favoured time at meeting this morning.
Help was vouchsafed to my comfort and joy that my heavenly
Helper and Putter-forth doth so strengthen me;
"`The grace of God which bringeth salvation hath appeared unto all men,`" etc.,
was given me to testify to,
and other matter which I can believe it was the will
of my Lord and Master I should hand forth.
We left this afternoon on our way to Chicago and Cedar Rapids for Viola.

30th.--Reached Cedar Rapids,
and can testify to strength being graciously given for the journey;
the language has been verified up to this day, "`As thy day so shall thy strength be.`"

31st.--Much every way to be thankful for, and started again this morning,
from Cedar Rapids to Viola, about twenty three miles.
W+++.+++ Hampton has an interesting family of young people.
It did us good to meet with them.
We made calls on a few friends this afternoon and lodged at the house of one of them.

11th Month 1st.--Made a call on Oliver Hampton before returning to W. H.`'s to meeting;
felt much openness and love for those we called upon; had a good time,
after labour for the Bread from heaven, and was enlarged in testimony amongst them.

2nd.--Went to James and Louisa Doudna`'s.

3rd.--Had an opportunity with them which afforded us some relief;
they seemed much broken,
and some encouragement we hoped would be laid hold of to their comfort.
W+++.+++ Hampton called for us, to take us to Cedar Rapids on our way for Bear Creek.
After leaving the house, I became low in my mind, without knowing the cause,
which induced me to query within myself if it was well and required to go to Bear Creek.
This led to my alluding to it to my dear wife,
who I found had also been feeling in the same way.
We felt very desirous to do what was right, if to go no further,
but return to Pennsylvania, which after looking at it, was concluded upon,
to my and our relief of mind, and our dear friend W. H. left us for his home.
We accordingly returned, going the opposite way to what we had purposed.

How good it is to seek for best direction and to
mind the stops as well as the puttings forth,
that we may in all our steppings be doing our Lord and Master`'s will.
How good it is to feel our dependence upon Him,
and to know the way which we have to take sometimes
to be so different to what we may have conjectured!
A peaceful mind has been the portion of my cup since
thus turning from what I before was looking to;
all these, the turnings and over-turnings, how teaching they are!
May I not say also, "`By these things men live,
and in all these things is the life of my spirit,`" so that there is, I humbly trust,
a greater depth of experience in the Lord`'s ways attained to.
Be faithful, O my soul, to every indication of thy Lord`'s will concerning thee,
and be willing at all times to do it.
Such a journey of over eleven hundred miles to visit one family, or two,
(in Iowa) may look too great an undertaking, and the query be raised, is it required?
but do not look at the greatness of the requiring nor at the littleness of the object,
but be faithful unto the death of all in thee, that He may reign and rule to the full,
and glorify thou his holy Name in all things and at all times.

5th.--First-day.
Reached Salem,
at about four o`'clock this morning and walked to D. Koll`'s. Attended
the little meeting here to my comfort and enlargement in testimony.

8th.--Attended meeting here again today and left in peace,
taking leave of our dear friends.
Left Salem this afternoon for Philadelphia after a tendering
time with dear D. K. and his wife and daughter.

9th.--Reached Philadelphia early and went to Wild Orchard.

11th.--Went to Hatboro`' to H. C. Cope`'s.

12th.--Attended Horsham meeting; a favoured open time in testimony and supplication.

13th.--Went to Joshua Longstreth`'s;
had a feeling time there before leaving for Woodbourne to go to Charles Moon`'s.

14th.--Attended the funeral of a neighbour of C. Moon`'s; a large gathering,
many or most of them Hicksites: was favoured in testimony.
"`This is my beloved Son, in whom I am well pleased,
hear ye Him,`" was the language that opened on my mind,
and I felt helped to enlarge on the whole subject,--the coming
of our Lord in that prepared body in which he appeared,
and his second coming by his Holy Spirit in the hearts of all men, reproving them,
convincing them,
and strengthening them in the way of everlasting
salvation by our following Him in his leadings,
and obeying the still small voice in all things, small as well as great.

15th.--Attended meeting at Fallsington,
and went the next day into Bristol to our dear friends M. and P. A. Kirkbride,
where we remained until the 21st inst., when we departed for our home.

20th.--This evening we had a sitting together, J. E. Maule and a few others with us;
a time to be remembered, in which I felt drawn out in testimony,
and supplicated that our little companies everywhere might be strengthened and helped.

21st.--Nine friends accompanied us to New York, and on board the "`Alaska.`"
It was a parting season on the deck of the steamer, I hope to be remembered.
Beautifully fine weather.

22nd.--The weather somewhat changed.

23rd.--A rough sea, so as not to be able comfortably to walk the deck.

Arrived off Queenstown on the 28th,
and at Liverpool on the 29th. Much cause for thankfulness
for divine condescension on this voyage,
which was made easy for us, may I not say?
O! the goodness and love of our dear Lord and Saviour for his helping hand of power.
Who is like unto Him?
How doth He answer prayer!
Bless and praise his holy Name, who hath done so much and so great things for us.
We are now at our comfortable home at Fritchley.

No further diary appears to have been kept by our beloved friend.
After his return from America, a gradual decline of strength was very marked,
and he did not go much from home except to attend
the Monthly Meetings as they came in course.
But his deep and lively interest in the cause of Truth and righteousness,
and love for his friends, was unabated,
as the following letters which have since been collected, will evince.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 10th of 12th Month, 1882.

[.salutation]
My Dear Son,

My thoughts have been with thee at different times since the morning thou left us;
the time seemed too short that thou spent with us to enter into much feeling together,
else I could have told thee of the deep interest I have felt and do feel for thee;
I do so want thee to choose, like Mary of old did, "`that good part,
which shall not be taken away`" if thou cleaves to the measure of divine
Grace bestowed upon thee for thy salvation from every hurtful thing:
I do feel such near and dear love for thee I want thee to know somewhat thereof.
My spirit yearns over and for thee,
that thou mayst indeed choose the best life as the treasure to be desired, which,
if we possess it, makes us truly wise,
and helps us to bear the many crosses and troubles
of this life in a way that nothing else can do.

O! do give up thy own will for the will of Him who is not a hard Master to serve,
but He does indeed reward with the fresh tokens of his love,
all who serve Him first and choose him for their portion in this life.
I do feel for thee and I trust sympathise with thee in some of thy cares;
but I want thee to look to a Saviour, the only One,
who blotteth out sin and transgression if we come unreservedly to Him; that is,
being obedient to his voice within, which tells us or shows us what is sinful.
O! do, my dear son,
give up to this voice which speaks from heaven in thee and says "`this is the way,
walk in it`"; if thou hearest with an obedient ear, thy peace will flow as a river,
and thou wilt know there is a God in the earth, even in thy earthly tabernacle,
and thou wilt rejoice with the righteous and truly find that Wisdom`'s
ways are ways of pleasantness and all her paths are peace:
not that we are to expect to escape trouble in this life, but we may know that within,
in our hearts and minds, which gives content under all circumstances.

So do, my dear child, for so I feel thee,
mind the Heavenly Visitant before all and everything else.
O! how it would rejoice our hearts, thy mother`'s and mine, to see thee,
or know thee to be walking in the Truth!
Thus much, my dear+++_______+++, are the overflowings of my heart for and to thee,
who am thy very affectionate father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 18th of 12th Month, 1882.

[.salutation]
My Dear+++_______+++,

With the parcel going to you and as much love as it is possible to send thee,
I send a little matter which may be useful,
though perhaps not immediately wanted but it will not do, as I expect thou knowest,
to estimate a gift always by its intrinsic value.
We have been favoured indeed in our journeyings since the 13th of last 5th month,
and arrived safely, and well (for us) on the 29th ult., our home, I think I might say,
never looking before so attractive and comfortable.

I may say this (though our home has always been comfortable,)
under a feeling and fresh sense that our blessed Lord and
Master does seal peace and comfort on the minds of his disciples;
and He does reward with more I might say than the "`penny,`" all our offerings,
and our obedience to his requirements of whatever nature they are.
O! my dear+++_______+++, He is worthy to be served with the whole heart;
running in the way of his commandments as they are
made known to us by his Holy Spirit within us!
It has cheered my heart, my dear+++_______+++,
to find by thy letter and from some feeling I have had respecting thee,
that thou art concerned to follow so dear a Lord and Master.
Those who follow Christ the Saviour do know from an inward sense given them,
something of how it is with others who obey the Spirit and walk in the fear of the Lord.

How humbly these are concerned to tread and not to go before
the Master even though the way may look like the way.
But by baptisms we learn of Him who is the Way, and the only right and safe Way,
the only Way to the Kingdom, and that all similitudes are not for us to follow,
for indeed the enemy is very busy to find an entrance into the minds of Christ`'s followers,
and to lead them on, if he can, before their good Guide.
And how shall we know whether to follow or stand still, but by keeping the eye single,
waiting upon Him, till He is pleased to appear, when there is no halting or mistake,
for in "`Thy light we shall see light.`"
Is it not so?
Then let us be more and more willing to be as little children,
and He will teach us to walk, and to run too, if He deem well.
The Pillar of a cloud by day and of fire by night must be watched unto;
for it is the Lord`'s directing power for the true Israelite of our day,
as in days of old.
Then I would encourage thee to be faithful and follow on to know
the Lord according to His precious revealings in thee,
and thou wilt do well.

My endeared love goes with this, and I remain as ever, thy affectionate father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. Crisp.

[.signed-section-context-open]
Fritchley, 15th of 1st Month, 1883.

[.salutation]
My Dear Friend,

It feels pleasant to take the pen,
if only to send thee a few lines to let thee know I hold the same feeling of
nearness in the unchangeable Truth which has hitherto existed between us,
in the desire for the spread of the Truth, if,
as faithful servants of our Lord and Master, we may be accessory thereto,
and this we may be according to our belief, if, we are watchful servants,
seeking to know His will in all that concerns us.
We have been pleased to have dear +++_______+++ with us.
We may trust she will be preserved faithful to her Lord,
which evidently she desires to be.
I believe she is in the Way, and if kept there she will keep humble,
as will each one of us.
O! how much depends thereon, keeping humble and watchful,
and leaning upon Him who was meek and lowly in heart;
how much depends upon solid retirement, waiting upon our great Helper,
who is near to every one of us, only He will be sought unto,
and therefore He proves us for our good sometimes, by hiding as it were,
his face from us for a little while.
O! how good it is to trust so good and gracious a Lord and Master!
How does He strengthen his little ones!

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 31st of 1st Month, 1883.

[.salutation]
My Dear+++_______+++,

Thy letter was very acceptable to us both.
It is a favour to feel and know from whence all our blessings flow.
To know the shining in our hearts of the pure Light, we cannot be too thankful for;
that which shows us what we were, what we are,
and what we may be by implicitly following its holy intimations and walking therein.
All we have, all we are, if anything in the divine sight that is acceptable,
we owe unto Him who first loved us,
and is ever ready to help us and shield us from the fiery darts of the cruel one.
Let us then put on, with divine assistance,
strength in his holy Name and watch unto prayer, and we shall do well.

[.signed-section-closing]
I remain thy very affectionate father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Mary M. Otis.

[.signed-section-context-open]
6th of 6th Month, 1883.

[.salutation]
My Dear Friend,

Thou hast been affectionately in my remembrance from time to time,
and I have thought of opportunities afforded last year,
of intercourse and mingling with thyself and thy dear family,
which are pleasant to recur to.
How fast time goes, and we are so much nearer to the end of our pilgrimage journey!
Though I do not often write to my dear, kind friends, I nevertheless feel them near.
And if we are preserved walking in the Truth, what a favour!
And the dear ones too of thy household.
Do give my dear love to them all, and tell them I wish them well on their way;
now is the time, whilst they are young,
in earnest to serve the Lord in all his requirings and manifestations,
for truly there is neither work, nor device, nor knowledge,
nor wisdom in the grave whither man hasteneth.
So may we everyone of us, be quickened from day to day, by the Holy Spirit,
keeping close unto Him, our Captain and Leader, who verily is a Saviour to all,
who come unto and trust in Him.
Let us not become discouraged, nor faint by the way.
Obstacles present to our straight going-forward,
and such we are to expect in the narrow way, but our safely going along,
how does it extol Him who is stronger than all; therefore,
let us press through the crowd of hindering things,
and touch (if only) the hem of his garment, and heavenly virtue will be found therein.

Thou wilt have heard, no doubt, of the sudden departure, whilst on a visit to us,
of dear Anders Evertsen.
Is it not a warning?
"`Be ye also ready.`"
Poor Sikke E. has reached her home at Stavanger.
She was, we thought, much supported in her great affliction,
and now she will we think feel lonely indeed,
no one there walking with her as a true Friend,
though I do trust there will be those who will sympathize with her in her affliction.
Her sister (not a Friend) met her on her arrival.
She is a kind sister to her we may believe;
but may we not believe, and I think thou canst testify thereto,
that there is One who is a husband to the widow?

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Morton And Abby Walmsley.

[.signed-section-context-open]
8th of 6th Month, 1883.

[.salutation]
My Dear Friends,

We are much concerned to hear of dear M. S. Kirkbride`'s illness
and do feel also much for our dear friend P. A. K.;
no doubt nevertheless, come what may in our Heavenly Father`'s will,
she will feel the arm of support underneath.
What a precious thing it is to be enabled to say in the hour of affliction,
"`my Heavenly Father knows all things; He hath done it.`"

It is very precious to think of his quiet spirit
and movings along whilst we were in your midst;
a good savour is felt to rest with us of the good times we had together,
and desires are raised whilst I hold my pen,
that the fragrance may yet be felt in the renewings
of Life and Truth,--that which hath no end.
And you, dear friends, are not lost sight of in our remembrance.
I seem to see you, or have done so of late particularly,
seated together at the hospitable board,
where a sense of the Lord`'s goodness in the quiet pauses has been experienced.
But changes must come! and a fuller participation of the
blessed incense known if we are faithful to the end,
to Him who declared Himself to be, and was known to be, Lord and Master,
to His chosen disciples!

What a favour to know this now, that He is indeed Lord and Master!
Let us be willing therefore to continue our trust in Him,
and to fight the good fight of faith even unto the end.
Though there may be deep and angry looking waves to assail
us and threaten the overwhelming of the frail bark,
"`be of good cheer`" seems to be the language of comfort to be taken hold of,
"`I have overcome the world,`" and in the world ye shall have tribulation.
The dear young people Edward, and Emma, are near in remembrance.
I have thought of them with feelings of love and deep interest since we met and parted.
I remember the language of Truth or inspiration whilst thinking of Edward,
that men of clean hands shall grow stronger and stronger.
May this be his and their experience, as well as our own concern,
to be so found as we tread along the pathway of our being here!
Our dear love is to you all in the bond of peace,
that which maketh for peace And now with much love to you both I close my little epistle,
hoping to hear again soon, and in desire that we may, as regards our dear sick friend,
be enabled truly to say "`Thy will be done.`"

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Briggs.

[.signed-section-context-open]
Fritchley, 9th of 6th Month, 1883.

[.salutation]
My Dear Friend,

Thy letter came to hand yesterday and was acceptable to my mind,
thy feelings being in sympathy with my own, and thy remarks encouraging.
Times of proving are no doubt good for us, even to walk sometimes as in dry places;
this has seemed to be my experience for a long time, a time of drought and scarcity;
yet I trust I am thankful in being able to say, not forsaken.
Well, my dear friend, let us trust in Him at all times,
who is strength to his little ones and weak ones,
who know they have no strength of their own to take one step in the right direction.
Thou hast proved this, and hast known our Lord and Master to be thy help and shield,
and thy exceeding great reward; then trust Him still.
May we not rest assured that if He has anything for us to do, He will give the ability,
and in the right and needful time.

To know that thou hast been helped, and hast obtained relief to thy mind, is a favour,
and ought to encourage to renewed dedication in the Lord`'s service.
Let us then be true to Him; what did the prophet Habakkuk say?
"`Although the fig tree shall not blossom, neither shall fruit be in the vines;
the labour of the olive shall fail, and the fields shall yield no meat;
the flock shall be cut off from the fold, and there shall be no herd in the stalls;
yet I will rejoice in the Lord, I will joy in the God of my salvation!`"
Happy, yea, blessed experience and trust in God!
May it be ours continually,
and may nothing shake us or drive us from off the true Foundation,
not all the buffettings of the enemy who lies in wait to deceive us,
but we know what the promise of our Lord and Saviour is to those who build upon the Rock,
or what He likens such unto.
Matt. 7:24, etc., etc.

I hope thou wilt always feel free to write,
and not withhold when thou hast a drawing in thy mind.
Those who walk in the Spirit can understand one another,
and human wisdom is laid low,--below everything that flows from the Spirit.

[.signed-section-closing]
Thy friend affectionately,

[.signed-section-signature]
John G. Sargent.

--

[.asterism]
'''

On First-day the 13th of Tenth Month he was too unwell to be out in the morning,
but attended meeting in the afternoon, and was very impressively engaged,
encouraging to diligence in seeking to be ready for a never-ending eternity, saying,
that in the Father`'s house are many mansions prepared
for the righteous but not for the wicked,
and concluding with, "`Amen and Amen.`"
This closed his labours in our meeting;
he attended the usual mid-week meeting the following Fourth day, but was silent.

In a sitting in the family one evening about this time,
he expressed somewhat to the following effect:--"`If we know ourselves,
we know our entire weakness,
and the need there is for us all to obey the Saviour`'s injunction, to watch;
and what He said to the disciples of old, He at times says now;
'`Could ye not watch one hour; the spirit truly is willing,
but the flesh is weak.`' The flesh is indeed weak,
but this is no cause for fear or mourning,
but is an incentive to diligence in keeping the watch;
and the soul of the diligent shall be made rich,
rich with the presence of the Lord himself,--a joy and pleasure far,
far exceeding all that this world can offer;
as they know who are diligent in keeping the watch, knowing their own weakness.
These are crowned with lovingkindness and mercy; the Lord delights to favour these;
for these is prepared an everlasting rest, when the things of time shall be no more.`"

At the time when the following letter was written,
our dear friend`'s physical powers were so reduced that there was very little
capability for any exertion--yet his mind being clothed with heavenly love,
he was animated to address this final parting salutation, as it proved to be,
to his dear friends in America, never again taking pen in hand.

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah S. Cope.

[.signed-section-context-open]
Fritchley, 31st of 10th Month, 1883.

[.salutation]
My Dear Friend,

As my dear wife is writing to thee,
I hardly like to let her letter go without enclosing
a little greeting salutation of love,
which seems to flow from the Fountain through a poor instrument;
and may it show thee and thine and dear Mary Sharpless,
that our former greetings by bodily presence remain fresh in remembrance,
for when the love of the Master prevails, how doth it spread forth, and increase too,
if there is an abiding in his love which is divine!
I do not correspond much with my dear friends across the Atlantic,
but that will not I trust be set against me as indicating a want
of that pure love which does so truly unite the brethren;
I think of you as my friends; and how are you all just now?

I would ask.
How is it with thee, my brother, and how is it with thee, my sister?
looking beyond the things of this life.
And dost thou rejoice at seasons still, under the shadow,
and in His arms of preserving power with great delight?
I do desire a continuance of the lovingkindness and tender mercies of our Lord,
that I may know what it is to live to Him, and this I do also desire for you,
my dear friends, and that the young men may be strong,
yet humble and valiant for the Truth, which is unchangeable,
and which strengthens all who are faithful and gives them the victory over death,
hell and the grave.
But there must be a living the life to know the victory!
There must be a continued feeling that we are nothing
and that our Lord is all and everything;
then the rejoicing in Him is known and He verily is our Beloved.
Now, dear friends, farewell to each one of you as if named,
and my love is also to those I do not name,
with whom we mingled in the love of the Gospel of Life, Truth and Love.

[.signed-section-closing]
Thy and your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

The last time he came downstairs was on the day of the Monthly Meeting held at Fritchley,
the 14th of Eleventh Month.
He was not able to attend it, but enjoyed the company of a few friends after dinner,
and a solemn silence spreading over them, he revived the words, "`I was brought low,
and He helped me,`" enlarging somewhat thereon.

11th Month 28th.--Before settling for the night he expressed himself,
as nearly as could be remembered,
as follows:--"`It is a great favour that I am able to say
that I do not feel anything to stand in the way;
not that I have any feeling as to whether the end is near or not.
All is good that is permitted: his tender mercies are over all his works.
If I should be raised up it will be for a good purpose,
and if I am not raised up it will also be for a good purpose.
He is merciful, just and true in all his ways.
It is good for us to value the goodness and mercy of God, who does all things well,
as we cooperate.
I feel as one of those who have not sufficiently appreciated
the value of the goodness and mercy of the Almighty,
under whose shadow I have sat with great delight,
and have felt myself unworthy of the great peace which has been bestowed.`"

"`There is more to be known than the reading of things.
I can say, God is a God answering prayer;
this I have known when I have stood in great need of merciful assistance,
I have known it given.
I have known that fulfilled, '`Ask, and it shall be given you; seek, and ye shall find;
knock, and it shall be opened unto you.`'`"

"`I have been humbled in considering the great goodness and mercy that have followed me,
a poor worm of the dust.
The Divine condescension to poor man is very great.
We are poor indeed,--we are nothing, without Him.
His mercy is everlasting, from everlasting to everlasting.
He is worthy to be loved and served above all gods.
We cannot sufficiently commemorate his goodness and mercy.
It is not merely in times of sickness for us to do this, but at all times,
by living lives of truth and righteousness, which we cannot do but by his power;
thus we should live to his glory.`"

During that night he was seized with a slight attack of paralysis,
chiefly affecting the head and arms, but leaving his mind about as clear as usual.

On the 29th he said to his son-in-law, "`I am favoured to feel no fear,
though I have been, I suppose, one of the most fearful as to the great enemy,
death;`" he also remarked, "`I cannot presume to say what may be,`" meaning,
as to whether the end was near or not.

A friend from a distance arrived the following day, and on her entering the bedroom,
he was affected to tears, but said, "`I don`'t weep for grief, I weep for joy.
'`Goodness and mercy have followed me all the days
of my life.`' '`Mercy and truth have met together,
righteousness and peace have kissed each other`'; they go together.`"

The following expressions were also noted down during the night: "`Christ within you,
the hope of glory.
O! it`'s a precious thing to know Christ.
Let us believe in Christ,
Christ the Saviour,--Christ the Redeemer,--Christ the holy One of old.
He who visits and redeems.
No cunningly devised fable.`"

"`It`'s a great thing to be faithful,--to mind that which reproves us day by day,
to trust in the Lord with all our heart, and not lean to our own understanding,
which has always been the work of the enemy to make people do.`"

"`Lovingkindness and mercy are over all His works.
We are not to look for no pain of body in laying this body down;
we are not to look for exemption, but we are to look for His will to be accomplished,
and each one of us is to work out our own salvation with fear and trembling.`"

"`We must be faithful, yes, we must, if we would know the true joy of the Lord,
the joy of God`'s salvation.
No righteousness of our own, will stand in that solemn hour;
we must trust in the Lord and joy in the God of our salvation.`"
"`Let us fear Him; let us fear the offending of Him, the Shepherd of Israel,
the God of my life and my salvation, I truly believe I may say.`"

"`What a favour to feel no fear of death, whenever it shall please the Lord to say,
'`It is enough.`' No fear, because God is love.
We must be taught of God.
No righteousness of our own will save us; it must spring forth, emanate from,
the good will of our Saviour, He who died for us and is ever present with his children.
I have all that I stand in need of; there is no lack to them that fear Him.
My only desire is the continuance,
the continuance of the same lovingkindness and tender mercy.`"

Several times he said, "`Praise the Lord.`"
"`The Lord is good to all, and his tender mercies are over all his works,
through Jesus Christ our Lord.`"

He also said, "`We know neither the day nor the hour when the Son of man cometh,
so we must watch, and if we do, we shall pray.
Watch and pray, Watch and pray; it is needful for all.`"
"`There is no other way, but Jesus Christ our Saviour, who died that we might live.
I am a believer in Christ Jesus, the Prince of life and the Prince of peace.`"

"`We are to glorify Him in the fire; He is glorified by me,
by and through the power He gives me.`"

12th Month 1st.--One of his daughters coming to the bedside, addressing her, he said,
"`Each one of you lies close to my heart.
The instructions of the Lord are the way of life; the Star of Israel,
that sheweth the way, and is the Way, the Truth and the Life.
There is no other way; He is the Door, and all must enter by Him, who do enter.
Well, I can desire nothing better for my children than
that they should love the Saviour of men,
and be faithful to Him in all things, not in little things only, but in all things,
and be of those who love the Truth,
and attend to the manifestations of the Lord`'s requiring,
not in going before but in following the Saviour of men;
He will lead and guide them in the path of Life.
There is nothing so precious as the Truth; I can leave it +++[+++this testimony]
as a legacy,`" and signified that why he could leave
it as a legacy was because he knew for himself,
"`the Saviour of men who begets the Life.`"

At another time, he said, "`I could say farewell when the time has come,
and when the Master is come; I can truly say farewell--farewell all.
You know I desire you to fare well when the last word is spoken.`"

"`I can rejoice, rejoice evermore, I can say, Praise the Lord,
who hath wrought so marvellously for me from my youth.
It is the Lord, let Him do what seemeth Him good.
Dear ones, be faithful.`"

Hearing that one of his sons from a distance had arrived, he was much affected;
putting his hands over his face he wept,
and supplicated for him that he might entirely follow the Lord.
He again wept when+++_______+++ entered the room, embraced him with a kiss,
earnestly exhorting him to walk in the Light, as God is in the Light.

A friend coming in to see him, he advised him "`to be found waiting on the Lord,
and feeling after his help.
Wait the full time; as the Psalmist said, '`Wait on the Lord, be of good courage,
and He shall strengthen thine heart.`' Yes,
He will strengthen thine heart and weaken the enemy`'s attacks;`" and
in allusion to the stand he had made in Society matters he said,
"`I feel no condemnation in the step I have taken, by taking hold of his Arm;
and many others who have done so, can say,
The Lord is a strength and a shield to all who trust in Him;
therefore be strong and of good courage, we shall enter the good land if we faint not,
and shall know the good Hand to lead us and the Arm of power.`"

2nd.--He continued very ill;
the following are some of his expressions during the night:--"`O precious life everlasting!
God is with us.
Glorious change from mortal to immortality,
when it shall please the Lord to take me to Himself.`"
"`Praise the Lord forever and ever; his own works do and must praise Him.
He hath covered thy head in the day of battle.
He hath given thee to drink of the precious wine, of the new wine of the kingdom.`"

"`Heavenly Father, be with thy little ones, thy faithful ones, wheresoever scattered,
that they may grow and increase.
O, cause thy Truth to flourish, Heavenly Father, in the earth.
Be with me, Heavenly Father.`"

Most of his family having assembled in his room in the evening, he remarked at intervals,
"`If I have done any good thing, it has been by the operation of His power,
His grace and His gift within me.
If I have done any good thing through my life,
it has been by Christ who hath helped me and sustained me.
To Him be all the praise.`"

"`O! I do desire my dear children may hold the faith of our dear Lord and Saviour,
Jesus Christ.
Acknowledge Him before all men;
acknowledge Him in all thy ways and He shall direct thy paths.
I do desire very much that my dear family in particular
will acknowledge the Lord in all their ways.
I can acknowledge Him as being over and above all.
I have often found in my pilgrimage that I have had to be as a fool amongst men,
and I have had peace therein.`"

"`I feel something of the shackles of mortality in the body and the evidence
of sweet peace through the great mercy of the Lord Jesus Christ.
Ah, it is not by any self-righteousness that man is saved, but by the Lord Jesus Christ.
Each of us has a work to do; the ability to do it is of Jesus Christ.
He will never leave you nor forsake you.
It is an easy thing to say Christ died for me, but O that this may be understood,
'`not by works of righteousness which we have done, but by his mercy He saveth us,
by the washing of regeneration,
and the renewing of the Holy Ghost.`' These things must be practically
carried out not by works but by grace through faith.
I hope none will ever mistake me in my faith and belief in the Lord.
I know that my own righteousness will not save me,
but it is through obedience to the work of Christ in the heart.`"

"`We are children of the Most High, if we are faithful to the great Teacher,
Christ Jesus, inasmuch as we are born again,
if we are living the life of truth and righteousness by faithfulness to God and
his work,--the operation of Truth being known and yielded unto in our hearts.`"

"`It is the practical thing that is needed; none need be ashamed of owning the Truth,
but He will own us, if we own Him.
We need not make a long list of professions, but we must be faithful,
and carry out by obedience that which the Lord requires of us.`"

3rd.--He remarked; "`A precious thing is Truth;
there is no treasure on earth equal to it.`"

"`That which I have learned has been taught me by Jesus Christ, for He is the Way,
the Truth, the Life.`"

"`I must not say much, but what it is to have an easy conscience, a peaceful mind, yes,
an easy conscience.`"

At another time, "`I want nothing but what comes through the good Hand of our God.`"

"`O how good He is!
No fear.
I believe I can say, Truth hath gained the victory.
The last enemy is overcome through Jesus Christ, our Lord and Saviour.
Yes, I believe I can say, '`Rejoice not against me, O mine enemy!`'`"

4th.--This morning he said, "`I have no pain, I have peace and joy, I have joy,
yes;`" and again, in reply to being asked how he felt, he said, "`Nothing but peace;
peace and joy in the Holy Ghost,`" and later on with weeping,
"`A mixture of peace and joy.`"
In the afternoon of the same day he was heard to say, "`I have nothing to complain of;
much to be thankful for.
I have everything that I desire, and more than I deserve.`"

After this there was very little more expression that could be recorded,
the great weakness producing much of a wandering state of mind,
yet he knew all who gathered round him till very near the end,
and was very patient and loving through extreme suffering.

His brother arrived about ten hours before his decease,
and after recognizing him with much affection, he remarked,
"`we must hold fast the profession of our faith.`"
He had previously said,
"`What a favour it is to feel that we are cared for!`" and
afterwards when struggling with the conflicts of nature,
he was heard to say, "`What a precious feeling!`"

After a very severe struggle with the great difficulty of breathing, nature yielded,
and he gently drew his breath shorter and shorter,
so quietly that those nearest to him hardly knew when he
ceased to breathe on Fifth-day morning about three o`'clock,
the 27th of Twelfth Month 1883, in the 7lst year of his age,
and his purified spirit we reverently and thankfully
believe was permitted to join that great company,
who "`came out of great tribulation,
having washed their robes and made them white in the blood of the Lamb.`"

His remains were interred in Friend`'s burial ground at Furnace, Derbyshire,
on the 29th of the same month, 1883.
