[short="Testimony of Fritchley Monthly Meeting"]
== A Testimony of Fritchley Monthly Meeting of Friends Concerning John Grant Sargent, a Minister, Deceased.

"`Precious in the sight of the Lord is the death of his saints,`" of which blessed
number we believe our late beloved friend John Grant Sargent may be counted,
whom it pleased the great Head of the church to remove from
works to rewards on the 27th day of 12th month last.

Our deceased friend was born in London in the year 1813,
his parents being members of the Society of Friends.

On the expiration of his apprenticeship in this country he went to live in Paris,
where he soon left off the appearance, manners and language of a Friend,
but after a time, whilst still residing there,
he became convinced and was constrained to resume
the testimonies of Friends in these respects,
and became diligent in the attendance of meeting, though he frequently had to sit alone.

Having thus comparatively early in life been favoured to hear the Saviour`'s voice,
he was not disobedient to the heavenly vision and call,
but having put his hand to the plough,
it continued to be his concern to follow his divine Master in the way of His requirings.

After several years he returned to settle in England,
and about the year 1851 received a gift in the ministry,
which he "`exercised in the ability which God giveth,`"
his ministry not being "`with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power,`"
evincing that he "`neither received it of man,
nor was he taught it, but by the revelation of Jesus Christ.`"

In the exercise of his gift he twice visited America,
besides several other labours in the United Kingdom and on the
continent of Europe,--in which services it was clear to his friends
that he had taken "`heed to the ministry he had received,
to fulfill it.`"

He was one of those who early saw and was deeply grieved
with the sorrowful declension in the professing church,
labouring in the ability given him to uphold the ancient and sound principles and testimonies
which Friends are called to maintain;--and in dwelling under this exercise he felt constrained
in the year 1860 to write to various Friends like-minded,
inviting them to meet in conference.
These conferences were continued from time to time for about
seven years and finally resulted in the establishment,
in 1869, of a General Meeting of Friends independent of London Yearly Meeting.
Of this General Meeting for a number of years our late dear friend was clerk,
and when near his end,
in recurring to these matters,--after giving full
expression to the peaceful state of his mind saying,
"`I can rejoice, I can rejoice,
for what the Lord hath done for my soul`"--he said
"`I feel no condemnation in the step I have taken,
and many others who have done so,
can say the Lord is a strength and a shield to all who trust in Him.
Therefore be strong and of good courage: we shall enter the good land if we faint not,
and shall know the good Hand to lead us and the Arm of power,`" with more
of a similar encouraging nature which cannot well be remembered.

Still nearer his close he said,--"`If I have done any good thing
through my life it has been by the operation of His power,
His grace and His gift within me.
To Him be all the praise.`"

The cheerfulness of spirit which was so characteristic of our beloved friend,
and was largely the result we believe of that peace which follows obedience,
did not desert him in the trying illness which preceded his close,
and in the contemplation of the near approach of death,
he was able in no common degree to testify to the happiness and thankfulness
which he then felt in the sense of the Divine goodness and mercy,
the same which had followed him all the days of his life.

The lesson which the example of our dear friend seems preeminently
to teach is that of "`obedience keeping pace with knowledge.`"
"`First the blade, then the ear, then the full corn in the ear.`"
It was by diligently occupying with the little that he became ruler over much.
Devotedly endeavouring to give up to the gentle inward
manifestations of the Spirit of Truth,
and carefully keeping to that whereto he had already attained,
it was his happy and blessed experience to know a steady advancement through the different
stages of growth from the child to that of the strong man in the Lord,
yea, we believe we may say to "`the perfect man in Christ Jesus.`"

And thus walking in humble watchfulness, carefully standing in his own lot,
and endeavouring to mind his own business and welfare,
not only was he favoured to experience preservation and growth for himself,
but it fell to him in a time of uncommon danger and difficulty to be found as
a faithful watchman upon the walls,--not as one asleep and ignorant of danger,
nor yet as perceiving it,
and either hiding his light or neglecting to raise the voice of warning,
but both by example and precept testifying to what
he believed to be the path of safety and duty,
in order that Friends, as a people,
may hold fast the profession of their faith without wavering,
in integrity and simplicity.

And now, whilst mourning our loss as of a father in Israel,
we may rejoice on his account,
humbly and reverently believing the language would
apply to his ransomed and redeemed spirit--"`Come,
blessed of my Father, inherit the Kingdom prepared from the foundation of the world.`"

And we are not without hope that He,
who raised up and qualified our dear departed friend,
will also see meet to raise up and qualify more labourers to work in his vineyard.
That it may be so,
and that faithfulness in all respects may be increasingly known amongst us,
is the fervent craving of our souls.

The interment of the remains of our dear friend took place on the 29th of 12th month,
1883, at Friends`' burial-ground at Furnace Derbyshire,
in the presence of a considerable company of Friends and others.

[.signed-section-context-close]
Signed in, and on behalf of Fritchley Monthly Meeting, held at Belper,
on the 14th of 2nd month, 1884.

[.signed-section-signature]
Horatio Blake,

[.signed-section-signature]
Clerk.
