== Chapter I.

[.chapter-synopsis]
* Birth
* Parentage
* Early Impressions
* Apprenticeship
* Commences Business in Paris
* Much Perplexity with his Partner
* His Attendance of Meetings
* Dissolution of Partnership and Relinquishing Business in Paris.

[.offset]
+++[+++John Grant Sargent, the son of Isaac and Hester Sargent, was born at Paddington,
near London, in the year 1813.
When about nine years old, on the removal of his parents to Paris,
he was placed with his brother at school in England.
In the seventeenth year of his age he was apprenticed to John D. Bassett, draper,
of Leighton Buzzard.
At the expiration of his term there he went to his father`'s home in Paris.

[.offset]
Respecting this period of his life, he has left the following memoranda:]

1826.--Towards the latter part of this year I was taken
poorly while at John Everett`'s school at Islington,
and in consequence went to be under the care of my aunts at Philpot Terrace, Paddington.
I believe this was a time of religious instruction to me.
A remark made by my aunt Lydia one day,
while I was talking of some drawing which I had done,
made such an impression as never to have been effaced from my remembrance, namely,
she hoped I did not think too much of myself;
which I trust has had a good effect upon me since.

1827.--On the 26th of the 1st month my aunt Lydia accompanied me to Isaac Payne`'s school,
at Epping, the first time of my going.
I felt unwilling to part with her.
My brother Frederick joined me towards the latter part of the time.
I was generally partial to walking round the play-ground with my friend T. L.,
in preference to playing or mixing with the boys.

1830.--On the 10th of the 4th month I left school and joined my dear mother in London,
to go to John D. Bassett`'s, at Leighton Buzzard, to try as an apprentice,
which being quite disposed to for four years,
I was bound in the presence of my dear mother towards the latter part of the year.
My mother had herself procured me this place.
My friends John and Hannah Grant, living here, were very kind to me,
as also were my master and mistress.
It was a relief to my mother`'s mind my not being in Paris.
I obtained once a year a holiday of ten days,
which I generally spent with her in Gloucestershire.
I believe that during this time I was favoured with the watchful care of Providence,
and felt frequently the visitations of my Heavenly Father,
though I was not sufficiently acquainted with them at the time.
I used to like walking alone in the fields,
and was favoured to gather some strength from the
perusal of a little book given me by Anne Bassett,
called [.book-title]#Guide to True Peace,#
which I believe tended in some measure to acquaint me with the intent of silent meetings.
Towards the expiration of my time I became tired of the business,
wishing after something less confining,
which caused me to be glad when the time came for my leaving.

1834.--I left Leighton, my apprenticeship being expired, in the 9th month of this year,
having received much kindness from all my friends.
During my stay at Leighton, shortly before leaving, my aunt Lydia^
footnote:[A daughter of Isaac and Lydia Sargent, born in Wiltshire, in 1794.
She appeared in the ministry in 1827,
and her gift was acknowledged by Westminster Monthly Meeting.
In 1836 she was united in marriage to Thomas Chalk, of Kingston.
Her last illness was short but we believe it may be said,
she was found with her "`lamp trimmed, and her light burning.`"
Shortly before she expired she was heard to say, "`All things are ready,
there is nothing in the way.`"
She died in 1851, aged about 57 year.]
visited me.
It was a very agreeable visit.
She conversed with John Grant as to my future occupation,
my then not knowing what to enter upon,
and being desirous of hearing of something in England.
We sat down together in the summer-house, in the shrubbery, on which occasion,
after a little silence, I believe he spoke in relation to me,
repeating from a text in Jeremiah, "`Do you seek great things for yourself?
Do not seek them;`" which has remained with me in memory since, and I trust to advantage.

I arrived in Paris on the 4th of tenth month of this year, all being glad to see me.
I soon found it was my father`'s wish for me to remain at Paris,
and although I liked it not, there appeared no way for me to do otherwise.
I accordingly assisted my father in attending to his brickfields, etc.

1835.--In this year my father made over to me his wood-bending utensils.
I now took to the business on my own account,
but not giving up the thoughts of settling in England, whenever anything should present.
With some attention in calling upon coach-makers I soon obtained customers.

It was about this time I threw off my plain coat, not liking to appear,
as it seemed to me, singular.
I took to a frock coat as they are called, and thus I was not known as a Friend,
though I was still attached to Friends and their customs,
but did not know the real foundation and essence of their principles,
nor did I understand the leading of the Spirit.

Having now a business of my own to attend to,
I could not give so much attention to my father`'s,
I therefore thought it was right to reduce my salary, which I accordingly did.
I was in the habit of attending the Wesleyan Chapel with my sister; Robert Newstead,
minister.
On the 9th of 12th month, father and myself had to appear at the _Mairie,_
in the _rue d`'Anjou_ to give our reasons for not appearing as Gardes Nationals,
or to receive orders to appear as such.
We were by the judgment given soon after,
cleared from that engagement by papers to that effect.

My father about this time was desirous that I should enter into the brick trade,
in addition to my wood-bending, there not being much doing in the latter.

1836.--In this year I entered into partnership with Auguste Charlot,
whom my father had known something of previously.

[.offset]
+++[+++About this time commenced a daily record of his life and conduct,
from which the following are selected with a view to show forth
his watchful care that the unflattering Witness in the soul,
might make manifest all that was displeasing to Him
whom he desired to serve with the whole heart:]

1838.--2nd month, 1st.--This day I attended a meeting held at No. 24, _faubourg du Roule,_
were I met Elizabeth Fry, with her husband,
also Josiah Forster and Lydia Irving (E. Fry`'s companion).
It was a very solemn meeting.

5th.--A large meeting at eight in the evening, at Mr. Taylor`'s at No. 6, _rue Monthator;_
many present.
E+++.+++ Fry held a discourse with the Wesleyan minister,
concerning the good that is to be done and the influence of the English in Paris;
also Josiah Forster gave his ideas on the same subject.
He read a chapter, and E. Fry spoke afterwards and appeared in prayer.

11th.--Went to meeting; about 20 present.
Father saw the _Commissaire de Police,_ about a permission to hold our meeting.

[.offset]
+++[+++The following is a copy of the letter addressed by the Prefect
to the Superintendent of the Police granting this request:

[.embedded-content-document.letter]
--

[.blurb]
=== Extract from a letter addressed the 3rd of April, 1838, by the Prefect of the Police, to the Superintendent of the Police of the City of Paris and in particular of the district du Bottle.

The Minister of the Interior has directed the Prefect of the Police
to authorize the holding of meetings of the Society of Friends
twice in the week in an apartment at No. 24 _faubourg du Roule,_
subject to the following conditions, enjoined upon Mr. Isaac Sargent,
member of the said Society.

[.numbered-group]
====

[.numbered]
_1st._ Not to place any sign outside, or notice,
indicating the performance of the worship carried on by him.

[.numbered]
_2nd._ That the said meetings shall only take place on Sunday and Thursday in each week.

[.numbered]
_3rd._ Lastly,
that they shall always end and the chapel be closed at nine o`'clock in the evening.

====

[.signed-section-closing]
Delivered as a true extract to Mr. Isaac Sargent,

[.signed-section-context-close]
Paris, this 18th of May, 1838.

--

3rd Month, 11th.--First day.
Had a pleasant meeting.
Dr. Erle and Mr. Voidet and little girl present.
I went to Rev.
Toase`'s at the _Madeleine_ in the evening.

5th Month, 21st.--This afternoon I left Paris for London to attend the Yearly Meeting.
This is the first Yearly Meeting (I believe) that I ever attended,
and was at all the sittings, except the first, not being in London in time.

7th Month,
21st.--I have reason to believe that the Lord is dealing very bountifully with me,
and feel desirous of giving up to the leadings of his Spirit.

10th Month,
20th.--I have been reminded how necessary it is in order to become a follower of Christ,
to prefer Him to everything else, however pleasant it may appear,
and thus He must rank first in our desires and affections,
as "`he that loves father or mother more than me is not worthy of me.`"--Matt. 10:37.
So he that loves the pleasures of the world more than God is not worthy of Him.

12th Month, 17th.--I derived some instruction, I trust,
from reading this morning an account from [.book-title]#Piety Promoted,# of Samuel Baker Pumphrey.
I have retired this evening in my room for the space of an hour,
which I hope I shall continue to do,
and trust I may receive help at these times in solemn silent waiting upon God,
and that what I read may be blessed to my soul.

Christmas day.
I finished reading the eleventh part of Piety Promoted, having, with few intermissions,
read a portion therefrom every day since I took it in hand.
I think I may say it has afforded me instruction and encouragement in the path of duty.
I also finished reading a little tract containing "`Tender Counsel
and Advice to all those who are sensible of their day of visitation,`"
by William Penn; from which I have, I trust, gained strength and edification.
I feel how necessary it is to follow the leadings of our Heavenly Master,
and desire that He may be mercifully pleased to help me
with power from on high to overcome the will of the flesh,
in the doing of his blessed and holy will.
I believe I may say, I feel that "`the spirit is indeed willing but the flesh is weak.`"
The Lord has, I believe visited me this day, and given me to know, in some measure,
what is to be my path according to his will, namely,
a strict conformity to the principles of our Society,
in my conversation with men especially,
and I trust that this yoke may be easy in my own experience.

26th.--I have desired today that I might be found doing the will of my Heavenly Teacher,
and have endeavoured to conform myself to the plain way of speaking,
both in French and English.
I feel confident that without his aid I could never be brought to do so,
and I trust that He will continue to be my help and strength in need.

27th.--I cannot describe to the extent,
what have been my feelings this day in the view of
having to say "`thee`" and "`thou,`" etc.,
in the French language,
and I feel assured that unless the Almighty is my help I shall not be able to go on.
I this day ordered a new coat in the Friends`' form.

29th.--This day the very great importance of our
acting up to our profession has appeared to my mind,
and I have been somewhat discouraged, in a fear that I may not be found so doing,
though outwardly professing to be a follower of the Light.
May the Lord be pleased to help me on in the way, dispelling all my fears!
I have this day decided, if nothing prevents, to leave Paris for England for three weeks.

31st.--I feel that I require humbling, in order that I may take up the cross willingly,
despising the shame--that I may not shun it,
but go in the way that I am inwardly directed.
I have been made sensible, in some degree,
of the need of looking to the present and leaving the future, for indeed,
"`sufficient unto the day is the evil thereof.`"

In looking back a little upon the events of the year, now nearly expired,
I am led to think how many mercies have been extended to me.
I have this year commenced the practice of retirement every day to wait upon God,
and though I now see that I have failed much in doing so aright,
nevertheless He has frequently been pleased to humble me before Him.

1839+++.+++ 2nd Month, 10th.--First day.
Since my return from England on the 30th of last month,
I have experienced a great lack of true humility and faithfulness.
I have felt great reluctance and some repugnance to comply with what I
have believed to be required of me in consistency with our high profession.
May He strengthen me,
for I am persuaded that without his aid and life-giving presence I cannot go onward.
This day I have felt it my duty to refuse to show or allow
to be shown any goods to an individual from the country,
accompanied by two others, who wished to purchase some shafts.
They wished much to see them to day and to purchase them to morrow,
but I could not in conscience comply with their request.
They promised to come on the morrow.
I feel fully satisfied that had I complied I should have been sorry afterwards.

11th.--This morning one of the individuals who came
yesterday for goods returned and made a purchase:
thus I count I lost nothing by the refusal yesterday.

25th.--I have this day felt a need of help to conform
to what I have believed and do believe to be right,
in using the singular number in the French language in addressing individuals.
To one individual to whom I have never done so before, I did so,
but felt it very humiliating.
He did not manifest any appearance of offence from it;
perhaps it might be from his being acquainted with some of our Society.
O that I may receive help and encouragement to go on accompanied
by a renewed conviction of its being the will of my Heavenly Father!

26th.--It is, I trust my desire that I may receive help spiritually,
to discover from day to day what advancement, if any,
I have made in pursuit of the Pearl of great price, that I may inherit it and enjoy it.

3rd Month, 19th.--I called this morning at Lawson`'s Hotel,
saw Josiah Forster and the Frys.
I thought on entering the parlour I made too low a bend or bow of the head.
I much desire I may not be acting thus inconsistently with my profession,
independently of its being wrong.
I may expect it will be more observed,
now I have changed my outward appearance in public, both as to garb and conduct,
than before, and such might think I am not sincere.

27th.--This morning I called at a notary`'s about some business requiring my presence.
I was under some anxiety previously, with respect to my having to appear with my hat on,
and perhaps to address any individual personally there,
not knowing how they might receive me, in using the singular number;
but I felt satisfied on leaving at not having acted contrary to what I believed right.
I believed there was no occasion for my addressing any individual personally,
as to require the "`thee`" or "`thou.`"

4th Month, 1st.--How trying it seems to the mind,
in anticipation of using the singular number in addressing the French,
they not knowing the motive!
May I be preserved above this fear of man,
not troubling myself about anything but simply doing the will of my Heavenly Father,
is my desire.
I feel there is need for continual watchfulness,
and not giving admission to the temptations to turn aside, which so often assail me.

4th.--Had a favoured meeting at _faubourg du Roule,_ and many present,
the two small rooms being partly occupied, in addition to the large one.
Elizabeth Fry held out to us much encouragement to be faithful,
acting up to our convictions of duty;
and said it was her belief that some present were
intended in no common degree for the glory of God,
in walking uprightly before man,
to be instrumental as leaders of people to righteousness,
and to speak of his wonderful doings,--or somewhat to that effect.
May this encourage me to be faithful to the pointings of duty!

6th.--I have indeed cause to be thankful for the
help which has been extended to me this day.
That which had appeared as a mountain before me has been removed,
and I hope it will prove an encouragement to me for the future,
to rely solely on that help which is all-sufficient
to support through every trial we may have to encounter.
"`Speak unto the children of Israel,
that they go forward,`" has been brought to my mind this morning, or to that effect.
May I do thus and be found advancing in the true and everlasting way!

7th.--It is my impression that I am to be faithful to what is committed to my trust,
and then I shall have more enlargement of understanding in spiritual things.

5th Month, 12th.--First day.
Went to meeting.
Towards the evening we heard that there was a revolution in Paris.
It appears there was fighting in the _rue Bourg l`'Abbe_ and some lives lost.
The cannon were brought out, and we were rather uneasy as to the consequences.

13th.--The National Guard were called, and seeing much anxiety manifested by the public,
and hearing all was not suppressed, somewhat alarmed us.
In opening my Bible this morning the following came before me, "`Let your mercy, O Lord,
be upon us,
according as we hope in you;`" and some of the previous
verses I thought very applicable to the occasion.

17th.--On going to my brickfield I was thoughtful as to my partnership with Charlot,
and that my wood-bending business alone might be sufficient for me,
and perhaps more to my spiritual advantage than being too much cumbered with business.
For some days I have felt a secret desire to disentangle myself therefrom,
but could not think how it might be done, not knowing Charlot`'s views;
the thought came to me that later I might view it differently,
and that Providence would direct.
On sitting down with Charlot at the field he talked to me about selling
our business (to my surprise) and I thought he seemed desirous so to do,
perhaps more so on account of the liability to disturbances in Paris.
And thus a way seemed opened, when no way appeared,
and I trust I may be guided by the Almighty in all my steppings,
and that only His will may be done whether to continue
together or to dispose of the business.

8th Month, 4th.--Having been very poorly for some weeks I left Paris for sea bathing,
and concluded upon going to Swansea, my brother and sister being then at Neath,
near Swansea.

26th.--At Swansea.
In the evening, after taking tea at H. Bath`'s, the bagatelle-board was brought,
and some played, but I thought best not to join, considering it a loss of time,
and I think those games where one party performs against another are by no means profitable.

31st.--Arrived at Neath in time for tea, where we found the Burlingham`'s,
also William Moyes and daughter.
Agreeable conversation during tea with Christiana Price.
We afterwards dropped into silence.
Ann Burlingham spoke very soon, addressing me and my sister, but especially the latter,
holding out encouraging language.
Junia Price spoke, addressing the young present.
Then Richard Burlingham, who addressed me in an especial manner and very affectionately,
giving me much encouragement, and exhorting to keep in the valley of humiliation,
to persevere and be faithful in the little; said I had been remarkably visited.
What he said seemed very consoling and affected me much, and this season was, I believe,
a renewed visitation of my Heavenly Father to my soul.

On taking my leave to return to Neath with E. and F.,
when giving my hand to Hannah Price,
she signified that she had something to express to me, which was this;
"`Keep your eye single and your whole body shall be full of light.`"
It was an affectionate parting with all.

When I recur to this evening`'s visit,
I cannot but admire my Heavenly Father`'s goodness,
and believe this is an answer to my prayers.

9th Month, 8th.--At Bristol.
After meeting dined at Gawen Ball`'s, where I met Daniel P. Hack.
Had a sitting together after dinner, when D. P. Hack gave utterance to these words,
"`Times and seasons are not at our command.`"
He addressed me in very encouraging language, much more so than I thought was my due.
He quoted from Scripture,
I believe all these words,--"`The Lord is good unto them that wait for Him,
to the soul that seeks Him.
It is good that a man should both hope and quietly wait for the salvation of the Lord.
It is good for a man that he bear the yoke in his youth.
He sits alone and keeps silence, because he has borne it upon him.
He puts his mouth in the dust, if so be, there may be hope.`"
He then told me what had been my prayer;
that I had taken the yoke upon me in the flower of my youth, or age;
that I might have to witness a state similar to the Israelites at the Red Sea,
who were commanded to stand still, etc.; that he believed I need not fear;
that He "`will bless me and will keep me as the apple of the eye;`" believed
that I should have to sing the song of Zion on the banks of deliverance;
and concluded in a very solemn manner.
I was deeply affected, and trust that what was given me at that time,
though but few of the words are fresh in my memory,
"`may be as bread cast upon the waters, to appear after many days.`"

17th--I left by the "`Emerald`" steam packet at about 6 a.m. for Boulogne.
The morning was fine and we made great way on our voyage,
but towards afternoon it became cloudy and ultimately very squally, the wind very high,
and rain falling.

We were very much rocked about, but though very easily excited,
I believe I was enabled to trust in Him, and my fears seemed allayed as to consequences;
and the encouraging language which had been given me, while on my visits,
by D. P. Hack and Richard Burlingham, recurring to my mind,
I felt some confidence and assurance that I should not be cut off at this time,
but that my life would be spared.
I felt the importance of having confidence towards God at such trying times.
After sitting some time quietly in the cabin,
I heard that instead of proceeding on our course to Boulogne,
we were steering for Calais on account of bad weather,
and that it was talked of putting back to the Downs.
I was pleased that we were enabled to make our way to Calais,
as otherwise it would have delayed us longer.
I afterwards heard that we had, on one occasion, as many as six men at the helm.
We arrived safely about eight in the evening.

18th.--Rose much refreshed.
After breakfast went about luggage and passport;
was told that my passport was too old to serve,
not having been signed for coming out of England within twelve months,
and that I must go to the Consul for another.
Proceeded there in great haste.
I observed he (the Consul) appeared rather silent.
He asked me if I could not speak English.
I had addressed him in French, telling him what I needed.
I therefore then spoke in English.
He walked into another room and I followed.
He commenced writing, and then said in a low voice, and as though displeased,
"`Take off your hat,`" which I scarcely hearing, upon my asking him what he said,
he repeated it.
I told him I could not do it, that it was contrary to my principles, and that perhaps,
he was not acquainted with the Society of Friends.
He immediately said that in my own house I took off my hat.
I told him that when I went in to remain, I did so.
He put on a very grave look, and appeared very angry, but I felt above fear,
and though he said he could not give me a passport without my doing so,
I was decided in my mind not to give way, whatever might be the consequences;
but I felt very soon relieved by his saying "`I cannot see the colour
of your hair`" (or to that effect) which caused me to say that "`for that
purpose I cannot refuse,`" and accordingly took it off,
and laid it by my side.
He then took very minutely, my description, asking me whether my eyes were blue or grey,
staring at me very hard.
I felt unusual confidence and coolness, with capacity for looking him in the face,
more so than I could have supposed I could have had
with a person in his station and rank,
but I believe the Divine Arm was underneath to help me;
I paid five francs six sous for my passport.
He previously asked me my height, but not being satisfied,
he measured me against the wall where was a measure for the purpose.
I said before leaving, that I was sorry my hat had caused offence, or offended him,
and told him that for the purpose of seeing the colour of my hair I could not refuse.
He said it had not offended him.
I did not wish him to consider that I had given way, or departed from my principles.
He again repeated, that I took it off in my house, when I stated as before,
that if I remained I did so.
I think I left him somewhat reconciled.

And now it is my desire to remember the merciful
dealings of my Heavenly Father towards me,
believing that He has in mercy and love to my soul,
afflicted me (not willingly,) for may I not say that I have gone on in iniquity,
notwithstanding I have been reproved for my sin.
Yes!
I have been preferring darkness rather than light, so that I have needed chastisement.
Yet He has been pleased in this dark season of affliction +++[+++alluding
to the illness which was the cause of his coming to England]
to hand out to me by his servants, encouragement, yes,
such encouragement as did it not come from his instruments, I could not have credited it,
no, not for a moment.
Thus, though I have been brought low, He has helped me and sustained me.
I have been told of the belief that I need not fear, that He will keep me,
that He will bless me.

O then may I seek his presence daily, to serve Him faithfully,
and never forget the love that He has shown me!
I have during this sickness been brought into great fear and much trouble;
but throughout I believe I have seen the Divine Hand underneath to support me.
On one occasion, on rising in the morning, I opened my Bible at the 38th Psalm,
which I believed as I proceeded reading, was shown unto me, with the feeling given,
that "`Your arrows stick fast in me, and your hand presses me sore.
There is no soundness in my flesh because of your anger;
neither is there any rest in my bones because of my sin.
For my iniquities are gone over my head: as a heavy burden they are too heavy for me.
My wounds stink and are corrupt because of my foolishness.
I am troubled; I am bowed down greatly; I go mourning all the day long.
For my loins are filled with a loathsome disease: and there is no soundness in my flesh.
I am feeble and sore broken: I have roared by reason of the disquietness of my heart.
Lord, all my desire is before You; and my groaning is not hid from You.
My heart pants, my strength fails me: as for the light of my eyes,
it also is gone from me.`"
And my earnest prayer was I believe--"`O Lord, rebuke me not in your wrath,
neither chasten me in your hot displeasure.`"
"`For I will declare my iniquity; I will be sorry for my sin.`"
"`Forsake me not.
O Lord: O my God be not far from me.
Make haste to help me, O Lord my salvation.`"
While under great trouble, the 130th Psalm also coming before me,
I felt that it was for me "`If you, Lord, should mark iniquity, O Lord,
who could stand?`"
May this time be remembered by me and blessed to me, is the fervent prayer of my heart,
and may his purpose be accomplished in me!
May I become whatever He is pleased to make me, as clay in the hands of the potter,
for I believe his desire is towards me that I should live and magnify his great Name,
both now and forever!

Since my return I think I may say, and I trust it is with thankfulness,
that I have been daily gaining strength, and feel a pleasure in my employments.
I trust I have not forgotten Him who has thus helped me.
He has rapidly raised me up, (the hand that afflicted me, though not willingly),
for which I feel there is cause for me to acknowledge Him in all my ways,
and to serve Him with greater faithfulness.

I have adopted a new plan here with respect to the distribution of my time,
which I consider more profitable and more comfortable.
I rise at six: spend a short time in silent waiting,
afterwards read from my Bible a chapter from the Old and then from the New Testament,
referring to the references: then, after keeping silence a few minutes,
I go from my chamber at half-past seven; walk round to my workshop,
and return to breakfast at eight.
Afterwards, I read a text for the day from a book compiled from the Scriptures by E. Fry.
Then, about nine, pursue my necessary calling in business,
whether at Paris or in visiting my brickfield at the _Porte al`' Anglais;_
return home to dinner at two; necessary occupations in business,
out or at home in my office or sitting room at the _Rond Point,_ commencing about three:
retire for silent waiting, and reading some part of the Scriptures,
generally such as not read in the morning, at six o`'clock till seven:
return to take my last repast, after which,
occupy myself till bed time or till I am weary,
with reading some interesting and instructive work.

10th month, 3rd.--I received an assignation to appear on the 7th of this month,
at the Commercial Tribunal to affirm to an account
against +++_______+++ Coach-builder in the _Champs Elysees,_
lately failed.

4th.--The assignation received yesterday has much occupied my mind as my religious
principles are such that I feel I cannot go with the multitude in giving that
honour to man (the uncovering of my head) which I give to God,
neither do I consider it lawful to take the oath, as expressly forbidden by my Saviour.
May He be pleased to direct me!
The letter expresses that if I cannot attend on that day myself,
I can send my _fonde de pouvoir._
I feel that I cannot authorize another to do what I would not do myself.

5th.--I attended to a summons for this morning to
// lint-disable invalid-characters é
appear at the _Agréé`'s_ of the _Tribunal de Commerce,_
to receive 20+++%+++ upon a bill due last month,
as arranged with on account of suspension of payment.
I felt no reproach of conscience on retiring from the office of the _Agree;_
having been preserved, I trust faithful in what was right, not fearing man;
keeping on my hat, though several others were present, and all uncovered.
May He continue to be my help and strength at all times!
The _assignation_ for the day after tomorrow still occupies my mind.
I hope to be divinely directed,
not in any way to shrink from doing my duty and standing faithfully at my post.

7th.--It is my prayer this morning that my Saviour will
be pleased to be with me and stand by me this day;
a sense of my duty to Him, to stand faithful, being upon my mind.
I read in usual course this morning the vii.
chapter of Deuteronomy which appeared to me very applicable
and suitable as an encouragement for this day.
Among my references from the same chapter,
was the following "`Be strong and of good courage, fear not nor be afraid of them;
for the Lord your God, He it is that does go with you:
He will not fail you nor forsake you.`"
This I receive from the hand of the Lord for my encouragement.

I was at the Commercial Tribunal entrance-room a few minutes before eleven.
Between eleven and twelve o`'clock the creditors of +++_______+++ were called to go in.
I waited till nearly all had entered, when I entered also.
Before I had taken my seat, the officer of the court told me in a low voice,
to take off my hat.
I told him I could not for a conscientious motive;
he then stepped up to the judges and communicated it to them,
and returned and signified as he passed me, that I was at liberty to keep it on.
I waited a few minutes, when after some other names, mine was called.
I walked slowly towards the Tribunal.
I was asked whether it was not 256 francs was due to me.
I said, yes; was then told to sign a paper whereon the sum was signified,
which I did accordingly:
then the President (Roussel whom I knew) said that
first of all he must tell me to take off my hat.
I told him I could not, that it was for a conscientious motive (_motif de conscience_):
he then no further alluded to it, but assented by a movement of the head.
I believe he then asked me to affirm.
I told him I would affirm after our simple form of affirmation or to that effect,
which he first said there was no occasion for,
but the person next to him leaned forward as if desirous to have it,
and then himself (the President) also.

// lint-disable invalid-characters é
I accordingly affirmed thus:_ Moi John Grant Sargent un de la Société des Amis, dits Quakers,
// lint-disable invalid-characters é
j`'affirme et déclare solennellement, sincérement, et en vérité (or avec vérité)
que cela m`'est du_ (meaning the sum owing to me) with which he seemed quite satisfied.
On leaving I told him I was _reconnaissant pour la faveur,_
acknowledging the favour of their passing by the departure from the usual custom,
as indeed he was very lenient towards me: he then enquired after my father,
and I left the court without any feeling of reproach,
believing I had acted up to what was required of me.
May I be reminded constantly of my Heavenly Father`'s help extended to me,
and thus always put my trust in Him, whatever difficulty may present!

9th.--Made an appointment to meet an architect at his house, about bricks for Corbeil.
Was strengthened to uphold my principles there,
notwithstanding it was somewhat humbling to me; the more so,
as on my entering his room he took off the cap he had on his head:
he afterwards replaced it, I supposed because I kept on my hat.
I after a while took off my hat, being warm and supposing I might stop a time.
He became very free, though at first he appeared rather reserved,
I think on account of my hat.
I had occasion to use _tu_ (thou) to him,
and thought he became at once more familiar and open with me.

10th.--Meeting morning.
I sat alone, Ann Knight^
footnote:[Ann Knight was a Friend from England who spent much of her
time in Paris in promoting objects of interest and benevolence,
chiefly, it is believed, in aiding the circulation of the Scriptures,
and in spreading information to promote the abolition of slavery.
The room used as a meeting room was in her house at _faubourg du Roule._]
having left last Second-day.
I was favoured to feel His presence with me, for which I trust I feel thankful.

12th.--This morning I was helped to bear the cross for which I feel thankful.
To use the plain language to strangers is at times trying to me,
but I am favoured to feel that His yoke is easy and His burden light.
May this continue to be my daily experience!

14th.--Was rather high in spirit and not sufficiently forbearing
with an individual today whose manner is sometimes rather irritable,
but who perhaps does not mean it.
Prayed to my Heavenly Father that I might be able to overcome this spirit.
I have been enabled to see more clearly into the nature of the cross;
it being necessary to keep us humble,
as when too much at ease and the way without some obstructions,
there is a liability to forget our good Guide.

17th.--This morning early when scarcely awake,
these words or similar were impressed on or uttered to my mind,
"`If you continue under his guidance, you shall possess the enemy`'s gate.`"
May I be found walking only according to his Light planted in my soul,
is my sincere desire at this time.

18th.--While walking out today, these or similar words came before my mind.
"`Go your way for this time,
at a more convenient season I will send for you,`" which
are nearly the same as those used by Festus to Paul.
May I not consider myself when so busy in my own thoughts,
as in a sense saying so to my Heavenly Master?

19th.--Was not sufficiently guarded in a little contention with Joseph at the brickfield,
asserting too strongly that of which I was not sufficiently certain.
My Heavenly Guide checked me at the time,
but in the heat of our conversation I did not give sufficient heed thereto,
letting a degree of pride have the ascendency,
not being willing to appear as indeed I am, ignorant, in the sight of my partner.
May I be more cautious in future and be willing to be anything
or nothing in the sight of man as there may be occasion!

This scripture has come before me in course this evening from Proverbs 13:3,
"`He that keeps his mouth, keeps his life:
but he that opens wide his lips shall have destruction,`" and from references to xxi.
23, "`Whoever keeps his mouth and his tongue, keeps his soul from trouble.`"
I feel that this is good caution to myself,
having been very remiss today with using my tongue too freely.
Again, from chapter xiii.
10, "`Only by pride comes contention: but with the well-advised is wisdom.`"

20th.--Rose later today on the reflection of its being First-day.
Why should I be later today than on another day?
I have seen the evil result:--hurried in my duties of the morning.
For the future I will endeavour to rise as early as on other mornings;
and may the need thereof be borne in my remembrance!
Sat alone at _faubourg du Roule._
Joshua Wheeler brought me a letter from John Hodgkin; was pleased with it,
and derived encouragement therefrom.
He concludes thus: "`The remembrance of your too short visit lives pleasantly with me.
May you hold on your way--watchful, humble, trustful, and at times, rejoicing.
Farewell, says your affectionate friend.`"

21st.--I feel a desire to be more humble and to walk closer with my God,
my shortcomings and lack of watchfulness being very manifest to me.

24th.--Believe my Heavenly Father helped me in prayer today.
Sat alone at _faubourg du Roule:_ found my thoughts very troublesome,
but believe He was near me.
A few minutes for retirement and watching unto prayer
in the middle of the day I believe to be strengthening;
but it is indeed necessary to be always on the watch.

25th.--Supplicated my Heavenly Father that He would restrain my wandering thoughts.

26th.--Am fearful I lose ground,
but trust my Heavenly Father will keep me from wandering from Him.
I trust this is my daily prayer.

27th.--First-day.
Rose as purposed without making any excuse for lying longer, it being First-day morning.

31st.--Sat alone at _faubourg du Roule._
Felt that my Heavenly Father`'s presence was with me.
My thoughts are a hindrance to the Word of life within me.
Read this evening xvi.
Proverbs, 3rd verse, encouraging to me:
"`Commit your works unto the Lord and your thoughts shall be established.`"

11th Month, 1st.--Daniel Wheeler^
footnote:[Daniel Wheeler was born in 1771,
and was originally a member of the Church of England (so called).
In his early years he entered the Merchant Service, and then the Royal Navy;
being paid off, he afterwards entered the Army, and after enduring much hardship,
it being war time, he quitted it, and settled in Yorkshire in 1796.
He became convinced of Friends`' principles, and was received into membership in 1797,
and in 1816 was acknowledged as a minister in the Society of Friends.
Under an apprehension of duty he offered himself to the Russian
Government to superintend agricultural improvements near Petersburg,
which were being carried on under the auspices of the Emperor Alexander,
between whom and Daniel Wheeler mutual esteem existed.
Leaving Russia in 1832, after a stay there, off and on, of about 14 years,
he gave up under a feeling of duty to visit the Australian Colonies, Tasmania,
New Zealand, and most of the Islands in the Pacific Ocean,
an arduous engagement which occupied him until the year 1838.
He felt it required of him again to go forth on his Master`'s service,
to visit Friends in some parts of North America,
but returned to Europe in 1839 before the completion of his concern,
on account of the rapidly declining state of his son Charles`' health,
who had been removed to Germain near Paris, and who died there shortly afterwards.
After this event Daniel Wheeler returned to America, where his health gave way,
and he died in 1840, aged 68 years.]
arrived at our house, having come from America via England, to see his son Charles.
I did not see him, being out.

3rd.--First-day.
Went to _Germain-en-Laye_ to friend Wheeler`'s. Sat down together,
excepting Daniel Wheeler and his daughter who were with Charles;
had hoped Daniel Wheeler would have been present.
Again sat together in the evening:
the only addition to our little company was Sarah Wheeler.
The little disappointment of Daniel Wheeler`'s not sitting with us has brought
to my mind the necessity there is for depending upon God and not upon man.
Have felt the Divine presence near me today and his preserving care extended towards me.

4th.--I received a letter today from my aunt Lydia Chalk, which gave me much pleasure:
in it she says,
"`The improved account you gave me of your health
was a source of great satisfaction to us,
also that you found things going on favourably at home,
as affording an evidence that you were in your right place when absent.
You have indeed renewed cause to be encouraged to an unreserved
dedication of heart unto Him who is so abundantly caring for you,
to trust in Him with all your heart,
'`and to acknowledge Him in all your ways.`' Thus you will be safely directed,
guarded and kept,
and reap that sweet peace with which the faithful are plentifully rewarded.
I cannot but reflect with grateful feelings on our late interaction
together in the society of some dear friends with whom we were
permitted to be closely united in the bonds of religious fellowship;
this as a little '`brook in the way`' might be accepted
by us as a fresh token of our Heavenly Father`'s love,
which, whether immediately or instrumentally flowing unto us,
ought to incite in our hearts the return of love, gratitude, and praise.`"

In another part of the same letter she says,
in allusion to a pamphlet she had given to my sister for me,
"`I think there are good reflections and resolutions contained in it;
but do not know at all by whom written.
I quite unite with him in the belief that unless what is conferred upon us,
is from the Divine hand, it cannot prove a blessing to us,
and that we are to be thankful to an infinitely-wise Providence, whose ways are perfect,
both for what He denies, as well as for what He gives;
who does not indeed '`willingly afflict,`' but who chastens us that we may be
partakers of '`his holiness,`' and thereby become prepared to enjoy his presence,
and wherein He is glorious, as the Scriptures testify, '`Glorious in holiness,
fearful in praises doing wonders.`'`"

6th.--Feel that I fall short of that true humility
which is necessary to a walking with God.
Felt it right today to tell our clerk that I was unwilling to furnish bricks for a theatre,
for which he had been making application, and that I wished him not to go there.

13th.--This morning I have not attended to the words of our Saviour,
and the enforcement of them upon me by H. Price, when in Wales,
"`Keep your eye single and your whole body shall be full of light;`"
for while I am heeding what man may think of me,
in my doing this or that, my eye is not single unto Him who requires such things of me.

Read from William Penn`'s advice to his children called [.book-title]#Fruits of a Father`'s Love:#

[quote]
____
Fear God: show it in desire, refraining and doing.
Keep the inward watch: keep a clear soul, and a light heart.
Mind an inward sense upon doing anything.
When you read the Scripture remark the most notable places,
as your spirits are most touched and affected, in a common-place book,
with that sense or opening which you receive; for they come not by study,
or in the will of man, no more than the Scripture did;
and they may be lost by carelessness, and overgrowing thoughts and business of this life;
so in perusing any other good or profitable book; yet rather meditate than read much.

In conversation, mark well what others say or do, and hide your mind, at least till last;
and then open it as sparingly as the matter will let you.
A just observation and reflection upon men and things, give wisdom;
those are the great books of learning seldom read.
The laborious bee draws honey from every flower.
Be always on your watch, but chiefly in company;
then be sure to have your wits about you, and your armour on: speak last and little,
but to the point.

Return no answer to anger, unless with much meekness, which often turns it away.
It is a wrong time to vindicate yourselves,
the true ear being then never open to hear it.

Cast up your incomes and live on half,--if you can, one third;
reserving the rest for casualties, charities, portions.

Be plain in clothes, furniture, and food,--but clean; and then the coarser the better:
the rest is folly and a snare.
Therefore, next to sin, avoid daintiness and choiceness about your person and houses;
for if it be not an evil in itself, it is a temptation to it;
and may be accounted a nest for sin to brood in.

Be sure to draw your affairs into as narrow a compass as you can,
and in method and proportion, time and other requisites proper for them.
____

Read this evening the 4th verse of the xvii.
chapter of John, "`I have glorified You on the earth;
I have finished the work which You gave me to do.`"
May I do the work which my Heavenly Father may be pleased day by day to give me to do,
that He may be glorified by me according to the measure
with which He may enable me to glorify Him!
Ps. 34 9th and 10th verses.
"`O fear the Lord, you his saints!
For there is no want to them that fear Him.
The young lions do lack and suffer hunger:
but they that seek the Lord shall not lack any good thing.`"

16th.--Through inattention and unwatchfulness I believe,
I failed of that peace which would have been my portion:
I will endeavour through Divine assistance to be more on my guard in future.

17th.--Fifth-day.
Sat alone at _faubourg du Roule_ this morning where
I was favoured to feel refreshed and I trust,
renewed in spirit.

21st.--First-day.
Sat alone at _faubourg du Roule;_ found my thoughts very troublesome.

22nd.--Reproved a man today at my brickfield for using the name of God,
or _nom de Dieu_ when angry with the horse; told him I did not like to hear it;
that it was forbidden by God take his name in vain.

23rd.--My Heavenly Master continues, I believe, to be very near me,
and I desire to be more attentive to his voice.
Surely He blesses me every day with many blessings!

24th.--Sat alone at _faubourg du Roule._
Though my thoughts wander, yet the Lord, I believe is near me.

25th.--My partner came this morning to talk of our brickfield concern,
and to know my opinion upon it, whether I believed it to be a good one.
For some days my mind has been occupied therewith,
rather wishing to be free from it for several reasons,
and the more especially as I do not see a probability of our gaining by it, if at all,
not for some time to come.
I therefore told him I had not the same opinion of it since
seeing lately the waste caused by some apparently good bricks,
when taken out of the kiln going to dust and cracking when exposed to the air.
Resolved to meet tomorrow at the brickfield,
to decide whether to continue making them the ensuing season or to wind up our affairs.
I trust I may be directed by Him who does all things well,
and that both of us may decide aright and be of the same mind.

26th.--Met my partner according to appointment.
Decided upon sorting out the bricks of the whole kiln of washed bricks,
before preparing for making more,
to ascertain the number of sound bricks out of the whole.
Shall decide from the results whether to continue or not.
It is my desire to seek and to find Divine direction in this important result and conclusion,
feeling my own inability to judge rightly without his guidance therein.
I desire to know my Master`'s will, and to be found walking according thereto.

28th.--Sat alone at _faubourg du Roule:_ the Divine presence with me,
but I not sufficiently attentive thereto.

30th.--To be employed in the vineyard of the Lord
I must be faithful to the smallest pointing of duty.

12th Month 1st.--First-day.
Sat down at faubourg du Roule at about eleven:
found it very difficult to restrain my wandering thoughts.

2nd.--This morning I took for the first time a sum to the Savings`' Bank, 300 francs,
considering it safer and more profitable thus to dispose of it, than keeping it by me;
having no present use for it.
Before doing so,
I endeavoured to turn my mind inward to know if there
would be any impropriety in so doing.

3rd.--I fear I am losing ground; not sufficiently humble and watchful.
O that I may know how to pray as I ought!
I feel that it would be a great relief to me to be
able to pour out my spirit in prayer to God,
but am in need of the help of the Spirit.
I desire to commit my way unto Him.

4th.--Still an unwillingness is, at times, too apparent, to the taking up of the cross.

5th.--Why should I shrink at using the plain language,
since it is my Heavenly Master`'s will?
Let me remember God requires the whole heart,--unreserved obedience
to all his commands inwardly manifested to the soul.

Sat alone at _faubourg du Roule._
My brick concern occupies too much of my mind, I believe.
May I trust in Him for his guidance!
I think I should be quite willing to work, myself,
a part of the day in my wood-bending business, but He, alone, knows what is best for me,
and for the growth of his Truth in my inward parts.

8th.--First-day.
Sat alone at _faubourg du Roule._
I find it very difficult to keep my mind stayed upon the Lord.

// lint-disable invalid-characters á
9th.--Saw Charlot at _Porte á l`' Anglais:_ talked of the state of our business,
and told him rather plainly my views thereon; feel that I ought not to be over anxious,
but trust in the Lord for direction.
Have not felt lately my mind so near the source of all good as it ought to be:
so many thoughts obstructing my inward dependence upon the Light.

16th.--Have felt, I trust,
some help to be extended this day,--renewed drawings of my Heavenly Father`'s love.
O that I may learn to stay my mind on Him and trust wholly in Him!
May He grant me help to silence all my own thoughts and imaginations;
believing they are my greatest enemies.

17th.--The Lord is graciously pleased, I believe, to open my spiritual understanding,
and to show me somewhat my present state; which is, I believe,
a need of a more entire surrender of heart to Him,--a dying to the world,
not regarding my appearance to man, but what I am in the sight of God.

31st.--How do I desire that I may be preserved;
that I may continue to experience the overshadowing of his love;
that I may feel after Him and find Him in all my ways, and know Him more perfectly!
During the present year, now nearly expired, his hand has been stretched out to me,
and He has led me, He has helped me, and delivered me from my fears:
He has indeed been gracious towards me.
O that I may make spiritual progress, and know Him, through the ensuing year,
if permitted to enter and go through it, to be my help and my shield!

1840, 1st Month 1st.--Opened my Bible this morning at the lxiv.
chapter of Isaiah.
The 4th verse seemed encouraging,
"`For since the beginning of the world men have not heard nor perceived by the ear,
neither has the eye seen, O God, beside You,
what He has prepared for him that waits for Him.`"

2nd.--Read this morning xv.
chapter, 1st Samuel; in the evening the xl.
Psalm.
The 22nd verse of the former seems connected with the 6th verse of the latter:
"`And Samuel said, '`Has the Lord as great delight in burnt offerings and sacrifices,
as in obeying the voice of the Lord?
Behold, to obey is better than sacrifice,
and to hearken than the fat of rams.`'`" "`Sacrifice and offering You did not desire;
my ears have You opened; burnt offering and sin offering have You not required.`"

3rd.--I feel that I need help to do the will of God.

4th.--The Lord is, I believe, abundantly caring for me.
O that I may endeavour to do his whole will; unreservedly to obey Him!

5th.--First-day.
Have been favored to receive help this morning in my waiting,
being enabled to stay my mind in a degree upon Him.
May He continue to help me, for without, I can do nothing that is acceptable to Him.

6th.--Have renewedly experienced my Heavenly Father`'s care:
He has been my strength in need.
I have this day ascertained my profits from my little
bent-timber business during the past year:
surely I have great cause to be thankful, for truly He blesses me!

10th.--I believe those that are least engrossed in business,
having sufficient and no more, are best able to serve God;
for with much business the mind is taken off from God.

11th.--I think I must endeavour to give more time
for waiting upon God that my strength may be renewed.

13th.--Have not been sufficiently faithful, fearing man.
May I for the future be more on the watch, for "`the spirit truly is willing,
but the flesh is weak.`"

14th.--Was favoured with some opening in the Truth.
That which my Heavenly Father has committed to my trust in this land, I must keep;
the Truth is clean.

15th.--I desire that I may be preserved in the Truth;
that my obedience may keep pace with the knowledge that is given me.
Let me endeavour more earnestly to seek the Lord; more willingly to do his commandments;
to run, to be zealous in his cause.

17th.--Have been truly helped by my Heavenly Father in a remarkable way today;
having been for a long time endeavouring to find out an error in the balance of my books,
to no purpose, not knowing where the error was, I turned my mind inward unto the Lord,
if so be, I might be directed to discover it,--and to my astonishment,
and I trust under a sense of his great condescension,
I was enabled to discover it almost as soon as my eyes were upon my paper,
to which I was, I firmly believe, directed.
May I remember this great condescension of my Heavenly Father towards me,
and at all times look unto Him!
May He be pleased also to instruct me in that which is a cause of anxiety to my mind,
and has been for a long time,--whether to continue
my brick business with Charlot or to renounce it,
now somewhat of an opportunity appears to be afforded.

Had rather a remarkable dream this morning.
I appeared to be swiftly passing down a stream in a small boat and without oars.
There appeared to be rocks, or something similar,
against which there seemed great danger of running.
I made use of one, and sometimes both hands as oars,
by which means I was enabled to steer clear and turn from the course of the current,
crossing it to a sort of harbour where I safely arrived,
though not without having been apparently immersed in water up to my head or face,
the water covering over my body:--here appeared to be Divine preservation.

18th.--Have felt the tenderings of my Heavenly Father`'s love.
From my dream of yesterday, I have drawn, or been shown, this conclusion:
that I am rapidly going down the stream of this life; there are many rocks in the way,
from which I may, by using my best endeavours, with Divine help, steer clear;
but that then, when I have overcome the many hindrances and dangers in my way,
if I am not watchful and obedient, I may, and shall fall--may I be preserved!

21st.--The Lord visits me day by day; but how heedless I appear to be to his visitations;
allowing my own thoughts to draw me off the watch! how dull
and ignorant I am! may He bear with me and teach me,
for I believe, truly he finds me "`as a beast`" before Him.
How has the Lord visited me this night: how awful was his presence: how fearful I was!
How can I sin willingly and knowingly against so great a God!
But alas, how soon forgotten in my busy, worldly cares!
O that He may bear with me!

22nd.--Surely the Lord is with me!
His presence overshadows me; his mercies are round about me;
his blessings are very many and his compassion is very great.

23rd.--I desire to commit my cause to the Almighty;
my mind is much troubled and absorbed with the desire
to know how to act as regards my brick concern.
Charlot seems to wish to continue.
I commit it to the Lord, desiring to do what is pleasing to Him herein,
trusting I can say, "`not my will, but Yours be done.`"
He truly knows what is best for me and the glory of his great name.

When reflecting that I have two branches of business, I query, is not one sufficient?
Am I not in danger of having too much of the cares of the world and the lust thereof,
upon my mind?
He knows my heart and my motives to action, and what is the desire of my heart.
I desire not the riches of this world: at the same time I believe I am over careful,
and not sufficiently trusting in the Lord; for He can and will, I am confident,
provide all that is necessary for me,
even as He has hitherto blessed me with more than a sufficiency for my own needs.

26th.--First-day.
Sat alone at _faubourg du Roule:_ My thoughts very burdensome.
Herein I believe the enemy builds his strongholds--in the thoughts, will,
and imaginations.

2nd Month 2nd.--First-day.
Had a comfortable meeting, George W. Alexander present.
The Divine presence, I trust I may say, overshadowed us.
George W. Alexander spoke in the way of encouragement to me to a daily waiting upon God;
he also appeared in supplication for me and for himself.
Met again in the afternoon at four: a solemn quiet meeting.
Went with George W. Alexander to the _Hotel du Rhin;_ drank tea with him and John Scobel,
and passed a pleasant evening.
John Scobel and George W. Alexander wished to interest me in the slave cause,
in which my great ignorance was manifest.
I believe these individuals, though much occupied in caring for others,
are also caring for their own souls.
I desire to make myself acquainted with this cause,
but I crave Divine direction as to my drawing my mind thereto.
I trust nothing may draw my mind off from seeking my own salvation.
He alone can put forth to every good word and work;
may He show me what to do for his glory on earth!

6th.--Sat down at _faubourg du Roule_ soon after eleven, G. W. Alexander, not being arrived.
He came in shortly afterwards, and took his seat by me:
had a sense of the Divine presence.
G+++.+++ W. Alexander spoke, and appeared in supplication.
He said to this effect,
"`In the book of Revelation it is written,
'`And the Spirit and the bride say, Come.
And let him that hears say, Come.
And let him that is athirst come.
And whosoever will, let him take the water of life freely:`'`" and from the vii.
of Matthew, 9th verse, "`What man is there of you, whom if his son ask bread,
will he give him a stone?
Or if he ask a fish, will he give him a serpent?
If you then, being evil, know how to give good gifts unto your children,
how much more shall your Father which is in heaven
give good things to them that ask Him?`"
And from xvi.
chapter of John, "`Hitherto have you asked nothing in my name: ask,
and you shall receive, that your joy may be full.`"
May this engage me to prayer,--to ask that I may receive the spirit of prayer.

Received a note from Daniel Wheeler informing me
of the decease of his son Charles at 4 a.m.

7th.--Went to Germain,
Daniel Wheeler related to me some particulars relative to his son`'s close.
Saw the deceased: a smile on his countenance, which afforded me pleasure to look upon.
Might not such be expressive of joy in beholding
his Saviour in entering the mansions of eternal bliss?

8th.--Purchased a steel watch chain, and laid aside my gold one,
not feeling easy any longer to wear it; having no gold to spare,
and even were such the case,
the impropriety is evident in a desire to appear before men to possess it.
I trust it may be under a right feeling, my so doing.

9th.--First, day.
Went to _Germain-en-Laye,_ accompanied by my father:
met G. W. Alexander and John Kitching at the train.
We all sat down together at the _rue des Ursulines_ at about twelve o`'clock.
Daniel Wheeler spoke: he commenced, I believe,
with these words:--"`There is therefore now no condemnation
to them which are in Christ Jesus,
who walk not after the flesh, but after the Spirit.
For the law of the Spirit of life in Christ Jesus
has made me free from the law of sin and death.`"
In the afternoon we had a silent meeting.
May Infinite Wisdom be pleased to order and dispose
of me through life as to Him may seem best!
May I endeavour not in any way to thwart the Divine will,
but mind every sense of duty ever so slight!

13th.--Went to _Germain_ by the eleven o`'clock train.
We sat down together:
towards the close of the meeting Daniel Wheeler spoke of the vine and the branches.
I believe the Lord`'s power overshadowed us,
and thus that our meeting was acceptable to Him.
Spent the remainder of the day with Daniel Wheeler and family.

14th.--Went to _Germain_ by the eight o`'clock train
to see off our friends with the remains of dear Charles.
My mind was impressed with some solemnity of feeling
in seeing depart these valuable friends,
taking with them their charge to deposit in English ground.
I believe we shall never forget having been brought together:
may it not be said to be the favour of a merciful and kind Providence,
for which may I be ever thankful, seeking alone his guidance, protection,
and the advancement of his Truth in the earth!
Great has been the kindness of this family to me;
and if my efforts to assist them during their stay in this town have been availing,
I sensibly feel that it is not I,
but a kind Providence who is thus caring for them in a strange land.

22nd.--I believe it is very necessary that I should walk closer with God,
and not be satisfied with merely taking up the cross in a few outward things.

24th.--Learnt that tomorrow I shall have to appear again at the _Tribunal
de Commerce_ to affirm,--this time to money owing me and Charlot.
May I be strengthened by my Heavenly Master, whom I desire faithfully to serve,
that I may not let fall any of our testimonies for the Truth!
I have experienced today, I trust, renewed extensions of his love.
"`Even so you also outwardly appear righteous unto men,
but within you are full of hypocrisy and iniquity.`"
While I may be appearing righteous, or as having a desire to be so,
I humbly trust the latter part of this verse may not be applicable to me.

25th.--Went to the _Tribunal de Commerce:_ Charlot was also there.
Sat down in the lower part of the _salle,_ C. by the side of me.
I did not feel that anxiety that I did the first time of going there.
Quite unexpectedly to both myself and C. my name was not called, but his;
the more surprising to us both as the greater part
of the sum was payable to my order only,
and I also it was that received the order to attend, whereas he received none.
Truly I may say the Lord has helped me:
but at the same time that I humbly trust my not having to go forward
to the bench or president to affirm as before I did,
was in his ordering, yet I desire not to rejoice at this, but rather may I rejoice ever,
when publicly having to bear testimony to the truth as it is in Jesus,
and bearing our religious testimonies according to my profession.
Have felt my Heavenly Father`'s presence today.

27th.--Sat down at _faubourg du Roule._
Divine love was, I believe, manifest;
but my own worldly thoughts rise up in opposition to the Light within.
How can I expect to become strong while this is the case?

3rd Month 3rd.--Pulsford called with two hundred francs for Josiah Forster`'s account.
He seemed disposed to argue on doctrines.
I desire that when thus asked reasons for our acting as we do,
I may not appear ignorant as to Christian and spiritual motives,
but I desire to leave the rest to Providence, that I may be directed what to say.

7th.--My Heavenly Father`'s care attends me I believe,
though feelings of emptiness of anything that is good attend me very much.
How do I desire at times when favoured to feel the drawings of my Divine Master,
that I may be in the Truth, not turning back in my duty to Him;
that I may overcome my worldly thoughts which of late have so engaged my mind!

13th.--Intending to go out to purchase some furniture for my new apartments,
I endeavoured to seek Divine direction that what I purchased might be
such as would not cause uneasiness to my mind now or at a future time:
and I believe I have met with right direction.
I intended purchasing a mahogany table, but chose one in walnut,
thinking it good enough for the present and likely to be useful at any future time,
also a wardrobe of the same and chairs in cherry tree, stained.
How do I desire that in all my steppings I may be favoured with best help!
But how poor and barren do I seem of anything that is good;
my thoughts rising up in opposition to silent waiting upon the Lord.
I sincerely trust I may meet with help, and that He will bear with me.

30th.--Yesterday I received a very interesting letter from Daniel Wheeler.
In it he informs me he was going to Portsmouth to join the good ship _Mediator,_
on the 30th, for New York.
In allusion to his leaving his family he says:

[.embedded-content-document.letter]
--

It is no small trial and exercise of faith to have again
to leave the yet surviving remnant of my beloved family,
and nothing could induce me to do this,
but that I may be found in the counsel of that holy will which is ever
excellent in design as it is perfect in fulfilment to every jot and tittle.
There is no other way of showing our love,
but that of implicit obedience to what we believe to be a Divine command or requirement.
"`He that has my commandments and does them, he it is that loves Me,`"
said the Saviour of the world,--and again,
"`He that loves father or mother more than Me is not worthy of Me,
and he that loves son or daughter more than Me is
not worthy of Me. And he that takes not his cross,
and follows after Me, is not worthy of Me;`"
and unless our obedience keeps pace with the knowledge bestowed upon us,
we had better never have known.

--

4th Month 1st.--Comprehended with more clearness some parts of Scripture.
I believe my Heavenly Father is pleased to enlighten, in a degree,
my understanding herein.
May He be pleased to continue his Heavenly regard towards me in bestowing upon me what,
in his Divine will is good for me!

22nd.--Before retiring tonight, the opening to my mind appears to be,
that I must be as an empty vessel before the Lord,
that I may receive of Him what He is pleased to dispense to me.

23rd.--"`Open your mouth wide and I will fill it`"
has appeared to my mind last night and today:
may I be ready and desirous to receive the Lord`'s teachings,
and whatsoever He may be pleased to hand to me!

29th.--Have been favoured to see more clearly my need of faith:
"`without faith it is impossible to please God,
for he that comes to God must believe that He is,
and that He is a rewarder of them that diligently seek Him.`"

5th Month 4th.--My mind has been much agitated today, not centred upon God;
too much in the outward.
May I learn and obey, that at all times, the outward may not thus impede the inward!

19th.--In my trouble I have called upon the Lord for help,
and an increase of faith to trust in Him, and have covenanted to serve Him,
and with his help to glorify Him in the earth,
in doing whatsoever He may have for me to do.
I believe I am strengthened in measure to trust in
his lovingkindness and willingness to help me;
and may I not be encouraged if found following his
commands as they are made known in my heart,
by this scripture, "`Many are the afflictions of the righteous,
but the Lord delivers him out of them all?`"
If obeying Him, may not I also trust in his mercy and favour?

20th.--Yearly Meeting commences today in London.
A time back I was anxious I might find direction whether to attend this Yearly Meeting:
how repeatedly have I been shown the fruitlessness of looking far forward,
and being anxious for the future, yet how incredulous I am!
What a lack of faith in my Saviour!
This has been more manifested to me of late,
perhaps because my troubles appear greater than needs be,
by looking forward and allowing anxiety to take hold of me?
I desire to trust in my Redeemer who has led me in a measure to see my own darkness
and the great need I have of help from Him to do anything good.

28th.--In my troubles I call upon the Lord to help me,
and may He be pleased to remove this darkness in his own time.
May it be for my good!

I sat alone for some time at _faubourg du Roule_ this morning under much heaviness:
my brother came in late:
was favoured towards the close of the sitting to draw near in a degree to Divine light.

31st.--First-day.
I have not followed my Guide this morning:
may I be more attentive and obedient for the future,
otherwise how can I expect to have the true riches entrusted to me?
Believing it right for me not to attend to worldly affairs on First-days,
I was not sufficiently watchful,
but entered into conversation with my father on a subject
of a letter he had received relating to business.
This caused him to hand it me to read, which,
though feeling a desire to do a few minutes previously,
I had resolved not to take it up today, remembering its being First-day;
but when he handed it me I was not willing to obey the monitor,
fearing I might displease my father.
Since doing so I have wished I had told him I would prefer seeing it on another day.
I hope in future, whatever may be the circumstance, I shall obey the voice within,
without letting in any other consideration.

My brother and self at meeting: a feeling of drowsiness attended me, a lack of the life.
I believe my Saviour has been near me today.

6th Month 8th.--I felt it my duty to go and ask Charlot to tell the truth
of our position in the business we desire to dispose of,
to the person charged by him to undertake it;
believing it not right to employ him otherwise,
as he would give a false statement to such as applied
to him for information respecting it.
In so doing I believe I am directed by my Guide, the Spirit of Truth.
Charlot told me he would not do it:
I therefore told him I could not conscientiously take any part in it.
He was very angry, but I believe I was helped by my Heavenly Father,
in that I felt very calm, though what he talked of doing was of the most unpleasant kind.
I afterwards heard that which gave me reason to believe
he was sorry for having been so moved,
and probably for what he had said.
May the Lord help me, and make known to me in the Light the way in which I may go!

7th Month 30th.--Again has the Lord spared me to see another birthday.
Many indeed have been his tender mercies towards me this past year,
and though fraught with many troubles, I have received many blessings also.
Have I made any progress in the Truth?
I trust through grace I have made some advancement, though small indeed it appears.
It seems to me that I have not been sufficiently steadfast and watchful,
not dwelling enough in the light afforded.
May I endeavour to be more attentive to the still small voice,
having my dwelling more inward.
My brother and self at meeting this morning: was favoured with help,
though much wrestling was my portion.

My partner called upon me today,
and informed me that our proprietor would give us
up our lease on certain conditions named;
this is some relief to my mind.
My position continues to all appearance to be one of much difficulty, but I trust,
I believe I may say in the Lord, that He will help me in his own time, in his own way,
and I believe He will not allow me to be a reproach to the Truth.
It has appeared to my mind that the state alluded to by D. P. Hack, when at Bristol,
which "`I might have to witness,`" is now come upon me,
for truly I see no way out of my difficulties unless the Lord help me,
and I trust I may say, on Him is my stay, for my mind has been comparatively easy,
since I have had this confidence in the Lord that He will help me through, in some way,
though what is unknown to myself.
I desire to wait patiently his time.

8th Month 8th.--Did not know before today of the decease
of our dear friend Daniel Wheeler at New York.
This affected my mind when reflecting upon it: how well he appeared when at Paris!
I should have written to him at New York,
had I not previously heard of his serious illness.
O that I may be enabled to walk as he walked, in all my ways acknowledging Him,
my Saviour, and being led by Him!

23rd.--First-day.
Arrived yesterday evening from England, a committee of Friends,
appointed to visit Friends in the South of France.
We had a favoured meeting this morning,
when the overshadowing of Divine love was manifested.
In the evening, Friends had a sitting with me and my brother at my rooms,
when we were likewise much favoured.
Encouragement was handed out to persevere, to be watchful,
to seek frequent opportunities of retirement,
reading of the Holy Scriptures and meditation thereon.
The language of our Saviour to his disciples, "`I have yet many things to say unto you,
but you cannot bear them now,`" was handed out with much encouragement to perseverance.

9th Month 11th.--How good is the Lord to my soul:
what benefits does He confer upon me! "`Your lovingkindness
is better than life,`" has appeared to my mind:
may the lovingkindness of the Lord preserve me, and be for my comfort,
for an establishment in faith!
May all his tender mercies and compassion towards me cause
a feeling of grateful praise to arise unto Him,
the author of all my comforts!

10th Month 7th.--It has been manifested to me today that I am not sufficiently faithful,
not taking up my daily cross with that willingness, and in that watchful frame of mind,
which ought to be.
May I be favoured to be more watchful;
may I experimentally know my Saviour in all my steppings;
may the eye be open to every pointing of the Divine finger,
and the ear attentive to the still small voice, that I may be obedient in all things,
is I trust the desire of my heart.

15th.--A feeling of my own weakness and ignorance is my attendant of late: this,
I trust is the Lord`'s doing that I may be fit to receive heavenly wisdom.

18th.--The need I have of more fervour and spirituality is greatly manifest.
I believe I have not been sufficiently prayerful.
O that I may receive help to pour out my spirit in prayer, true prayer, unto God,
that I may experience my blind eye to be opened, and my deaf ear to be unstopped,
for truly the enemy has dominion over me in keeping
me from the enjoyment of true peace by my many thoughts,
thus hindering me from hearing the Shepherd`'s voice.
I have been off the watch today; may I be more watchful in future!

31st.--Today has been brought before the view of my mind
the importance of being faithful in little things,
for otherwise how can we have great things committed to our trust?

11th Month 1st.--The Lord has been good and merciful to me this day.
He has been pleased to manifest Himself in the Spirit to me,
for which I desire to be thankful.
O! may I increasingly seek his holy presence,
and allow that to be my first care and delight;
that all other things may be an after consideration with me.
As the spiritual eye is opened, how unimportant do worldly things appear!

15th.--Was strengthened today,
being enabled in a degree to silence my own thoughts in our meeting.
Was reminded of the patriarch Jacob`'s wrestling with an angel,
as figurative of our wrestling in the spirit, that we may likewise obtain the blessing.

21st.--Have been favoured to see somewhat into that passage of scripture given forth
by our Lord pertaining to the "`pound laid up in a napkin,`" and to query with myself,
am I rightly occupying with the talent entrusted to me?
I have to deplore my lack thereof in not being sufficiently given up to my Lord,
in not making unreserved use at all times of this talent,
in withholding from a fear of man.
Ought the use of that which is entrusted to me,
or that which is made known to me as a requirement, to be withheld at my will?
No, assuredly, for in so doing it cannot be making that use thereof,
which is and was intended by my Lord in bestowing it upon me.

1841+++.+++ 1st Month 2nd.--This evening I have been much off my guard,
allowing my temper to overcome my better feelings;
having been called more narrow-minded than many or most Friends.
I was angered thereby,
and used too many words and without allowing my ear to listen to my inward Guide:
whereas I have since been reminded that I ought to
consider this as an honour rather than otherwise;
to choose the narrow way and flee the path of sin,
requires more than our own wills will accomplish.

26th.--What need there is for me to be thankful to
the Lord for his wonderful leadings in the Truth!
I desired much to know his will, having felt the chastening of his hand yesterday,
and He has condescended to answer my prayer and to show me the way wherein I am to walk.
He has shown me that our unity and fellowship one
with another and with Him ought to be in spirit,
in the gospel, and that that which is outward will wither away;
and I trust that this day I have borne the cross and found comfort therein;
and that also I have not given offence to one professing the same principles,
though not feeling himself, perhaps, called upon to bear quite the same marks.

31st.--First-day.
Met at _faubourg du Roule,_ and for the first time on the first floor, having changed rooms.
B+++.+++ Wiffen and my brother with myself formed our little meeting.
I esteemed it a favour thus having a Friend from England to sit with us the first time,
and one that belongs to the same Monthly Meeting as myself.
I believe I may say with truth,
that we were favoured with the overshadowings of Divine love and regard,
for which I desire to be thankful.
How I do desire that the blessing may attend us in our little meetings;
that we may go on in becoming acquainted with the Captain of our salvation,
and that in due time our number may be increased, to meet together in his name,
in this city; and surely He can do it.
When I reflect, I can, I believe,
see the Divine hand in the procuring of this place for us;
so suitable and so much to my own mind.
I had desired we might have a place exclusively for the purpose of worship,
and for the keeping of Friends`' books,
and not to be occupied as an apartment or dwelling, as has been the case;
and thus is my desire granted.
Thanks be unto the Lord, I believe I can in my heart say,
for his customary lovingkindness, and let me always put my trust in Him!

That which has been on my mind today has been the truth,
that in the world we shall have tribulation, but that in Christ Jesus we may have peace.
"`Peace I leave with you, my peace I give unto you: not as the world gives,
give I unto you:`" let me then seek that peace which is to be found within,
in doing his will, in walking in the Spirit,
in minding every manifestation of the Spirit of Truth, that I, through Him,
may overcome the world, and yet not I, but Christ within me!

2nd Month 7th.--First-day.
Was much favoured at meeting.
I think I felt more of the solemn covering than I
have been accustomed to feel on such occasions;
for which favour the language seemed to arise while sitting under the solemnity, "`Come,
taste and see that the Lord is good.`"
I trust this was heartfelt;
and O that my dear Saviour may continue his lovingkindness to me!

O my soul, your Heavenly Father has been very near you throughout this day!
May I be enabled at all times to look only unto Him, not unto man,
that He may have my whole heart and confidence!

23rd.--The Lord has favoured me with heartfelt desires in prayer for his gracious leadings,
and communion with Him;
that He will be pleased to subdue my vain and evil thoughts and make me a child of God.
My desires and solicitude have also been for my brother
that He will preserve him from falling.

27th.--I trust that what I have done today has been in the light of Truth:
I have fresh reason to believe that Divine guidance is with me:
went this morning to see Charlot for the purpose of ascertaining whether
he had done anything towards an amicable settlement with Durand;
did not find him at home,
and in consequence was engaged during the day in drawing up a letter to him,
renewing the expression of my desire to act conscientiously towards Durand,
not endeavouring to recover upon him the loss we have sustained by other means.
I did not execute a letter to my satisfaction, and was engaged therein late in the day,
when a letter arrived from Charlot.
I was pleased in not having sent to him;
and from this circumstance with the results of others at other times,
I experience that it is safest to see the way quite clear before putting in practice.
I drew up in a somewhat different manner this evening
the subject which I felt clear to propose to him,
namely, an amicable arrangement with Durand without rendering him any wrong,
expressing it to be my desire that Charlot may look at this affair, _en conscience,_
for that he as well as myself has a true Witness within
him which approves the good and condemns the evil.
May Truth prevail!

3rd Month 2nd.--Went to _Point du Jour,_ and when there,
hearing that the young man Larcher was returned home from the hospital, and very ill,
I called to see him.
Found him very ill, apparently in the last symptoms of decline.
It was my desire to say something to him that might leave an impression for good,
and while sitting by him with my mind waiting inward,
though feeling void of anything for expression, of exhortation or otherwise,
yet these words came across my mind, _Tourne toi vers le Seigneur_ +++[+++Turn towards the Lord],
which I afterwards expressed, twice intimating that that was what I had to say,
or would say to him: he seemed too ill to talk much.

12th.--Left Paris for Kingston; arrived safely on the 14th, having been much favoured.
Went to meeting with uncle and aunt +++[+++Chalk]
in the afternoon, where I was strengthened,
and much and largely favoured with the overshadowings of Divine love and mercy.

16th.--Uncle read after breakfast Ps. 69.:
the words "`I restored that which I took not away,`" impressed my mind
as being applicable to my position and requirement in my difficulties.

22nd.--Conversing with J. F. Marsh,^
footnote:[John Finch Marsh was born in the year 1789,
of parents who were members of the Society of Friends.
In the 22nd year of his age he spoke for the first time in a meeting for worship,
and in 1818 he was acknowledged as a minister by Devonshire House Monthly Meeting.
In a short record of him, from which we quote,
it is stated that his travels in the work of the
ministry extended over a period of forty-three years,
commencing in 1822.
His ministry like his nature, was loving and persuasive,
bearing a testimony to the spiritual and inward nature of religion,
and of the powerful working in the secret of the soul,
of that grace which brings salvation.
He was eminently of a meek and quiet spirit,
endeavouring through life to keep himself unspotted from the world.
He was not insensible of the departures from primitive
faith and practice within the Society,
and mourned over them.
Shortly before his decease he expressed himself thus: "`I am not altered:
I am a true Quaker, a true Friend, there must be a living people;
there must be such a people.
Ah! they have slid off the foundation, and are building on the sand,
and they will find it so when it is too late.`"
On a previous occasion he wrote, "`This is a day of shaking, scattering,
and sifting,--a day in which I think it may be said,
that the leaders of the people have caused and do cause them to
err.`"
{footnote-paragraph-split}
He died at Croydon in Surrey,
where he had resided the greater part of his life, in the autumn of 1873,
at the advanced age of 84.]
he told me that he thought as to the past I had been in my right place,
but as to the future we could not say what a day may bring forth;
recommended waiting on the Lord, and believed He will direct me.

23rd.--Left London for Boulogne; was favoured to reach home on Fifth-day morning,
and surely I may say in every respect, both with me in my journey,
and at home in my absence, the Lord has cared for me.
Let this incite me to diligence and watchfulness,
always to seek his holy guidance in all things,
and let me ever acknowledge Him in all my ways!

4th Month 3rd.--In my meditation this morning on my past feelings when at Kingston,
relative to my having seen and consulted Friends upon my awkward position with Charlot,
at which time I felt some conviction that I was looking too much
to man,--while considering this and my returning home without any
other result therefrom than Friends`' opinions and advice,
and that not altogether satisfactory on the whole to my mind,
these words have passed through my mind, "`My own hand has gotten me the victory,
and not man.`"
How true this is!
The Lord is helping me, and all praise will be due to Him for my deliverance,
for which I believe I can behold the hand of the
Lord working for me from the day I left England,
and may I not say, his hand has all along been with me?

4th.--First-day.
After much wrestling, was favoured to feel a renewal of strength, much to my refreshment,
for which I desire to be thankful.
A+++.+++ Knight, my brother and self, composed our little meeting.
What an exposure of my own weakness there has been this evening,
how was all sense of good overcome and Satan triumphed; but I fervently, and I trust,
humbly desire this triumph of anger, which so overcame everything else within me,
may with Divine assistance never appear again in like manner.
I have seen my own nothingness and need of constant watchfulness,
and I trust humility may prevail on every occasion in future.

12th.--Second-day.
Applied today at the Savings Bank to withdraw the sum I have there.
First-days are those named as only those on which such applications are received.
I stated my objection from a conscientious motive to appear on that day:
was referred to the agent or one of the principals, who upon my stating as above,
and that I was one of the Society of Friends, granted my request without hesitation,
and gave me a written order, for which I thanked him, to receive it on the 20th.

16th.--Called upon a man about our brick-bats, who after conversing on the subject,
said he wanted them for cement for the fortifications.
As I went to him without knowing this, I did not, on his telling me so,
think it required of me to refuse to sell them to him, but since,
I have felt it right for my peace of mind to go to
him and clear myself from entering into the affair.
Accordingly I went this evening for that purpose, and I trust I have done right,
and that thus in the retrospect I may have peace.
It is probable I might have sold him all we have, had I felt clear to do so.

21st.--How good is the Lord towards me,
how wonderfully has He been leading me through many troubles and difficulties,
and his own hand is getting the victory!
All the praise and glory is due unto Him.
What reason I have to trust in Him alone,
and how has He been pleased to show me in experience, blessed experience,
that vain is the help of man!
But bless the Lord, O my soul, He may be trusted, for notwithstanding all my fears,
and the telling of my troubles to others, all have failed,
but his own hand which has gotten the victory.
Let me continue to look unto Him,
and let me ever trust in Him for deliverance in every time of need, in his own time,
for He can do it.

22nd.--I wrote a letter to uncle and aunt +++[+++Chalk],
wherein I stated something relative to uncle`'s business +++[+++the drapery]
to the effect that it might suit me, as I had heard he was intending to sell it.
I took the letter to one post-office, but there, was too late; so went to the other,
but hesitated about sending it on account of what I had written relative to the business.
After walking about in the streets and in the post-office yard,
I resolved pretty much not to send it and walked away;
and have since thought I did well in not sending it.

23rd.--I believe there is abundant reason for me to trust in the Lord,
for surely He has helped me in many ways.
Have felt that I have not lately been dwelling so
near to my Guide and Preserver as I ought,
but trust I may be favoured to have my strength renewed.

24th.--My mind has been much disturbed today with my thoughts till towards night, when,
and since which I have been favoured with help,
and received some comfort in reading part of an
[.book-title]#Account of the Convincement and Religious Progress of John Spalding,#
which I felt much unity with: this sort of reading I find the most strengthening.

25th.--First-day.
In weakness today, and I believe I may say under temptation.
How needful it is to keep in the power that preserves from evil;
may the Lord grant me help in every time of need!

26th.--In endeavouring to draw near to the Lord in inward quietness,
I was graciously favoured with a portion of peace, very refreshing and strengthening,
for my mind has of late been much tossed to and fro without a stay.

5th Month 13th.--Dined with H. Pease at the hotel.
Was helped to withhold from doing that which I did not feel clear to do,
and believe I can say I had peace therein.
Was asked if I would go to the panorama,
where was to be seen the "`burning of Moscow,`" but declined doing so;
and being asked if I had an objection,
I stated that I did not feel it right for me to recognize war pieces,
and that feeling a scruple in my mind, I believed it right to attend to it.

16th.--My brother and self are intending to be at the Yearly Meeting.
Upon this my intended visit to England,
I expect will result a decision whether to remain in business at Paris,
or to leave and settle in some other in England.
I trust I may meet with best direction, in the Lord`'s will.

18th.--A. Elliott sent me a letter to take to England for her, having heard I was going.
Upon looking it over in my mind I felt it right to write her a few lines and return it,
stating my scruples to taking letters to avoid postage,
having in our meetings for discipline to answer collectively the query,
whether we defraud the king of his revenues and customs.
Though there is the possibility of my giving her offence in so doing,
I feel that I have acted right therein.

Went to the Passport Office.
On going in was called to loudly to take off my hat:
another passing me touched the brim of it, signifying that I must take it off.
I still keeping it on,
the policeman came forward and peremptorily asked me in a loud voice,
why I did not take it off, upon which I told him, _Je ne decouvre pas la tete aux hommes,
pour un motif de conscience_ +++[+++I do not uncover my head to men,
from a conscientious motive]: he then left me.
I was no further troubled, but used very civilly:
how greatly I am helped to bear this testimony!
And I trust nothing may be permitted to turn me aside from
what I am shown is right for me to do from day to day.

19th.--Having latterly beheld something of vain show in wearing a gold seal and key,
I have thought well to lay them aside and to take simply to my steel key again:
as a follower of the meek and lowly Jesus,
I think my desires ought not to be placed in the attainment or possession of such things.

On the 22nd I signed the agreement for the giving up the lease of our brickfield,
which is now finished with the exception of having
the signatures of the creditors of our proprietor.
I trust all will go well.

My dear brother continues unwell, but much better:
he had intended leaving for England the day he was taken poorly:
thus how true we do not know what a day may bring forth!
I have thus been detained from going to the Yearly Meeting,
but I believe all is far the best, and that it is right I did not go.

On the 25th my brother being sufficiently recovered
to render it apparently prudent for me to leave,
I did so, and was favoured to reach London well on the 27th,
and attended three sittings of the Yearly Meeting.
We were very kindly received by Friends.
Though my visits have been pleasant,
so much going about tends to draw the mind off from the inward,
which I have experienced during this visit.

Since my return home I have desired to attain to a feeling of Divine peacefulness,
and resignation to the will of the Lord, being somewhat unsettled,
but I believe it is safest to leave the future, trusting in the Lord:
this seems difficult at times to attain unto.
I have had some thoughts and desires that the way may open
for me to take my uncle`'s drapery business at Kingston;
but that which seems likely to be a barrier, is the superfluous part,
of which it appears to my mind to partake,
and which perhaps if taken away would very much reduce the profits.
I believe that uncle has dispensed with much and perhaps all that seems to him objectionable,
but it appears right for me to depend and trust on my inward Guide;
and that I may thus be led clear of all hindrances to the Truth, is my earnest desire.

7th Month 6th.--This evening I have been favoured to feel of the goodness of the Lord,
to see his merciful lovingkindness, and of his wonderful works which do praise Him.
He has cared for me, He has been mindful of his covenant,
and has not only helped me in and through difficulties, but has blessed me with benefits.
He has truly done wonderful things for me, for which I desire to praise Him,
and to be found walking in his will.
I read this evening before tea, the xiii.
chapter of Romans, and before going to bed Ps. 111.,
in the reading of which Psalm I have been helped to my refreshment,
and I believe I may say an eye has been opened to see the hand of the Lord and
his blessings bestowed,--"`He has given food to those that fear him;
He will ever be mindful of his covenant.`"
May I then put my whole trust in Him, and give myself up more unreservedly to follow Him!

8th Month 14th.--I trust I may very soon be quite clear of my partner,
that I may be free from this entanglement, wherein I have experienced much trouble,
and wherein I have been marvellously helped by my Almighty Benefactor and Preserver.
I trust and desire that what has been,
may prove of use to me for the future as regards experience,
and that all may work together for good.

9th Month 18th.--First-day.
At meeting was favoured towards the close with a degree of strength.
Have been led to contemplate the many deliverances which the Lord
has effected for me when trouble has followed upon trouble,
and no way appeared, but truly He has helped me,
and I trust I may remember his goodness all my life long.
It appears to me that I have abundant cause to trust in
Him who has hitherto done such great things for me.

10th Month 13th.--This afternoon my true friends, Gilbert Gilkes and wife,
left Paris for Chalons to Nismes, having spent about eleven days here.
I have enjoyed their company, and was much with them.
With these dear young Friends I have felt much unity and great freedom,
and it is my belief we shall not regret having been brought together in this place,
but rather rejoice in the remembrance of the great lovingkindness
and tender mercies of our God who has helped us.
Desires have been afresh raised within me to know the Lord`'s
will with respect to my steppings in this life,
having again been brought to consider the subject, am I in my right place?
O that a clear sight may be given of what to do at
this and every time of seeking unto the Lord,
that I may not be found transgressing, but always in his will,
not touching or tasting anything that may prove a hindrance to his work in my soul,
or his praise on earth.

14th.--Craved earnestly of the Lord that He would turn unto me the light
of his countenance and answer me in my desire to know his will concerning
me as to my stopping in this place or leaving it;
and in my endeavouring to turn in silence unto Him.
He was pleased to condescend unto me,
and to my inward ear was uttered in pleasant and intelligible language, the words,
"`Trust in the Lord,
and lean not to your own understanding:`" for this favour
and merciful condescension of my Lord I desire to be thankful,
and to put my whole trust in Him, for truly this has been lacking;
for I have not looked sufficiently unto Him;
and may He be pleased to continue to favour me and to speak
unto me in his mercy and condescension to my soul,
which I believe I may say, longs for more of the knowledge of Him.

17th.--My brother and self at meeting.
Much perplexity of mind has attended me this day,
accompanied with fervent desires to know the Lord`'s will concerning my future steppings,
as to disposing of my business, and leaving Paris.
This evening my mind has been much engaged in contemplating a change, namely,
that of leaving Paris, and going to some Friend`'s for a few months to learn the farming,
which my mind holds to, and I trust is of right direction.

12th Month 31st.--Have endeavoured in retirement after a feeling sense and remembrance
of the Lord`'s mercies and favours unto me during this year,
which have indeed been great and many.
Have also desired of my Heavenly Father that He will be pleased to continue them unto me,
and this ensuing year to establish me and settle me that my mind may not be roving,
not knowing what to do.
This is my earnest desire, that my mind may be stayed on Him,
and that I may appreciate his favours,
and see his hand which has been so mercifully extended for my help in
the various difficulties which have apparently risen up before me,
believing that my mind has not been sufficiently turned to Him from time to time,
who has worked deliverance for me.

1842+++.+++ 2nd Month 20th.--Have been enabled to see that
the Lord has indeed been good unto me,
and favoured me with many blessings, in satisfying all my real needs hitherto,
although I have sojourned more than seven years in a strange land,--although
I have had to encounter many difficulties and trials,
yet he has helped me to overcome all to his own praise.
Of late my mind has been engaged in considering the subject of quitting this place,
but I believe I can say that a desire has been formed within
me to do only that which is in the Divine will,
that I may be in my right place, whether here or in my native country:
and may I be mercifully favoured to know a growth in grace, a becoming more humble,
and mindful of all the benefits I have received from the hand of the good Master!

3rd Month 13th.--On looking again at what I am likely to undertake, that is,
the disposing of my business, it appears to me to be a right thing,
and that it will be well for me to be loose from the world,
to have nothing of a binding nature as an occupation,
but only what may leave my mind quite at liberty,
may I not say even if I only have bread and water to support the body,
and raiment to put on.
O that a willingness may be more and more wrought
in me to be whatever the Lord would have me to be!

14th.--Went to the Tribunal of Commerce at the Bourse
to affirm to the correctness of an account.
I was told to take off my hat on entering, which refusing to do,
the officer went up to the President to speak of it:
he returned without saying anything to me.
When my name was called I went up to sign and affirm.
After signing, the President told me to lift up my hand, to which I replied,
"`I do not lift up my hand.
I do not take an oath.`"
I was then told my affirmation would not be received,
and was asked if it was contrary to my conscience: I explained that it was so.
It being said that I could have employed another, or given a power,
I said that it would be the same to me to authorize
another to do what I do not approve of,
as if I did it myself.
The President and another refused to accept my affirmation without the raising of my hand.
One that was on the other side of him came down by the side of me,
and looking very pleasant, told the President that I was a Quaker,
and that our affirmation is accepted in England:
and the other who was next to him also appeared well disposed;
thus there were two in my favour and two against me.
The President then concluded to receive it as valid,
and asked me if I affirmed to the correctness of the account,
and in answer I repeated the form which Friends make use of.
I was told very pleasantly by the two who were in my favour, that it was sufficient.

Before leaving them I explained that it was not from any lack of
respect that I appeared before them with my hat on.
Thus I have been again helped this day to the praise of his name who does wonders for me.
May I ever mind and be faithful to his inward teachings, and not be afraid of man,
who can only do what he is permitted to do by our God!

19th.--Again I have been wonderfully helped this day also,--the Lord has done all for me,
so there is indeed renewed cause to trust wholly in Him.
Charlot came, and an agreement was made to mutual satisfaction,
to meet on the first of next month for the settlement to be effected with him.
We parted very pleasantly.
My uncle, Thomas Sargent, having taken my bending business,
we called to know whether the shop could be retained after the 15th of next month,
and finding that it cannot, we went to see one I have had in view,
but found it cannot be had; consequently we had to seek another.
Where to meet with one so suitable, I did not know: we saw one,
but there seemed some objections: we proceeded,
but without any expectation on my part of finding
what we wanted in the direction we went,
but, as if so ordered, we soon saw a place apparently suitable and well situated.
Truly I do believe the hand of the Lord is in all this,
and I am more and more confirmed in the belief that his own good time
is at length come for my liberation from this place,--the way seems clearing,
mountains being removed,
and a sense of the Lord`'s great goodness to an unworthy creature is mercifully granted.
May I be enabled to praise Him and magnify his name at all times,
and serve Him with my whole heart is my sincere desire, and I trust it is my prayer.

31st.--In endeavouring to draw near to the Lord in
inward abstraction and quietness of mind,
it has been brought to my remembrance, that He has abundantly blessed your provision,
and fed you, and preserved you all your life long until now.
"`What I have had and now have is from the Lord,
and O that He may still go with me and bless me in the way that I shall go,
and make me more and more acquainted with Him, and more and more to love and praise Him!

According to agreement between me and my uncle this is the
last-day that I am in possession of the bent-timber business,
which has all along since I have been in this country been a profitable undertaking,
and for which I have cause to be very thankful both as to past and present,
having had a comfortable maintenance for a length of time therefrom.
I have cause indeed to say the Lord has cared for me in a strange land.

5th Month 7th.--A feeling of the Lord`'s power and condescension
I think has been afforded this evening in enabling,
notwithstanding the tumultuous thoughts which so greatly impede,
to draw near and know Him in his manifestations to my poor soul,
which has of late been much lacking in the feeling of his holy quickenings,
arising I believe, from being too much absorbed in worldly affairs.
A desire has been created in me to be led in the right way and to devote my future days,
wherever my lot may be cast, to his service.
Truly He has kept me and instructed me during my stay here,
and brought me to a measure of the knowledge of Him, praised be his name!
And O that He may be pleased still to lead me and make me more acquainted with Himself,
and enlist me as a servant in his vineyard, to give me the wages which He may please,
so that I may from time to time know the tokens of
his heavenly love to the renewing of my strength!

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia Chalk.

[.signed-section-context-open]
Paris, 2nd of 5th month, 1840.

How pleasant it is to me to know I have friends who are interested about me:
I have not only been told so, but have felt it to be so.
How can it be otherwise, when we have experienced the danger that surrounds our path,
than that we should feel for one another; indeed,
then we can feel for him who is weak and of little faith;
but at the same time we know that He who has delivered out of the jaws of the lion,
can also protect him and grant him strength according to his day.

Even in this land of darkness and infidelity, surrounded by many temptations,
there is preservation and equal safety, I believe, as in other places to the believer;
for now we are given to experience the truth of the prophecy,
"`I will put my law in their inward parts, and write it in their hearts,`" which,
as we give up to its leadings, I have faith to believe, will save at every time,
and in every place from every evil.

The little meeting has consisted of but one attender
for a length of time on First and Fifth days,
till Ann Knight`'s arrival, excepting once only,
when Daniel Maule from America was present and my father,--D. M.
being on his return home from some parts of the Continent.
To return to the subject of the little meeting,--though there is lacking,
as at other times also, a stayedness of mind free from worldly thoughts,
that the Shepherd`'s voice may be heard and known from the voice of the stranger,
yet a greater appreciation also is lacking of such seasons of quietness and feelings
of dependence as are in mercy and favour afforded,--I know this must be waited for.

As it is our privilege as a religious Society to
have testimonies and such as the world esteems not,
committed to us, of the great Head of the Church for his name`'s sake, we have I think,
reason to expect that those who are endeavouring to follow their Lord and Master faithfully,
will have some experiences which may prove interesting to one another,
and perhaps confirming in our faith,
and at times such as may have been attended with deep inward baptisms;
for our Saviour`'s declaration,
"`The servant is not greater than his lord,`" prepares us to expect that his
followers in this world will have to endure many trials and conflicts:--and it
may be expected that in a country such as this,
where a true confession of our Saviour before men is so lacking--(as
regards my own observation) a member of our Society,
in upholding our principles has much to contend with in the cross to the natural man,
but (it ought to be with thankfulness) I can say,
hitherto I have been marvellously sustained in every trial, to my great encouragement.

[.signed-section-signature]
J+++.+++ G. Sargent.

--

8th.--We were seven in number at meeting today.
This being likely to be the last time we shall sit down
together at Paris on a First-day while I am a resident here,
my desire has been that it might be a favoured time,
and truly I may say the Lord was graciously pleased to show Himself
among us in somewhat remarkably giving me to feel his presence,
so that I sat under his shadow with great delight,
being quickened by his power upon my poor soul:
truly the knowledge of the Lord is very precious to me.

13th.--This morning I opened my Bible at xv.
ch. Deuteronomy,
from the reading of which I am brought to consider of my release from this place,
which is about to be effected this day,
intending to leave Paris to take up an abode in my own country.
I have been here more than seven years and a half,
during all which time the Lord has had a watchful and compassionate care over me,
notwithstanding my many sins of omission and commission.
May He now be pleased and henceforward,
to bless me in the way that I go and preserve me from evil,
and enable me to praise and bless his great name!
Such is I trust the sincere and earnest desire and craving of my soul;
surely He has done very wonderful things for me,
and led me hitherto in a way that I knew not.
He has called me out of the deep mire and clay and delivered
me out of great waters that threatened to drown my soul,
praised be his name!
Amen
