== Chapter II.

[.chapter-synopsis]
* Arrival in England
* Visits his Relations and Friends
* Accompanies John and Edward Pease to Pyrmont, Minden, and the South of France
* Visits Paris on Several Occasions
* Accompanies A. A. Jenkins, and William and Mary Forster, to the South of France
* Removes to Kimberley in Norfolk
* Enters Upon a Farm in Surrey
* His Marriage
* Removes to Ireland
* Writes an Epistle of Love and Caution
* Reflections
* Letters to L. A. Barclay
* P. Rickman
* J. Sargent
* J. G. Hayman
* W. Hodgson
* J. F. Marsh
* T. Drewry And I. B. Letters From W. Hodgson and T. Drewry

1842+++.+++ 5th Month 15th.--Reached London a little after one
p.m. Left direct for Kingston and went to meeting there:
was favoured with a renewal of strength,
a feeling of the overshadowings of Divine love overshadowing the tabernacle.

24th.--Grover Kemp breakfasted with us: he handed much encouragement to me, saying,
that I should dwell in the land,
and verily I should be fed,--that I should have the richest of blessings, the Treasure,
and temporal ones also,--that I may be tried to a hair`'s breadth:
recommended or exhorted to sit alone and keep silence.

6th Month 11th.--It seems necessary to live one day
at a time--have not felt quite so much discouraged.
O that I may not miss my Guide, but be humble and teachable,
walking before Him in unreserved dedication and resignation to his will!

17th.--Went to Brighton Monthly Meeting: a very favoured meeting.
D+++.+++ P. H. spoke at much length:
he expressed a belief that some would be raised up in that Monthly Meeting
who would have to tell others of the Lord`'s wonderful doings for them.
I felt it to be a truly instructive and favoured time,
accompanied with some belief that I should become one of that number
to declare of the Lord`'s goodness towards me in having delivered
me from many sore and grievous trials and afflictions,
to which (some having gone through or going through), D. P. H. alluded,
as that there would be given them beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.
He also believed that there were some of the preciously visited ones present,
one of whom I knew myself to be,
for truly He has visited me in a remarkable manner
from time to time with the tokens of his love.
O that I may be increasingly faithful to all his manifestations!

1843+++.+++ 1st Month 10th.--Peaceful feelings at John Catchpool`'s. He addressed me,
+++[+++counselling]
to go deep, to feel my way from place to place: only stop when I can feel peace,
that I may set my foot in the right place: mind the pointings of the Divine finger.
J+++.+++ C. does not doubt, but the way will be clearly pointed out to me.

11th.--"`When a man`'s ways please the Lord He makes even his enemies
to be at peace with him,`"--and the angel of the Lord shall chase
them:--"`he that tells lies shall not tarry in my sight.`"
Be willing to become a fool among men.

2nd month 26th.--To Peel meeting in the morning,--to Westminster in the afternoon.
In the morning meeting that Scripture of "`the stone cut out of
the mountain without hands`" was brought to my mind with instruction,
showing me the necessity of laying aside, in order rightly to worship,
all my own strivings, and to be resigned to the Divine will,
and to endeavour to turn inward from all that may be of our own imagination or doing.
Towards the close of the meeting John Hubbard stood up with the same,
and explained that we ought to or must cease from our own inventions.

[.offset]
On the 27th he went again to Paris to consider further about business.

3rd Month 25th.--When you are assailed with temptation,
flee for refuge to your Saviour and Redeemer as a
little child runs to its parent when afraid,
for the Psalmist says, "`The Lord is my strong rock, my deliverer, and my high tower.`"

26th.--Was favoured with calmness at meeting.
Some friends from England were there.
I believe it is good for me to receive in humility what is handed to me in the Light,
and not to handle it: my own reasoning--the carnal mind, cannot please God.

[.offset]
4th Month 12th.--He returned again to England, not finding it his place to stay in Paris.

4th Month 27th.--The thought has arisen this morning
whether it may not be the Lord`'s will,
and whether I ought not to devote my days to his service,
keeping myself free from worldly business, and that He may have spared me for this end.
This evening I have remembered how that the Lord`'s disciples
gave up all (their outward business) and followed Him.
O that I may know his leadings and drawings!

28th.--

[verse]
____
Be simply faithful to thy inward Guide,
Heedless of mortal laugh or mortal frown,
And in thy Maker`'s service fortified,
Fear not the cross, for that secures the crown.
____

6th Month 27th.--Quarterly meeting +++[+++for London and Middlesex]
which was adjourned till five o`'clock in the afternoon.
The subject of discontinuing one of the London week-day
meetings in the morning and substituting one in the evening;
or having one held in the evening on a week-day (which subject
was brought from one or more of the Monthly Meetings to the Quarterly
Meeting) was entered upon with I think much interest.
On hearing it I felt strongly the impropriety of making any alteration in this respect,
believing the sacrifice ought to be made,
that it must be more acceptable when performed during the time that is
applied by others (usually) to business and that it would tend to weakness.
G+++.+++ Stacey seemed to feel in the matter as myself,
and after S. Gurney had expressed a similar view or feeling,
I believed it was required of me to express the few words,
"`I am quite of the same mind on that subject,`" which I trust was right,
and it afforded me relief in doing.

8th Month 3rd.--Left London for Paris.

11th.--Let me ever flee from temptation, not look at it.
I may expect to meet with temptations while in this body;
let me then ever be on the watch, O my soul!

13th.--My brother and self only at meeting.
In the evening after a walk I went solitarily home; but to my comfort,
though no mortal was there, I found I was not destitute,
for in seeking unto the Lord inwardly I found what was better to me than outward company.
O let me henceforth value retirement!
He that has so often, and especially during my residence at Paris formerly, helped me,
remains forever the same: He changes not.

22nd.--I believe Divine instruction has been afforded me today
from our Saviour`'s words to his disciples in Matthew 10:27,
"`What I tell you in dark, that speak in the light: and what you hear in the ear,
preach on the housetops.`"
I believe I ought in no way to flinch from the cross in what is shown me as my duty,
but to speak in light that which my Saviour reveals
to me as his will in the secret of my soul.
A more full surrender and a willingness to bear the cross before men and
to become a fool among them seems required of me if I would have peace.
It seems as though I am in my appointed place,
and that there is work for me here in the Master`'s cause,--the Truth as it is in Jesus.

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay.^
footnote:[Lydia Ann Barclay was born at Clapham in 1799.
Her parents were Robert and Ann Barclay,
the former being directly descended from Robert Barclay,
the author of the [.book-title]#Apology for the True Christian Divinity.#
Respecting her childhood but little is left on record;
she appears to have been early favoured with the merciful visitations of heavenly love,
by which her heart was tendered,
and she was gradually strengthened to yield obedience to the Light of Christ in her soul;
so that as she grew to womanhood, knowing her will measurably subjected thereto,
she experienced a deepening in the root of life,
and was enabled to bring forth fruit to the praise of the great Husbandman.
In one of her letters written at a later period she says,
"`we were brought up to the use of prayers morning and evening;
and very often went with our governess, who was of the established church,
to her place of worship.
This I became uneasy with, when about fifteen; and showing a dislike to it,
she never pressed it again.
Places of public amusement, and dancing, were also given up about the same time,
and music soon after.
Oh! how tenderly have I been dealt with!
I can never sufficiently remember it.
He has led me gently along, showing me by degrees, first,
what he would have me avoid and forsake, and then,
what he would have me to do and pursue.`"
Dwelling under the operation of the grace of God,
and the tendering baptisms of the Holy Spirit,
notwithstanding the contrary influence of the associations by which she was surrounded
she was led into great simplicity in her appearance and mode of life.
She was thus, as it were, a silent testimony-bearer, in the midst of luxury and pride,
to the purity and cross-bearing character of the religion she professed;
the conviction of which had, nearly one hundred and seventy years before,
been designated by her worthy ancestor, David Barclay, of Ury,
as the "`perfect discovery of the day-spring from
on high,`" upon his own soul and others of his family.
She appears to have first come forth in the ministry in the year 1831,
and her gift was acknowledged in 1835, being then resident at Croydon, near London.
It has been testified of her ministry that "`though sometimes of few words,
they were weighty and powerful,
striking at the root of the evil nature in those who heard her,
and directing to a close waiting upon,
and obedience unto the Divine Teacher manifested in the heart,
whom she declared to be none other than the Spirit of Christ the Saviour.`"
Several times during the course of her pilgrimage, she changed the place of her abode,
under a sense of religious duty; and was engaged, at times,
in travelling in the service of the gospel, in many parts of England, Scotland,
and Ireland.
She finally settled at Cockermouth, in Cumberland,
as the place she had seen while in Scotland,
where she would be likely to finish her earthly career.
{footnote-paragraph-split}
But
that which distinguished her,
perhaps,
more than anything else was the clearness with which she saw the
danger of the modern innovations upon our ancient faith,
and the faithfulness with which she withstood them.
Her spirit was often deeply afflicted in a consideration
of the superficial and unsound writings afloat in the Society,
especially those of Joseph John Gurney,
and the sad effects thereof in promoting a system of religion more agreeable
to the inclinations of the uncrucified will and wisdom of man,
and an outward, self-active, and wordy ministry in accordance therewith;
and she felt bound, not only to maintain an unequivocal testimony against this system,
but also to caution against any connivance or compromise with it,
either through the fear of man, or under the specious plea of charity and forbearance.
She died at Cockermouth, the 31st of 1st month, 1855, aged 55 years.]

[.signed-section-context-open]
Paris.
11th of 9th Month, 1843.

[.salutation]
My Dear Friend,

It has been much on my mind of late to write to you,
and wish to let you know how it has fared with me, feeling as I have done,
much freedom to communicate with you thereon.
It has been a long winter season with me, though I trust I can say,
and with thankfulness, that hitherto I have been mercifully preserved,
and favoured with food sufficient to keep alive,
though much weariness and seeming desertion +++[+++have attended], at times almost to despair;
but a secret hand has been underneath to sustain me through all,--His name be praised!
If you have not heard you will learn by this that I am again in Paris,
where I have been about five weeks.

Previously I was spending a time in London, and in the West;
but not feeling that I had a home, and not knowing what to put my hands to there,
I looked towards this place again, without an object pointedly in view,
or anything wherein I felt I could decidedly engage
without a discovery of the Divine will therein;
yet it seems most like my home here, and through renewed favour,
I have of late felt that it is good for me to wait
upon the Master to know what is his will,
to be wholly resigned to what He may order and appoint; believing,
in a degree of faith now afforded,
that He will order and make manifest what is good for me, that his will may be done in,
and concerning me.

It will soon be a year and a half that I have been unsettled.
In that time I have had opportunity of becoming more
acquainted with the state of our Society;
and it seems to me that the number of the truly primitive ones,
like to some whose journals are in print, is very scarce.
Such as these I have desired to meet with and to know them where they are,
and what they do in this troublesome world.
I have an idea they are scattered, as it may be in solitary places,
one here and another there.
I wished to find an outward dwelling near or among them;
but we cannot see of ourselves what is best for us, for in all my will and choosing,
I have not found that which I wanted.
I have felt that there is very much to hinder the Divine work in this day,
which is as a stumbling block to that simplicity
and dependence which as a body we profess to uphold,
and which does not become the followers of the meek and lowly Jesus.
I desire that the past may tend to my profit.
It will be truly pleasant and agreeable to me to have a letter from you,
as soon as you think well to write to me here at
my quiet home--home until I know the Master`'s will,
if so be I may be preserved in the patience.
I have felt much unity with your late dear brother`'s +++[+++John Barclay`'s]
experience related in his letters, some of which I have been reading in course.

Our meeting is kept up though often I sit quite alone as I used to do.
Sometimes there are three of us, or may be four.
Farewell.
I am your sincere and affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

9th Month 24th.--In my bedroom before going to rest under
a desire that I might be directed as to my anticipated journey^
footnote:[A business journey with a view to ascertain whether it would be right
for him to return to Paris and recommence the timber-bending trade.]
that the Lord`'s will might be done therein,
I opened my text book and the passage came before me, "`Commit your way unto the Lord;
trust also in Him; and He shall bring it to pass.
And He shall bring forth your righteousness as the light,
and your judgment as the noonday.`"

10th Month 6th.--Reached home with a sense of the Lord`'s
great goodness to me during this journey of about 250 miles,
out of which I reckon I walked 100. I believe I can say I have been much
favoured and strengthened from day to day in a degree to take up the cross,
though not so fully and willingly as I ought to do; yet the Lord`'s hand and presence,
I believe I can say, has been extended from day to day,
accompanied with a feeling that I have been under his special care and protection.
O that this may afresh incite me to put my trust in Him,
and to look to Him for the ordering of my ways!

16th.--Left Paris for London.

17th.--At sea.
All day excepting short intervals, very rough, squally weather, so much so,
that much discouragement prevailed with some, and the captain seemed anxious:
we knew not how it would terminate, but the Lord preserved us from harm through all.
I was very thoughtful and endeavoured to look back in mind
to the motive of my coming and being where I was.
It seemed I was in the line of duty as to my outward concerns, and a belief attended,
that the Lord would preserve us.
How precious and desirable seemed the state of living
in the daily fear and service of the Lord:
how comforting to the soul at such a time as this!
and though I believed I might have been more faithful,
yet I felt a degree of confidence and trust in the Lord.

11th Month 14th.--Returned to Paris again.
+++[+++The object of this visit does not appear.]

19th.--At meeting as usual.
The substance of some cautions of instruction which I have received from my inward
Monitor during my late sojourn in England,--Think well before you speak.
Be more inward and talk less.
Let the first day of the week be entirely free from
business matters whether in thought or word.
Be very cautious in giving an opinion about another, and as much as well may be,
avoid it; and endeavour to know the good only in all.
I believe, from unwatchfulness,
there has been cause for the above cautions being
impressed upon my mind as essential to my peace.

29th.--Through favour and to my great comfort,
I have of late had to see in the Divine Light,
that it is not the Divine will that man should contrive
and choose of himself where to dwell,
or what to do, for promoting the glory of the Lord in the earth;
that it is the creature`'s work to hearken and obey,
and not to run or act according to his own understanding,
though it may appear to be helping the cause;
for that "`it is not in man that walks to direct
his steps,`" in regard to promoting the Lord`'s glory.
Therefore, O my soul, wait patiently on the Lord, and be not careful,
only that you keep on your watch constantly unto prayer,
that you may draw down his compassionate regard; and knowing,
obey in the least manifestation, his blessed will.
Therefore it is not for you to say, I will live in Paris,
that there may be a Friend or Friends, in this place,
or because some Friends have wished it might be so;
but if your Master wills your being here, trust and believe He will order it so,
and you will know his will therein, if so it is,
and if your eye is open and your ear attentive to
his heavenly voice in your inward parts;
for there the Lord has spoken to you, and will continue to do as He may see fitting.

12th Month 18th.--Great and unmerited favour;
a feeling of the Divine approbation in his peaceful overshadowings this morning,
in a season of retirement, was afforded,
which does appear to be an earnest of his will as a seal to my anticipated steppings.

20th.--Left Paris for Southampton.

[.offset]
+++[+++After his return to England when under much proving,
not seeing any way to go forward in business,
he was requested to accompany Edward and John Pease on a visit to Friends in Minden,
Pyrmont, and the south of France, "`to render them`" he says,
"`such service as I am able.`"
John Pease had been liberated by his Friends for this engagement,
and his father to accompany him.
No record is left of the time of their return.]

1844+++.+++ 1st Month 16th.--Left London in company with Anna A. Jenkins, William Forster,
and his sister Mary, to proceed to the South of France, A. A. J. of Rhode Island,
having a certificate.
I was requested by the Committee to accompany them.

20th.--Reached Paris after a favoured journey and much to be thankful for in many respects.

2nd Month 12th.--Went with A. Jenkins and M. Forster to Montpellier and Cette.
I went contrary to best feelings, without faith,
believing that this is not my path of duty.^
footnote:[It will be here perceived that the sensitive mind of
the subject of these memoirs was introduced into considerable exercise;
it was occasioned by yielding against his convictions,
to accompany A. A. J. and her companion to the above
named places of public resort and interest,
not in their line of service.]

13th.--"`There is forgiveness with You that You may be feared,`"
has presented to my remembrance both yesterday and today,
and that the Lord loves mercy and not sacrifice is
consoling to the condemned heart and tribulated mind.
How plainly it was shown me yesterday, and is also today,
that I have stepped out of the path of faith and duty by
not giving up to the (perhaps) slight but true manifestation,
before leaving Congenies for Montpellier and Cette,
that it was not according to what was and is right, but expecting greater manifestations,
I did not walk according to the measure of Light afforded,
which has since brought trouble upon me, and I have been reminded in the way,
of the case of Jonah, and whether my not being in my duty, something might befall us:
without faith there is no peace, and out of the path of duty there is no safety.
If the Lord restores me to favour after his whole will is
done in judgment upon me for thus stepping aside,
then I trust I shall give heed to the smallest manifestation of the Truth,
and no more consult with flesh and blood; not heeding what any may say.

25th.--__Chalons sur Saone.__
We sat down together at the Hotel.
Dryness seemed my portion, yet some help or feeling of good was, I believe vouchsafed.
Walked out by myself before dinner when I was led earnestly to crave a blessing,
and to covenant to serve the Lord in the way of his requirings.
I laid before Him my desire that He will be pleased on my return
to England to set my feet in the way wherein I may go.
I do believe if the Lord answers this my prayer that I shall ever record
it as a signal favour and merciful token of his compassionate regard,
for the sake of his son, Jesus Christ, my Saviour.
While thus laying before Him the desire of my heart,
I have also desired that nothing improper for me may be granted,
but I have very earnestly craved a blessing from his hand (from
whom comes every good thing) in this the desire of my heart.
I believe the encouraging counsel "`Trust in the Lord and lean
not to your own understanding,`" is again renewed this day,
to press forward in what, in the Light, appears right, and not to look to consequences.

3rd Month 8th.--London.
What a favour to be returned in safety, without bodily injury, in health,
and I do trust my best welfare has not suffered loss,
though I have had to mourn over weakness and deficiencies:
may I profit from past experience!
O my soul, return thanks unto the Lord by unreserved obedience to all his pointings!

5th Month 20th.--In quietness; keep there and dwell very deep,
for it is there that the Lord`'s will is to be known: a feeling of peace,
and favoured with the feeling of the Lord`'s goodness to me in thus caring for me.
O! keep low and wait upon the Lord this Yearly Meeting time.

31st.--This day closed our Yearly Meeting affairs
under a solemn feeling and covering of good,
the Lord`'s holy presence being powerfully felt--a time of great favour:
have been made very sensible of it towards me in a remarkable manner.
The Lord guided me and delivered me out of the net which seemed laid for me;
and had it not been for the sensible feeling given that
the path which seemed open for me was a wrong one for me,
I believe I might have erred from the purposes of the Lord concerning me--for
which favour I desire to be very thankful and more watchful in future.

6th Month 27th.--Quarterly Meeting +++[+++at Norwich]:
saw Thomas and M. A. Bayes--arranged to go to Kimberley on 7th day.

7th Month 18th.--Made an arrangement with Thomas Bayes to remain with him to learn farming.

9th Month 30th.--Received a letter from R. Swan +++[+++of Capel in Surrey]
about his farm, concerning which I had written to him,
having heard it would be available to rent.

1846+++.+++ 1st Month 16th.--Left Kimberley on my way for Bregsell Farm (R. Swan`'s).

6th Month 25th.--The Lord has indeed dealt very bountifully with me,
and O! that I might feel more thankfulness for the
blessings and favours which He confers upon me,
for truly He loads me with benefits in every way when I stand in need,
forever blessed be his holy Name.

[.offset]
+++[+++In the Twelfth Month of this year he was united in marriage with Catherine Doubell,
of Reigate.]

1847+++.+++ 12th Month 4th.--At about ten minutes past three o`'clock
in the afternoon was born to us a son,
our first born--how great thankfulness seems due for the
Lord`'s many favours to us his dependent creatures.

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Hickman.

[.signed-section-context-open]
Bregsell Farm, 11th of 2nd Month, 1850.

[.salutation]
My Dear Friend,

What a remarkable event has occurred to you:^
footnote:[This refers to a remarkable deliverance
from robbers who had entered the house.]
we can indeed feel for you,
and I trust with you also in attributing the honour to Him only to whom it is due,
in thus extending help to you in such an (otherwise) alarming time.
Does it not show us all how good it is to trust in the Lord,
who can so marvellously restrain and preserve.
I think I can say the relation thereof,
or rather the reflection thereon has seemed to endue my mind with a little
fresh courage and confidence that if we are so found endeavouring to live
under the power of the Lord we shall neither need to fear any evil,
and that no evil (in reality) will be permitted to come near our dwelling,
for I cannot look upon this as an evil, but permitted in love and wisdom,
it may be further,
still further to show how the Lord makes bare his arm to
deliver and to incite to still greater confidence in Him,
for who, but He is worthy to be served; silver and gold, the work of men`'s hands,
is as a thing of naught in comparison with the possession of his love and favour,
so that on the one hand our love for Him is increased,
and when some earthly things are taken from us, on the other,
the vanity of all perishing things is shown to us.

[.signed-section-closing]
Your sincerely affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

1851+++.+++ 11th Month 20th.--I left Bregsell on my way to Ireland via.
Waterford to Moate, the object of this journey being to see for myself,
and to endeavour to know what would be right for me in regard to
a removal to superintend the management of a farm called Hall,
near Moate.

23rd.--Spent first-day chiefly with T. and M. A. Bayes, at Clonmel.
At meeting this morning very unexpectedly a feeling of duty
arrested my mind to stand up and express the scripture declaration,
"`This people have I chosen for myself,`" with that
also of "`They shall show forth my praise.`"
Quietness covered my mind after this my first expression in a meeting for worship,
and the trust was with me that no harm was done, and that I had not erred.

12th Month 12th.--I again visited Hall.

1852+++.+++ 1st month 6th.--Went to London with my family on my way to Ireland.

[.offset]
+++[+++Here they remained until the year 1854,
when again was the language realized "`This is not
your rest,`" and in a remarkable manner,
wherein it was clear and plain that the finger of his heavenly Leader pointed thereto,
a way was made to take a wood-turning mill at Cockermouth, in Cumberland,
and although entirely unacquainted previously with the business,
he was enabled to carry it on and to provide for the maintenance of his family.
The following epistle was written during his residence in Ireland at a period when an
individual from America was causing much grief to Friends in England and Ireland,
and was extensively circulated.]

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle of Love and Caution to the Tender-hearted Everywhere.

[quote.scripture, , Matthew 24:5]
____
For many shall come in my name, saying, I am Christ,
and shall deceive many.
____

[.salutation]
My Beloved Friends, Brethren And Sisters,

You who are dear and precious to me in the everlasting covenant of Light and Life,
my spirit craves that you may, at this eventful period of time,
turn your hearts and minds unto the Shepherd of his flock,
inward! inward! where Christ is, and will dwell,
if so be you are followers of Him in faith and love,
holding fast the profession of your faith without wavering--for this, my friends,
we are all exhorted to do, nothing doubting, and He who has been and is your Alpha,
will also be, as you live unto Him, your Omega.

But, my friends, wherever you are scattered on the Lord`'s earth,
never was there more need for a closer walk with
the God of our fathers than at the present time,
when, indeed, the enemy of our souls is lurking about us, as it were, in secret places,
endeavouring to lay waste God`'s heritage through his messengers,
under that insidious disguise of pretended righteousness, which, verily,
is not the righteousness of God,
but of man`'s own conceivings and falsehood--that
which would destroy the flock of the Lord,
though under an appearance of love and heavenly-mindedness, built up in self-wisdom,
nourishing their own hearts, and the hearts of those they can captivate,
with the bread of deceit and violence, which is not of or from the Lord,
but coming out of and from the sparks of their own kindling.

Beware, then, I beseech you, of such, who are puffed up,
and the disturbers of God`'s peace.
"`Peace I leave with you, my peace I give unto you; not as the world gives,
give I unto you.`"
My friends, there is a false peace and a false rest; there are itching ears also,
and not a few ready to feed them, even from the conceivings of their own fertile brain.
Let us beware of such, and only receive that into our hearts which will bear the fire,
proving all things, and holding fast that which is good;
not taken up in our own minds with the many words and high-famed eloquence,
when it is only the fruits of the natural part in man,
and very captivating to the outward ear: but hearken,
hearken awhile! and let us remember for our instruction, that,
to "`hearken to the voice of the Lord,`" inwardly manifested,
is better than all "`whole burnt offerings and sacrifices`"--those offerings
which are burned upon the altar of man`'s judgment and natural understanding,
and sacrifices to the god of worldly wisdom and eloquence.

How, then, may some tender mind say, are we to know what is of the Lord, and what is not,
while under such disguise?
words of truth! which, verily, are words of truth, but not dictated as you believe,
by the Spirit of Truth in such.
Wait, oh! tender soul, wait upon Him who will, in his own time, show you; feel after Him,
and you shall discern whether there is that in the earthen vessel,
which will bear witness with your spirit,
testifying that such a one is the chosen of the Lord, for his own work and service;
and if the savour is not there,
if the unction does not appear to the witness for God in you,
be not hasty to form a judgment; yes, form none of your own; make not unto yourself,
unto your own mind, a god of this or that, though the truth may be spoken,
for the enemy of man can, and does,
transform himself (emboldened in this our day from the multitude
of his votaries) into an angel of light.

Be, then, very watchful, and take not up with anything, howsoever good it may appear,
which has not upon it the impress and seal of the Holy One; and in time you will see,
yes, the Lord will give you to see, that which serves and honours Him,
and that which serves and honours Him not:
and fear none of those things which you may be told shall come upon you,
because you can not go with the multitude in this way or that way,
but cleave closely unto your Spiritual Guide,
remembering the language of our dear Redeemer when on earth, to a beloved disciple,
who asked, "`And what shall this man do?`"
The answer was--"`What is that to you?
You follow me.`"

The day was to come when "`grievous wolves`" would come into the fold; the more, then,
it behooves us to look and see, to watch continually,
and acknowledge nothing that the Spirit does not acknowledge, though the Lamb`'s coat,
may be put thereon; for verily in due time shall be seen by the sheep,
in the light of the Lord, that which serves Him, and that which serves Him not.
Oh! the great danger there is in looking unto men or man`'s judgment,
though clothed with the spirit of love and zeal; for be assured, my friends,
this is not the true love of the Spirit--there is a false love and a true love,
a false unity and a true unity--that which binds up and can heal in the true love,
and that which can cover with a plaister under the cover of love,
and yet does not heal in the true love,
or the love which is of and from the Spirit of Love;
inasmuch as there is one love of the world,
and another love of the Father--the one proceeding from the world and owned by the world,
and the other proceeding from the Father and owned by the Father.
Let us beware of "`the foxes that spoil the vines.`"

And this is worthy of our consideration--+++[+++See [.book-title]#Shewen`'s Meditations#,
pages 27 and 28]:--"`We are now come to the true and living way, the ancient path,
in which the righteous in all ages ever walked.
Now this remains, that we always feel our hearts engaged to walk in this way,
and to keep sensible of that power which saves from evil,
that we may adorn our profession;
for if any that profess this everlasting way enter into temptation, or commit evil,
they do not adorn their profession, but are a scandal to it,
and lay a stumbling-block in the way of others,
who are where we were when wandering in desolate places,
and travelling in the desert howling wilderness.--The
day of such will be turned into darkness,
and the curse due to him that lays a stumbling-block in the way of the blind,
and that leads him out of his way,
will fall upon them.--Therefore it concerns all to be watchful,
and persevere in that which is good, to be as lights of the world,
and as the salt of the earth indeed, that we may never leave shining nor lose our savour.
Whatsoever was written afore time was written for our learning,
and it is profitable to meditate and consider that many in former
ages had much experience of the power and presence of the Lord,
saw many of his wondrous works,
and travelled through the Red Sea and wilderness to the borders of the promised land;
yet, through murmuring and disobedience entered not therein,
nor did enjoy the end of the Lord in bringing them out of Egypt`'s land,
and many may in this age fall short, as they did, if we walk not close with the Lord,
and learn, by what is written, to take warning,
lest by disobedience and unbelief we fall short of
receiving the great recompense of reward.`"

In conclusion, my friends,
I would say in humility of soul before the Lord--Beware of the leaven,
the outward leaven, which would leaven into its own likeness.--Let the inward leaven,
the precious leaven of the Kingdom, be your mainstay and support.--Farewell in the Lord.

[.signed-section-signature]
J+++.+++ G. Sargent.

[.signed-section-context-close]
2nd of 6th Month, 1853.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Jane Sargent.^
footnote:[This dear friend was one, who through a long course of years,
maintained an exemplary life and conduct consistent with her religious profession.
She was a true mourner over the many deviations and
falling away from first principles in our Society.
Especially did she lament the superficial ministry consequent upon the change
of doctrine which had gained ground among us.
{footnote-paragraph-split}
Her mind was much distressed with the changes taking place in the discipline,
and in the year 1851 she believed the time had come
to cease from attending the Yearly Meeting,
and gradually withdrew from the attendance of any meetings for discipline,
but continued to attend the meetings for worship where she resided,
until about the year 1873, when she thus writes to an intimate friend.
"`And now my dear friend in reply to your allusion
to having heard of a change in my religious views,
I wish to inform you, it is entirely a misconstruction,
for they are the same that they have been,
and in full unison with the doctrines and principles of the early Friends;
from which the present constituted Society have of late years so greatly departed,
letting fall one testimony after another.
Doing away the chief queries has opened a wide door for deviation and declension.
But more especially to be deplored is the lapsed or changed
state of the ministry becoming too generally superficial,
and, unless under the influence of the Holy Spirit,
the utterance of words in our meetings is not likely to profit the people.
Greatly was I burdened with such frequent interruptions,
hardly allowing me to arrive at the quiet, collected settlement of mind,
so necessary for the performance of worshipping the Lord in spirit and in truth; that,
after endeavouring to try the fleece wet and dry (not hastily, and in the cross),
I came to the conclusion it was best for me to withdraw
from the meetings and to sit down quietly alone at home,
which I am in the practice of,
and wherein I have at times been permitted to feel peace and the sweet Master`'s presence,
who condescends to fulfill the promise to be with the two or three
as also with the solitary ones who meet in his name.
My love to my friends remains undiminished.`"
Our dear friend continued this practice as long as health permitted.
{footnote-paragraph-split}
In the year 1879 she had a very severe illness,
wherein was remarkably displayed that He who had
been her morning light was now her evening song;
and although labouring under great bodily weakness,
she had much counsel to hand to several members of the meeting from which she had withdrawn,
and many tendering opportunities were experienced.
Heavenly joy and peace filled her soul, and she was often heard to say, "`Oh,
the love of God; it is inexpressible! beyond conception! yet what am I,
a poor unworthy creature to be so favoured.`"
"`Oh, if my testimony should encourage only one to persevere it is well worth all the suffering,
and what is all this light affliction compared to what my precious
Saviour endured when the sins of the whole world lay upon Him?`"
"`It is almost more than human nature can bear to have such a foretaste of heaven,
and if the foretaste is so precious, what must the reality be?`"
Contrary to the expectation of all her friends, she was again raised up,
and in the following year was able to be removed to the residence of her nephew,
J+++.+++ G. Sargent, at Fritchley,
where she continued to give evidence of her entire
unity and satisfaction with the course taken,
and her desire remained unshaken for the prosperity
of the little company with whom she had united herself,
though in consequence of her great age and weakened faculties, much was not expressed.
She died at Fritchley on the 26th of 8th month, 1882, aged nearly 94 years.]

[.signed-section-context-open]
Hall, near Moate, Ireland, 28th of 1st Month, 1854.

[.salutation]
My Dear Aunt,

Some account of dear John Wilbur, and his son, since they came to us, seems due to you,
and now that they have left us,
I will try and give you some particulars respecting their visit.
They came to us from Dublin after attending the meeting there, at the close of which,
the system adopted in London and elsewhere, was also adopted after their example,
denouncing John Wilbur as not of us.
Well, you may imagine, we were well pleased to have him and his son with us.
I met them at Moate, and glad we were to get them under our roof.
They were with us two meeting days, 1st and 4th,
in both of which dear John Wilbur was engaged in a lively
testimony for the Truth as professed by us as a people,
by our early Friends, and down to the present time.

The Friends in Moate received them in a way different to what we expected;
some of them asking them to call after meeting, which they did,
though to receive them in any other capacity than as strangers,
and for hospitality`'s sake, they do not seem prepared.
We were comfortably confirmed in our views and feelings
respecting this dear old servant of the Lord,
and it has been strengthening to us to have him with us.
They stayed with us from 6th day to the following 5th day,
when they left for Clonmel and Waterford.
I felt bound to accompany them to Clonmel, and there to act as it seemed best,
whether to go further,
and it seemed with me to bear my testimony unflinchingly for the Truth,
as believed in by us as a people formerly, and by a remnant down to the present day,
by thus accompanying one who was, we have no doubt,
led here by the Master himself to stand for his name among us,
and as a beacon for some among us to follow in his steps.

We found no openness to lodge at Clonmel, so went to a hotel.
On first-day dear John Wilbur^
footnote:[John Wilbur was born at Hopkinton, Rhode Island, in 1774,
of parents who were exemplary members and elders of the religious Society of Friends.
He came forth in the ministry in the thirty-sixth year of his age,
and his gift therein was acknowledged not long after,
and being careful to attend to the monitions of the heavenly Teacher,
he became an eminent instrument in the Divine hand for promulgating the
glorious truths of the gospel of life and salvation to his fellow men.
The dissemination of unsound and anti-christian doctrines by Elias Hicks and his adherents,
was the occasion of much sore trial to him,
and he was constrained faithfully to bear his testimony against this spirit of unbelief;
firmly adhering to the ancient testimonies of the Society in regard
to the divinity and offices of our blessed Lord and Saviour,
Jesus Christ.
{footnote-paragraph-split}
In the years 1831-2
he made his first visit to Great Britain and Ireland;
where he soon saw the working of a spirit,
the tendency of which was in the opposite direction to Hicksism--to carry the Society
back towards the outward and literal views of the formal professors of the day.
And when, a few years after, Joseph John Gurney,
who was strongly identified with the latter views, visited America,
John Wilbur entreated him to disavow such portions of his printed works,
as were not in accordance with the ancient and well-known principles of the Society;
but this the former refused to do;
and failing also to prevail upon the Meeting for Sufferings of New England
Yearly Meeting to investigate those writings and decide upon their soundness,
John Wilbur felt constrained as an individual from a sense of religious duty,
and in accordance with the requirements of the discipline,
to warn his fellow-members against imbibing these unsound sentiments.
{footnote-paragraph-split}
The
result of the faithfulness of J. W. herein,
was his disownment at the instigation of the Yearly Meeting of New England,
on the fallacious charge of detraction,--in other
words--obstructing the service of an accredited minister,
notwithstanding that he offered to prove that he was acting
in accordance with the discipline in what he was doing.
The partizans of J. J. G. refused to listen to his plea, declaring,
with but slender regard for truth, that doctrines had nothing to do with the question!
The further effect of this action was that the Yearly Meeting itself became divided,
and the dividing and disintegrating process went on affecting
more or less all the yearly meetings on the American continent,
producing an amount of unsettlement throughout the Society which can hardly be realized
to its full extent.
{footnote-paragraph-split}
The persecution of this Friend for his
fidelity to the cause of Truth as professed by Friends at the beginning,
will ever remain as a dark chapter in the Society`'s history,
and when the mists of prejudice shall have rolled away,
will stand as a beacon and a warning to all,
and as a remarkable instance of how rules of discipline
intended for the preservation of the Church,
may be so prostituted as to become engines of oppression
and persecution.
{footnote-paragraph-split}
In the year 1853,
John Wilbur paid a second visit to Great Britain and Ireland.
This time it was to those who would receive him in the way of his coming.
The Meeting for Sufferings, as representing London Yearly Meeting,
therefore desired an interview with him,
before whom he spread his concern for the preservation of
the Society on its ancient ground of principle and discipline,
and showed that this was what himself and Friends in New England had been standing for;
and that where the matter had been fully investigated,
as was done by Philadelphia Yearly Meeting,
this was found and acknowledged to have been the case.
Although he had the opportunity of relieving his mind,
and they were unable to gainsay or resist what he said,
yet he found them fully committed to the views of J. J. G.,
and unwilling to acknowledge that any portion of his writings were unsound!
Thus his previous apprehensions of the lapse of the Society from its original and fundamental
principles were abundantly confirmed.
{footnote-paragraph-split}
He died in 1856,
aged about 82 years.]
was engaged in the morning meeting in a sound and clear testimony which none could gainsay.
The two elders went off directly after meeting.
I saw them go out together, but there was no denunciation after meeting as at Dublin.
We dined at E. Malcomson`'s between meetings.
The afternoon meeting was silent.
One or two of the elders went off,
but remained and shook hands with John Wilbur and requested to speak to me,
so we had a little time together.
He asked me if I had peace in being there.
I told him yes.
I also brought before him John Wilbur`'s testimony in the meeting,
but he told me he did not want to allude to that, (or to that effect).
We parted friendly after he had recommended me to return home.
But, Oh! how superficial were his reasons and arguments.
Here, in Ireland, they say we ought to submit, submit to the elders,
to lay aside our own feeling for theirs, etc., etc.
John Wilbur felt clear of Waterford without staying a meeting there;
accordingly left by steam-boat for Bristol.
It was a favour to have them with us, and we can but miss them now greatly.

[.signed-section-closing]
Your affectionate nephew,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John George Hayman.^
footnote:[This dear Friend was born at Hersfeld, in Germany, in 1803,
and came to England, where he resided at or near Lindfield, in Sussex,
about the year 1830.
Before this time the testimonies of Truth had become
so precious to him that he had embraced them,
and was desirous of walking in accordance therewith.
In due time he made application for membership in the Society of Friends,
but not being able to speak English, he told those appointed to visit him,
that they must sit down and feel for themselves.
The Monthly Meeting of Lewes and Chichester accepted his application,
and he became a diligent attender of meetings for discipline as well as worship.
In process of time the introduction of unsound doctrines and the departures in practice
from the testimonies of our worthy predecessors became a great grief to him,
and he abstained from the attendance of meetings for discipline for several years,
feeling most easy to do so.
{footnote-paragraph-split}
His
desire for the revival of the discipline,
of which for so many years he had been deprived,
among the people with whom he was nominally associated,
because of its being perverted and laid waste, was eventually satisfied.
He became united to Friends of the Monthly Meeting of Fritchley, because,
to use his own words,
"`It was the only means of coming out of Babylon.`"
{footnote-paragraph-split}
Having
borne a faithful testimony to the Truth in his day and generation,
he departed this life in great peace, on the 9th of 8th month, 1870, at the Holmwood,
near Dorking, Surrey, aged 67 years.]

[.signed-section-context-open]
Hall, 9th of 2nd Month, 1854.

[.salutation]
Dear George,

I have very much feared that my long silence in this way
after the receipt of your very welcome and acceptable letter,
would lead you to think me indifferent about you--but I do assure you, my dear friend,
that such is very far from being the case.
Your letter came before John Wilbur arrived,
and I thought it would be well to wait till he came,
and thus time has swiftly passed over without writing to you.
Well my friend, your letter came at a time when it was peculiarly encouraging,
the day before leaving for our Quarterly Meeting at Dublin.
Ah!
George, it is very good for us to commune one with another,
there is that to be felt with those who are endeavouring to walk in the same way,
which is like face answering to face in a glass.
Is not this your experience?
The oil will flow and overflow sometimes to the gladdening of one another`'s hearts,
and is not this of the Lord?
"`All my springs are in You,`" said one of old; and so it is in this day,
praised be the Lord,
for verily we do know from a living experience that all good comes from Him,
that our joy is in the Lord, and that "`He is the portion of our cup.`"
I rejoiced in reading your letter,
and in knowing how you were led to be faithful to the Lord and his cause,
and was bold to acknowledge Him in his appearances
in that faithful and chosen servant John Wilbur,
whom we do greatly love and honour for the work`'s sake.
We believe him indeed to be the Lord`'s servant, and devoted to Him,
and very sweet is the savour to us that remains now he is gone.

He and his son were with us nearly a week,
and poor I accompanied them to Clonmel and Waterford,
and there I found I must part from them on board the steam-boat for Bristol.
We have since heard from them by a letter from John Wilbur from Bristol.
We understand that he looks to leaving for America in about a month.
How interesting to us was your account of your journey and visit in Germany,
and about the little company, near Minden.
How cordial it would be to my mind to meet with them.
You must have been refreshed thereby,
and may not your visit there be esteemed as a favoured brook by the way.

Yes George, through this vale of tears,
there are refreshing streams for the weary traveller,
and for the lonesome traveller journeying towards Zion.
Have you read the [.book-title]#Pilgrim`'s Progress?#
I am, while writing reminded of that: there are those on the way, who may,
and do join us and go along with us, but all do not go all the way,
the whole length of the journey; there are so many turns, so many by-paths,
so many inducements to turn from Christ the true Way,
and we ourselves are in jeopardy every hour of our lives, unless we cleave closely,
very closely to the Heavenly Rock which is higher than we are,
and under whose protection and shade there is salvation.
May we then look continually to this Rock, Christ Jesus, our Light,
our Stay and our Help while we are dependent on Him,
and not lean upon man who is a broken reed.

What is the reason you do not attend the meetings for discipline?
Is there something in the way?
Is there no life there?
A vessel that has Light in it (and Light is Life) if placed
in a dark place will give light to those around,
and may not this be your case my dear friend, if you go with and among them?
Though they be dark, yet if the Light does but go with you do not keep away from them,
it may be your Light will kindle theirs;
but after all I leave you to that which convinces, I do not judge you,
I only write what comes before me,
not willing to judge according to any judgment of my own.

Do write whenever it lies upon your mind with a little glimmer; you may help us:
for we need help,
though we can also acknowledge the good Master condescends greatly to
favour us in our solitary allotment as to fellow feelers--ours is a poor,
very poor meeting in one sense, but rich enough in the other, when rich we need nothing,
is not this the truth?
Now farewell in every sense of the word,
may the richest of blessings continue to be yours,
may the light of the Most High very often cheer you on your way,
and may both of us know daily preservation from the Lord.

[.signed-section-closing]
Your sincere and affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.^
footnote:[William Hodgson was born at Sheffield in 1804,
of parents who were members of the Society of Friends.
Most of his father`'s family removed to America in the year 1822; his son William,
who was serving his apprenticeship to the drug business, in London, followed in 1827,
and settled in Philadelphia,
where he carried on business until within twelve years of his decease.
Possessing strong convictions, good natural abilities,
and yielding to the operations of the Spirit of Truth,
he became remarkably quick of understanding and clear
in his apprehensions of Divine things.
He early saw that what was being promulgated in England as the doctrines of Friends,
came very far short of the true standard of our profession,
and laboured with the ability afforded,
both with pen and tongue to avert the calamity which
he foresaw was impending over the Society.
{footnote-paragraph-split}
When Joseph John Gurney,
the chief author of these modifications of the views of Friends,
visited America in his capacity of Minister of the Gospel,
William Hodgson made no secret of his disapproval,
and attached himself to those who felt bound to oppose the spread of unsound doctrines,
and laboured to protect the Society from their baneful influence.
As a member of the Meeting for Sufferings,
which may be said to be a standing committee of the Yearly Meeting,
he had a large share in the preparation of its documents,
which had for their object the defence of the Society`'s principles, and in so doing,
he knew by sad experience what it was to have to
contend with false or half-hearted brethren.
He maintained an extensive correspondence with his
fellow-professors on both sides of the Atlantic,
and the remarkable clearness and cogency of his style
rendered his communications extremely valuable,
for of him it may be truly said,
that in respect to all questions affecting the welfare of the Society,
his trumpet gave no uncertain sound.
{footnote-paragraph-split}
He was the author of the following works:--[.book-title]#Life of John Pemberton;#
[.book-title]#Select Historical Memoirs of the Religious Society of Friends;#
[.book-title]#Selections from the Letters of Thomas B. Gould;#
[.book-title]#The Lives of the Reformers and Martyrs before and after Luther;#
[.book-title]#The Society of Friends in the Nineteenth Century,
etc.# besides several smaller publications.
His pen was ever ready in defence of the original faith of the Society,
and the last-named work which was published in 1875-6, in two volumes, is,
as its title in full indicates,
a historical view of the successive convulsions and schisms
in the Society of Friends during this present century.
This work abounds in valuable information faithfully and impartially set forth,
and although cavilled at by some and ignored by others,
the facts and conclusions contained therein have never been refuted, and it will,
without doubt,
form a valuable contribution to the history of Friends as a distinct people.
He died at Philadelphia, on the 24th of 12th month, 1878, in the 75th year of his age.]

[.signed-section-context-open]
Cockermouth, 30th of 3rd Month, 1855.

[.salutation]
Dear Friend,

I fear you have thought me remiss in not writing to you respecting
our mutual loss in the decease of our dear friend Lydia A. Barclay,
whose spirit fled from the earthly tabernacle, not long after I wrote to you,
giving an improved account of her state of bodily health;
but I expect you are made acquainted before this with circumstances
connected with her departure from this scene of conflict and trial.
Such was in no small degree the portion of her cup, while, we have no doubt,
she was favoured above many with the aboundings of
heavenly love and the covering of his Spirit,
through grace and giving up thereunto.
O! it does one good to think of her retirings in spirit,
her watchings at the posts of her doors, that the Beloved of her soul might not pass by,
as it were, without leaving of his fragrance,
the sweet smelling odours of his Divine presence
who was as a rich canopy cast over her mind.
Yet her spirit would, for the desolations in the church, the way marks many,
very many of them thrown down,
for the persecutings of Esau and the backslidings of Israel, go mourning on the way,
under deep tribulation; which, may we not believe in no small degree,
hastened the laying down of that frail tabernacle, so worn and so weakened thereby.
It was a comfort to us to be with her at this solemn period.

The desire now seems to prevail, to follow her as she followed Christ.
With the love of myself and wife,

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From William Hodgson.

[.signed-section-context-open]
Philadelphia, 10th of 6th Month, 1855.

[.salutation]
My Dear Friend,

London Yearly Meeting appears to be in a lamentable condition indeed.
Letters just received by the Gurney people here,
represent almost the whole body +++[+++in England]
as gone over to the party of the separatists in Ohio, etc.^
footnote:[Referring to the recognition by London Yearly Meeting, in 1855,
of the "`smaller body`" in Ohio,
which seceded upon the refusal of Ohio Yearly Meeting
to recognize the "`larger body "`in New England;
which had disowned John Wilbur and dissolved the monthly meeting to which he belonged.]
Will there be no stand raised against this in your land?
Will all the sound Friends be satisfied to remain in connection with a
Body which has so far vitiated its standing as a Yearly Meeting of Friends?
Yet the result might have been anticipated,
and indeed was so in some degree by some of us,
though we did not think the division would be quite so prompt or so sweeping.
We have, however,
only as yet heard the proceedings up to the beginning
of the sitting on Seventh-day morning,
when the large committee was to make a report to the Yearly Meeting.
What afterwards transpired we have not heard.

But it must be remembered that the whole difficulty came from London Yearly Meeting.
It did not originate here.
We were a harmonious body all over the United States,
however weak and faltering and backsliding,
until J. J. Gurney made his appearance among us,
sanctioned by the authorities of the Church in Great Britain;
and behold the distraction which reigned among us by the time he left these shores!
And this distraction and devastation has been going on at a fearful rate ever since;
so that by far the greater portion of the Society seems to be swallowed
up in the vortex of a fearful separation from true and ancient Quakerism.
There seem to be very few among you who appreciate duly the nature of the case.
Yet I trust there are some, nevertheless,
who will not be found bowing the knee to Baal and kissing his image.
These will have great sufferings to pass through if they maintain
their true integrity in the midst of such a general departure;
and a departure characterized by such plausible and fallacious misrepresentations.
I would that faithful,
honest-hearted friends could have the true state
of the case fairly and fully before them,
so that they might be favoured by the Lord`'s gracious help,
to see the stratagems of the cunning adversary,
and clearly to understand the fearful lapse that has come upon us.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
W+++.+++ Hodgson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Rickman.

[.signed-section-context-open]
Cockermouth, 12th of 10th Month, 1856.

[.salutation]
My Beloved Friend,

I write as I feel, that you are still given up in heart to serve the Lord,
and willing too, I believe, to give your body to be burned,
if required by your good and gracious Lord and Master.
May you be strengthened for every good work and service which He may allot to you,
and O! what an honour to be thus employed!
Therefore, let your courage fail not.
As for me, I can,
and do wish you "`God speed;`" we need true Israelites and
clean handed workmen and work-women to do the Lord`'s work,
and by them and through them it shall prosper.
Those that are like-minded have need to keep very close in the present day,
very close together I mean, and the language is, I believe,
going forth to these "`Fear not;`" when the sifting is over,
there will be a people to his praise, who will shine to the glory of God the Father,
may we not believe so?
If we may but stand in this day of shaking through all the mixture,
and persevere with patience through all disguise, what a favour!
The whole work is the Lord`'s.

In reply to your solicitous desire for my encouragement,
I cannot but say in my heart that times of refreshing do
come and help is indeed laid upon One that is mighty:
what a favour (though I fear not sufficiently prized
by me) to feel the overshadowing of his love,
and Him indeed to be with us!
In regard to outward things I am also, able to tell you still,
that He blesses in "`basket and in store;`" there is enough with, and for the day,
and for the morrow too.
I feel encouraged with my business, and find it in a peculiar manner fitted to my mind,
so that way has (I can say) been always made for me, and it never is so narrow,
but that I am enabled to walk in it, through his wonder-working power,
and ever bountiful hand.

Nothing is, I believe, so good for us, as often--yes, oftener than the day--to turn all,
and lay all,
by his strengthening help at the footstool of his power and love in the silence of all,
when the command goes forth as it often does,
"`Be still,`" and though this may be not always attained,
yet to wait and hope for his salvation.
I have written much more than I intended to you,
but there is that which I feel that seems in you to draw from me:
may this united feeling of (I believe) true Christian love be ever our continued experience;
and fail not my dear sister in the Truth, to hand, when enabled to do so,
a word of caution or encouragement to a brother who I dare to believe and hope,
knows that without Him he is nothing, but with Him he can be all things that He requires.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 19th of 10th Month, 1856.

[.salutation]
My Dear Friend,

What a favour it feels to be now and then to meet with those,
in whom we feel the germ is deeply seated and germinated,
which will and does answer to the precious Life as face answers to face in a glass.
And this is, even in this cloudy day, our favoured experience sometimes,
though perhaps far between, to meet with; and then such can hold sweet converse together.
"`As iron sharpens iron so does the countenance of a man his friend,`" and can we
not say also the same in perusing the written memorial of a departed valiant,
or the meekly obedient servant who has gone to his or her rest?

__The Examination,__^
footnote:[[.book-title]#An Examination of the Memoirs and Writings of Joseph John Gurney,#
by William Hodgson, Jr., Philadelphia, 1856, 145 pages.]
I have read.
It is well for us to have the whole truth,
and it is always cheering to me to know of its being vindicated against error.
I have been edified, I may say,
in the perusal of this [.book-title]#Examination# with the sound views therein brought forward,
of some of our early Friends.
Would that these were not so trampled upon, as in this day they are, by many among us,
who are not of us inasmuch as they have gone out from us, or never were of us.
I desire your encouragement my dear friend;
may your hands be always made strong by the mighty One,
even by the hands of the mighty God of Jacob!
And may you always be a fruitful bough to his praise,
who can fit and qualify in every needful time.
My mind has been brought under
much feeling in regard to the love of change now prevailing in our Society,
I fear to our hurt,
and the hindrance of a growth in the precious Truth to a very great extent.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John Finch Marsh.

[.signed-section-context-open]
Cockermouth, 27th of 11th Month, 1856.

[.salutation]
My Beloved Friend,

In looking a little at debts due in letter writing and intentions not yet carried out,
I find your name to stand upon my mental list, and will now endeavour,
if only by a few dry lines, to cancel it.
My dear friend, to look back to our interview in Park Lane,
when permitted to partake of your very kind and cheering hospitality, is refreshing.
It was one of those seasons wherein the true leaven,
I believe was permitted to work to a little further
establishment by grace on that immutable Rock,
which is Christ Jesus.
I say to be a little further leavened and seasoned, through mercy and love,
by the working of that grace which deepens and strengthens when Friends who are like-minded,
and in the unity of the faith are permitted rightly to meet
together as I trust and believe we were at that time.
O how strengthening it is to the younger in experience to meet with the elder,
those who have known the way before them, and trodden the slippery path,
known the dangers by the way,
and that constraining and restraining Power and holy
Virtue which saves from and in every danger,
when obedience is yielded thereunto!

I have remembered, when with you it was (you said) a wintry season in your experience,
and this, no doubt, with all of us has its time, and is good for us.
It feels to be so, that this is truth,
and we have to endeavour patiently to abide under it.
To such as yourself it cannot be a new path or any new thing:
as for myself I have of late felt as though summer was gone never to return,
so void of strength, so poor and low.
This experience I have said in my mind, is nevertheless good,
and if rightly abode under until our change comes, brings confirmation with it, that,
of ourselves, we can do nothing,
that all good and all strength comes from Him who works
in the believer to will and to do of his good pleasure,
and to suffer if and when He pleases.

Poor +++_______+++ also, has very much to contend with,
and is learning something of the fiery warfare,
even it may be to the treading upon scorpions,
which will not be permitted to hurt when they are
trodden upon in that faith which is of God,
thus keeping above all that is not of God, and contrary to the Truth;
and in which Power it is intended, I believe,
that we should not be in any way hurt or unduly cast down.

[.signed-section-closing]
I am, very affectionately, your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Rickman.

[.signed-section-context-open]
Cockermouth, 19th of 8th Month, 1857.

[.salutation]
My Very Dear Friend,

I wish if only by a few words on paper,
to assure you according to the best of my ability,
that it feels pleasant at times to turn my thoughts to so kind and interested a friend,
who I know feels true love to flow towards us.
As to your catching a little help from such a one as myself,
I eagerly would catch a little from you,
for I believe I never felt more poor and in need of help;
the stones of the brook seem dry as though the refreshing
streams had long since ceased to run:
nevertheless, I may yet say, there are times now and then,
when favour in the way we can desire, or a measure thereof, is dispensed,
so that we may know we are not forsaken.

Your account of some of those we know, is very interesting to us.
Capel still sounds familiar to us, and Dorking too.
I know but little of C. R. K. and desire while writing that all
is well with him and that the favour of man may not hurt him;
may he be strengthened by that Divine Power, which is strong in our weakness,
and who ministers to our need severally as He will, if we are humble, patient,
and willing to abide the refining and purifying process.
I continue to believe that without the humbling power
attends us on our way we are not safe,
and that such a one (perhaps quickly sprung up, in favour with man,
and I do not doubt with God) will need it,
and that in no small degree if he becomes a polished shaft in the mighty Hand.
There may be nothing more dangerous for some of us than the favour of man.
How much there is, you know, that is of man and not of the Lord, that now works among us,
in our religious meetings, and which is according to the contrivances of men!
How little some of those who seem to sway and rule among us,
how little some of these know of the one true and saving baptism by a yielding
to the power of it implicitly in the secret of their hearts!

I seem to feel for you in your expectation of +++_______+++ among you.
Who is sufficient for these things, may we not cry out?
But we know in whom we have believed, and on Him we must believe still,
and in patience unto the end, which is to crown all: but we need refining;
some are settled on their lees, and they will have it so:
but Jacob is not like unto them, there is the babe-like spirit yet among us,
which cries Abba, Father, and prevails with Him.
Let us hope to the end,
for we believe that all things work together for good to the obedient soul.

[.signed-section-closing]
Your very affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

1858, 3rd Month 4th.--To meeting in Belfast.
Fresh cause to rejoice in the Lord my Saviour,
and to know that it is good to serve +++[+++Him], and willingly give up to his requirings.
I had some hesitating thoughts about giving up to the delay it might occasion,
as to getting through my business and leaving for home,
but I have had fresh cause to feel thankful in having yielded
to apprehended duty in going to meeting this day,
and can say I have been helped onward to more business thereby,
through the unexpected encouragement, without solicitation on my part, of two Friends,
after meeting, to go to for orders,
and a letter of introduction was given me to the manager there.
Seek therefore first the Kingdom and the worship and service of our holy Redeemer,
and truly all things needful may be looked for, according to the promise in Scripture,
"`All things needful shall be added unto you.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 24th of 5th Month, 1858.

[.salutation]
Dear Friend,

I have not felt it laid upon me to attend the Yearly Meeting.
These are troublesome times,
"`the whole head is sick and the whole heart faint,`" may it not be said?
As a people we seem fast sliding downwards and backwards;
nevertheless I believe there will continue to remain a remnant who will
serve the Lord unshackled by any armour but what the Lord does put on,
and these are they who are to "`turn the battle to the gate.`"
Can we not some of us say in tenderness of soul before Him,
and in that sense which is begotten in us, "`How goodly are your tents,
O Jacob! and your tabernacles, O Israel!`"
It is also given us to see at times, and this for preservation on the immutable Rock,
that on the Watch-Tower only, and in humility of heart, minding well our steppings,
whether as relates to thought, word, or deed,
that hereon and herein is our life given us as it were for a prey.
May we my dear friend, be of this number,
who are of those whom the Lord says shall be his when He makes up his jewels

[.signed-section-closing]
With love, your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Rickman.

[.signed-section-context-open]
Cockermouth, 31st of 12th Month, 1858.

[.salutation]
My very dear Friend,

I have not given you any particulars of the late Conference,
but you would no doubt be in possession of the result
or conclusion for reference to the next Yearly Meeting,
which has felt very trying to us and to many, because those in high places,
and men looked up to, are mingling themselves with the mass and going with the multitude,
and it does appear,
are so blinded as to believe they must accommodate the wholesome rules
dictated to our predecessors by the Spirit of Truth as of the Truth,
to those who are weak, instead of by example and precept too,
bringing or endeavouring to bring these to the standard,
which as they go from strength to strength their eyes being anointed to see,
they are required to uphold,
and thus proclaim in the face of the people and to the glory of God.

Oh! how degenerated do some of these appear whose eyes the god of this world,
surely says, my soul, has blinded,
so that they stumble and do not obey the everlasting Truth,--that Truth
which was in the beginning and has been through time ever since.
But we believe there will yet be a people unto the Lord left faithful,
pure and true to his standard, who will not mingle with those that have gone back;
but who will stand to their Master unflinchingly; and the strength that is in them,
and will be in them, will strengthen and gather others yet unborn,
so that there will be a mounting upwards as on eagles`' wings,
and no fainting by the way as the fainthearted do, and slide backward.

We have, some of us,
faith to believe that the dross shall yet more and more appear
and that those that are refined shall stand over all;
so may we be faithful, unflinchingly faithful to the Master,
for it is by these that Jacob through the strength of his God shall arise,
it is by these that the star shall be seen,
and following it they shall know Him to be their Light and Guide even unto death
through a crooked and perverse generation that have turned their backs upon Him.
Well, my dear friend,
how encouraging it is to know there are those in the land who are true to the Master,
and to meet with them is precious, and they know each other face to face.
These ought to encourage one another and will encourage one another,
for they cannot do otherwise: their faces do shine,
and they behold one another in the likeness of their Lord,
that likeness wherein man was first created, even the glory of their God;
but those that are degenerated and gone from the Master know not them nor their Head,
for they are departed from both Him and them.

You ask me if I returned home with a relieved mind.
I did, having been strengthened to lay down my life in the Conference (I trust),
and it may be I appeared a fool there for the cause of Truth,
which I believe I advocated, and felt as dear to me as ever,
and you know that when the Master strengthens and puts forth, He goes before,
and the fear of man is taken away; this was my experience at that time,
that though at the first I seemed all blank,
and as though there was nothing for me to do there,
yet I felt constrained and raised up for service, both (I believe) to reprove for error,
and contend for right things (the Truth).

[.signed-section-closing]
I remain, your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Rickman.

[.signed-section-context-open]
Cockermouth, 17th of 3rd Month, 1859.

Since I wrote to you last I have been on a French journey, with, I believe, good success,
and hope it will prove advantageous in the way of business,
and it may be strengthening also in that which tends to strengthen in
the hidden life,--a coming more under the cross as respects our testimonies,
which to me feels more trying to carry out abroad than at home:
nevertheless my view is that it has to be borne at home or abroad,
and that the Spirit of Truth requires the truth at our hands if we would be clean-handed,
as much in one place as in another.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 18th of 7th Month, 1859.

[.salutation]
Dear Friend,

It needs not many words to acquaint you that I unite with you,
in your views of how things are among us, and how they ought to be.
I return you your letter with a feeling of, I may say increased interest if anything,
accompanied by a desire that we may wait often upon
our Holy Head to know his will in all things.
And I have thought, and again in the reading of yours have dwelt upon the thing,
that it might be well for the scattered few, as we appear to be, who are like-minded,
to meet together,
as those who "`feared God and spoke often one to another,`"
that we might strengthen one another in his Name,
and in those testimonies we feel bound to uphold,
as well as against those innovations upon practices which had their
rise in the faith once delivered to the saints.

The Lord could give strength as well as all knowledge
in the revelation of his will in this matter,
to the bringing of it about;
and my mind turned to the meeting together of such
at stated times and in stated places with this view,
even if it were once in six months, such as by correspondence might be thus assembled,
those who are baptised into a sense of the state of things,
with full purpose of heart to cleave only to our testimonies for God,
as revealed unto us by his Son in our hearts,
and as were delivered to our forefathers in the Truth
after the same sort;--and this might be,
by a meeting for worship to feel the solemnizing of the Head,
and be baptised together more closely than we now are or
can expect to be (perhaps) in our mixed assemblies,
and afterwards it might be our object to look into, consider,
and dwell upon those wholesome advices,
rules of faith and practice handed to our forefathers,
and kept to as queries and advices for a time, but now already altered,
and likely to be still more altered than they at present are,
in order to bring these advices and queries down to the people`'s standard,
instead of bringing them up thereunto.

My view is,
that meetings for worship thus gathered as a general
meeting to be held at appointed times,
would if in the Divine counsel and fear,
grow by the attendance of others likewise desirous of retaining the principle:
but in such sittings as followed the meeting for worship, I would say,
there ought to be only such as were already themselves in the principle
and approved practices (which are the fruits thereof),
that there might be no schism in the body,
but that harmony and peace which Truth leads into,
and which those who are led by it are willing (and it is their souls`' earnest
desire) to be found bowing under:--thus the work of God would grow,
and we would be strengthened,
so that thereby we should be enabled to hold up the head in hope, and bless the Lord.

I have thought that independently of the above we would not forsake
the assembling of ourselves together as our manner now is,
as I believe it might be the Divine will for us so to do;
and if brought to anything of the sort I have described,
we must then leave all results in the Divine fear, and to his unerring counsel,
which I believe would not be withheld from such,--and peradventure
it might end in our present meetings disowning us from them,
but this would not be, I expect, all at once,
and we might be by that time a banded company of honest hearts and hands here and there,
where Truth through obedience to its pointings was kept to.
Ponder it and let me know your views and feelings thereon.

I have written in so much haste as the matter has flowed that perhaps,
you will have difficulty to read it.
In the meantime farewell, with our united love.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Thomas Drewry.

[.signed-section-context-open]
Fleetwood, 28th of 7th Month, 1859.

[.salutation]
Dear Friend,

The views penned by you have somewhat taken hold of my mind.
I much unite with you in what you point out as the view of your
mind as to the course which might be right to to take by those
who desire to maintain the ancient testimonies of the Society,
and who cannot go along with those who would change them.
I have felt as if I could give up to be one of that small
company unworthy and weak as I feel myself to be,
and I can believe that as we moved along with a single
eye that we might be a strength to each other,
and come to experience a much larger measure of unity in our assemblies than
perhaps we can expect in our present mixed companies;--that "`bond of peace,`"
resulting from a true "`unity of spirit`" we are in these days,
I fear, much strangers to, at least I feel it to be much my case,
so that in measure I appreciate the company of those who in their measures are faithful.
I feel that we might realize something of this true fellowship in these gatherings,
which would cause us to rejoice,
and feel thankful that it had pleased Him "`to undo`" according to his will,
"`the heavy burdens and to let the oppressed go free, and to break every yoke.`"

I unite with you that a meeting for worship should precede,
and that the meeting held afterwards should be of those who are in unity;
so that as you observe there might be no schism in the body.
I have often thought over what it has been given you to write,
and something of thankfulness has been the covering of my mind,
that such has been presented to you.
It is indeed needful for us to dwell near to Infinite Goodness
that the right way may be made more and more manifest,
and if clearness to a certain extent is given,
it may be well not to be too anxious for more knowledge
than may be vouchsafed from time to time.

I wish to be careful in what I commit to writing not to exceed my bounds,
but your view of looking into,
considering and dwelling upon the Queries and Advices is satisfactory to my mind,
retaining the savoury and sound portions and omitting that which is otherwise.^
footnote:[This remark refers to the 1834 edition of the rules of [.book-title]#Discipline and Advices.#]
I have long been of the mind that to make the acquaintance of (with the view of conferring
with) those who are firm for the old land-marks of our Society was very desirable,
but in my interaction with others, these I find are very few,
so that those who would be willing to take part in a general
meeting of the kind pointed out would be few.
This however does not affect the matter as regards its rectitude, not in the least;
our place and endeavour will be to feel after what is right and to do it,
leaving the consequences.
I hope the matter will have its due place in our minds, and as freedom is given,
we may lay before those who are like-minded with ourselves
the view of a general meeting as it has appeared to you,
leaving out names.

I feel much interested in your observations and shall be
glad to hear from you again pretty soon as you have freedom,
and to know whether the subject is becoming more matured in your mind,
and how it is regarded by others of your friends would be interesting
to me as you might feel your mind engaged in freedom to communicate.
We should be as a city set on a hill; we should have need of best help,
which I have faith to believe would be afforded,
as it was our desire to serve and obey Him in our day and generation.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Thomas Drewry.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 14th of 8th Month, 1859.

[.salutation]
Dear Friend,

Your acceptable letter came to hand in course,
and I feel that I have been long in replying thereto.
It was a comfort to my mind to find that you could go along with me in my views,
and I would hope that there would be those who could also
look at our state and standing in the Truth as a Society,
as we look upon it;
but since I last wrote to you I may acknowledge there
have come discouragements to a present action thereon,
while at the same time it is well for us, I believe,
to endeavour to look to Him who is over all discouragement.
I have also had to believe that there is a lack of truly united views or seeing eye
to eye in some very important points where we would have not much looked for it,
so that while I believe it is well for us to endeavour
to strengthen one another in the root,
there has come a cloud over more, which the time may be near for the lifting off,
but the time must be waited for.

Ah! my dear friend we are not looking all, it would appear one way,
or may I say we are carrying about with us vestiges of the man which retard our progress,
and prevent seeing eye to eye while any of these remain.
Perhaps it may be well for us to keep in mind the one essential point we have
arrived at (in desire and prayer for our people) that of endeavouring,
each of us, to strengthen where we can in that which we believe in, as Truth,
and endeavour, while striving to keep therein ourselves, to build up in the same,
though the extension of our views be not at present carried out.

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 9th of 10th Month, 1859.

[.salutation]
My Dear Friend,

I fear it may almost seem negligent my not sooner replying to your acceptable letter,
but not feeling quite ready or quite free to put
pen to paper relating to those matters of Truth,
so interesting, and I may say more than interesting,
zealously affecting our spirits for Zion`'s welfare within our borders, I have delayed.
My mind has from time to time turned towards you,
and it feels comforting your desire to encourage me.
O that there were more found than we know of,
sincerely desirous of encouraging one another,
whom we might feel bound with us to the testimony,--"`to the law and to
the testimony,`" which is precious in our day as ever it was,
and perhaps more precious, because less regarded I apprehend,
than in the days of our forefathers in the Truth; I mean among those under our name.
Isaac Penington`'s description of mystery Babylon is very striking and very true.

Since I last wrote to you I have had occasion to visit Glasgow and saw William Smeal;
we had some conversation together as we mostly do,
in the short time I had of his company.
This time in the course of our conversation, I yielded to a fervency of spirit,
if I may so say,
and alluded to my desire that those Friends who feel bound to our testimonies (Truth`'s
testimonies) might meet sometimes together for the strengthening of one another,
and to my surprise rather, he acquiesced in my feeling, and thought it would be well.
He also said he thought at a Yearly Meeting time would be
most suitable as regards Friends being then met together,
that are as to their dwelling, so scattered.
My mind has from time to time reverted to the subject
of my letter which you alluded to in yours,
and I may say has been renewedly dipped latterly
into a sense of what feels to me to be our need,
that of knowing one another and mingling together if it can so
be for our refreshment in the Lord and encouragement one of another,
in this day of shaking and treading down.

What a favour, what a privilege would it not feel,
could those who are thus minded meet sometimes together, as a select company of Friends,
and read over together,
and dip into the life of some of the queries and
minutes respecting those important testimonies,
as to our every day walk in life,
somewhat like those worthies before us lived in and felt bound to the maintaining of,
as may be seen by some of the minutes left on record!
I hope you will understand what I have written of my feelings.
Use all freedom in writing and be faithful at all times to your Master,
to others and to yourself, and the Lord will bless you.
Farewell.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Thomas Drewry.

[.signed-section-context-open]
Fleetwood, 28th of 2nd Month.
1860.

[.salutation]
Dear Friend,

You will I dare say think me a long time in replying
to your three acceptable letters duly received.
I have as before often found myself mentally inditing a letter to you,
but have of late been so busy and at times felt so devoid of good,
as not to be able to think, let alone write.
Amidst all,
I may acknowledge that the consideration of questions affecting
the welfare of our Society has felt very near to my best feelings;
and of these the subject first mentioned by you last autumn has been foremost.
I should be glad to hear what further progress it has made in the view of your mind.
I hope you will be encouraged to go forward as way opens,
though it may be that the openings are small.
We may remember that it is by little and little that the outward day dawns,
so it is often with the works of the great Creator in man,--the light
gradually breaks in on his mind in great condescension to his low state.

I have sent you two pamphlets received lately from America.
They are valuable.
From that entitled [.book-title]#Serious Review# (Philadelphia, 1860), much instruction may be derived,
applicable to us as members of a divided religious community.
I believe that clearness of apprehension,
as to our position and the right course to pursue,
is a valuable gift from the Giver of all good,
and I have thought that the perusal of this [.book-title]#Serious Review#
has cleared up the grounds upon which we should rest.
I was particularly struck with the force of a remark contained
therein--that London Yearly Meeting was a separatist body--and
there seems no getting over the force of the argument.
Right reason is a gift, but if permitted to lie dormant, it may be taken from us;
therefore, with our great predecessor in the faith--Barclay, we must, as he did, use it.
Only to think of the conclusion--London Yearly Meeting a separatist body!
Is it not a very solemn conclusion!
Would that it were in our power with a clear conscience to rebut the grave charge!

We had at our meeting this afternoon +++_______+++ of +++_______+++ who is
on a religious visit to some of the meetings in this quarter.
He stayed at our house,
and in course of conversation I asked him if he had
read the [.book-title]#Journal and Correspondence of John Wilbur,#
he replied, "`no.`" I recommended it to him.
He said he had read a good deal of the controversy in the Friends`' periodicals,
but had not time to read Wilbur`'s journal,
he was then engaged with John Yeardley`'s journal.
I made bold to tell him that I hoped he would not
close his mind against the perusal of Wilbur.
I felt grieved to find one in his station so disinclined
to inform himself on such vital points.

[.signed-section-closing]
I remain, your friend,

[.signed-section-signature]
T+++.+++ Drewry.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 15th of 4th Month, 1860.

[.salutation]
Dear Friend,

I may inform you with regard to the subject,
the very important one respecting which you query of me "`what
further progress it has made in the view of my mind,`" it has,
I trust in best wisdom, only lain dormant the appointed time,
and that through all I may maintain a humble, yet fervent desire, to let alone,
or give up in obedience to any motion and every motion that comes from the Lord.

My mind, I may acknowledge, has again turned to what did appear,
and on again perusing what I had written at the time I laid open
to you my views by way of a general letter to solid Friends,
Friends of Truth,
a freshness has in some measure again sprung up accompanied with a feeling desire
to know the Lord`'s will if I shall cast it forth either to take root,
or be blown as chaff by the winds (the Lord`'s blasts) as a thing of nought,
and only imagination,
but the Lord forbid that I should lessen in any degree his great lovingkindness
which all my life long He has bestowed upon me in reviving in me the word
of his almighty power against sin and iniquity,
and deception of any sort;
so that I do trust I may look upwards in a truly
humbled sense of his condescending regard,
even unto such a poor one as myself,
who am wholly dependant upon Him for every good thought, word or deed,
inasmuch as that He has +++[+++visited]
and does continue to visit me.
Your encouragement, my dear friend,
to accept what is manifested to my mind as it may be opened, though small, is animating.

Oh! could we but say London Yearly Meeting even amid much acknowledged
weakness had in its collective capacity espoused the cause of Truth and
had not shrunk in moments of its greatest trial to testify against error,
and to cleanse the camp of its adherents without respect to wealth, position, influence,
or any other thing.
But alas! where are the anointed elders?
or where is the spirit of our elders?
Women or the womanish spirit rules over us in our church or body of professors!
I am not surprised at your remarks (altogether) respecting +++_______+++
and many more of our day are afraid of the Jews,--the Jew outward.
Thus much in answer to your first letter.
Now for your last received.
What a state of things at York!! Yet need we be astounded?
No!
Matters must grow worse and worse until there be
contrition and sorrow for the things that are past,
until there be an unlearning of that which has been learned out of the unmixed truth,
until the Lord appears with the hammer and sword to slay the unrighteous man,
the transgressor in judgment,--the supplanter of worm Jacob in our day.

But where is +++_______+++? I have known him from a youth,
but not until lately as a stately tree, but my dear friend, I tell you my mind,
only leaves are there as regards the place wherein they have put him,
I mean the ministry.
I am grieved nevertheless at the hearing of it, but if we live so long we shall see,
I believe, that such who are full of leaves will never until they shake them off,
and are renewed within by the humbling power of God,
will never flourish in the courts of the Lord`'s house, yes, says my soul,
and may this never be, but only through and by the one everlasting Way, Christ Jesus,
on whom, whosoever falls, shall be broken, and that savingly so,
to the glory and honour of Him to whom it is due.
Your account is truly interesting respecting +++_______+++.
I can believe he stands very much alone,
and would like well we were more acquainted.
He did well to oppose the sentiments expressed so boldly.
Oh that we (we I say,
for I feel there are here and there those who can and do come under
the gospel appellation we) knew more of one another face to face,
and the time may be at hand.
How lovely are they in their lives!
I feel I can say in beholding them in my mind`'s eye, "`How goodly are your tents,
O Jacob, and your tabernacles, O Israel!!`"

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.offset]
+++[+++The following letter is the expression of the concern so much
resting upon the mind of our dear friend about this period,
showing what appeared to him to be needful for the welfare and preservation of the flock.
Had the course thus pointed out been more generally followed
by those who were alive to the state of things in the Society,
how different might have been the position of Friends now!
The result, however,
was that a few were encouraged to meet together in the way described,
and more or less have continued to do so to the present time.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Cockermouth, 4th Month, 1860.

[.salutation]
My Beloved Friends,

In that which changes not, and of which by the grace of the Father,
I have with you received a portion, I salute you,
my heart being warmed therewith at this time,
and I have desired to open a little to you in that freedom
which is given to us as children of the same Heavenly Parent.
I do salute you, shall I say +++[+++as suffering]
with you in the bonds of the gospel, for which,
and in the life of which so many of the Lord`'s visited
children have and do continue to suffer bonds,
not outwardly by imprisonments and stoning,
etc. as did some of our fathers in the same unchangeable Truth,
but being spiritually bound we do groan sometimes,
inwardly from the severe bondage and hard usage we sustain in our spirits,
through the oppression of the enemy,
and that by his deceit and wily workings in those who would be of us,
and who bear our name as people of the same fold, but who have not yet entered it,
or have erred therefrom.

And my spirit yearns and cries unto God, the God of our life,
that He would be pleased to redeem his people from this cruel yoke and bondage,
which unless He be pleased to support us under it, or arise for our deliverance, must,
I apprehend, crush us as a people.
Unless the fathers and the mothers be faithful and stand fast,
where shall the children be?
And does not wisdom now lift up her voice in our streets,
and open unto us that which is of the Father?
And will we not endeavour with the ability which God gives,
to strengthen the things (the small strength of Jacob) that remain,
so that we and our children,
those who are young and tender under the Lord`'s
visiting power with which He is pleased to visit,
may gather strength for the fight,
and still maintain and continue to uphold those precious testimonies
to his Truth revealed in our inward parts to be Truth and no lie,
and which our dear and honoured predecessors, so many of them, boldly stood in,
and sealed their testimony thereto with their blood!

And shall we not show forth more boldly and unflinchingly than we perhaps have done,
that life which is as blood running through the inward man,
our strength and life in best things, heavenly things?
Shall we not endeavour to confirm one another in this precious,
hidden life which is as the very soul of a man to us?
Shall not we who are in the Father`'s likeness according to that redemption purchased
for us by his beloved and only begotten Son through his sufferings upon the cross,
and our several measures of obedience cooperating with his love working
in us--shall not we show our love for Him who first loved us,
by cleaving fast to that Word of his grace which is as a hammer that breaks to pieces,
and as a fire that consumes, in his controversy with the things of Esau,
that which is for the fire;
but which (His love and His begotten in us) has been hitherto, it may be,
too much hid in us and not brought forth, only as a thing that is lame, blind or halt,
and perhaps too much despised by ourselves,
instead of being offered boldly and unreservedly according as the Lord has called for it?
Will not the Lord visit for these shortcomings unless we are more faithful?
and how can we expect his kingdom to come upon earth,
as our fathers some of them fought for it,
if we continue to be thus dwarfish in our testimony-bearing for Him,
who requires a whole burnt sacrifice, and shrink from fully showing what we believe,
and as well in whom we believe?

My mind runs upon this,
and I believe the call may now be going forth to be more faithful
and more noble in espousing what we believe to be truth,
and testifying against what the Father by his Son shows us to be error.
And may we not believe my dear friends,
that in order for our strengthening and the compact
of the body after our manner of belief,
and the pulling down of Satan`'s strong holds (which
he appears to us to be building up in the minds,
even in the reasoning part of many who are under our name)
it would be well for the few in Jacob to arise,
wash, and anoint,
and strengthen one another`'s hands in the Lord by meeting together with one accord,
in one place at times,
though it might not be oftener than once in six months as a general
meeting for worship at a stated and most convenient place;
there to build one another up by showing our faces one to another,
and seeking together to worship after the manner we profess
to do for the Lord`'s blessing among us.

And it might be afterwards to encourage one another such as are of one mind,
also to assemble for the reading over and dwelling upon that sound
form of queries and wholesome advice given forth to our forefathers
under and in the powerful unction of the blessed Truth,
in order then and there to feel the constraining and restraining power thereof,
as the Lord our Head might be graciously pleased to work in us.
I have thought that so doing might tend to our preservation
and building up in our most holy faith,
from which we desire to swerve not.
In such first gathering together, I would suggest such as might incline to meet;
but in the after meeting, at an hour previously fixed upon,
only those might gather whose eyes are open to the Truth we profess,
by being baptised into a sense of the weight and
importance of these testimonies committed unto us,
and that no nominal or merely birthright professors be of that number,
but such as the mind of Truth pointed out,
who might be before appointed by those who know one another or in other words those
who in the fear of the Lord have in the sense of our mournful condition as a people,
been accustomed to speak to one another concerning the things of the Lord`'s house.

Ponder these things, dear friends,
in your hearts and feel after the mind of Truth therein.
Does not Truth cry out in our streets, why do you stand back?
Why do you not come forth and show yourselves on
the Lord`'s side who has appeared unto you?
and may his work prosper in our earth for He has planted it there for some wise purpose,
even his own glory and our everlasting peace,
that peace which He gives to the faithful (we know),
and which neither professor nor profane can take
away while we abide faithful unto him our Leader,
and the Counsellor of his people Israel.
So, dearly beloved friends, farewell in the Lord,
who is over us and in us while we are his by obedience to his spirit within us.

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 26th of 4th Month, 1860.

[.salutation]
My Dear Friend,

It has been very comforting to my mind from time to time to know through your
pen to one or other of our nearly united Friends on this side the water,
that the precious cause of the Master is as dear to you as ever.
Comforting to us it is to find there are those here and there, though they seem but few,
few as the gleaning grapes, that own with us the impression of the Master`'s finger,
and are desirous of being found with Him whether that be in suffering or rejoicing.
Own with us, I have written,
feeling assured that if your spirits do testify with our spirits the one thing,
we can without boasting set our seal to that testimony
or witness in our own minds that it is true,
and that one is our Master, the Lord Jesus.

May we then dear Friend, is the language of my heart at this time,
be encouraged to put on the whole armour of God with which to repel the adversary,
the gainsayer and the cruel mocker, under our own or any other name,
and walk forward journeying to,
and in the land of promise which is rest and peace to such as walk therein.
You have an abiding sense of our great weakness here,
and it may seem there are none by whom Jacob shall arise,
but the Lord can gather as well as scatter by the few in our day,
as He did in the days of old, yes, and He will scatter and gather too, if each one of us,
on whom his holy hand is even now laid,
will only walk according to the measure bestowed of his free grace;
for I am more and more confirmed in the belief,
that He has a seed and a righteous seed that will serve
Him through all the buffetings of the cruel enemy,
and will serve Him in the way too in which He may require,
though it be to the casting of us out from among
those whom we ought to be able to claim as brethren.

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From William Hodgson.

[.signed-section-context-open]
Philadelphia, 4th of 6th Month, 1860

Having recently written to my dear friend Thomas Drewry,
and in the supposition that he would probably show you that letter,
in which I had in some degree described the condition
and sad state of control of Philadelphia Yearly Meeting,
and the serious concern of sound Friends therein that it might be rescued
in the ability afforded from the hands of those who have been so long
crushing out the pure life from it and turning aside true judgment,
under the plausible plea of keeping all together in one heterogeneous mass,
to such a degree as to destroy the living testimony
which it once had against the heresy of our day,
and give strength on the contrary to the opponents of the Truth,--I was in hopes
that if you had seen that letter and noticed what I said therein respecting Friends
who love the pure Truth being invited to meet together in conference,
to wait on the great Head of the church,
you might have seen that it furnished in some degree a substitute for the +++[+++expression of]
sentiment you might have looked for from me,
in regard to your own concern for Friends in your land.

Your concern seemed so similar to that which has actuated our own Friends here,
that the coincidence seemed quite remarkable,
and I could not refrain from confidentially showing your
circular letter and the two letters accompanying it,
to our dear tribulated Friends, Joseph E. Maule and J. L. Kite,
to whom it afforded comfort, as well as to myself and wife.
I take it for granted that you will kindly keep me informed of
the result of its distribution among sound Friends in England.
I have perused it several times, to satisfaction,
and think it appears like a right concern as a commencement
for raising a standard in your land for the ancient Truth;
and so far as it goes, I have good unity with it,
believing it would tend to rally Friends,
and promote a fellow-feeling and harmony of concern for the very
necessary work in which you must find yourselves engaged,
if you expect to escape with your lives from this great defection.

I consider the proposed alterations in the discipline and queries,
as merely the natural fruit of the seed sown in backsliding doctrines,
which have taken root extensively in the soil of a cherished, worldly spirit.
Sarah Alexander`'s [.book-title]#Voice from the Wilderness#^
footnote:[Sarah Alexander, the wife of Samuel Alexander, of Leominster,
was the author of a small publication of 63 pages, entitled [.book-title]#A Voice from the Wilderness;#
being a brief review of the calling, progress,
and present decline of the Society of Friends.
It was published in 1860.
She died soon after, on the 22nd of 4th month, 1860, aged 51 years.]
correctly traces the defection to these unsound doctrines;
and any attempt at reform or renovation of the Society,
which stops short of an avowal of this doctrinal basis of the heresy,
will fail of its object,
and prove only a superficial application which cannot
heal the wound of the daughter of Zion.

I feel exceedingly desirous to hear whether any standard
has been gathered unto at your late Yearly Meeting.
My mind was often engaged in thinking of you during the time of its session,
not without a hope that perhaps there may have been
sufficient strength experienced by a few,
to meet together as you had proposed,
and wait on the great Master for the inshining of
his divine light respecting your future steppings;
I should rejoice to find that this had been the case,
and that Friends had been animated with a little
of pure and primitive zeal to hold on their way,
and place the testimony of Truth over the heads of backsliders and opposers.

The case of dear Sarah Alexander seems a striking addition to the list of true
testimony bearers who have been early removed from the scene of conflict,
to partake of the never-ending joys which the Lord has in
store for all those who are faithful unto death;
and I do desire it may serve to animate us who remain awhile longer,
to endeavour to stand in true single-hearted obedience to all his requirings,
as with our lives in our hands, willing to give up all if required,
so that his will may be done in us and by us,
let the enemy vaunt himself over us as he may, and cast our reputation under his feet.

The conference meeting to which I alluded in the forepart
of this letter was held on the day of Bucks Quarterly Meeting.
There is a prevalency in that Quarterly Meeting of sound,
substantial Friends who are much looked down upon by "`the middle men`" in high positions;
and these like Tobiah of old are disposed to discourage and disparage the concern
of "`these feeble Jews,`" to rebuild the walls which have been broken down.
Yet there is something in the concern which they cannot stand against,
with all their craftiness and all their malice;
and I believe they will still find it more and more so, to their shame and discomfiture,
as Friends continue with a single eye to look to
Him who has evidently led them in this way.

The meeting was a remarkably solid,
favoured opportunity in which the minds of Friends were
greatly bowed under a sense of the weight of the concern,
and an evidence to them unmistakeable that the Lord`'s
presence and power were round about them;
that the wing of his ancient goodness was extended for their help and encouragement,
and that their thus meeting together, to wait on Him for his counsel,
and to endeavour to animate one another therein to
stand firm against the inroads of the enemy,
was acceptable to the great Shepherd of the sheep.
It was with great unanimity that they conferred together
and agreed to meet again in the 9th Month.

They did not apprehend that any document was required of them at the present time;
but I think it not unlikely that when they again meet,
it may be thought best to issue something for the information of their fellow-members,
and to show the ground of the necessity which they feel for sound
Friends to endeavour to sustain their meetings in the Truth,
including of course the next Yearly Meeting,
and as many of the constituent meetings as may be
practicable with the Lord`'s assistance and guidance.
It was thought there were about (at least) 100 members present of both sexes,
including some from each of the Quarterly Meetings,
and it is hoped that at the next meeting the number may be increased,
this having been so eminently owned,
and many Friends not having received notice before hand.
Quite a goodly number of solid Friends were included in the company, several ministers,
elders and overseers, and well-concerned young people.
But we must now expect that certain machinery will be set a-going
to thwart the concern and throw cold water upon it.

[.signed-section-closing]
With true unity and love, your friend,

[.signed-section-signature]
W+++.+++ Hodgson.

--

1860+++.+++ 8th Month 11th.--On awaking this morning,
"`The Lord`'s hand is not shortened that it cannot save,
neither is his ear heavy that it cannot hear,`" was brought to my remembrance,
attended with some increased feeling of strength,
through the lovingkindness of the Lord;--also the taking the "`shield of faith`" was
opened to my understanding as all-sufficient to repel the darts of the evil one,
who has of late been nigh to overcoming, and would have overcome still further,
had not the Lord limited and restrained him in his temptations.
May I be more closely on the watch in future,
that he gain no ground by hearkening to the temptation!
For truly it is in hearkening and looking at the temptation
that there is the gaining ground upon the poor weak vessel,
as on the other hand there is the escaping the snare by turning
a deaf ear and shutting the eye of the mind to his suggestions.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 14th of 8th Month, 1860.

[.salutation]
My Dear Friend,

Your letter was very acceptable, and I thought to have replied sooner.
It is especially animating, as you say, to know in spirit,
though distantly separated as to the outward, those who are one with us,
like-minded and stronger than we are in the faith of the dear Son of God,
that we may thereby be encouraged to hold on our way, still trusting in that grace,
which is food indeed and drink indeed to the hungry soul,
which is at times ready to faint.
It was very encouraging to us to find that you and the dear friends named,
had unity with what I had put to paper as a concern upon
my mind for the strengthening of the pure-minded among us,
and the walking clear and upright before the Lord in our several allotments.
Your view or unity therewith, I may acknowledge,
has seemed greater than I could apprehend anything could merit from so unworthy an instrument.
It has been passed into a few hands previous to our late Yearly Meeting,
but there has not been that response thereto which perhaps, you would expect.

I was at the Yearly Meeting for a few days only,
while the subject of the alteration of our queries, or rather the act of revision,
was going forward,
and I think you will not be surprised in knowing that I felt as one having
neither part nor lot in the matter when this revision was before them;
only before the act had commenced, in testifying in what ability was then given,
as well as previously at the Conference relative to the latter part of the 4th query,
against lowering the precious standard to the weakness of the people.

But the stream is too strong, and there is no resisting the current successfully,
but they are left,
and permitted to prevail in their present departed and degenerated state,
so that we are stripped indeed, or rather our nakedness does appear,
and it may be well that it should,
that it may be made manifest more and more what spirit they are of,
or where they do stand, not in Jordan truly,
but high in their reasoning strength above the Seed.
Well, I may add that while there I felt almost like one alone,
and it did not feel then to be the time for anything more on my part.
But there was a stand against them,
though this was to be trodden for the then time under their feet, but not, I trust,
to return altogether void unto Him who raised the cry against their acts.
Oh! the fascinating,
bewitching spirit that pervades and crushes to the preventing as yet,
of the pure unerring spirit of Truth from being in dominion.

It feels encouraging to think of those in your land who are faithful.
We are not sufficiently sincere as standing in the Lord`'s presence
at all times and before the enemy of all true righteousness.
We are yet in bondage to the favour and spirit of those who are leading men among us,
but my spirit at times craves in secret that this may not always be,
but that we may shake ourselves from the dust that hangs about us,
and in the divine fear and strength arise and shine,
putting on the beautiful garments of humility, fear,
and that power which overcomes in the name of the Lord.
O! that we may be true to God at all times! but for
this there must at all times be the watch maintained,
that the enemy do not get in,
even among those who may be for the arising of Jacob
and the deliverance of the Lord`'s people Israel.

I have lately, in my walks to and from my business,
been reading the "`Appeal`" of your Yearly Meeting in 1847 for the ancient doctrines;
this has further opened my mind to the state we are in, and it raises the cry in me,
'`Lord,
who is sufficient for these things?`' And my vision is sometimes
cleared so as to see our people where they really are,
and how poor and stripped we are left.
But the Lord can equip for the battle, even the little and weak and foolish ones,
to war against the strong,
who are so strong in their own strength and so wise in their own conceit:
and these are they, these little ones, yet outside the walls,
kept out by the adversary who has been a liar from the beginning,
who I do believe will yet be anointed to batter down the strong,
opposing spirit which it may be is already at nearly Babel height, and then,
oh! then the Lord will have the glory due unto his name,
and praise ascribed unto Him by them, his little, lowly dependent ones,
who cannot and dare not do anything without He says, '`go forth,`' and goes with them,
even before them, to slay and to conquer that which is for the sword,
and to remove out of the way that which is as a stink in his nostrils,
even the rubbish at our walls, which, when it is removed,
some will be accounted worthy to build and restore,
that that which is impure may not enter.

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 23rd of 8th Month, 1860.

[.salutation]
My Dear Friend,

I have been reading over the paragraph in the epistle
from our last Yearly Meeting referred to by you,
and I can see with you,
that it is a very defective statement of the ground
upon which our principles and testimonies are built;
this I believe is the least that can be said against it,
and it is tinctured with the error of our day,
holding up Scripture before the Spirit that gave the Scriptures forth.^
footnote:[The objectionable passage referred to is the following:--"`But,
convinced as we are that the doctrines and testimonies of our Religious Society
rest on the foundation of the Divine will as revealed in Holy Scripture,
we believe that the result, +++[+++of this criticism and animadversion+++]+++,
as in many instances has already been the case, will be an increasing conviction,
among our members and others,
of the scriptural soundness of the Society and its principles.`"
{footnote-paragraph-split}
It bears the construction that the doctrines and testimonies of our Religious Society
rest on the foundation of the Divine will as revealed in Holy Scripture,
and in no other way.
Had the passage concluded with terms signifying that these doctrines
rested on a revelation of the spirit of Truth in the heart of man,
which teaches all things necessary for us to know, and brings all things to remembrance,
it would have been safe, and in harmony with Scripture and Friends`' principles.
Although this sentence of the 1860 epistle is at variance with the true
and original principles of Friends it coincides with the epistle of 1836,
where novel views of the place and authority of Scripture, were, for the first time,
introduced into the Society`'s official documents.
{footnote-paragraph-split}
If the writers
of the 1860 epistle had been so minded they might easily have shown that the scriptural
soundness of the Society`'s doctrines and testimonies was undoubted,
although their authority rested not, properly speaking, on Holy Scripture,
but on immediate Divine revelation upon which we are not only entirely
dependent for the right understanding of what has been recorded
in time past of the things pertaining to life and salvation,
but also to know the Divine will concerning us in our particular day and generation,
and the true application of Christian principles to present circumstances.]
With regard to your reading it at large, I am not surprised at your feeling about it,
and how can we but be brought into a very narrow place, often, in such times as these?
And it may be we shall yet have to do and leave undone, for the ease of our spirits,
that which at former times may not have been required of us.
This I would say as the light shines brighter and brighter unto us,
as a harbinger of the perfect day.

If at any time you do not quite understand my mode of speech,
I hope you will be candid enough to let me know, for I desire to learn and be instructed.
I quite agree with you that there is a "`forcing, as it were,
matters through the meetings of discipline in the face of much disunity.`"
I believe you will feel much relieved in not occupying the station of clerk.
It must be painful indeed to be in that position,
and I also believe that a Friend who is faithful to ancient principle cannot occupy it,
unless it be in some isolated case; we are as a body so far departed from it.

[.signed-section-closing]
I remain, your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Thomas Drewry.

[.signed-section-context-open]
Fleetwood, 8th of 11th Month, 1860.

[.salutation]
My Dear Friend,

I felt glad that the paragraph in the last Yearly Meeting`'s epistle,
has struck you in the same way as it did me, which is no more than I expected.
I have named it to several who concur with us.
It may afford you some insight into the state of our Monthly Meeting
if I tell you that I pointed it out to one of our elders,
a Friend past middle age, who has had much experience in discipline,
and he did not see it, or, at any rate would not acknowledge it!
I have read the epistle in our small meeting, also as clerk in the Monthly Meeting.
I wish to avoid the appearance of striving or contention
in what one does or leaves undone.

I am relieved from the clerkship,
though I filled the office till our last Monthly
Meeting when the new clerk took his seat at the table.
The gravestone question was suspended during my tenure of office, but +++[+++was then]
carried, notwithstanding the dissentients.
I think since my last letter to you we have had Rachel
W+++.+++ Moore and her husband from Philadelphia,
in this country.
I have not heard them: they had no meetings in this part of Lancashire.
Being Hicksites the Meeting for Sufferings rightly
put Friends on their guard against them,
and in most places I find that Friends set themselves right with the public,
witnessing that these strangers were not of our communion.
When will the Meeting for Sufferings be consistent,
and as guardians of the Society protect it against other
heresies than the one promulgated by Elias Hicks?

In some places the Hicksites have preached so like the orthodox Friends,
as rather to stagger some honest-hearted ones,
and these have imagined that as the Meeting for Sufferings
has warned Friends against both John Wilbur and the Moores,
therefore there must be some community of principle
or similarity of sentiment between the two.
A very great mistake, just one of those mistakes which we are all liable to,
but especially those who refuse to inform themselves,
and will not read such books as John Wilbur`'s Journal.
There is little to be done for those who will not exercise their judgment,
but who blindly allow themselves to be led about by others, who,
to a great extent are in the predicament of blind leaders of the blind.
In some places the two Hicksites have enunciated
doctrines much at variance with those of Friends,
and their attempts to preach like Friends, and to pass themselves off as Friends,
are not one whit more culpable than for the Gurneyites to
preach like Friends and pass themselves off as Friends.

[.signed-section-closing]
With love, etc.

[.signed-section-signature]
Thomas Drewry.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From W. Hodgson.

[.signed-section-context-open]
Philadelphia, 30th of 12th Month, 1860.

[.salutation]
My Dear Friend,

I was sorry to find that no perceptible result ensued from
the spreading of your concern before Friends last spring;
but I have hoped you would not be unduly discouraged on this account;
for it may prove as seed sown in some places, that may in due time spring up,
or as "`bread cast upon the waters that returns after
many days,`" if the Lord see fit to order it so.
And whether so or not,
if you have faithfully endeavoured to clear your own hands of what rested
upon them from the Lord as a burden for his backsliding people,
there will be a feeling of peace doubtless granted in the retrospect.

The day is indeed a dark and cloudy one,
and well may the query often arise from discouraged hearts, "`Lord by,
whom shall Jacob arise, for he is small?`"
But through it all, there is a little gleam of hope (what if I venture to say,
of faith?) that a remnant will yet be enabled to arise from all the rubbish,
and shake themselves from the earth and its entanglements,
and be enabled to stand in the strength given them
of the Lord (not in any strength of man,
or wisdom of man) and turn the battle to the gate against his enemies.

But what I desire for those in your land who see the backsliding of professing Israel,
is that they may not tamper with it,
but honestly and boldly (in the fear of the Lord alone) withstand
it to its face "`because it is to be blamed;`" yes,
withstand it also in the face of the people,
and let them know that this which has assumed the place of the ancient truth,
is not the ancient truth, but a fallacious, dead, empty imitation of it,
even as Babylon was said by Isaac Penington to be painted so as to look like Zion,
yet she was Babylon still.

I am still persuaded that there must be among you
a coming forth and testifying against this Babylon,
this imitation, this confusion, this false but plausible show,
this dead and empty shell without the kernel,
if your lives are to be preserved and you are still to know a living,
gathered church in that land where the Lord did so gloriously shine forth
in the days of our forefathers in the blessed and unchangeable Truth.
And I long that some may truly realize this and seek to know a preparation of heart,
so that the Master may find qualified instruments to his hand when
he may arise to shake terribly that which is of the earth.

[.signed-section-closing]
I am affectionately, your friend,

[.signed-section-signature]
W+++.+++ Hodgson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 11th of 4th Month, 1861.

[.salutation]
My Dear Friend,

For a long time past I have desired to salute you in a measure of (I trust) that fellowship
which is known by the followers of the Lamb slain from the foundation of the world.
Yes my dear friend, and is He not still slain in the hearts of a great number among us,
who are as stumbling-blocks to the honest-hearted little ones who are seeking the Way,
the Truth, and the Life,
and such they will be until that which hinders in them is removed out of the way.

Your letter was very acceptable and sharpening in the best sense.
Well, another Yearly Meeting is near at hand,
and will have probably concluded before this reaches you.
When way opens do give us a little account of how it is with you,
and whether in your struggles for that life which is everlasting,
you have had your consolation added to,
or whether you have had to come still lower than you have hitherto had to do,
in conflict and suffering for the seed`'s sake.

I noticed your remarks expressive of your concern for us here, that we may be valiant,
withstanding the enemy, in our backsliding Israel, to the face.
Well, may it be so,
and may those upon whom the weight is laid,--and there are some of these
I believe--may these stand as valiants for the Lord of hosts in his dread,
showing their enemies that it is their Master they serve,
and evidencing that He speaks through them.
Oh!
I believe the Truth is becoming more and more precious to some,
even to such as are archers for the Lord their God,
and that notwithstanding the stout-heartedness of the wise according to to the flesh,
the Lord does enable them to show forth his praise and his power too,
through some of the little ones; and that there will be a seed to serve Him,
we need not for one moment doubt, I believe.

Well!
I am increasingly of the belief that what is shown us of Mystery
Babylon (or Babylon in the mystery to the eye and perception,
except when and where quickened by grace) is to be withstood and warred
against in that self-same spirit which quickens to behold it,
so that the paint is nothing to such, but she is Babylon still.
Nevertheless I do firmly believe that we must, all upon whom this favour is bestowed,
be watchful that we do not let slip that which we do know by a lack of keeping
very near to our Leader and well-known Preserver in the right way.

Oh! that Friends on your side may keep so near to the Head and one another in Him,
as that they may know that Life to prevail which swallows up all
and everything that would mar the work in themselves and in others;
for if you come forth as gold that has been tried in the fire,
if you come forth with the Master`'s signet which is the owning presence,
and there abide, you may be as leaders of the blind, to bring many out of darkness,
and restore through his mighty power "`the paths to walk
in,`" and many may be brought nigh through your faithfulness.
And may we also be so favoured,
but we must cleave to the Lord through all in this
day of apostasy and backsliding among us.
Farewell in that love which is deeper than words.

[.signed-section-closing]
I am, your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
London, 2nd of 6th Month, 1861.

[.salutation]
My Dear Friend,

I received your acceptable lines, and since then have been, as you may suppose,
very closely engaged in attending the long sittings of the Yearly Meeting.
I have wanted to write to you and let you know how heavily some of us
are going along with the head bowed down because of the oppression,
as we are accustomed to believe, of the enemy, who has, it appears to some among us,
taken his seat in the Church.
Well, they have done what they listed and are permitted to work,
and having wrought according to the mind that is in them,
they have brought forth the fruits so incompatible with Truth`'s dictates
in the spirit of his humble self-denying followers (as we believe),
so that we are a poor and afflicted remnant who cannot join with them.

The acts of the Conference^
footnote:[This was a Conference or series of Conferences,
which began by the assembling in London in the 11th Month of 1858,
of about three hundred Friends from various parts of the kingdom,
to consider the propriety of expunging from the fourth
query the clause which refers to "`plainness of speech,
behaviour and apparel.`"
Without attaining unanimity after much disunity had been expressed,
the Yearly Meeting was recommended (contrary to the well-established custom of Friends
in cases where there is a divergency of view) to alter the fourth query as proposed.
When brought before the Yearly Meeting of 1859,
there was a conspicuous lack of agreement as to the
adoption of the recommendation of the Conference.
Notwithstanding this, it was kept moving,
and the Yearly Meeting concluded to submit to another and smaller committee the revision
of the whole of the queries and advices and report to the Yearly Meeting of 1860.
Although Friends were hopelessly disunited as to the propriety of these changes,
so far from there being any hesitation in going forward,
it was next proposed to revise the whole of the Book of Discipline;
accordingly another Conference was held in London in the 11th Month of 1860,
and again in the 2nd Month of 1861.
At the Yearly Meeting of 1861, the various alterations,
additions and omissions proposed by the Conference, were,
with but slight exceptions adopted.
It may be truly affirmed that this was not the first instance in
which it was not the united and harmonious judgment of the more
truly enlightened and exercised members that prevailed,
but the sentiments of the majority: the same occurred in 1850 on the Gravestone question;
in 1853 on the payment of Impropriate Tithes;
in 1855 when a separatist body of Friends in Ohio was acknowledged,
and in 1856-7-8 on the Marriage regulations.]
are with very little exception or alteration confirmed by the Yearly Meeting`'s acceptance,
after going through the altered, and omitted, and new minutes for the new book.
Probably you would know something of what was to come before us from the Conference.
As I understood it,
the first paragraph and part of the second under that of names of heathen gods,
and using the common names for the days and months, is omitted.
There was some attempt to do away with the "`Morning Meeting;`" this is not done,
but they are to meet less often,
and I believe their radius to be enlarged by adding from the adjacent counties.

I have been so sorely pained in mind that it has almost overwhelmed me,
so that one blow after another has seemed so heavy
as to take me off in a great degree from the detail,
and fill with sorrow of heart at the turning, as it were, upside down,
of our former disciplinary arrangements, advices, etc.,
therefore I shall refer you to a better reporter than myself.
I am driven increasingly home, the best home I trust,
to abide in the quiet as much as may be permitted,
after having been helped to show that I was not in unity with the proceedings before us.

No way has opened for us to sit down together as a company
by way of Conference and feeling upon the present doings, etc.
I did mention my exercise in that direction to a few,
but there has not been a pointing in their minds, or strength therefor;
so I am quite willing to leave it,
trusting that He who knows the hearts and what is
the desire thereof will stand by us and be in us,
strengthening us to be faithful to Him and to one another.

[.signed-section-closing]
Farewell from your sympathising and affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Thomas Drewry.

[.signed-section-context-open]
Barrow-in-Furness, 6th of 6th Month, 1861.

[.salutation]
My Dear Friend,

I was glad to hear that you found a few while at the Yearly
Meeting willing at once to fall into the view of a Conference,
which has long pressed on my mind as a desirable step,
though I feel my own unworthiness to take much, if any, active part in it,
beyond doing what little I could.
I see something of the necessity of starting from and proceeding
on the right foundation in such an important step,
so as not to be driven about from one thing to another
according to what we may hear said;
but to seek after stability of mind,
and it may be some are timid in a movement of this sort,
and want to see a great deal more than is permitted for them to see,
and this we may know is not always vouchsafed.
But the little done in faith,
desiring to be true to our convictions according to what has been shown to us,
may lead to a further insight, and it may be we should gather strength ourselves,
and at the same time be able the more effectually to resist the enemy.

And as we keep to the one thing we should have to
make considerable allowances for diversities of gifts,
of temperaments.
The course of some may be quite strange and unusual to many of us.
They may have to be very rough with the transgressor, though in love;
and it may be so out of the common way that the tender
and delicately-reared ones may even stand aloof,
lacking the hardihood of mind,
though if they came to the right foundation and dwelt there they would see that,
as in the natural world the storm and the tempest
and the beating rain have their part to perform,
no less we know than the warm sunshine and gentle showers,
so have these their work no less than the others.
I often think that the members of our Society are in the main so artificially brought up,
so select and apart from the working everyday world that
they almost repel the working and labouring population,
and how few mechanics, etc., there are among us; why is it so?
Nothing so likely to attract this large class as an honest
out-spoken declaration of the Truth and against error,
without respect to the persons of men.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Thomas Drewry.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 23rd of 6th Month, 1861.

[.salutation]
My Dear Friend,

Your acceptable letter was received,
and met with a response in our hearts as emanating from the heart of one
whose sole desire is to serve the Lord in his day and generation.
And I may say that we with some we know and love of like mind with us (though
compared with the mass we are few) do also mourn in the secret of our hearts,
on account of the great defection that has crept in,
and holds sway in our Society to the over bearing of our number,
so that we are truly of the captivity,
and awaiting the time of our deliverance from this creaturely yoke that oppresses us.

But great as is this number compared with ourselves, even almost surrounding us,
yet we do know that One even mightier than they all, is our Captain, and +++[+++is]
as able to deliver as in the days of old He was,
from the host of the Egyptians who followed hard upon the
Lord`'s children in their journey to the Red Sea,
and it may be that our deliverance also is nearer than we know it to be.
This we know,
that individual faithfulness is the alone way for the Lord`'s redeemed ones,
whereby they will experience safety, whether it be by standing still or marching onwards.

If you had been at our last Yearly Meeting you would have been oppressed indeed.
I was there, but refused my name at our Quarterly Meeting as representative to it.
There were times during the sittings that the thought crossed my mind.
Shall I go out and sit no longer with them?
But this did not seem to be my place.
I was strengthened to testify against some of their doings under a feeling of the necessity,
and we were a small number who did so, but how few! like a handful, perhaps a dozen.

I truly can say that at times when constrained to stand upon my feet, I feared no man.
But of no avail was it, for they work by concert it would seem,
and are bound together like unto a confederacy.
Influential and "`sworn`" men,
to act together (it has seemed to me) men who are trusting to that wisdom
which is of the intellect and now bears sway and rules among us,
to the wounding and the stifling of the precious life in our meetings
and in the hearts of the little ones (too many of them),
so that we are become a people that is robbed of our strength to a great degree.

And what I have been ready to marvel at has been,
that so many in the upper seats at our Yearly Meeting
to whom we would look for some help,
keep their mouths shut,
when there is so much pulling at our testimonies and knocking down our waymarks,
that an easier way may be made to the kingdom.
Oh! how have I been pained at the beholding of this!
So that I did throw out a stone at this sort of doing,
and took occasion to show them that when there appeared
something that immediately would affect their standing,
such as doing away with the Morning Meeting as was mooted though not adopted,
then they could arise and testify.

Oh! the lukewarmness it does appear to me on the part of these whom I
have called in my heart the "`men of might who have not found their hands;`"
who have lost their strength it may be by concert,
being bound together, not to the law and the testimony,
but bound to act together in that which alone would,
or is able in their present state and condition to preserve to them, outside harmony,
and unanimity of action, even being led and guided by affectionate feelings,
or that which would maintain them; so they are not strong or fit for battle,
or to stand accepted in the Lord`'s sight.
This is my view of the prevailing state and condition of the people in this day.

They have done much (I consider) at this Yearly Meeting upon the
strength of the Conference movements to lower the standard.
Nearly all that has been brought into the meeting by the Conference has been accepted,
the omissions, additions and alterations to a great extent in the book of discipline.
Of course having made one great step by doing away previously with part of our 4th query,
all other things must be made to harmonise with that;
thus there must be no appearance of the words, "`plainness of speech, behaviour,
and apparel,`" nothing that would offend the ear or hurt the mind of the young and inexperienced,
but all must work by love,--this outside love and unity.

The advices are to be read once in the year at the close of a morning meeting for worship.
This has caused some among us much uneasiness,
and we feel that we must testify against it;
some are resolved to walk out of the meeting if feeling as already they have felt.
They have lowered our testimony against the use of the names
of heathen gods for the months and days of the week,
by withdrawing the advices thereon from the [.book-title]#Book of Extracts.#
But without much detail, which I feel unable to give you,
or afraid lest I might do it incorrectly,
I may say they have followed the heart`'s desire of the weak,
and thereby have weakened their own strength.

I may now inform you,
that early on during the meetings I felt constrained to mention
my feelings to two Friends as to its being well for those who grieved
under the existing state of things among us and could see together,
to endeavour to have a little conference before returning to their homes.
This was accorded with by a very few, say three or four,
but there did not seem to be strength or opportunity
during the sittings to bring it about,
and afterwards there was no opening.
I thought if we could have met together,
we might have been a little strengthened one in the other and come away refreshed.
It seems to me there is a bridle upon those who are of the Select Meeting,
and here (in this direction) our help is not to come, but may help be laid upon others.

Yet, we need not fear,
for we know the Lord is on our side though He permits that which can only
be seen as right when looking with the eye of faith to Him,
the all-wise and all-sufficient Disposer of events.
To my view, I may say,
the further these wise ones go into the departures
or become one with and approach to other denominations,
the more shall we who cannot go with them, become refined and strengthened,
if we abide with our Captain, and be the better able for coming clean away at the last.
While true it is, and I never more saw it than lately,
that the leaven abroad which spreads from these busy workers, is dangerous,
and we have need to beware thereof, that we become not ensnared thereby.
Indeed, if the time was come, safer would it be to be quit of that which may entangle.
But the Lord can preserve and will preserve those whom He
enables to see and feel this leaven even unto the end.

It is very interesting to us to know particulars of your Conference meeting,
and it seems so much in accordance with what ran
through me in concern for ourselves in this land.
Well, dear friends,
may you continue faithful watchmen and watchwomen
and labourers for the holding up of the building,
and may you be valiant at all times against the enemy
who is ever busy to blast and destroy God`'s husbandry,
God`'s work in the soul of man!
May you be faithful men and women, and you may be helpful to us,
and stir up that which is good, and it may be ready to die in us.
So wax strong, and be of good courage, and the Lord will fight for you and for us,
and we shall know his testimony to go forth among
us for our peace and encouragement in well-doing,
so that a little one may yet chase a thousand and two put ten thousand to flight.

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To I. B.

[.signed-section-context-open]
Cockermouth, 26th of 7th Month, 1861.

[.salutation]
Dear Friend,

Being kindly invited the other day to come to our friends +++_______+++ in the evening,
the object being understood to be to hear you read certain
matter which you have written upon parts of Scripture,
I have felt drawn to put pen to paper and inform you that I have
been distressed in mind in considering the course you have taken,
with a view I can quite comprehend to do good (and as far as this goes,
a laudable object), but I have something against it,
and feel I must relieve my mind in thus laying it before you.

Are you a minister of the gospel,
that gospel which is the power of God unto salvation to all them that believe in it,
to those who believe to the saving of the soul,
by yielding obedience unto the revelation of Jesus Christ inwardly manifested,
which is no other than the gospel which saves?
Are you my friend, a believer in this power,
and feeling yourself drawn in gospel love to minister
the same to those that will hear you,--ministering,
as the oracle of God, the fresh supply from his communion table,
and yet you believe that bread is to be gathered by you (at the time good for
your own sustenance if not the fruit of the reasoning powers of intellect),
and to be secured or kept by your own hand until the morrow, or any other day,
and then handed to the multitude?
Do you believe that this bread so kept and given forth in your own time and will,
can be different to that which the Israelites were commanded not to keep over the day,
for if so it would stink?

Yes my friend, I am distressed in thinking of this new way sprung up among us,
some of you who would do good,
putting on armour and strength which I can view to be no other than your own,
which cannot avail profitably to the people,
but rather spread an influence and savour that is not acceptable in the Divine sight.
For truly if we profess to be of this highly favoured people,
brought as it has been out of the mixture and self-performances
in its offerings unto the Lord,
we must remain there and not go back again into our
natural strength of capacity or intellect,
grasping and handling Scripture in our own time, will and way, which others do,
who have not come beyond it.
Otherwise, we may just as well do as some do who make no profession with us,
take our comments, and some of the stale bread of yesterday,
and feed the people therewith, without the putting forth of the Master,
which the gospel teaches every true minister of Christ to wait for,
and not to offer the gatherings of yesterday, whether put on paper and read,
or brought to a meeting for worship to be vocally offered there.

So dear friend, I desire to leave the matter with you, having as I believe,
felt thus much required of me to lay before you, feeling as I do,
that the way remains unchanged;
that what our predecessors in the Truth learned of Christ, the Way,
has still to be learned by every one who would come to Christ our Lord,
for truly we must know Him for ourselves before we
can take as much as one step towards Him:
truly I believe there is a people who would "`come to Christ,`"
and if they are but kept in the waiting for Christ,
and not stepping before Him, these will know Him for themselves.

But, oh! that there were more of the fathers that knew Him sufficiently for themselves,
that they might thereby come more under his anointing hand,
and thus be enabled not merely to say, "`here is Christ,
or lo He is there,`" "`come to Christ or go to Him;`" but
beholding Him and living themselves under the anointing,
they would also be enabled to show the Way, the Father, and the Kingdom.
But alas! the leaven of this world which has no part in Him, the Christ,
has covered as with a cloud many, yes, very many of this people,
who sit as yet in darkness,
and in their darkness would do something for Him,--and in this state these
can be no other than blind guides leading them that would see,
and so neither they nor the people whom they lead,
do walk in the light as Christ is in the light.
With love and earnest desires, I am your friend,

[.signed-section-signature]
John G. Sargent.

1861+++.+++ 8th Month 25th.--Have felt strengthened and
comforted in reading today at the _Hotel de Gand,_
Samuel Rundell`'s [.book-title]#Observations on the Commencement and Progress
of the Work of Vital Religion in the Soul.#
What a precious book this is! how it answers to my belief,
and I humbly trust I can say in a measure to my experience! what
food for the mind there is in the truths contained therein!

Paris.
9th Month, 3rd.--In a little pause after reading a chapter in my brother`'s bedroom,
he being poorly in bed, the words passed +++[+++through]
my mind, "`my eyes have seen your salvation,
therefore will I trust in you,`" and I was helped to open my mouth thereon,
with peace to my own mind.

I sat down in my room here at about ten o`'clock and was comforted in so doing.
O how worldly does all appear around! the people appear to be walking in darkness
instead of the true light which enlightens all who walk in it.
May I bow more and more to its discoveries in me,
that I may be more and more the child of it,--of Jesus the Light.

Arrived at Lisieux at night.
Have been again led to speak in the railway carriage to
one or two passengers on subjects relating to the best life.
It seems wonderful to me how way has hitherto been made for converse on religious subjects,
or the one great concern of life, in travelling along as well as in commercial offices.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 19th of 9th Month, 1861.

[.salutation]
My Dear Friend,

Our Quarterly Meeting is now near.
May we hope to see you here?
Come and help us!
If way opens in your mind to direct your steps here, you would have a welcome.
In unity there is strength, and at these times we need all of it that we can muster.
I received a few days ago your "`Observations`" which
appear to be written by one who fears not,
and has nothing to fear.
It will no doubt be unpalatable to many, but we have perhaps to remember,
that that medicine which is most nauseous is sometimes most needed.
So I desire my dear friend,
that these "`Observations`" of yours may stick close to the parts affected,
and not be removed till they have wrought a good work,
though something further may be needful to effect a cure.
There continues to be abundance of need to go on and hold on, and be faithful,
each one of us, to that which, as a service (however mean it may appear,
or loathsome to our natural touch and taste) is given to us as
a dispensation of the blessed gospel of Christ the Saviour.

[.signed-section-closing]
I remain, your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--
