== Chapter III.

[.chapter-synopsis]
* Letters to W. Hodgson, T. Drewby, T. Chalk, J. F. Marsh, L+++.+++ E. Gilkes
* Letters From W. Hodgson and J. F. Marsh
* Conference Meetings in London and Birmingham
* First Notice of a Friend`'s Meeting at Fritchley
* Letter to one of his Sons

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 2nd of 1st Month, 1862.

[.salutation]
My Dear Friend,

Your letter with the minute from your General Meeting held
in the 9th Month was very acceptable and animating to us,
and it has had circulation among some of the tribulated remnant in this land,
though not yet among all.
You have the sympathy of those who have had its perusal,
and some feeling remarks have been elicited towards you; yet there does not seem to be,
at the present time, the one accord to meet outwardly together in one place,
as you have done, though the advances of the enemy are bringing us, I do believe,
to feel an increase of hope that the time of our deliverance draws nigh.
That there is an advancing on the part of those, or that spirit which rules in them,
and would rule over the heritage of God, is very evident,
and boldness increases therewith,
so that now there seems no stopping of the stream even by any who
(too late) may see that they have proceeded too far,
in their giving way to meet the wishes of the uncircumcised in heart and ears;
for having lost the power through letting go, they cannot find their hands again,
but "`the men of might have lost their hands,`" and have not the true strength in them.

Some of us feel that we cannot partake in the Discipline
in whatever favours or comes under the recent changes,
and are only waiting that we may see what the Lord would have us to do.
In Ireland they have very lately had a Conference
relative to the Queries and Marriage Regulations,
and are quite disposed to go the way our Yearly Meeting has gone.
Some few sound Friends there feel it much,
but I was told when in the North lately (at Belfast) that "`it was no use,
numbers now ruled;`" and so it is, even young men,
unripe and unfit as yet for hands to be laid on them, are made tools of,
to their own hurt as well as that of the body.

Well, we must believe that the Lord, in wisdom above that of man,
is permitting this devastating scourge upon this poor Society
(though rich in this world`'s goods) for good in the end;
even I believe that some may come forth as gold; yes, tried in the fire,
that now burns upon them, though it may not yet be at the hottest,
and when He shall see fitting,
(and his time is the best time) then such shall come forth with rejoicing,
even confirmed by his Almighty Power,
and prepared more fully than yet they may have been to trust in Him.

3rd. Your acceptable letter, my dear friend,
has been received after penning the foregoing, and we feel deeply interested in it,
but I shall not attempt now to go into matters therein alluded to,
further than that the whole seems to bring again into thoughtfulness and to raise fresh
desires to be found faithfully occupying that place purposed for us to fill,
and to be found ready to stand still or go forward as the Master may in condescension
make manifest so plainly or intelligibly to the ear and the eye quickened by Him,
as not to be mistaken by either staying behind or going before Him.
May our daily endeavour in humble watchfulness be to keep with Him,
and this in an especial manner, through all temptations.

I want to read again your valuable letter,
and to dip into the truth of which it savours deeply to our feelings.
But you know, I can fully believe,
that times and seasons are not always at our command amidst
the varied and needful engagements of a business life,
but how congenial and refreshing it is when at liberty so to do,
to retire from outward concerns to search for the Treasure,
and abide under its refreshing and invigorating influence.
What wonders are at times made known, and how much is seen by us there is to learn,
instead of all being learned!
The all seems yet unknown comparatively,
and in this we can praise the Lord and Giver of all.

Farewell, in the bond of that love which none know but the disciples of our Lord,
your sympathising friend and brother,

[.signed-section-signature]
John G. Sargent.

--

1862+++.+++ 2nd Month 25th.--To Devonshire-house Meeting.
Was strengthened to speak to the opening given on the prophet`'s words to Baruch,
"`Do you seek great things for yourself?
Do not seek them,`" whether possessions, or worldly honour or reputation,
and also alluded to his further declaration,
"`Your life shall be given you for a prey wherever you go,`" testifying
that the precious life is so given to those who are willing to
follow the Lord Jesus wherever He goes and leads,
through suffering and buffeting of different kinds, and that,
even from false brethren;--quoted the Scripture,
"`The foxes have holes and the birds of the air have nests,
but the Son of man has not where to lay his head,`" and was much helped,
to the encouragement of some present,
as was fully manifested by individuals after meeting.
I felt constrained to go to this meeting,
though not knowing of its being meeting-day till ten o`'clock,
and was consequently about three-quarters of an hour after time,
and had to set aside my previous arrangements for the morning in faith.
May I ever be encouraged therefrom to yield to the
sense of duty before every engagement of my own!

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 25th of 4th Month, 1862.

[.salutation]
My Dear Friend,

I have your interesting letter giving an account of your visit
to W. B. It interests me to learn of his welfare and feelings,
and although it does not appear that any besides himself and his wife,
have absented themselves from meetings for discipline on account of the changes,
yet we can but believe it is right to firmly attend to conviction in this,
as in any and every other matter.
The time has not seemed come for us to do so;
nevertheless we have been brought to look at it very closely,
and desire to be found standing in our lot to the end of our days,
in whatever that may be; and though arduous to stand and work so alone in our meetings,
as we seem to ourselves to do, yet it must be so,
and that we are yet to testify for the good and against wrong things;
may we be very faithful, and I believe we, and all who are faithful,
will wax stronger and stronger.

I had in our last Quarterly Meeting, as you seem not to be altogether a stranger to,
to make a stand against what to me is evil, yes an evil thing and bitter,
to help that which is wrong.
It was with me to propose to our Monthly Meeting that a proposition^
footnote:[This is a mode prescribed by the discipline of
the Society to initiate and promote alterations in the rules,
to establish new rules or other desirable changes,
which when proposed to and adopted by a Monthly and afterwards by a Quarterly
Meeting are brought in due course before the Society`'s Annual Meeting,
to be considered and accepted, rejected or modified as the case may be.]
should go to our Quarterly and from there to the Yearly Meeting
for the removal of the yoke from off the necks of the disciples,
(to use the words of Scripture,) by discontinuing the reading
of the advices at the close of a meeting for worship,
but the Monthly meeting would do nothing in it.
I met with hard usage there, and none with me; so under I believe some fresh feeling,
I brought it before the Quarterly Meeting,
as a matter in which there was room for abundance of true charity,
and for the relieving of the distressed,--those who
are truly distressed and burdened with this yoke;
for this I was severely reprimanded by an elder (in
man`'s spirit I believe) not in right authority,
and such was the view I had given me of the state of our poor Society
indicated by such a proceeding (that of reading the advices at the close
of a meeting for worship) as approved of by the Yearly Meeting,
that it was brought before me to be as iniquity,
inasmuch as I believed the enemy had made such an
advance as to come up to the very door of the sanctuary,
the place of true worship, spiritual worship.

I mean not the meeting place outwardly, but the place of true prayer, that place where,
in assembling together for the true worship, when gathered into the Name or Power,
in the stillness of all flesh, we are permitted to be in the sanctuary of our God,
and nothing that defiles, even the letter which kills must not enter:
the enemy it seems to me has got up thus far, even at the very door,
and further than that in the minds of some, for there are those who would,
through his crafty devices, have the reading in the meetings; and thus the enemy,
who was and is, a liar from the beginning would, and will I believe,
get in and take whole possession of the house or minds of these,
who are not so gathered in the Spirit, even the Holy Head,
as to see that he is not needed there, for that he is a liar and ever was so.

These words I did not give expression to, so at large, but under this feeling,
and with what I did express in that meeting for discipline,
I gave utterance to the word (which did present itself and
from which I dared not withhold expression) iniquitous,
and have felt no condemnation for so doing, though I would willingly have found another.
Under this feeling of its being strong,
I expressed a hope that friends would bear with me in the use of it;
but it was afterwards caught at, and I was reproved as before stated,
though I did not hear what the elder was saying, and was kept above all he said,
for he felt to me to be in the spirit of a man and not in the true
authority which gives life rather than takes from it;
we must be willing, or we must expect, that man`'s judgment will pass upon us,
but never heed; if we are but seeking to have every wrong thought,
word and act judged down by the Spirit of the Lord,
we need not fear what man can do unto us,
but rather let us glory in being accounted as sufferers
for the cause of the dear Lord and Master,
who suffered so much for us, and who is so persecuted by those who know not what they do,
and may we be found in the spirit of the martyr who could
while under the persecuting power which stoned him to death,
pray that the Father would forgive them.
Thus much my dear friend respecting the word I made use of,
for which some may have judgment against me, but I would have them look well,
into the subject matter, and forgive if they have aught against me,
while I do most earnestly desire to be kept in all humility, and close,
very close to the Law and to the Testimony.

I think I never did feel more or see more the need for us
individually to be very faithful to every conviction,
no matter in how small matters this has to be exercised; faithfulness is the watchword;
may you and I have a firm standing in this,
even in giving up of all and in taking up of all too,
that the dear Master sees fit to ask for of us.
Oh! it is good to hear the voice that calls for more at our hands,
in whatever way that may be,
whether it be in making a stand according to the little stop in the mind,
in any outward thing to be given up, or taken up;
so shall we who hear and obey (if we hear and obey) grow stronger and stronger,
and if we grow stronger inwardly there will be an
outward manifestation of it too in some way,
for the Lord will make a thorough work, not a half work,
but the whole man must be renewed both outward and inward, and so He will be glorified.
Farewell, with much love,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 25th of 6th Month, 1862.

[.salutation]
My Dear Friend,

There is much that is calculated to impress the minds of individuals,
if not to open their eyes, now-a-days, if they are willing to receive the Truth,
but I believe the multitude of active ones in our day are
too fast set to be turned back or brought to the Touch-stone.
But we shall do well, I believe, to endeavour to stir up the pure mind in any,
while we show forth a godly life and conduct among men.
It feels to me we have to labour in the ability afforded to fasten
the nail where it has in any degree been driven by the great Master;
then on the other hand,
it seems as though the flood would devour the good that is stirring in those tender
minds who would come over to the unchangeable Truth as the Friend holds it.
But we must, I believe,
be willing to leave the outcome to Him who has all power in Heaven and on earth.

I have been thinking and feeling about my post of agent to the
Philadelphia Friend which gives uneasiness (the paper) to some.
I would not in the least degree put a stumbling block in the way
of my brethren or those whose hands I desire to strengthen.
A trying time at our Quarterly Meeting yesterday.
The tabular statement of statistics it appears, is to be an annual production,
with which I have no unity.
These are the fruits of the natural will in my view,
not productive of good or life in our meetings,
and take the place of higher matter which,
owing to their not more fully coming unto or under the Power, is so much excluded,
and our meetings become tedious, and they find they must hurry through the business,
and thus we depart from the substance to the shadow.

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From W. Hodgson.

[.signed-section-context-open]
Philadelphia, 18th of 8th Month, 1862.

[.salutation]
My Dear Friend,

In Ohio the state of things among those who have been esteemed as sound Friends,
is indeed sorrowful.
Through remaining mixed up with this dreadful fascination of the Middle Party there,
many seem to have overstayed the right time,
and now appear to be losing their strength rapidly;
so that we fear the number of those who may escape
with their lives in that part of the heritage,
may eventually be only as the gleaning of the grapes when the vintage is done.
It is sad to think of and mournful indeed to contemplate where many may be led to,
if they are not mercifully favoured to be snatched
as from the devouring fire before it be too late.

I greatly fear that some with you are in a similar danger from similar causes,
even from a fear of the consequences (in the view of poor finite
man) in a faithful discharge of duty in this day of great defection.
I begin to fear whether even any remnant of a gathered church
will be preserved among you on the ancient foundation,
for a time at least;
though I still believe the Lord will have a people even in that
land where He brought out our forefathers in the beginning,
to hold up his pure standard of truth and righteousness.
But it may be from the highways and hedges,
for the unfaithfulness of the children of his people.

Let me encourage you, my dear brother,
not to flinch from a due discharge of what you may feel in the Light,
which never deceives, to be truly laid upon you of the Lord.
For great will be the reward of those who will stand firm and upright in this evil day,
honestly concerned to do what the Master requires of them,
for the continued upholding of his pure standard before the nations,
and for the exposure of the specious attempts to
pervert the way of his unchangeable Truth.
Great is the necessity for those who have been enlightened
to see these things in their true light,
to stand faithful in their allotment,
not swerving in any degree to the right hand or to the left, from fear of,
or hope of favor from man,
but looking to the great Master alone for the renewal of strength and
ability to walk in the tribulated path which he may point out in his wisdom

The state of things in the nominal Society in your land, as in ours, is indeed awful;
and very serious will be the result to those,
who for the sake of ease or any other earthly consideration,
are willing to connive at it, and be mixed up with it,
I am at the same time well aware that it is needful for
you to know the putting forth of the Shepherd of Israel,
so that when you shall go forth,
you may sensibly know Him to go before you and sustain you.
What I am anxious for however,
is that none may be stayed by reasonings with flesh and blood, as some, yes many,
in this land have been to their great hindrance and hurt,
if not to the lasting blinding of their eyes to the way of peace and safety.

May we all seek to know more and more of obedience
to the smallest requirings of Him who is the Way,
the Truth, and the Life.

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
William Hodgson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To T. Chalk

[.signed-section-context-open]
Cockermouth, 12th of 9th Month, 1862.

[.salutation]
Dear Uncle,

The visiting of this and other parts, by Committees appointed by the Yearly Meeting,
we feel to be at this time a very serious undertaking,
attaching no light responsibility to those that have appointed,
as well as to those thus moving about under the appointments;
and in the consideration of so important a step the query arises in my mind,
"`By whom shall Jacob arise, for he is small?`"
Surely by no other can it be but by the mighty power of God, and truly we do know that,
however small and despised in this day of extolling of the intellect, and of much doing,
+++[+++the true Seed may be], the God of Jacob is able of the stones even,
of this or any other people, to raise up children unto Abraham.

And how does my soul desire that He may be pleased to confound the wisdom
of the wise and to bring to nought the things which are,
(in their sight) and that his name or power may alone be exalted!
But alas! how far off this does appear,
inasmuch as weakness instead of strength does so prevail--and
the people will have it so--even the multitude of counsellors,
from whom we ought to expect and look for better things--surely such cannot profit
the people if they have weakened themselves by thus lowering the standard;
until at least, they humble themselves and show to the people that they have erred;
then they may be able, by faithfully abiding under the chastisement of repentance,
as they strengthen themselves in the God of Jacob, to say, "`Come up here and come to us,
and we will do you good.`"

But this state, if I mistake not in my feeling, has yet to be arrived at,
and therefore I would say,
no committees should have come forth at the present time from the Yearly Meeting,
for the reason that it is not in qualification for such a work.
Would that it were otherwise! that those appointed were prepared to say where they go,
we have erred, having departed from Him who was our Strength and our Lawgiver;
then we and others of the little ones who tremble for the Ark,
would hail the coming of such among us;
but under present circumstances and the existence of the wide-spreading evil,
we cannot,--but are pained (inwardly) at the sound of your footsteps.
This is my feeling as regards the Committee,
not applicable as regards your and Aunt`'s visit to us,
whom we shall be pleased to see socially.

I remain, with our united love, your affectionate nephew,

[.signed-section-signature]
John G. Sargent.

--

9th Month 29th.--I left home on my way south for Chesterfield.

10th Month 1st.--Went with W. Bingham to the Monthly Meeting at Furnace;
was strengthened to say that "`the Lord`'s hand is not shortened that it cannot save,
nor his ear grown heavy that it cannot hear,`" and that
"`a double-minded man is unstable in all his ways.`"

17th.--In London.
This day was held a meeting,
by appointment of Friends who are feeling the backslidden state of our Society
from the ancient ways--the way of the Truth--the good old testimonies for Truth,
yet ever new,--being let fall by very many among us,
and "`Who is sufficient for these things?`"
The Lord alone can be our helper.

Seventeen met at Joseph Armfield`'s,
and endeavouring to turn our tribulated minds and spirits unto the Lord,
we were favoured together, I believe, with His owning Presence.
For years past it had much rested with me and others also,
that it would be well for Friends feeling the state of things
among us--the oppression of the wrong spirit at work,
to meet together and seek for best help to be strengthened
together in the good and right way of the Lord,
and for a little of the true confirming together which is by his Holy Spirit,
and that we might have a Conference together upon that which so affects our life,
and by reason of which we go greatly bowed down, some of us.

This we had, and were refreshed and animated together I believe,
to hold on our way in the unchangeable and ever blessed
Truth--minding the pointings of Truth,
and to be always faithful in meetings for Discipline
to testify for the Truth and against error,
as ability may be afforded us, in no way compromising with unsoundness.
We parted after two sittings, the first being a meeting for worship, with the prospect,
if so permitted, of meeting again early in the third month of next year.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 13th of 11th Month, 1862.

[.salutation]
My Dear Friend,

Your letter has been received, and as usual your hand-writing is always acceptable,
conveying, as your letters do, so much that is refreshing and confirming in the life,
that precious life which is substance.
We need substance out of the Heavenly Treasury.
My dear wife wrote to you rather lately and informed
you of our meeting in London on the 17th last month,
brought together, I do verily trust, in more than man`'s appointment,
by Him who cares for his sheep and regards their sighs and groans
under their bondage and their desires to be found by Him serving
Him only who is worthy forever to be exalted above all.
There are many strange gods in our day,
many graven images unto which men are found to bow down themselves,
in worshipping them and regarding them as God,
and we that see and know these things are borne down in great measure under them,
nevertheless we cry, Lord save us, spare your people; and, glory to God,
we can sometimes look up and bless His holy name.

With regard to the manner of calling this meeting,
our friends Daniel Pickard and Thomas Drewry came together
to us about the time of our last Quarterly Meeting.
It was when under our roof that the matter of Friends meeting together
according to my previous concern a few years back was brought before us,
and we concurred that it would be well for Friends to meet,
such as might feel drawn to such a meeting,
and we ventured to look forwards to some time in this month,
to be looked further at after I had seen W. B.,
and it was with me to see him by the way of my business journey then happening South.
This friend has discontinued attending meetings for discipline.
Accordingly I went direct to his house,
and my mind was much turned to the holding of such a meeting,
but we fixed no time together.

W+++.+++ B. told me if I would write to him on my way homewards
through London he would meet me there.
When in London and talking over the subject with Joseph Armfield,
we both thought it would be best for such a meeting
to be held in London rather than elsewhere,
for the first meeting, and there seemed to be strength enough with us to look to a day,
the 17th of last month, when I thought I could look to being again in London,
so left it with him to write to Friends and suggest the thing,
and to bring it about if way opened for it;
and on my return to London from France on the 16th,
I found arrangements were made for the meeting next morning at
eleven o`'clock at Joseph`'s and we sat down seventeen in number;
there would have been more it seemed had it not been for a misunderstanding
that women friends were not expected to attend.
Perhaps T. Drewry will have given you an account of the meeting.
We met at eleven, and sat perhaps two hours and a half,
and afterwards entered a little into one or two matters but found
it best to adjourn and met again at 3.30 p.m. I think it was nearly
seven o`'clock before we separated as a Conference.

The subject of attending meetings for discipline as now constituted came first
before us and it seemed the prevailing view that it would be best to attend them.
My own had been the contrary,
but the hope of our assembling from time to time in the capacity then met,
led to look at it hopefully that if right to absent ourselves
from such the way would be made clear to us.
It was seen that we could not uncompromisingly accept of
the appointment of representative to any of the meetings,
and that it would require watchfulness in the meetings how we took any part,
but that while attending we must look to our duty as may be manifested at the time,
whether it be to testify for the truth or against error.

The retrospect remains peacefully on my mind,
and with such as I have had communication with since,
and I do trust we may be strengthened as to the future and
enabled clearly to distinguish between thing and thing.
I notice the desire you feel that we may be strengthened
before it is too late to do the work of our day,
according to the Divine will; this is truly our desire, and that nothing may hinder us,
neither the fear of man nor any other hindering thing,
for many are the snares set for man`'s detention from the full work designed,
as well as sometimes to forward his overstepping the mark,
and for this perhaps the snare is as great as the other.

The desire, my dear brother,
while writing opens afresh in my heart that we may ever
be found walking together and worthy to walk with the Lamb,
for truly my heart feels very near you, as it were in the closest of bonds,
feeling that you have chosen the Lord for your portion
and I do desire ever to be found doing the same.
I trust that in the important matter which has just lately been
entered upon (I refer to our meeting on the 17th of last month,)
the step has been taken when the way opened rightly for it.

If we have but moved with the Light of the glorious day, all is well so far;
and now it remains that there be no standing still,
but that as the Light moves we also move, and as the cloud rests, we also rest.
May this be our favoured portion of experience.
It is not for ourselves only that we desire an establishment in the Truth,
but that our dear children also may after us have to look back
upon our paths and see that the God of Israel was with us,
and that they may, by the blessing upon our examples,
be increasingly willing to tread in our steps.

[.signed-section-closing]
Your sympathising friend and brother,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From J. F. Marsh.

[.signed-section-context-open]
Croydon, 3rd of 11th Month, 1862.

[.salutation]
My Beloved Friend,

Although in taking the pen it may not be needful to write much,
yet feeling you brought near in affectionate remembrance
I may perhaps venture on a little,
and while thinking on you, my precious friend and brother,
I am reminded of that sweet portion in Ps. 24,
"`who shall ascend into the hill of the Lord?
or who shall stand in his holy place?
He that has clean hands and a pure heart;
who has not lifted up his soul unto vanity,`" etc., and again in Ps. 15,
is described a citizen of Zion, "`Lord who shall abide in your tabernacle?
who shall dwell in your holy hill?
He that walks uprightly, and works righteousness,
and speaks the truth in his heart,`" etc.
And how precious are those words of our dear Redeemer,
"`Blessed are the pure in heart for they shall see God!`"

Well, in thus quoting it may be seen that I am writing to one who knows and feels the truth,
that "`without holiness no man shall see the Lord,`" to one whose
heart has been sweetly visited by the Day-spring from on high,
and in the day of the Lord`'s power sought to be dedicated to his work and service,
a willingness having been wrought to follow on to
know him in all the ways of his leadings and requirings,
and in proportion as obedience has kept pace with knowledge,
peace in your soul has been as a river, realizing in your experience that Scripture,
"`Then shall we know if we follow on to know the Lord;
his going forth is prepared as the morning; and he shall come unto us as the rain,
as the latter and former rain unto the earth.`"

Yes, have you not known my brother, His going, putting and leading forth,
prepared for you as the morning, and his coming again and again unto you,
cheering your soul with the sweet incomes of his love and peace,
as the latter and the former rain unto the earth?
Has not the dew of heavenly good often rested on your spirit,
as an evidence of your faithfulness being accepted
by Him whom your soul desires to serve,
affording you the occasion to say, "`The right hand of the Lord does valiantly;
the right hand of the Lord is exalted; the right hand of the Lord does valiantly.`"
Then "`be strong and of good courage,`" strong in the Lord and in the power of his might

[.signed-section-closing]
Very affectionately your friend and brother,

[.signed-section-signature]
John F. Marsh.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John F. Marsh.

[.signed-section-context-open]
Cockermouth, 29th of 11th Month, 1862.

[.salutation]
My Precious Friend And Brother,

I have felt gladdened with your comforting letter of the third of this month,
and my mind has from time to time since turned towards you,
with a view to sending you if but a few lines, such as I might be enabled in reply.
The passages of Scripture, my dear friend,
which you have brought before me depict a pure state, a heavenly state,
that which is indeed worthy of our pressing after,
and endeavouring with holy ability to be found in.
What a favour to be found dwelling in righteousness, in the Lord our righteousness,
subject to all his laws which are written in the heart of the believer,
for it is the Lord`'s good will to keep them there; his Law is in their heart,
"`none of their steps shall slide;`" this truly must belong to the practical believer,
while nevertheless we do admit that He bestows of this Law upon all,
that they may grow up therein and thereby, and that it may increase within them,
through becoming subjects of his kingdom, through faith, in the true obedience thereof.

Ah! we do indeed know of the Lord`'s goodness, of His great mercy,
and that his compassion fails not;
how gently He has led us along! requiring no more of us than He
is both able and willing to give us the needful ability to perform
and herein we can bless and adore his holy Name,
for "`He gives power to the weak and to them that have no might`" of their own,
"`He increases strength.`"
To the obedient soul,
truly does peace flow abundantly and the heart does know what it is to sing for joy.

[.signed-section-closing]
I remain your very affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

1863+++.+++ 3rd Month 5th.--Met as appointed at Leeds.
We were I trust helped together.
Eighteen in number in our first sitting, which was a meeting for worship.
We separated in peace, after holding two sittings in addition to that for worship.
Read over the old Queries of 1802, and we spoke to them as matter was furnished,
I trust I can say.

[.embedded-content-document.letter]
--

[.letter-heading]
To Louisa E. Gilkes.

[.signed-section-context-open]
Cockermouth, 19th of 4th Month, 1863.

[.salutation]
My Beloved Friend,

Words as you know, are not always needed,
yet we sometimes feel that it is best not to withhold them,
whether they be words of encouragement or sympathy, and sometimes it may be of reproof.
On this occasion I feel best satisfied to offer my mite of tender
sympathy to you as to a beloved sister in the Lord,
whom her Lord has seen fitting to deprive of her nearest and dearest tie upon earth,
in infinite wisdom and mercy no doubt; for in all his ways is wisdom unfathomable by man,
and mercy,
the depth of which is only known as we are dipped by Himself into the water of purification,
and refined by the Spirit and power of regeneration.
Yes, I feel I can offer you the hand of sympathy as that of a brother who has also
known something of the chastening of the Lord though not sufficiently yet;
it does often appear for the fully humbling and breaking down of everything,
so as to render the clay unmixed and entirely fit for the moulding
of the Potter into such a vessel as He would have me to be.

Well, dear Louisa,
you have those who can and do sympathise with you in this time of sore
trial--but though you know not what (to the full) your Lord does,
perhaps it may be said to you,
"`you shall know hereafter,`" so bless the Lord in this his dispensation,
and he will have respect unto his handmaid,
and cause "`the solitary places to blossom as the rose,`" and your
faith to be increased to the rejoicing of the soul in Him,
who is the Beloved of all that love Him.
I have ever held, since our first acquaintance (I believe I can truly say),
dear Gilbert in affectionate nearness, as a brother in the warfare,
and not the less so because we have not met much or corresponded of late.

And now may we who survive, continue our warfare, first of all daily in ourselves,
against an unwearied adversary, and next,
in the world to the subduing of the Lord`'s enemies in the power of his might;
then when our time comes we shall be prepared to say as said the Apostle,
"`I have fought a good fight, I have finished my course, I have kept the faith:
henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, shall give me at that day: and not to me only,
but unto all them also that love his appearing.`"

[.signed-section-closing]
Believe me affectionately,

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Dublin, 30th of 4th Month, 1863.

[.salutation]
My Dear Friend,

I am not surprised at the impressions left after
our last meeting having grown fainter in your mind.
We have to pant sometimes after a renewal of heavenly blessings and favours;
we must not expect them, any more than the manna kept too long,
always to abide in their freshness I apprehend.
How many lessons we have need of sometimes to remind us or arouse us to faithfulness!
This in respect to your omission referred to by you at your
Quarterly Meeting which caused you some uneasiness afterwards.
While at the same time I apprehend that some of that which comes
before us previous to so meeting may be taken from us,
as I have sometimes known with regard to openings which may have presented in meetings
which it might seem probable would have to be offered in the line of ministry.
But where there is uneasiness felt afterwards for an omission,
may we not believe that there ought to have been a giving up.

I am attending this Yearly Meeting believing that a small pointing thereto would,
if joined in with, yield peace.
In the two large meetings on First-day and yesterday, I was strengthened to stand,
which yielded peace afterwards.
Much has not felt required of me in meetings for discipline.
J+++.+++ Thorp and several other friends are here.
J+++.+++ T. has said much about intellect in one of the
sittings for discipline as well as in one for Worship,
and much about Scripture reading.
He hoped reading the Scripture in meetings for Worship would not yet be brought about,
or to that effect,
but he was not sure but they might be read on First-day
afternoons by getting together for that purpose,
where no meetings are held in the afternoons.

This I looked upon would be if brought about, in that respect, a beginning of sorrow.
These words presented to my mind,
and I felt best satisfied (this was while the state of Society was under consideration)
to say that I believed there was danger of making the Scriptures an idol,
and I hoped the reading the Scriptures would not
become a substitute for meetings for Worship.
This is the only time in these meetings that I have opened my mouth.
Great discouragement sometimes stares us in the face,
viewing what our Society now is... I had an opportunity with J.
Thorpe at the dinner table of opening my mind in the company,
way being made for it,
on the subject he brought forward in one of the sittings relating to the
introduction of the Scriptures when no afternoon meetings are held;
this I feel thankful for, as I wished to throw it off and relieve my mind.
I hoped he would recall it, which however he does not incline to do,
and thought if we had more opportunity together I might see differently.

We must be faithful and make use of anything that
is really given us by the Father of mercies,
not hiding the candle under a bushel or under a bed,
but as prompted by Him make use of the talent or talents bestowed,
that it may turn to His praise who gave it; what an honour moreover it feels,
in any degree, to have to advocate the precious Truth in its simplicity and fulness.

[.signed-section-closing]
I remain your true friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Cockermouth, 17th of 5th Month, 1863.

[.salutation]
My Dear Friend,

I have diverged from responding to the first part of your letter,
in which you allude to your own ill state of health;
you have been the subject of my thoughts wishing to know how it might be faring with you,
and I am pleased to know of your feeling better, and hope,
if consistent with the Divine will,
that you may know an increase of bodily strength
together with times of rejoicing in your inward man,
at the sunbeams of the everlasting Life coming in,
when the whole being can humbly rejoice and bless the Saviour.
All His ways are right, as we are sometimes enabled in our experience to testify,
and what a favour it is, to know this for ourselves!
But what searchings of heart does this knowledge sometimes bring into (a part
of the wonderful plan of redemption) to see what stands in our way,
or what there may be of the old man that has yet to be slain in us,
before the great work (though not too great for his wonder-working
power) be accomplished according to his purity,
reflecting itself thoroughly and perfectly in us to the honour and praise of His Name.

Well, my dear friend, we seem both of us to have been under (as I apprehend) discipline,
and I believe it is your and my desire that the work be thoroughly accomplished,
that we may be vessels entirely fit for His use,
whether he be pleased to make use of us or not.
Some are for use, others he calls away.
Now to allude to our last little gathering at Leeds.
We met eighteen in number at the first sitting for worship; a dear,
tried woman Friend came from Croydon, accompanied by Louisa E. Gilkes,
under a feeling of duty, and glad we were to have her company.
Richard Hall (an elder) from our quarter,
was also with us; he was the only member of the Select Meeting there,
but we have the company of two overseers of Leeds meeting,
who (one in particular) expressed much satisfaction at being with us, in much brokenness,
and hoped these meetings would be continued.
We felt it to be a favoured time (we trustfully believe
it was so.) In the afternoon it seemed well to read over,
and pause thereon for expressions if called for,
or reference in connection with changes that may have taken place,
the Queries as they stand in our book of discipline of the edition previous to 1834.

This called forth remarks which it seemed well to bring forward,
and Friends were encouraged to faithfulness in occupying with their gifts,
and to watchfulness in meetings for discipline, which they attend,
as to receiving appointments,
attending to the pointings of Truth and testifying therefor,
as well as against that which is contrary thereto.
We have felt our meeting to be strengthening,
and enabling a little to the holding up of the head and
the hands in what feels to us to be a tribulated path.

The subject of continuing to attend meetings for
discipline was again brought forward in this meeting,
and very fully and feelingly entered into, when it was the united judgment,
with the exception of one dear friend,
that the time was not come to absent ourselves therefrom.
I fully unite with you,
that if your or our allotment is of the Lord`'s ordering and appointment,
we must not murmur at the smallness of our numbers for a time,
whether in actual separation or still mingling with those
who do not see with us but look upon us as wrong;
and let us, as you remark,
"`encourage a hope that in his own time He will yet
favour Zion and satisfy her poor with bread.`"
Yours seems a trying and proving position,
and no marvel that they (the committee) could not bear the Light striking at them,
and that they were glad to get away.

Our Yearly Meeting is now about commencing, I had not thought of being there,
but believe I must in a few days go up to it from (unexpectedly) feeling if it continues,
and desiring to be in my right place,
and then to occupy with whatever may be bestowed for the occasion.
But how few we are now who see (or act) alike;
it is hard work and like working against hope,
but if we are any of us enabled for any (the least) service, may we be found faithful.

I remain your affectionate and sympathising friend,

[.signed-section-signature]
John G. Sargent.

--

5th Month 22nd.--I reached London ready for attending
the second week of the Yearly Meeting.
Was much helped from day to day and favoured to obtain relief of mind in various sittings,
so that I felt the reward of peace.
The manner of transacting the discipline I believe to be more in that which is superficial
and less in the Life than it was two years back--very rapidly going through it,
having a Clerk at the table who lacks depth.

At the close of the meeting a small company of Friends met at Joseph
Armfield`'s to seek together for Divine strength--those who are
bowed down with a sense of the state of our once favoured Society,
for the encouragement of one another, if so it might be,
and to see one another face to face.
In this opportunity favour was granted us in a feeling that the Master was with us.

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Cockermouth, 2nd of 9th Month, 1863.

[.salutation]
My Dear Friend,

Truly we must look unto the Head, and not lean one upon another,
and this will apply to our daily walk,
minding the monitions and leadings of his Holy Spirit dependent thereon,
and upon the crumbs even which fall from time to time from his table of living provision,
of which there is enough and to spare for all his dependent little ones,
wherever scattered the world over.
May I, and all of us, my dear friend,
become more and more alive to this necessary appendage to the Christian and the Quaker,
even simple, childlike dependence upon the Head, looking for the movings of his finger,
and then obeying.

With regard to these siftings, it is not more than we might expect,
and happy it is there are those who will bear the sifting and be purified,
purified through the operation--knowing that without
watchfulness and deep and close dwelling,
they themselves, we ourselves (if of this number) of the living and faithful,
shall also go away;
therefore it is my desire to encourage you and to take fresh courage myself.
And let us keep very close, increasingly close, unto the Power which overcomes,
look to the Power,
the enemy will sometimes bring in the reasoning which stands not in the Power,
but which will if we abide not therein, leaven us also into itself,
looking out instead of within, even without in the activity of thought within ourselves.
This must not be, but the eye and the desire must be in the Head.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To W. Hodgson.

[.signed-section-context-open]
Fritchley, 3rd of 4th Month, 1864.

[.salutation]
My Very Dear Friend,

For such I feel you to be in the unchangeable Truth, a lover of it, and a defender of it.
My mind has not been indifferent to your brotherly epistle,
which has refreshed and animated some of us, having been read by several.
A long cessation of correspondence has existed,
but varied circumstances it may be on both sides have caused it.
We have moved from Cockermouth to this place,
which is a village about ten miles from Derby.

It is a comfort to our minds to know of your remarkable recovery and restoration,
comparatively, to health and strength.
That this may be continued to you is the desire of our minds,
for truly such as are enabled to work in the Lord`'s
vineyard in upholding the good old way of Truth,
must be choice in their day and generation.
But some such are taken away in the prime (as we have cause to believe) of their day;
so the call is renewedly to bear this in mind, and to be diligent;
those whom the Lord of the harvest entrusts with a larger share than many,
of his precious jewels, for their occupying therewith.
And seeing he does this because of their faithfulness,
it the more behooves them to renewed diligence and steadfast obedience

You may well be brought into mourning on account of the
devastations of the enemy in this our native land,
"`the abomination of desolation standing where it
ought not,`" and this to a very great extent.
I trust there is a little band of testimony bearers left,
and of opposers to the work of the enemy (I would hope) according to their several abilities,
and the measure afforded, but these seem to be few indeed.
I trust we are some of us brought together at times,
and are brought to the acknowledgment that the Lord is indeed with us and among us;
and this does, I believe, apply to our late Meeting for worship and Conference following,
in which, throughout, we had to experience, more than at either time before,
of the overshadowing of the holy Wing.
We met at Manchester on the 2nd of this month, about twenty-six in number,
of which eight were women friends.
Our dear friend, Matilda Rickman,^
footnote:[This was the first Conference M. Rickman attended.
She was a much esteemed elder of Lewes and Chichester Monthly Meeting.
Gradually she was given to see where the Society was drifting,
and was constrained to bear her testimony against its proceedings,
by a withdrawal therefrom,
feeling as she often expressed that "`whatsoever
is not of faith is sin`". She settled at Fritchley,
with her closely united friend, Louisa E. Gilkes in the year 1868,
and was a diligent attender of the meetings constituting that Monthly Meeting.
M+++.+++ R. died at Fritchley in the 2nd month, 1882, in the 83rd year of her age,
seven weeks after following the remains of her dear friend L. E. G. to the grave.]
was with us, with Louisa E. Gilkes.

At this Conference was brought in a document, preparing (we hope) for the press,
showing the sad declension, by way of the changes that have taken place,^
footnote:[This work was drawn up by Daniel Pickard, of Leeds,
and afterwards revised and adopted by the Friends attending the Conference Meetings.
It was published in London in 1864.
Its full title is, [.book-title]#An Expostulation on Behalf of Truth,
Against the Departures in Doctrine, Practice and Discipline,
in Which the Revised Queries,
Rules and Advices of London Yearly Meeting of Friends
Are Examined and Compared with Former Editions.#
Although this was a public indictment of London Yearly Meeting, showing from its acts,
by a large number of [.book-title]#Extracts from the Queries, Rules and Advices,#
its lapse from first principles, and was temperate in tone, being, as its name implies,
an expostulation, yet, it was never answered!]
the Yearly Meeting countenancing them by the alterations
and additions in the late revision of the Book of Discipline.
We think it is a valuable collection, springing from the exercise of a brother among us,
others also viewing the desirability of a testimony of this sort.
Slow progress, or but little, I may acknowledge, appears as to these meetings,
or the work in them, but we have felt refreshed together in the Lord, I can, I believe,
truthfully say.
I have still to admit that all are not quite of the same mind with regard to
the attendance of the meetings for discipline under the present constitution.
There are some who are ready to discontinue their attendance of them,
while others think it is not right to do so,
or that good may yet be done in the attendance.

Since we have been here we have been holding our meetings at our own home,
but we think it will be best to open a meeting in the village,
or attend the meeting nearest to us, which is Furnace.
But this is about four miles off, and we are as many as twelve altogether,
and it is too far for us all to go, unless we had a commodious conveyance,
so that it appears more reasonable for us to sit down together here,
and it is more likely than not that others would meet with us if we had a public room.
I trust the right way will present before long for our acting therein.

How, my dear friend and brother in the Lord, how it would, I think,
rejoice my heart to come and shake you by the hand, if in right ordering,
but whether this will ever be, is only known to the Lord,
who does bring wonderful things to pass; however,
whether present or absent one from the other,
let those who humbly have to believe in times of His appearing that they are His servants,
let them at all times endeavour to keep on the armour of His righteousness,
which they verily do know,
though they may be compassed about with many difficulties by the way,
to be sufficient to bring forth to the honour of His ever excellent Name.

17th.--This has been laid by unfinished.
I now return to you in mind, and may I not say in heart too,
for my soul longs after the good, and sometimes feels it,
that is partaken of by the brethren.
Since last writing we have attended the Monthly Meeting at Chesterfield.
A certificate of removal for us and family was brought to the meeting,
but deferred being notified in any way, it manifestly appeared by previous contemplation.
What will spring out of the matter I know not,
but not having been attending the particular meeting, except on very few occasions,
and sitting down at home,
I think the idea is that we are about to set up a separate meeting.

As to asking consent to open a meeting here,
we are not at the present time feeling easy so to do,
and thus show an allegiance to their authority,
that of the present backslidden organization.
It may be the time is now come to arise and shake ourselves from the dust on our garments,
and come clean out from them,
as regards the attendance of more disciplinary meetings with them,
but I apprehend something will be required by way of testifying in this Quarterly Meeting,
where we are comparatively strangers, before we quite leave them.

I unite entirely with you in the judgment that it is a delusion,
the waiting for something more glaring or more tangible than the
evidences we have already of the great and general departure (with
only few exceptions) from the principle we profess to hold,
and which has been held by all true Friends.
Your remarks are good, my dear Friend,
with regard to standing aloof from many who still
retain a "`name to live,`" but who are gone,
as it were, into the shadow which declines.
It is good, indeed,
to feel that we are at any time brought down into
that low valley where we can give up all,
as you write,
for his sake who has condescended to enlighten us in regard to his precious Truth,
and has called us to stand for his precious testimonies
in the midst of a crooked and backsliding generation.

With regard to the address issued by the so-called Meeting for Sufferings,
which you allude to, respecting the war,
how can anything they touch while in alienation from the true principle, be clean?
It must show itself; the fruit must be according to the tree,
though it needs sometimes the vision of the just to see it.
May we be afresh animated to strengthen the things that remain,
as regards our several particulars in this land,
and you by a steadfast adherence to that which has been shown you in the light.
So may we be encouraged by your faithfulness,
and that cleanness may be in the camp of God, the whole camp, whether with you,
or with us, for the Truth is the same everywhere,
and the children of the Truth are the Lord`'s people,
however far divided as to the outward, by sea or land, and know one another in Spirit,
whensoever the Spirit brings them together,
and even the very countenance outward indicates to such that they are brethren,
and they walk together, for they are agreed;
and they testify that Truth is truth and no lie; and they love it,
because it makes them like it, and it has made them free, free indeed!

"`Choose the good and refuse the evil,`" are very significant words,
and how binding upon us all.
Choose the good in ourselves, choose the good in others, for He that plants it is One,
whether in us or them.
"`Go and do likewise,`" this shows example is to be followed,
a measure of His good Spirit going before, within us,
which has to cleave to every appearance of good, coming from the same Spirit in others,
so that nothing that it can or may do outwardly will offend, for it must be of the same,
which is supremely good.
Your account of the sufferers during this war has much interested us--a trial of faith,
as in days gone by.
To conclude, my dear friend, with your words,
"`may we stand firmly for the Master and his pure Truth in our day and
generation,`" that so we may serve Him who is greater than all,
and yet condescends to appear in the least, and it recurs to mind in the least,
those who are least in their own eyes +++[+++He condescends to appear in such]
more than He can do (for there is not that room to enter) in those who are not
yet brought down into a state of nothingness as pertains to themselves.

[.signed-section-closing]
In brotherly love I feel to be your true friend,

[.signed-section-signature]
John G. Sargent.

--

1864+++.+++ 9th month 18th.--Met the first time in the Cottage Meetinghouse at Fritchley.
A quiet favoured time, life springing up in the morning meeting.
In the afternoon not so lively.
A feeling of peace, and I trust thankfulness,
was the clothing of our minds at thus being provided with a comfortable Meetinghouse.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 17th of 9th Month, 1864.

[.salutation]
My Dear Friend,

Your description of the state of those in New York Yearly Meeting is very comforting.
Their epistle to the remnant of Friends in England will find a response
in the hearts of the livingly concerned here to whom it may come.
I hope you have felt satisfaction in your late move of residence.
It feels a favour when, at any time, shown the way; in this the heart can rejoice.
There seems to be, as we advance on our pilgrimage through time,
fresh calls for faith and faithful walking, even in paths we have not before known;
in these an increase or greater measure of faith or trust must be our portion,
if we would grow in strength.
This has been called for in our late move to this part,
but I am more and more willing to believe that the Shepherd
of Israel is condescending to lead in the way,
and it may be that the good Hand is preparing us
to endure hardness as soldiers in his ranks.
May this be our favoured experience, even to know how to endure,
that we may be saved in the day of close proving;
for what is to come upon us we know not yet.
There is strife,
and striving in man`'s spirit which must eventually know a downfall or be brought thereunto,
under the powerful working of the wisdom of God.
May it be in the ordering of the Lord that this is come upon us,
that we are accounted as disturbers and disorderly walkers, because we cannot, yes,
dare not, go with the false current and bow to the decrees of the Yearly Meeting.

We had a comfortable little meeting on First-day--our first in the cottage,
which is a long room well adapted for the purpose.
Two stranger members with us, and a third who was visiting us previously.
It is a favour indeed to be permitted to feel that we are owned together,
amidst conflict as regards some, on account of our setting up this meeting.
I may have named it before to you,
that I have not felt free in my mind in the present state of the Society,
to ask permission of the disciplinary meeting,
though when the committee brought in their report to the Monthly Meeting,
after visiting us,
I told the friends of our prospect of holding our
meetings in another house laid out for the purpose.
May the heavenly wind blow all adverse currents away in due time.
It is well for us to have a proving why and for what end we do as we do.
The Lord knows it is to maintain through all, our endeavouring at least,
to act for the Truth, and to walk unspotted before him.

I have omitted, I believe,
to inform you we were highly favoured at the close of our
last Conference with the owning presence of the Master,
this in an eminent degree overshadowing with solemnity,--the Crown of all our meetings.
In this I believe you will rejoice with us.
May we so walk as to know again and again, and not only when so assembled,
but at other times also, the banner of Truth lifted up,
and our Ebenezer to be exalted to the praise of Him
who is the Omnipotent Judge of all the earth.

[.signed-section-closing]
I am your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 26th of 11th Month, 1864.

[.salutation]
My Dear Friend,

Your acceptable letter was received with pleasure and comfort.
Since that time we have met in the same way as previously; this time in London.
We continue to feel that it is good for us so to do.
I think we were over thirty in number, and spiritual strength was, I believe, renewed.
But way does not yet open for much more decided stepping; some are very fearful,
if that is the right word.
I desire much that the unchangeable Truth,
which led our forefathers and still leads those who will be subject thereunto,
may be our strength, and bring forth judgment unto victory,
in all our proceedings for the cause of Truth,
and that the halt and the blind may be either led onward into safety,
or that the camp may be purged from all that unduly stay behind,
that thus we may be a willing people,
being led and governed by the true Leader and only safe Guide.

I handed in the Epistle from the Friends on your side the Atlantic,
addressed to the "`Remnant of Friends in England.`"
I had read it myself to comfort,
but the prevailing judgment of Friends at the meeting was, not to read it;
it being considered that there was no organized body to whom this appellation will apply,
way did not open to receive it.
There were nevertheless some who were quite prepared to appreciate it,
and it has been circulated among some who were not at the meeting,
and it is now in circulation.
It may be well also to add that satisfaction has been expressed with the reading of it.

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 28th of 12th Month, 1864.

[.salutation]
My Dear Friend,

It feels pleasant to have a little fellowship in this way;
your feeling of unity and sympathy with us is very cordial.
We have cause to feel thankful for an improvement in health, some, if not each one of us,
since coming into Derbyshire,
though there has seemed to be an increased demand upon time and energies,
more than was anticipated.
I am encouraged to trust that the step taken is a right one,
and in the ordering of a kind Providence.

The view that A. F. takes does not surprise me;
I am quite prepared to believe that the idea even
of a separation is quite unsavory to most,
and that this prevails among such as are averse to
the changes (or some of them) that have taken place.
What seems to be dreaded is, I believe, an amalgamation with the new views,
by little and little giving away our strength; herein is, I have no doubt,
need for the watch, so that the fear, I apprehend, should be,
not lest we forward separation, which fear is a part of human policy or reasoning,
but lest we become mixed with the people in that which is unsound or of the new leaven,
by not standing firm upon the Rock, and thus keeping to Truth`'s testimonies,
and letting the Lord rule by his pure light working in his and by us.

So, I believe, if we would walk in the everlasting Day,
we must let fears of separation alone,
and allow the true and holy leaven to work for and by us what the Lord may choose;
so that in effect it will thus be what He chooses and what He works,
and not what we fear.
For the fear of man brings a snare, in whatever way it is exercised,
inasmuch as where this fear is, trust in God does not prevail.
So my view is that we have nothing to do with such fears,
but to walk onward in the Light according to the measure bestowed,
as though we knew no such thing as separation, but having the Lord always before us.
Man`'s policy or natural wisdom is the cause of all this evil that has come over us.
Why then allow it to work among us in the shape of fear to be separated, fear to offend,
or any other fear than that of departing from the fear of God?
What have we to do with it?
Are we not told to keep the eye single, and the whole body shall be full of light?

Now, if we be fearing or contriving against separation
by diverging from that which might work it,
while our path seems made clear to us and certain, is, in this, the eye kept single?
Surely we must not expect the whole body to be full of light if we steer our own way
to avoid what human reason shows us is dangerous--but the true danger lies in this,
choosing our own way, and in the fear of man, or of man`'s wisdom,
which brings with it a snare.
I think you will understand me.
If our trust is in the Lord,
if we have partaken of his goodness and owning condescension, in our steppings thus far,
let us not entertain anything but that good thing which is our strength, our Light,
and our Guide.

I incline to believe that the sub-divisions you alluded to may be in best wisdom,
and a necessity for the purifying of the Church, as a sifting from sieve to sieve,
till that only remains which the Lord chooses should remain.
And then it is,
when the few grains of pure wheat remain alone that
the eye must be kept constantly upon the Captain,
and according to their faithfulness,
out of the fear of man will they thus be preserved to the Lord,
and draw those after them,
who as yet had not been ready to undergo the whole purifying process.
So if faithfulness is abode in by a remnant, and patience too, we may hope and trust,
I believe, that the Lord will be glorified in them,
and a gathering to the standard will be the result.

With regard to S. E.`'s remarks as to the station the Master has placed us in,
in the Church,--the Church of God is composed of living stones, not dead ones.
These must act for Him according as He orders.
The eye that sees, it must be for a purpose, and we must be subject to his commands.
I esteem S. E.,
and I regret he thinks (as it appears to me) that it is on account
of annoyances that we do not walk with those who are in the changes,
nor act in the discipline.
This I hope is not a correct view, it is not a solid basis,
and unless there is something stronger to stand upon,
we had better bear the annoyances for our humbling, and not move from under them.
I have written much, but hope no harm,
and with sincere desire for our (each one`'s) preservation,
strengthening and increased clearness of vision and steadiness of purpose,
as the way is made clear to us.

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
John G. Sargent.

--

1865+++.+++ 4th Month 13th.--At Monthly Meeting in Belfast was engaged in testimony.
Was reminded how that help and deliverance comes
not always in the ordinary course of things,
and how he that was at the pool of Bethesda was healed,
who was waiting for the troubling of the water, but in that instance was cured by Him,
who was by him, out of the common course of things

For the first time in a meeting for worship I bent the knee,
and supplicated that our petition might be heard,
and that the overflowing scourge might pass over;
that the Lord would hear from his judgment seat, and in judgment remember mercy,
that the lost soul might be redeemed.
This seemed to have reference to what had been described by other Friends in the meeting,
as a state of condemnation for pride and haughtiness on
the part of the daughters of Zion (a state present),
"`walking and mincing as they go,`" etc.,
and as though time was very short with such a state.

Felt I was helped to this fresh act of dedication,
(may I not say.) All praise unto Him who I humbly trust moves me to fresh acts of obedience.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 28th of 5th Month, 1865.

[.salutation]
My Dear And Much Valued Friend,

I am afraid you are thinking too well of such a one as me,
of whom I desire humbly to say, "`I am poor in Manasseh,
and the least in my Father`'s house,`" for it is the poor in their own eyes, truly poor,
who are fed, truly fed; and the least also in our own sight, or esteem,
who are truly great, so think not of us above that you ought,
any more than we are so to think of ourselves or
our own attainments in the spiritual warfare.
Truly, when in the light of the Lord we see ourselves, something of our stature,
how humbling then to see how little we are in our best attainments,
compared with what we ought to be.
Then where is there room to boast?
Man only can do this, because he sees not as God sees,
and this is a state not to be coveted.

Perhaps T. D. may have written to you respecting our late meeting in London,
in which we were favoured,
and strengthened to make an appointment to visit the Meeting for Sufferings,
in order, as they may be enabled,
to solicit the attention of that meeting to the very serious
changes recently made in the doctrine and discipline of
our religious Society as the same are set forth in a book,
entitled, [.book-title]#An Expostulation on Behalf of the Truth.#
The Friends who attended (four in number) were detained
about two hours before being received,
and it was preconcerted in the meeting not to enter into a discussion;
so after three of the Friends had relieved their minds among them,
and after very little remark, they withdrew.
I have heard nothing as resulting therefrom,
but it is another step whereby some relief is obtained.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
John G. Sargent,

--

[.embedded-content-document.letter]
--

[.letter-heading]
From William Hodgson.

[.signed-section-context-open]
Philadelphia, 30th of 7th Month, 1865.

[.salutation]
My Dear Friend,

It is very plain that there is no ground for hope in the present organization,
for a pure standard to be raised for the ancient faith and practice.
+++[+++In England]
I apprehend they must be left to the corruptions which they have chosen and cherished.
But I do often long that a remnant, if ever so small,
may be preserved and strengthened to stand for that
way in which our forefathers found safety and peace.
Yet this must be through suffering and deep humiliations,
a willingness being wrought to be accounted as fools, yes,
as the very scum of all things by those who are soaring
aloft in their imaginations and fancied attainments,
and conscious of being looked upon as wise and great and good by
those who are in the same worldly-wise spirit that rules in them.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
W+++.+++ Hodgson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 12th of 11th Month, 1865.

[.salutation]
My Dear Friend,

Your acceptable letter came to hand,
written at a time when you were confined to your bed, and feeling low, I apprehend,
under discouraging circumstances.
May I trust you are now feeling better again in the outward, and inwardly revived,
for seasons there are of conflict, besetment and trial,
for the wise purpose permitted of humbling and raising up again,
that the creature may know wisdom and continue growing therein;
that all the glory be given to whom it is due,
and that we may again and again see that our whole
dependence must be upon God and the Saviour,
whom man by reason acknowledges, but not so experimentally,
without this humbling by the breaking down of His Power.
To know of your being helped to a good degree of recovery, would be a comfort to us,
but our desires, for ourselves or for others, have to be subject to the Divine will;
if the Lord will, ought to be our petition

Our little meeting here continues, I am able to inform you, to be,
according to our belief, in the Lord`'s ordering, and owned,
we desire humbly to acknowledge, by Him who cares for the sparrows.
Were you in reach of us,
glad would we be to mingle with you that we might feel together where Truth is,
and seek to know together the mind of Truth.
What a favour to be found in our right places if so be we are faithful therein!
You allude to our Conference and the communication with the Meeting for Sufferings,
which was, as you suppose, with a view to clear our hands towards them,
rather than with any expectation of inducing them to retrace their steps.
Our last meeting was held in Birmingham.
We have hitherto felt it right to hold these meetings,
though I believe in our last we sensibly felt our weakness and dependent state,
and right that we should feel this, which is a favour;
yet the good Master does own our desires therein, we do believe,
and we have been encouraged thereby.
We are nevertheless weak indeed,
and do not come up to that which we could desire for strength, for stature,
and clearness of vision,
or walking answerably to the pure living testimony which the Lord would lead into,
was there more true devotedness to Him.

Your account of your General Meeting is interesting to us;
showing to us that you have stronger men and women than we have,
to come up to the help of the Lord against the mighty man,
the man of much strength according to the wisdom of this world, which wisdom,
how often it does step in, and sits as an angel of light;
but we need not be deceived thereby, if we do but watch and keep humble; so doing,
we keep close to our heavenly Guide.
But for lack of this, or going therefrom, we go from Him,
and follow the great deceiver who really loves the darkness and hates the light.
I lately attended the Quarterly Meeting at Leeds under an apprehended feeling of duty,
and sat the meeting for discipline,
in which I felt drawn to raise my voice by way of testimony.
I have been given to feel, I think I may venture to say,
that there are those in this poor Society, who, as it were,
know not their right hand from their left, and my spirit has,
I also desire humbly to say, yearned over these,
that the Lord`'s power may go over them and that
they may be shielded from the enemies`' snares,
now so thickly spread by the hands and the example too of those who rule;
who "`have lost their hands,`" or have stepped into rule
without being placed there by the Head of the Church,
or such as the former whose bows have not abode in strength,
the Strength of the Redeemer, and so they have fearfully turned aside,
and instead of being watchmen and watchwomen,
have become snares and gins to the house of Israel.

May we, my dear friend, be preserved under that Heavenly Wing of power,
which while under we are safe, and the archer cannot come at us nor hurt us.
The abiding is sure, while the hands of the soul are lifted up for safety.
Now my dear friend, I, and we,
do desire to salute you in that which is so near and dear to each one of us,
trusting in the Lord that he will keep us.

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 11th of 3rd Month, 1866.

Your letters, my dear friend and brother, are fraught with much that interests us both;
and some have been much so with that which is cause for mourning and deep conflict.
Where shall we go?
The answer is quite plain; abide by the Master.
We are often brought into a very straight and trying place, but not too much so,
I believe, to be helped through and over; but that eye which does not see,
wants sometimes to see before the right time comes--the Lord`'s time.
We can only fight for the Lord in his time and in his way.
Poverty and strippedness have been much my portion of late,
and may patience be the needful accompaniment, then there may be hope.
The Conference Meeting you have alluded to as knowing nothing about,
from hearing or written communication,
was one of less encouragement than I think previous ones.
Indeed, we are but a poor, weak company.
There does not seem strength to take any decided step unitedly; there needs to be,
I believe, more of a seeing eye to eye, more of the true unity as to moving along;
we are indeed very few, and none but the Lord alone can help us, strengthen us,
or make us as a band to meet the adversary.

With regard to the state of the Church here, it is conflicting indeed,
and I can see no other way for us,
than to mind our own business and be faithful to Truth`'s secret leadings,
then I do trust a seed will be preserved,
though there may have to be a contending for the
faith as it was once delivered to the saints,
by going forth and moving among the adversaries and
weak ones with our lives in our hands.
May we not trust that if very watchful we shall know all
these turnings and overturnings to work for our good,
and that no positive evil will be permitted to come nigh our dwelling--that safe,
deep and inward dwelling with, and in, the Lord Jesus,
that as deliverance does not yet arise for us from the Lord we
may yet have to lift up the voice against the accursed thing,
in the meetings for worship and for discipline too,
without feeling that we are one with them, or can work as they work.

I have sometimes felt best satisfied to remain and
to watch and to do as utterance has been given me.
So, my dear friend,
I wish to let you know just how I have been led (as
I apprehend) to view the state and condition we are,
as a people, in.
It is a life of dangers, fraught with perplexities often times,
and many are the temptations, so we have need to be humbled and to be kept low.
The many subdivisions on your side are painful,
and yet I cannot say they are surprising,--sifting as from sieve to sieve,
and then what does remain?
May it be life, and life enough to outlive the death and darkness so much prevailing.
O, that all might come into the true humility and subjection, therein, then,
with the heart open to instruction which comes therefrom,
there would be a cleaving to that only which is good,
and brother would cleave to brother in the unchangeable Truth.

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

1866+++.+++ 9th Month 1st.--Met in Conference in London.
There might be about thirty Friends present in our meeting for worship;
a favoured time it was felt to be, and in the sittings throughout, ending next day,
when we parted in the feeling that it had been good to be there.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 30th of 12th Month, 1866.

[.salutation]
My Dear Friend,

On reading your last very acceptable letter, my heart saluted you in Gospel love,
love unfeigned flowed from me as to a brother beloved who
desired the prosperity of Truth in our land as in his own,
and truly, I believe you not only desire it, but, labours for it also,
in the ability which the Lord your God gives you, so that I can say, go on,
and the Lord your God be with you and prosper you in that which he commits unto you.
I have at this time again taken your letter for perusal
to take up such parts as may seem to call for a reply.
You query of me what may be the accounts we receive
from your side which seem conflicting or puzzle us.
Your cautionary remark in words of Scripture are, I believe applicable,
and very good in the matter, "`Take heed how you hear.`"

What has been conflicting is the accounts that have reached us of divisions
and subdivisions on your side and among all those who have felt drawn
off from the new organizations as they may be called,
though under the name of the Society,
for it does seem that with you and with us the old Society has become newly organized,
even in the letter, and not of or in the Spirit.
"`Go not after them, nor follow them,`" are the words which come to mind.
But on looking at the probable state of such companies as do feel themselves drawn off,
or in other words quite as correct, left to themselves,
I do view it that there will be at first some who are not sufficiently
humbled or come off from the favour and fawning of man,
or the love of the honour which is of man; so there still must be a sifting,
a further sifting as from sieve to sieve,
before that which is entirely free from the chaff remains.

I believe our heads have been lifted up from this depression,
so as to be enabled to look at things, somewhat as we have believed they are,
and remembering still that there must come tribulation,
and we must (all those who love and fear God, the God of their lives) pass through it;
so I would encourage, from my heart, those dear friends who see in the Light,
not men as trees walking, but things as they really are, that they be faithful,
that they pursue that which they are called unto;
that they put no other garment on than that of the Spirit, no mixed garment;
that so they be not spotted,
and that they be thus accepted of Him who will and does clothe
with his own clothing spiritually and that also outwardly,
which is in conformity thereto, so will no wolf be permitted in the fold,
the fold of Christ, because he is the Shepherd thereof and cares for his own.

Would, my dear friend, that we were stronger in the faith,
that there were more of such too,
who are prepared to hazard their lives (all that is theirs) for the precious Truth.
Then might we go forward;
but unless we are willing to go "`in this our might,`" in the measure that is bestowed,
we shall not achieve much for the Lord, for ourselves, or for our successors,
the succeeding generation.
As regards our Conference Meetings, you are no doubt right,
that there are "`hangers back among us, even to the weakening of the faith of others.`"
I think you have very clear views of our position; favoured opportunities we have had,
but it may nevertheless be, that some of us are too much hanging back,
and it does seem as if very few of our number are prepared, or have been so hitherto,
to take any decided steps;
but there is a fear among us lest we do in any way
appear to others to be forming a separated body;
this seems to be the care and the fear, of some especially,
and a strong objection was manifest in our last meeting to the making any minutes, so,
much has not yet been done in this way.

1st Month 20th.--And now my dear friend, I again take the pen,
and may inform you our Conference was held as appointed, on the 8th of this month.
The meeting for worship, the first sitting, was a favoured one.
I do not remember feeling that we have been more owned together at any former meeting,
and through each sitting.
We were about twenty-two in number.
The old Queries in the 1802 edition of the Book of Discipline were read, and, I believe,
seriously considered, and some remarks made thereon.
We feel it good to read the old Queries.
The Friends who had been on a religious engagement into Wales since our last meeting,
holding meetings where there are none established, gave in a report of the same,
and of the help vouchsafed.
The concern had been brought before us at our former Conference,
though no minute was then made.
But at this meeting no obstruction arose,
and we were favoured with strength and ability to go forward, I believe, step by step,
and to make some advance in unity one with another.
The friends who went with the sympathy and encouragement of the meeting,
were Daniel Pickard and Louisa E. Gilkes, accompanied by Matilda Rickman,
and we can believe she was helpful to them.

Well, my dear friend, while thus much looks encouraging, I do believe nevertheless,
we are still in the weakness, and need more strength, more of the true boldness;
there may be something that hinders from so fully going
forward as would be to the praise of the great I AM,
and may we be permitted in mercy to see the hindering thing and know it,
each one for ourselves;
may we be endued with more of that power which strengthened
our forefathers and led them forth.
To hear of your meetings and the holy help vouchsafed in them from time to time,
and the faithful messengers among you, is encouraging, and there is a power which,
if we know it in our midst, and day by day for and in ourselves,
does lift us up above discouragements that otherwise would overcome us,
and there would be no faith in us,
but assuredly while we feel the Father`'s love in our hearts by
the visitations of his Spirit through and by his son Christ Jesus,
we can but believe, though there are times when faith gets low,
and remains low till the Replenisher comes in for our help.

There is, indeed,
abundant evidence for our learning the need of watchfulness that we go not after,
nor mind, that disaffected spirit which errs, and would draw us off from the discipline;
so salutary as it is felt to be by those who know their own weakness,
and how prone man is to slide imperceptibly from the right path,
the alone path of safety, the sure Guide, whom to know and follow is life eternal

In near fellowship in the unchangeable Truth, I am your friend,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

1867+++.+++ 1st Month 8th.--Met in Conference in Birmingham as appointed.
About twenty-two Friends present at our first meeting,
in which a manifestation of the Lord`'s power was known to the rejoicing of our hearts,
and I felt constrained (for the first time in an assembly in this land) to bow the knee,
and supplicated that there might be an offering up of a meat offering
and the pouring forth of a drink offering unto the Lord,
acceptable to Him, at that time, and that whereas we, some of us,
believed we had long enough compassed this mountain (or state in
which we then were) there might be known a going forward;
and I did believe that the Lord was graciously pleased to hear from heaven,
His dwelling place, and that there was at this Conference a stepping onward,
and an advance made not before known among us,
obstructions being removed that before had stood in our way, and in this particularly,
that our clerk made minutes of proceedings, with unanimity,
and no hindrance--whereas at our last Conference there had been some hindrance, and,
I believe, stoppage of the Life.
The queries were read, and seriously considered to our edification.

Cockermouth,
2nd Month 10th.--Have again to praise the Lord for his help in my inward man,
having in both meetings, had to declare for Him; in the afternoon,
"`that a living dog is better than a dead lion,`" and to show a little, I believe,
of the application thereof.
Truly of this day I can say, help comes from the Lord.

24th.--At Barrow, and to meeting at Loughborough.
Was impressed with the words and experience of some,
that "`we spend our years as a tale that is told,`"
therefore we do well to watch at Wisdom`'s gate,
that we may be taught so to number our days that
we may apply our hearts unto wisdom,--heavenly wisdom.
We were six of us at meeting.
Life prevailed towards the end of the meeting, in which and by which utterance was given.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of his Sons.

[.signed-section-context-open]
Belfast, 5th of 2nd Month, 1867.

[.salutation]
My Dear +++_______+++,

You have been in my thoughts since we parted yesterday,
and I feel as though I could be most easy to impart to you a little in this way,
of the concern I feel for your real welfare in that which is good and of primary importance;
for what are all outward and transitory things and
enjoyments and lightness of spirits in the outward,
compared to the substantial enjoyment of inward peace and a truly quiet mind,
held and strengthened in the God of peace,--that holy quiet
in the inward man which is known to the followers of Jesus.
What I so much desire for you is, more of this inward quiet and stayedness of mind,
more of the heavenly ballast which is as an anchor, and which,
while in the innocent enjoyment of the outward,
prevents and stays the mind from dwelling there,
so that the mind thus knows a sure and safe anchorage while
passing along day by day amid temptations to soar aloft,
which I believe the enemy would keep you from the knowledge of;
I hope you will understand me?

--

1868+++.+++ 2nd Month 6th, Manchester.--On my way home from Ireland on business,
I attended meeting here this morning, and was helped I believe,
to deliver what was given.
"`I will not trust in my bow,
neither shall my own arm save me,`" enjoining waiting upon the Lord the full time,
that our own hearts may be strengthened and we be fit for His service--not
offering nor eating anything that dies of itself,
remembering how Saul offered before the time,
not waiting long enough--not to trust in anything
that is of the natural man or in the wisdom of man,
and if we trusted in Him, He would feed us with food suited to us, and in his time,
(or to that effect) He would enable us to shake off the dust and arise,
and our light would shine brighter and brighter unto the perfect day.
Felt peaceful in the conclusion of my offering.
