== Chapter IV.

[.chapter-synopsis]
* Visit to America Accompanied by M. Rickman and L. E+++.+++ Gilkes
* Letters to his Wife
* Letters to T. Drewry, D+++.+++ Koll, W. Hodgson, J. D. Otis, J. F. Marsh, P. Mitchell
* Letters From D. Koll, W+++.+++ Hodgson
* Letter to one of his Sons
* Visit of W. C. Meader and J+++.+++ D. Otis to England
* Reflections When on a Business Journey in France
* Public Meetings at Fritchley and Monsal Dale.

1868+++.+++ 4th month,
2nd.--At our Conference meeting held in London I laid before Friends there a prospect
which I had long had of visiting Friends in their meetings in America,--those who had
withdrawn from the main bodies on the ground of unsound doctrine.
Unity and sympathy were expressed, and our friend L. E. Gilkes opened a similar prospect,
also Matilda Rickman as her companion.
I believe I may say, of a truth, the Lord is with me in this thing,
and that he has been pleased for my help and encouragement to say to my inward ear, Go,
and I will go with you.
O that I may ever trust in Him!

[.offset]
+++[+++As will have been already gathered,
our dear friend had by this time thoroughly lost confidence in London Yearly Meeting,
and no longer attended the disciplinary meetings in connection therewith;
but being desirous of conforming to good order so far as circumstances would allow,
it seemed best to submit his concern to visit America to the only
meeting in which he had confidence as a meeting of Friends.
As however the Conference before which the matter was brought,
was not an organized meeting, some hesitation was felt as to giving any credentials,
but copies of the minutes made on the occasion were allowed to be taken,
and are as follows:--]

[.embedded-content-document.minute]
--

At a meeting for Conference held in London on Fifth-day, the 2nd of Fourth Month, 1868,
about the usual number of Friends were present.
Our dear friend John G. Sargent, in a brief and weighty manner,
laid before us a concern which for a number of years had rested on his mind,
to visit the small bodies professing the ancient
faith of Friends on the other side of the Atlantic,
but who are not in correspondence with London Yearly Meeting.
Our friend Louisa E. Gilkes has also expressed a similar concern and Matilda
Rickman her willingness to accompany the two former Friends.

The subject was solidly deliberated upon,
and much unity was expressed with these our dear Friends and sympathy also,
in the arduous engagement they had in prospect.
It was concluded to postpone the further consideration until tomorrow.

3rd.--We have at this time again had under our serious
consideration the concern of our dear Friends,
and we feel that we can offer no obstruction to the prosecution
of the service they believe to be required at their hands.

--

5th Month 8th--I left home in company with my wife and son
P+++.+++ also our friends Matilda Rickman and Louisa E. Gilkes,
for Liverpool in order to leave next day by the "`Russia`" steamer for New York.
An evidence was graciously afforded me and my dear wife of its
being in the Divine will for me thus to go to visit Friends.

9th.--Was much broken in the prospect of leaving my dear wife and all my family behind.
Great favour was extended this morning in a time of quiet before leaving our bedroom,
in which the words ran through my mind "`The Lord is with us of a truth.`"
This I do desire to remember with gratitude to the Father
of all our mercies and our Lord and Saviour Jesus Christ.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
On board the "`Russia,`" 9th of 5th Month, 1868.

[.salutation]
My Dear +++_______+++,

It is in my heart to write you a few lines if not more,
not having seen you quite so lately as your dear brothers and sisters.
We all lodged at Liverpool and came away by the tender,
it might be soon after ten o`'clock, for the vessel;
several of our dear friends with us.

We are now going steadily on our way for Cork harbour,
at which we may arrive about eight o`'clock tomorrow morning
and leave in the afternoon between three and four o`'clock.

Well my dear boy,
I feel you and each one of you (with your dear mother) very precious to me,
and my earnest desires for one and all are,
that Israel`'s Shepherd may gather all into his everlasting arms of safety,
and preserve you unto the end.
And I trust that in his own time He will be pleased to bring us all together again,
and this with peace.
So let each one be watchful unto Him, hourly watchful, maintaining it,
and we need not doubt or fear but He will care for us.

We are about twenty passengers in the second cabin,
much more select than we should be in the first;
and the only difference is a difference of saloon,
but ours is comfortably arranged for regular meals and plenty.
I was pleased to have your letter and interested in its contents.

Well my dear boy, I shall think of you all; distance cannot prevent this,
and though for a little while we may be far separated,
I feel a comfortable evidence that this is in the Divine will and in this
we ought to desire to be found for the short time any of us have below.
My dear love flows to you and each one of you.
Farewell very affectionately.

[.signed-section-closing]
From your loving father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
On board the "`Russia,`" 9th of 5th Month, 1868.

What favours, my beloved one, we enjoy and what peaceful minds,
although nature has felt before, and at our parting sorely broken down,
but there is One who knows our weakness and who has compassion upon us.
And now I trust we may be,
through his continued lovingkindness favoured to
know Him near to us and directing all our steppings.
I am hoping that you feel sustained and that you
will indeed be enabled to rejoice in hope,
and that when the good Master may be pleased to bring back again we may rejoice together;
this has been often fulfilled after my little journeys on needful business,
and may we not trust it will be realised after such a one as this, to which duty has,
we believe, called.

I lack nothing as to the outward, and the Master favours me richly within.
How comfortable is his presence and what is there like unto it?
My desires are truly that you and all of you may
be helped by the watchful and unslumbering Shepherd,
and my trust is and faith too, that He will care for you and us.
What cause for thankfulness that not a shadow of a doubt is permitted
to assail the mind as to the rectitude of the step taken;
the quiet confirmation thereof rests comfortingly upon the
mind and there is abundant cause for the renewed resolution,
as was expressed by L. E. G. in our little meeting this morning,
"`Let others do as they may, as for me and my house,
we will serve the Lord;`" so let every one of us be faithful
to his call and in his service and all will be well.

--

10th.--Arrived this morning at about 8:30 off Cork Harbour.
Favoured was my experience this morning on waking,
the dear Master`'s presence being manifest to my humble admiration,
causing gratitude to arise in my heart; may I remember it for good.
Stayed here on board till about four p.m.;
then after receiving the mail bags,--a large number,--left
on our way to cross the great ocean,
reaching the line of the last point of land at about nine o`'clock.
Had our little meeting this morning,
in one of our small cabins and were favoured therein: a fellow passenger joined us.
My mind was accosted with the words "`The generation of the upright
shall be blessed,`" and a little enlargement given therewith.

12th.--Have been enabled to rejoice in heart while
walking the deck in the evening of today,
at the lovingkindness of my Lord.

13th.--Feeling quiet in mind.
Surely this would not have been had I not been in my rightly allotted place.
May I ever trust in the Lord.

14th.--I suppose we may now be about mid-way between Liverpool and New York.
I have not felt any misgivings, but continue,
through favour to feel in my right place in thus coming out and leaving all for
the sake of the cause of Truth and in obedience to apprehended duty.
O! how good the Lord is.

15th.--We had a comfortable season of waiting together this evening before bed-time,
in which I felt it right to revive the language,
"`He will beautify the meek with salvation`" and expressed the belief
that He has given to each of us "`the garment of praise for the spirit
of heaviness`" as a blessing in its being the covering of our hearts,
or to that effect.

17th, First-day.--Had our meeting this morning in the saloon,
in which we each had something to communicate.
"`O house of Jacob,
come and let us walk in the light of the Lord`" was much with me
and expressed as the invitation going forth to us all.
There might be a dozen persons present besides ourselves, and much quietness prevailed.
In the evening had a quiet opportunity with the steward;
in this I felt particularly drawn to address him.

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
On board the "`Russia,`" 11th of 5th Month, 1868.

[.salutation]
My Beloved Wife,

I have been favoured with comfortable feelings in looking at this important stepping,
today;
so that I have rejoiced in heart at the favour of the Lord to me--nothing
but peace in my present position and the retrospect of the past:
this feels a favour indeed; and the desire of my heart is,
that this you can partake of with me though so far
separated by this great expanse of water.
Dear M. R. has told me she felt very peaceful.

14th.--I conclude we are about mid-way on the Atlantic this evening.
What a new feeling to be under is that of being so far from land,
and how is our dependence shown me upon the great Ruler of the universe.
Something of a feeling of awfulness pervades the mind but not a
doubt is permitted to assail me as to being in my right place.

17th, First-day.--Very fine weather and a calm sea.
We held our meeting this morning at about 10:30, in the saloon,
some fellow passengers sitting with us.

18th.--I think I did not allude to the way of getting a meeting yesterday.
It felt to me that it would be shunning the cross not to meet as we did,
and as way seemed to be making for it by two or three being willing to sit with
us instead of going into the other saloon to what is called their service,
I felt constrained to it and M. R. and L. E. G. united that it would be well to do so.

19th.--This is a new experience, on board ship so many days,
and I do trust it will have been one of some new learning and increased trust,
showing at least cause for it, in Him, who has been my Preserver from my youth up,
and my heart has felt this morning a fresh spring
of gratitude for his condescending nearness to me,
as manifested in my inner man.
At the same time I have proof that I might rely more trustfully
than I do upon Him in times when the thoughts are overcome with
any sense of outward uncertainty of our position as to danger.
The time seems near for a careful watch to my steppings in the
"`new world,`" among I believe dear brethren and sisters,
and desire for me that I may be preserved from either
going before or staying behind our good Guide,
that so I may not miss of the reward,
and be favoured to return to you and you in the right time.

[.signed-section-signature]
J+++.+++ G. Sargent.

--

20th.--We moved into the dock early,
and landed it might be 9:30 a.m. Were truly welcomed by dear William Hodgson who met us.
We proceeded to Philadelphia and were met at the
depot by Joseph E. Maule and Solomon Lukens.
In the evening had a favoured opportunity at W. Hodgson`'s in company with W. H.,
his two daughters, +++[+++and several other friends.]
I had to speak to the goodness of the Lord that "`it is good to trust in the Lord.`"

21st.--We left by seven o`'clock train on our way to Scipio,
travelled through a wilderness country and reached Great Bend in the evening,
and there supped at a hotel.
After which we proceeded by train again for Owego arriving about ten p.m.

22nd.--We left Owego by six o`'clock train for Ithaca--a beautiful spot,
studded with houses, by lake Cayuga.
We had with us Mahlon S. Kirkbride of Fallsington and Sarah and Lucy Cadwallader,
mother and daughter, also of Fallsington, and found them agreeable Friends.
From Ithaca we went by steamboat on the lake to Aurora.
We were kindly met by James D. Otis with his conveyances and taken to his dwelling.
Here we feel to be among consistent Friends,
and feel unity with them in our mingling thus far
and I believe we shall continue to do so.
In the evening we gathered into stillness.
The words sprang up in my mind, "`Awake, psaltery and harp,
I myself will awake early,`" which I gave expression to, in the desire we might,
by doing our part,
prepare the way of the Lord for the tuning of our hearts to his praise,
querying was there not cause for this, the praising of the Lord,
who had wrought so marvellously for us all.

23rd.--The select Yearly Meeting was to be held this morning at Poplar Ridge.

24th, First-day.--Meeting at Poplar Ridge at ten o`'clock.
In the afternoon we met about four o`'clock,
in which I had again to stand and exhort to watchfulness on the right
hand and the left as with the tool in one hand and the weapon in the other,
in the view, as I expressed,
that our enemy like a roaring lion goes round about the righteous,
seeking whom he may devour.
It was with me to say on rising,
that the enemy lurks in secret places ready to draw into his net,
under the view I had of the need of watching on all hands;
as while openly engaged in the withstanding of the opposition in
the one direction he might be working to draw away in another,
though not openly.

25th.--Met this morning for the transaction of the discipline.
After a long pause preceding any engagement by the clerk and some preliminary matters,
J+++.+++ D. Otis opened to the meeting a concern he had for the prosperity of
the Truth that men and women Friends should sit together for the discipline,
and after much solid deliberation it was concluded to open the subject to women Friends.
Accordingly J. D. O. and another Friend went into their meeting and after their deliberating
thereon (men Friends waiting meanwhile) a woman Friend came in with the reply:
the shutters were then raised and we all sat together.
Before this, during our lengthened silence preceding any business.
I had risen and felt strengthened to encourage Friends in their waiting,
feeling that it was good so to do; my mind was instructed and I was comforted,
as I told them, in the belief they knew what they were waiting for.
What a contrast this afforded me to London Yearly Meeting.
It has felt altogether a strengthening time, and one I hope to remember for good.

27th, Fourth-day.--Meeting for worship this morning at eleven o`'clock.
My place seemed to be, to be silent.
A hard meeting it felt--no getting down to the savour of Life,
except towards the breaking up.
The afternoon sitting was at three o`'clock.
Epistles were read, including one to our Conference in England.
The meeting concluded under a feeling of the Lord`'s overshadowing
goodness and presence with us to our gratitude and praise.

28th.--We left J. D. Otis`' and our dear and kind friends there after a favoured time,
in which sitting we were helped to cast off what remained,
and my mind found relief in this opportunity in addressing the
young people as well as the company unitedly then present,
of which there were many.
We proceeded to Auburn, about twelve miles, to take train for Albany.

29th.--We left this morning for Philadelphia.
This has been a day of renewed extension of our heavenly Father`'s
care and regard over us for which my soul desires to be thankful.

31st.--To meeting at ten o`'clock.
My mind was soon introduced into feeling with the words "`Be clean,
you that bear the vessels of the Lord,`" and I opened my mouth thereon.

6th Month 2nd.--Went to Fallsington to attend the General Meeting for Pennsylvania.
It felt a time of favour in which I obtained relief to my mind.
The meeting closed well, being much favoured together,
and we parted in love and a feeling of much harmony.
Afterwards went to Benjamin Cadwallader`'s, a homely comfortable dwelling.
The salutation rested on my mind soon after entering, "`Peace be upon this house.`"
Great simplicity and consistency appears in the habitation of these dear Friends,
B+++.+++ and S. C., and comfort was felt with them.
A very comforting parting opportunity we had,
dear B. C. addressing each of us while standing together.

12th.--Returned to Philadelphia and left for Newport.

13th.--We arrived at Newport, Rhode Island, and went to Lydia A. Gould`'s,
sister to the late T. B. G. In the evening a number of Friends
gathered together and we had a favoured time.

14th.--We had a favoured meeting wherein I was helped to the relief of my mind,
reminding me there is One who is all-sufficient for us in
every place and for all He requires of us.

15th.--Two sittings today,
wherein I desired to be found faithful and was helped to be so,
to the obtaining of solid peace.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Newport, Rhode Island, 17th of 6th Month, 1868.

[.salutation]
My Very Dear Boy,

I have wished to write to you, and now take the pen to do so,
if only to let you know not one of you is forgotten by me;
you are all very precious in my feelings.
Not naturally only I trust are my feelings drawn forth for and towards you,
but I do desire your spiritual welfare.
This, my dear boy, is more than all, to be desired by you for yourselves,
as well as by me for you,
and that peace which surpasses everything that man can comprehend with his natural
understanding I do desire for you as well as (at all times) for myself.

Now in this tabernacle we behold things as they appear to the natural eye only,
unless our spiritual eye is opened by Him who only can open
and enable us to discern between thing and thing,
so as to give things their right names,
as Adam was enabled to do things in the outward creation.
Thus possessing the Truth for ourselves in dependence upon the Opener,
we are responsible for the Gift, to walk thereby, or answerably thereto,
and the Truth is precious to us,
and we are unwilling to part with it (if we keep dependent) for any outward thing.
Mind this, my precious boy, and it, the Truth,
will keep you and lead you onward in the begettings thereof, even in its own Life,
the precious life of Truth, which Truth begets in all who obey it.

5th day.--Again I take the pen to add a few lines.
We are still at Newport, and expect to go tomorrow morning on our way to Nantucket.
We have had a favoured time here.
I think much of you all,
and would set off at once to join you again gladly
if I knew I could find peace in so doing.

[.signed-section-closing]
With very dear love, I remain,

[.signed-section-closing]
Your very affectionate father,

[.signed-section-signature]
John G. Sargent.

--

18th.--The usual meeting for worship was held this morning--a relieving time.

19th.--Left Newport for Fall River; from there to Nantucket.

23rd.--To Hyannis by boat; from there to Providence and on the 25th to Philadelphia.

27th.--Rose early.
A low time, feeling my own weakness, enable me to govern my thoughts, O my God!

7th Month 1st.--To Bristol meeting, where was some tenderness, I believe,
felt in the bringing home of Truth to the heart and understanding.

2nd.--Left for Salem, Ohio.
The heat very intense.
Amy Albertson accompanies us on this journey.

5th.--Meeting here at eleven: only one held in the day.
"`Master, do You not care that we are perishing?`"
was brought to the view of my mind,
which I was enabled to cast off in this small gathering near the
close of the meeting and was helped with best help so to do;
the sense that He was Almighty,
and the knowledge of his willingness to help in the hour of need,
being present in my mind.

8th.--Went to meeting here, in which near the close,
I was engaged to the relief of my mind and peace therefrom.
"`Awake you that sleep,`" etc. in which I was sensible of help bestowed.

9th.--Left Salem, D. Koll and A. Albertson accompanying us for Ulysses,
in the State of New York.

10th.--At Ulysses.
How much cause we have for thankfulness of heart
for all our mercies and blessings of preservation.
It appears the thermometer hereabouts has been at 104° in the shade.
We travelled about 437 Miles from Salem to this place.

11th.--In the evening after supper +++[+++at the house of W. M.]
we had a favoured time together.
I was led to speak of Dathan and Abiram, and the earth swallowing them up;
how that there may be the like now spiritually, though not outwardly,
and that wonders and miracles are still known unto the living children of God;
with a caution lest there be a being swallowed up in the earth or becoming earthly,
desiring that it may be given to the faithful children to see how this applies inwardly,
and that these have to warn others.
Daniel Koll then followed in a somewhat similar manner +++[+++and]
in our walk back to Charles Owen`'s told me he had been
led to be faithful in this instance by my faithfulness,
and we were encouraged in our speaking together by the way.

12th.--To meeting at ten o`'clock, in a building used for a meetinghouse and school.
"`That which may be known of God is manifest within`"
was the engagement of my mind and spoken to.
A large company met and we were favoured in the afternoon.
I had to compare individuals to having each a little boat without any oars of our own,
and dependent upon the ability given to us to cross the ocean of life, and for help,
strength and vision to avoid the rocks and shoals hidden and seen,
on our way across to our desired haven of rest and peace.
Called after supper at +++_______+++. Felt it right to allude to Jesus
entering the temple and overthrowing the tables of the money changers
and driving out with a whip of small cords those that sold doves,
who made his Father`'s house, which is a house of prayer,
a den of thieves:--the heart is designed to be the temple of the
living God and we have to submit to the lashes and stripes,
for the driving out all that is unclean and unfit
for the abiding of the Lord in his temple.
Supplicated at the close that the Lord would unloose the bands of wickedness,
and let the oppressed go free.

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Ulysses, 12th of 7th Month, 1868.

[.salutation]
My Dear +++_______+++,

You have been, as well as all of you, much on my mind from time to time,
and had it not been that I knew you would share in
the general information I send weekly home,
I must have written to you.
I was much pleased to have your letter my dear boy,
and your feeling manifested therein drew you very close to my heart.

It has been very warm, the thermometer at 94° in the shade,
and even upwards in a few instances, when we were on our way, and in Ohio,
so that it felt very overpowering.
I never that I remember, experienced the like before.
We are now I think more used to it so as to bear it better, and it is not oppressive.
You would, I expect, have particulars of our travel to Salem, a small town,
many coloured people there.
Opposite the Friend`'s house where we were staying, there were old and young.
It is strange to us to see children of such, standing about in the streets.

Since writing the foregoing we have arrived at Jerome Hunt`'s near Bath,
about 48 miles from Ulysses.
We came six of us in two carriages, which took up the day, leaving about five a.m.,
resting from about twelve till four p.m.,
then travelling till about nine p.m. The carriages are very light with four narrow wheels,
but high, with two horses, pretty light also.
We have with us Daniel Koll, a German Friend, who came with us from Salem,
and Amy Albertson, from Philadelphia.
D+++.+++ K. is a pleasant and agreeable friend and companion in different ways,
and what is the most so to me is that he feels as a brother in the Lord,
faithful to what he apprehends his Divine Master requires of him,
which is strengthening and confirming to me;
he has more than once wished me when writing home to give his love.

O! my dear boy,
how great is the comfort and peace of mind we feel when
we believe the Lord accepts our endeavours to follow him,
which is to do or leave undone whatsoever we feel in our minds that He requires of us.
There is no peace like this and it is well worth our serving Him for,
were there no other object in it,
but we ought all of us younger and older to bear
in remembrance that it is not for our own enjoyment,
but for his glory and the doing his will that we have a being here.
I enjoy dear William Hodgson`'s company very much, he is to me as a brother beloved.

I hope you are steadily applying to business and doing your very best in the way of duty.
It seems as though I may be able to give some idea when to look for our return with this:
we desire to do what is right, and I trust may be directed in our return.
Did I not believe my remaining up to this time was right I would not have been here now,
but the affectionate part would have induced me to prefer my home,
though abundantly cared for every way,
and kind friends and kindred spirits to mingle with over here.

I was in the Broadway, New York,
for a short time on our way to Philadelphia from New England:
I could have supposed myself in a part of the _Rue de Rivoli,_ Paris.
Some would be much interested in being there, I cannot say this in particular of myself.
Whether Paris, New York, London or any other city or town, all seem nearly alike,
humanity moving up and down,
and it is to be feared a very small number of their population moving in the
Divine fear and minding the strivings of the heavenly Monitor within them,
in their hearts.

[.signed-section-closing]
With very dear love to you, my dear boy, I am

[.signed-section-closing]
Your very affectionate father,

[.signed-section-signature]
John G. Sargent.

--

13th.--Left Ulysses for Bath.

17th.--Travelled to Jesse McCarty`'s at Elklands,
which is situated on the Alleghany mountains.

18th.--Went to Silas McCarty`'s. Here I revived the language "`Strive to enter
in at the strait gate--strait is the gate and narrow is the way,`" etc.,
showing there must be a striving to enter in, and what the striving is--namely,
submission to the manifestations of the Divine will
and following the Saviour in his leadings, etc.

19th.--This morning Aaron McCarty came and sat with us during reading.
Afterwards I had to revive the language,
"`O that I may die the death of the righteous and that my latter end may be like his!`"--as
that such may spring from the heart and with it the sure evidence that in order to die
the death of the righteous we must live the life of the righteous,
listening to the voice of Him that speaks from Heaven, and be faithful to his leadings,
with more, to the relief of my mind.

21st.--Left early for Philadelphia.

22nd.--Attended Monthly Meeting here and came away with a relieved mind.

[.embedded-content-document.letter]
--

[.letter-heading]
From Daniel Koll.

[.signed-section-context-open]
Salem, 23rd 7th Month, 1868.

[.salutation]
My Dear Friend,

In that fire of love that Christ has kindled through mercy in our hearts,
to the purifying thereof, may we be favoured through obedience thereto,
to press forward in holiness.

Dear brother,
be not dismayed if through obedience to our dear Lord and Master Jesus Christ,
you should be brought before the council of them that sit, as it were in Moses`' seat,
and by them be delivered over to the judgment seat of the Gentiles,
and then should feel as if you were forsaken of them even,
who in times past had sat with you in solitary places.
O my dear friend,
may it then in mercy be brought to your remembrance
that the servant is not better than his Master,
who suffered abundantly more for us,
and that greater is He that is in us than he that is in the world.
He was never foiled in battle,
He is worthy to be trusted in and obeyed in all his requirings.
O that you and I may be favoured to keep in the patience of the saints,
waiting for that bread which the angel prepared over
the coals of fire for the prophet anciently;
whereby he lived many days.
Yes, this bread prepared by the fire of the Holy Spirit,
is the only bread that will strengthen us to hold on our way toward Zion and give us
the ability to call others to come and taste of it and see how good our Lord is.
O that we may through the operation of this holy fire,
be melted more and more in oneness, until we become one in our Lord and Saviour,
being thus prepared to enter into eternal rest, peace, joy, and glory.
Amen.

[.signed-section-closing]
Your sincere friend and brother,

[.signed-section-signature]
Daniel Koll.

--

24th.--Left Philadelphia for Nottingham, Maryland.

25th.--We made a call upon Eliza and Susan Kester.
After rather a long silence I revived the language--"`When I consider your heavens,
the work of your fingers, the moon and the stars which You have ordained,
Lord what is man that You are mindful of him,
or the son of man that You visit him,`" alluding to the consideration of the creation,
not the outward only, but that in the heart, and querying,
Is He in all our thoughts?--do we consider his ways?
and that it is his own works only that do praise Him.

26th.--+++[+++At]
meeting felt to draw the people to the place of true waiting, using the words,
"`Get down to where nothing is,`" (or similar) and was helped to my relief.

27th.--Had an opportunity at +++_______+++ +++_______+++`'s,
whose husband was present, not a member, I believe.
It felt given me to say,
"`Strange books and idle stories must be given up for more solid food to the mind,`"
and made allusion to there being no room for Christ in the inn,
but that he was laid in a manger--so there may be no room
for Him in the heart--it may be full of other guests.

29th.--Attended the meeting at Little Britain.
Was helped with strength to the relief of my mind.
Joseph E. Maule sounded an alarm,
"`Prepare to meet your God,`" and for this end to set the house in order.
It was with me also (the words coming intelligibly to my mind) when he took his seat,
to renew the same saying, for this end, or in order therefor,
"`Prepare to fear the Lord.`"
It felt solemn to take this up, but my mind was preceded with a calm,
and help for the occasion.

8th Month 1st.--In Philadelphia.

2nd, First-day.--To meeting here.
Was helped with a little portion for delivery in the meeting in the morning
and was strengthened to give up to bend the knee in that in the afternoon,
partly on behalf of those who go and of those who stay in
the prospect of our departure from them next Fourth-day.

5th.--We left W. Hodgson`'s for New York and Jersey City +++[+++in company with many friends.]
A parting opportunity was afforded at the hotel,
in which M. K. and J. W. offered prayer for our preservation across the deep.
We have indeed need to feel truly thankful for all the help vouchsafed
to us from day to day throughout our journey by sea and land,
no delay having arisen from illness or any other thing.

7th.--This day`'s watchword in the opening of Truth, I believe I may say,
has been,`"Avoid every appearance of evil,`" evil presenting itself in the mind,
in any of its appearances (of any kind).
O that I may learn thereby, and profit to my lasting benefit.

9th.--Had our meeting in my cabin.
Felt poverty within, under a sense of my need of best help always,
but a desire arose that the Sun of Righteousness may break
through the inward mist or covering of my mind.

13th.--I felt it right to remind some of my fellow
passengers of the lightness and mirth of some,
last evening, hearing their loud voices in the saloon,
and expressed my belief that the Witness must have condemned
them in their consciences if they looked within.
This afforded relief of mind and did not appear to give any offence, being done, I trust,
in godly fear and a desire to reach the Truth in them.
By watching for the opportunity in the course of a little
conversation which I endeavoured to encourage for this end,
I was enabled I trust, to take hold of the matter timely and to the purpose,
but whether fruit may appear therefrom in them must
be left to Him who knows the end from the beginning.

14th.--A boisterous sea last night; little or no sleep from the tossing of the ship,
but was preserved in quiet trust, and a feeling I believe that He does all things well,
and felt no fear.
Have not the prayers of our dear friends availed with Him who cares for us!
O that there may be increasing trust and renewed dedication to Him to whom I owe so much.

15th.--Arrived off Queenstown at about 9.15 a.m. A sense of Divine goodness has
I believe pervaded my mind and in our quiet time after reading this morning below,
I was led to commemorate in my inward habitation the goodness
and mercy of the Lord to us both by sea and land,
and gave expression thereto, acknowledging that we have one debt more due unto our God,
and desiring that we may pay it henceforth,
and abundantly utter the memory of his great goodness to us each one.

[.embedded-content-document.letter]
--

[.letter-heading]
To W. Hodgson.

[.signed-section-context-open]
Fritchley, 18th of 8th Month, 1868.

[.salutation]
My Dear Friend,

In a deep sense of the lovingkindness of our great Protector and keeper,
I can now inform you, with your dear daughters, and others,
our dear friends whom we have left, so far away as to the outward,
that we were favoured to reach land on Seventh-day evening, the fifteenth of this month,
after a fine passage across the Atlantic,
though attended for a short interval with a strong wind, and consequently heavy sea,
last Fifth-day night and part of Sixth-day.

Through it all, I can testify to a secret, supporting Power, enabling to feel no fear,
and an evidence within that his wondrous works within as without,
do declare that his name is great, to my admiration and rejoicing in heart;
while again and again I have had to realize that truthful language,
"`You will keep him in perfect peace whose mind is stayed on You,
because he trusts in You.`"
And while recording this, I feel bound to acknowledge my belief,
that the prayerful desires for us of our dear friends--you whom
we have left and those whom we have come back to--have availed
with Him who verily does condescend to hear our prayers,
and to enable to trust in Him, and stays the mind in time of need.

We were forty-one passengers in all, comparatively a small number;
no really congenial society on board,
and none that we could feel much openness with in conversation.
You will be able to form some idea of the comfort it afforded me,
when the steam tender came out to take us and our packages to land,
to see on board the handkerchiefs waving of some of my dearest
ties on earth--my dear wife and three of my family.
I need hardly pretend to describe my feelings or theirs.
They were soon up on the deck with us, and while rejoicing in the reality,
I trust thankfulness was the covering of the mind
to Him who had thus brought us together again,
and in as good, if not better health, than when we parted.

And while writing I am reminded how much is due to
my heavenly Benefactor for his immediate help,
from my going out to my coming in again; and of how great a debt is thereby incurred,
for which I am become responsible; and not only for spiritual benefits,
but also for so many temporal blessings,
and so great care bestowed in more than things needful, by my dear friends,
(brethren and sisters in the Lord) on your side the great deep.
Well, my dear friend,
it feels sealed to my mind that it was right and that the Lord did so direct
and order that we might meet! and I trust that his all-wise purpose may be answered;
but I feel I do need perhaps more than ever, the prayers of the Lord`'s people,
that my eye may be thoroughly anointed,
and my strength be made firm in the faith of the Gospel,
so that I may pass on unhurt by the things without,
and that the life may be strengthened and increase for the
accomplishing the Lord`'s whole will concerning me.

I omitted to number among those who met us at the steamer, Joseph Armfield,
who came on here with us.
On First-day evening our meeting was well attended, all our seats being occupied,
and it was a favoured time together.

[.signed-section-closing]
I am your sincerely obliged friend,

[.signed-section-signature]
John G. Sargent.

[.postscript]
====

P+++.+++ S.--While making allusion to the great kindness shown to me by my dear friends,
I desire to acknowledge it with thankfulness unto the Giver of all good,
as done by you all unto Him, who moves upon the hearts of each one of us,
as we yield unto his impressions,
and who opens a door in the heart one unto another where
and in whomsoever the true love of the Father exists.

[.signed-section-closing]
Farewell, my dear friend,

[.signed-section-signature]
J+++.+++ G. S.

====

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 2nd of 9th Month, 1868.

[.salutation]
My Dear Friend,

You have been with me in thought sometimes since
my return home with a desire to write to you.
Probably you have before this received some particulars of our return.
We were ten days on the water, a little rough and some foggy weather,
but the most part a fine passage.
We left many kind and dear friends behind... I do believe it would
do you good to mingle with these dear honest-hearted friends,
who are sincerely desirous of standing for the Truth without any compromise,
and their example therein is a stimulus to us to do likewise.
I felt William Hodgson as a brother in the best sense,
and do feel that if we had such near enough to us
to meet frequently it might be helpful to us,
while on the other hand,
we know it does not do to make our friends our props to lean upon.
Their consistency in the general is encouraging,
and the view of our state over here by comparison very weakly.
Yet there are there also different growths and some weaknesses,
we must suppose and believe too.
But if concerned to be faithful we may hope an increase will be known with them,
and we may hope with us also.

Since our return I felt my mind drawn to request
the Friends of Birmingham who meet in the Conferences,
to hold a meeting on last Fourth-day in the forenoon
instead of attending the usual meeting;
our friends M. E. and L. E. G. uniting therein,
which the Friends acceded to and we were much favoured together.
It felt well to invite Friends at the close of the meeting for
worship to the consideration of their meeting together for the
solemn purpose of worship apart from the usual meeting there,
and a desire attended my mind that that meeting which we felt to
be owned in no small degree by the Master Himself in our midst,
might be as a link in a chain not to be dropped.

O! that we may each and all who have been accustomed to meet together hitherto,
feel after the pure mind of Truth in our own particulars
to know for ourselves what is our duty to do.
For does not our good Master call for greater allegiance than has been manifested by us,
even a firm stand for his holy Name to walk by.
Have we not gone on long enough in the name of a Society which
has very much if not altogether lost its savour as to what it was,
and is it not time for individuals to feel after that they may know the pureness of
Truth in themselves and into what it leads those who are given up singly to it.
It is no fable that a manifestation thereof or of
the Spirit is given to us to profit withal,
but we believe there is a vitality in it and some of us know it,
but if its manifestations are made subject by ourselves, to our own reasoning or policy,
imagining we can steer the ship, whereas the heavenly Pilot alone can do it,
we shall still go on in the way we have been going, and so remain in weakness,
unskillful and unable to hold up the standard to the people,
being one with them in the mixture.
I did not think of writing so much or in such a way when I took the pen,
but as matter has come so I give it to you and trust it will be received in the
love in which it seems to spring forth from the heart to the guiding of the pen.
In a feeling of weakness, I remain

[.signed-section-closing]
Your friend sincerely,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 18th of 10th Month, 1868.

[.salutation]
My Dear Friend,

I have this morning received your welcome and very acceptable letter,
as well as one from our dear friend J. E. M., also very cheering to us.
It does seem to lay increased responsibility upon us having thus
been brought into the way of increased help by an acquaintance
with you our dear friends on the other side the ocean,
whose unity with us and encouragement to go forward is strengthening;
may we make good use thereof.

Our Conference meeting has been held in London as appointed.
The morning of the day we left for London we had by previous appointment,
a visit from six of the Quarterly Meeting`'s Committee to breakfast with us.
We did not feel otherwise minded in the matter than to receive them hospitably
and not to enter unbidden upon that which they ought (were they qualified
by the Master) to have entered upon with me or us;
but much to our surprise they kept silence as to anything that
could indicate their being with us upon any appointment whatever,
not making any allusion to my late visit to you, nor the state of Society.
We endeavoured I trust, to know and keep our places.
Four of the six wore no appearance of Friends.

After breakfast, and without any previous knowledge or choice,
I read the chapter which came pretty directly to view on opening the book,
which was the xvi chap, of Isaiah,
and it did seem to me as though in this case they
could not "`bark`" or were restrained therefrom.
Surely, are they not "`blind watchmen, ignorant,
and shepherds (if shepherds at all) that can not understand?`"
There was a very short pause,
the woman knelt almost directly and the rest of their company stood.
We all kept our seats and feeling nothing required we soon dispersed,
it being time for them to leave us on their way to the Monthly meeting.

We felt peaceful in the retrospect and proceeded on our way to London in the afternoon.
Our first Conference sitting (for worship) was a laborious time; the Well seemed stopped,
no springing up of life till near the close,
when it was known that all good was not entirely gone.
It seemed to me there was a cause; something had crept in to hinder, yes,
there was something thrown into the minds of some present by the enemy of all good,
and then how hard to get along,
as it proved to be all through till nigh the end of our last sitting, (there were four).
Then life did arise and spread over us to the comforting of some of our hearts,
and to encourage us in the sensible experience that we were not forsaken;
but it has felt to be the most trying time we have had since we first met in this way.

We were favoured with help I believe I may say (the three who visited your land)
to give in a little account of the merciful help every way bestowed,
on our way out, while with you,
and returning home--calling for gratitude and praise unto
Him who had helped us and opened the way for us so remarkably
in the hearts of our friends among whom we have moved.
Then came the subject of the Epistles brought from you, the Yearly and General Meetings.
It was concluded to read them,
though not without a query as to whether they should not be first
taken out of the meeting to be read by a nomination to do so,
but this was dispensed with,
and our dear friends on your side should know that
encouragement was felt to come thereby and comfort,
though this with opposition too, yet kept under.
The subject of replies is deferred.

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 29th of 12th Month, 1868.

[.salutation]
My Dear Friend,

We are as a Conference in a trying position now;
and the foundation of some among us is being tried it may be to the very bottom,
and the sifting may even have the effect of separating those that were separated already
(but not wholly it will appear if this be the case) from the mass of confusion and delusion.
Our next Conference, now very near,
is not looked forward to with that feeling we once had,
when looking towards these meetings; some of us going before,
and those that thought they were first now being last, leads into troubles,
but not inward trouble,
nor a disturbing of that which is not to be disturbed and is immovable,
only of that which cannot abide the fire.
My remarks at our last Conference with reference to our holding offices under the old
organization seemed to cause some difficulty and I suppose of course non-concurrence.

No doubt you are right in your conclusions that when a decided
step or stand comes to be taken that some will drop away from us,
and this I think we may expect, though as yet it has not appeared;
but we have only had one Conference since the stand we have taken.
Some are not yet prepared in their homes to make such renovation and cleansing as to
be prepared for a forsaking of that which is unclean or in the mixture without,
and are not yet free from the trammels of men,
the honour and friendship of those they have hitherto
been with and been honoured if not flattered by;
but you have known what this means,
having been partakers in the sufferings occasioned thereby.
And yet I believe when this has been patiently endured,
how great must be the crown and rejoicing wrought out in
the willingness to give up all these and other trammels,
and to follow Christ as He now appears to each one of us for our restoration
from the fall and out of all that would hold us in bondage.

We do some of us see the unsubstantial nature of their position and their entanglement,
and I trust it will not move us who have made a stand, any one of us,
though our number is very few;
but I apprehend we do find there is a fastness of hold in thus having done,
beholding as it seems to me we do, the goodness there is in it,
the firmness there is by it;
and that we see more clearly what they are in who yet remain where we were,
mixed up (though in a measure only) with those who do not
seem even to desire to take flight out of Egypt.
I have received +++[+++several letters from our dear friends]
all very acceptable to us, and bringing fresh responsibility with them,
for all good springs from one Source, the Source of all good,
and his instruments love one another.
May this continue and abound, and it will do so, if our love for Him does so.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 28th of 1st Month, 1869.

[.salutation]
My Dear Friend,

I expect our dear friend L. E. Gilkes gave you very full
particulars of what took place +++[+++at our late Conference]
and no doubt would convey the feeling of sorrow that must more or less attend
the minds of those who are brought into suffering on Truth`'s account.
This I may say has been our experience.
We have had to partake of that cup which has never I think,
been quite so bitter to the taste before at any of these meetings,
arising from a more full and open exposure of what was in man,
even in some attending these sittings,
but the Lord was near to help and preserve from answering
again in that spirit which can never build,
but must lay waste as it is cherished or given way to.

Our first sitting (the meeting for worship) I can say felt to be a favoured time,
which the Master owned with his presence to a feeling of gratitude and praise,
and strength was renewed,
but matters afterwards did not move on as would have been a comfort to us.
The subject of answering the Epistles from our dear
friends on your side came again before us,
and it was plain that there existed the same impediment to its being done as before,
and this with comparatively a few, nevertheless they were of the most active among us.
These urge that there are others besides you holding sound views on your side,
and that if we addressed you,
it would be a declaration in favour of you (the Friends
whom we visited) to the exclusion of the others,
which they are not satisfied to do from the circumstance of our visiting you,
or from our report.
I believe we did, each of us who were led to you, clear our minds at this Conference,
as well as at the preceding one.

Those who now meet or sit apart from the old organized meetings are only seven;
one at Birmingham, one at Bakewell (and attenders sometimes) and five at Fritchley.
It is a solemn consideration, but I can say, faith is not shaken,
the future as well as the present is the Lord`'s and to
do his will only is the prevailing and I trust only desire,
and that we maybe found in Him and with Him through all that may be allotted to us.
The copy of the minutes made at the Conference in the 10th month,
expressive of gratitude, etc.,
in the reading of the Epistles among us will I expect reach you before long.
It did not seem that anything more could be done
by the Conference with any degree of harmony;
there was not a preparation in the minds of those there, for doing more;
though the manifested opposition was chiefly by three or four, I might say three;
two spoke of leaving the meeting,
and had the same spirit been manifested (which indeed felt to be a wrong spirit)
on the part of some of us who were for feeling after a different course,
it would have been painful indeed, not in suffering for well doing, but the reverse,
for not keeping in subjection to the Spirit of Truth in our hearts.

What may yet appear we do not know, but if faithful and low in our minds,
I trust and believe we shall know that peace which makes up for
all that we have gone through and may yet have to go through.
We are feeling, I think,
more than hitherto we have done how few we are who are walking in this way,
of withdrawing from the multitude,
but I trust we may be accounted worthy to hold up the standard,
and it may be others will join us, but whether or no,
if peace and the owning Power accompanies, we need not fear.
But until tried we do not know the degree of our faith;
and we need indeed to be prayerful that it fail not.

Yesterday was held our little Monthly Meeting here at Fritchley,
which we feel we can say, with thankfulness, I trust, was owned of the Master.
We sat on for a time after the meeting for worship broke up,
and ability was given to propose for the consideration and feeling of Friends,
our holding a similar meeting next month, which is concluded upon if permitted.
After deliberating on this subject our friend L. E. Gilkes laid before
us a concern that had rested on her mind to visit the people of this village,
which she was encouraged to go forward with in the ability given.
Thus we know not what a day will bring forth.
The way not only for our egress from the old organization has been made thus far for us,
but a way before unopened is gradually and step by step opening,
so that we feel I think I might say something of an awe in the sense thereof,
attended with thankful hearts.

And gratitude also arises in the feeling that we are not alone,
but that we have dear friends in unity with us on your side the great water,
who now seem brought so near to us.
May we be strengthened and with you seek an establishment on that Rock which is immovable.
Thus you may see a door has opened for us at a time when,
if the Lord had not been on our side, we had been altogether foiled and scattered,
so marked has been and is the division among some of us who attend the Conference meetings.
So another of your dear relations is gone: another warning to us among many more,
that we be ready.
May you all hold comfort in the belief that it is well with him: no more sorrow,
no more anxiety, no more uncertainty,
but that certainty and that security which is of and in the Truth.

[.signed-section-closing]
I remain your nearly united friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Lille, 29th of 3rd Month, 1869.

I am hoping to be at Croydon this day week if so permitted: do not see what time,
nor whether First-day can be spent in England,
but if permitted to enjoy a goodly portion of the good Presence in waiting upon
Him who is the true joy of the whole earth when He is found (as was my experience
yesterday when sitting in my temporary chamber) it does not really matter where,
though we like to be with our companions in this pilgrimage travel;
but I am more and more convinced that we must not depend
one upon another if we will find Him who is the truly Beloved,
and a privilege it is indeed to sit under our own vine and fig tree and know
his coming in to our souls with that consolation which strengthens for the warfare.

If we (the little band) keep this in view, that He will be with us,
as with the twelve disciples of old, we need not fear because of our smallness in number,
nor smallness in strength according to our own view,
for the Lord will have faithful hearts,
and the true worship which He said should be neither
in that mountain nor in Jerusalem as it then was,
but each one must be a worshipper in spirit and in truth;
this then may be verified by us who see and feel that desolation has overtaken Israel
and that the abomination thereof stands in the holy place where it should not.
So let each one be encouraged, and others too may be encouraged by us,
to come up to the mountain of his holiness where is neither strife nor contention,
but peace and thankfulness of heart before Him,
who is known by waiting upon and for Him to be the joy of the whole earth;
who is like unto Him?

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James D. Otis.^
footnote:[A worthy Elder of New York Yearly Meeting,
who bore a faithful testimony against the innovations of our day.]

[.signed-section-context-open]
Fritchley, 6th of 5th Month, 1869.

[.salutation]
My Dear Friend,

We have been holding our little Monthly Meeting today here,
and have felt strengthened to take another step,
as we believe in a forward direction--believing it to be consistent with
the mind of Truth that we should at such seasons make a record of Truth`'s
leadings and our movings along in the apprehended line thereof.
I enclose with this, minutes of this day`'s meeting,
(the first made by us) which it seems well to transmit
to you as Clerk of the Yearly Meeting,
to be held at Poplar Ridge (as we suppose), this month,
for the judgment of Friends as to the reading of them among you

[.signed-section-signature]
John G. Sargent.

--

The following is a copy of the minutes referred to:--

[.embedded-content-document.minute]
--

At a Meeting held at Fritchley at the close of one for worship, the 6th of 5th month,
1869, it was felt to be the judgement of Truth, that a book of record should be kept,
and that record should be made at these meetings,
(this being the fifth that has been held for the last five
months after this manner alternately at Fritchley,
Bakewell and Monsal Dale), of what may be deemed right to commemorate,
of the Lord`'s dealings with us, or of our proceedings,
with a view to his honour and his praise in the earth.

2nd Minute.--A concern has been expressed at this meeting that our feelings of
sympathy and love should be cherished for our dear American friends who,
in connection with their nearly approaching assemblies,
and the visits paid to them last year by some of our number,
have been afresh brought to our remembrance,
with a thankful sense of the many favours then partaken of,
and desires for the preservation of our dear friends,
and their steadfast walking in the Truth; for the upholding of which,
in its ancient purity and simplicity, a testimony is borne by them in that land.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 25th of 7th Month, 1869.

[.salutation]
My Dear Friend,

My mind turns towards you and other dear friends whom we visited last year.
I can truly say my mind is with you in brotherly love as much as ever it was,
perhaps I might say more so.
And in this precious feeling I can and do wish you Godspeed
on your way in the pure and unchangeable Truth.
Since writing to you I have received an acceptable letter from you,
with other letters from some of our dear friends on your side very acceptable,
reminding us,
as I verily believe of the true meaning of the words of our Lord at a former time,
"`One is your Master, even Christ, and all you are brethren.`"

I am thinking you and perhaps others may be looking for some particulars of our
late Conference Meeting held at Chesterfield on the 8th and 99th of this month.
I feel that such remarks as I have to make thereon,
preponderate by far on the side of conflict,
nevertheless I can say a sense of the Divine Presence and owning was graciously vouchsafed,
and ability was known to fight for the precious banner of
Truth that it may be more and more exalted among us,
even among those who have thus met together.

There was not a multiplicity of subjects to come before us,
but there seemed a need to contend for the faith.
A correspondence has been going on with one or more of the Friends in Sydney.
There were some remarks respecting our manner of dress as querying the propriety of it.
The reading of one of these letters caused a heavy exercise to
fall upon me (from remarks then made by two individuals with us),
to stand for the testimony, which is one of peculiarity,
become so through the customs of the people which are changeable and vain,
leaving Friends marked and singular, which undoubtedly, as regards them,
is a safeguard and strengthener; this is my conviction,
for I again and again prove that what is done for
Truth`'s sake brings peace and strength with it.

We were but a small number at the meeting.
The question was mooted by the clerk whether another Conference should be held;
it did not feel to be our place to stop the holding of them,
but it did feel the continuance of them hangs upon a slender thread.
The next was concluded to be held at Birmingham, in the 10th month.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 13th of 11th Month, 1869.

[.salutation]
My Dear Friend,

I noticed your remarks in answer to my request which do not convince me.
The grievance I feel lies with a few individuals
who are sore at our having taken steps without them.
Our steppings were in accordance with a feeling of what was right for us;
we hold no bitter feelings against our friends, but of this,
it seems we cannot convince them.
Again and again there have been endeavours in our
Conference meetings to convince them but not effectually.
I do not see that we can satisfy them without going
back to them and walking in their line of things,
and so turn our backs, when we feel strengthened in the way we have taken.

When our friends give up judging us for this thing
then there will be I believe a very different feeling.
We cannot take to ourselves the judgment they put upon us for lack of
appreciating our endeavours to be found giving heed to the Master`'s call.
But I do not wish to put any gloss upon our endeavours.
I believe the pure Witness in the hearts of our friends will convince
them we are striving to serve the Lord in our day and generation,
and we must all be accountable to our Heavenly Master, and to Him either stand or fall.
Let us strive therefore to stand, and He will give us all,
abundance of peace which will be serviceable to the preventing of jarring
one with another and bring others of our friends to a more decided stand,
to be one thing or the other and not middle men.

I hope when you have opportunity, you will come and see us.
We are still pleased to see our friends and can shake by the hand
any of those who have been accustomed to meet with us,
wishing them well.

[.signed-section-closing]
With love, your friend sincerely,

[.signed-section-signature]
John G. Sargent.

--

1869+++.+++ 11th Month 14th.--Was helped in meeting; felt constrained to declare that a busy,
active mind finds it hard work to get into stillness inwardly,
yet that it is attainable by waiting for it and wrestling with the ability given,
even as through a night and unto the break of day,
as did the patriarch of old:--alluded to his leaning upon his staff as typical of our
leaning upon the Lord as our staff and worshipping Him when thus met together.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 25th of 11th Month, 1869.

[.salutation]
My Dear Friend,

It has been gratifying to us and cause for thankfulness that our two dear
friends D. Koll and M. S. Kirkbride have been safely wafted over the Atlantic,
and we trust both have reached their homes in safety.
It was a comfort to us to have them with us at the time they were here,
in particular at the Conference meeting, where we had a proving time to go through,
of a sort unknown to us before, and now we feel a little company indeed;
but if the Master be with us, it matters not who is against us.
We feel little and in need of that strength which comes from above;
a day at a time seems enough, but help has been vouchsafed,
and we may trust I believe for more.

Those we have parted from, or who have shown themselves against us, were not our helpers,
so we have not to regret on our account, the discontinuance of the Conference meetings.
It is comforting to know of the exercise of the brethren
on your side for the welfare of Zion;
may they be encouraged to labour in the ability afforded, and may you, my dear friend,
be refreshed and animated by beholding the good that is stirring,
and be enabled to rejoice and praise the Lord in
the knowledge of fruit being brought forth,
answerable to the travail of your soul for the good of Israel.

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John F. Marsh.

[.signed-section-context-open]
Fritchley, 28th of 11th Month, 1869.

[.salutation]
My Beloved Friend,

A feeling of love this evening flows through my mind towards you
and your dear wife with a desire to communicate as much to you,
for it is long since anything passed from either side the one to the other,
and it may not be for the best altogether to keep silence.
And why should we?
Does not the same love one toward the other still exist?
I trust it does, and that we may believe it,
though it may seem almost as though we were severed,
because in obedience to apprehended duty some have gone somewhat out of
the track which the rest seem to believe they are not called out of.
But this need not diminish our true love one for another,
but in serving the Master we may each one rejoice, and we do rejoice when serving him,
though no man know it,
but I incline to believe that neither you nor we can truly serve
Him without something thereof being known to each other.
Love will bound forth in its springings up and aboundings in us.

Well my dear friends you know, I expect,
that here we have (in Derbyshire) our little Monthly Meetings.
These are a help to us and cause for thankfulness that we are therein
helped by Him who knows the heart of every one of us,
and how greatly do we desire that more of our dear friends whom we love,
felt they could comfortably meet with us.. But this we can leave with the Master
and trust He will add to us according as there is a preparation for it.
We have not as yet seen or felt anything of a condemnatory nature,
but peace in the step taken, of getting out of the mist,
a little further up out of that which beclouds, and is a very strong opponent,
that of reason,
or of suggestions that would huddle up together all of the
same profession though not walking after the same rule,
nor minding the same thing, the Lord`'s inward pointings,
the sure unerring Guide which so many in the Society, more than ever no doubt,
now set at nought.

And have they not, my beloved friend,
been going further and further from the safe Guide these years past?
And have not many been kept back by them,
who might have clean escaped the snare had they not hearkened
to the plausible baits that have been held out to them?
And so the eye has become dimmed and some things that once looked as they really are,
in their true colours, now seem very much reconciled and pass almost if not quite,
as the King`'s coin, whereas it is only forged.

We are all favoured with our usual health, and hope this is your experience,
but years pass over us and we are reminded that the poor tabernacle must be laid down,
and O, that the day`'s work may keep pace with the day and that the answer may be,
"`Well done, good and faithful servant!`" this I can desire truly for you and ourselves.
With very dear love to you both in that which remains forever, I trust I can say,

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

12th Month 7th.--Our two friends William C. Meader and James D. Otis arrived at Liverpool,
where I met them and brought them to Fritchley.

18th.--I accompanied W. C. M. and J. D. O. to Middlesboro to +++_______+++`'s
where we met with much openness from himself and wife.
Felt poor and stripped in mind but was helped through.
W+++.+++ C. M. was opened pretty largely in our sitting with them.

20th.--We left Middlesboro for Wyersdale to visit Abraham Kelsall, wife and family.
Met with a comfortable reception.

21st.--Expected to leave here this morning for Fleetwood but W. C. M.`'s mind
was drawn to invite the neighbours to come and sit with us this evening.
Have felt very poor and sometimes much as though stripped of all that is good.
I trust it is in the all-wise dispensation of unerring Goodness.
I feel as that it may be a weaning of my mind and heart from earth, more and more.
A new dispensation it feels to me.
The meeting in the evening was well attended, perhaps thirty persons being present;
a favoured opportunity.
W+++.+++ C. M. was largely engaged and deep attention given;
it closed after a quiet time of silence, to satisfaction.

22nd.--Left A. K.`'s this morning.
After breakfast, in a favoured time, reading being over,
my mind was accosted with the words,
"`I counsel you to buy of me gold that you may be rich,`" which I gave expression to,
to the relief of my mind, with some addition,
which I believe was to the tendering of the minds of some of the family.
Arrived at Fleetwood and were met at the station by Thomas Drewry.

23rd.--Accompanied by T. D. we walked to Thornton to call upon an aged friend,
John Hornby, who gave us a true welcome.
We were drawn into silence; my mind was accosted with what Elisha said to Elijah,
"`My father, my father, the chariot of Israel,
and the horsemen thereof,`" which I expressed,
with the belief that he would soon be gathered to his everlasting rest.
W+++.+++ C. M. addressed him at some length.
It was a feeling opportunity.
We went forward to John Walsh`'s, a farmer;
here we dropped into silence and I had to give expression to words to this effect,
that the meekness and lowliness of the Lamb is portrayed in his followers and
that none are his followers but those that are in the true meekness and lowliness.
T+++.+++ Drewry accompanied us to Preston; here we called upon John Toulmin,
who with his daughter, received us kindly; he gave us a true welcome.
We took tea at William Clemesha`'s; he manifested true kindness and before we left,
he showed openness of heart and mind towards us.

24th.--Went to Mary Buckley`'s (at Manchester) who seemed pleased to have our company;
had an opportunity before leaving, and utterance to relief was given.
Reached home tonight.

27th.--Left home in company with W. C. M. and J. D. O. for Birmingham.
To William Graham`'s this evening.
W+++.+++ C. M. was engaged after tea at some length,
and I felt called upon to address those of this house,
exhorting them to come out from that which is, in my mind,
comparable to a city of confusion and desolation, wherein,
though there may be many more righteous than there were in Sodom when Lot was drawn out,
I believed the solemn call was to them to come out.
It felt with me to lay before them the solemn responsibility
they were under on this account.
How it was received in their hearts must be left,
but my mind was relieved of a weight thereby.

28th.--Went this morning to breakfast at William
Watkins`'. W. C. M. was helped in his testimony.
Had a refreshing call upon Thomas Tinnion and wife.
Left for London.

29th.--Held a meeting this morning at Joseph Armfield`'s.
Horatio Blake and Julia Armfield sat with us.
A time in which was found strength and utterance.
In the afternoon we went to Croydon to J. F. Marsh`'s.

30th.--After breakfast this morning and a long travail of spirit as it seemed,
dear W. C. M. spoke at considerable length,
and way appeared to be made in the hearts of our dear friends to
receive our two American Friends in the way of their coming.
Last evening my mouth only was opened in our sitting--that the
blessed of the Lord are those who are reviled and against whom
wrong things are said falsely for his great Name`'s sake.
This morning I trust help came to wind up to our comfort.

We left Croydon for Dorking,
I believe with peaceful minds and met with a truly
cordial welcome from George and Sarah Hayman.
Sat awhile with dear Elizabeth Dale which was a comfort.
Encouragement flowed forth to her from W. C. M. and myself.
Had a refreshing call at John and Ann Marsh`'s; a comforting reception,
and entrance found for the living thing.
Called at William Bennett`'s; I trust good prevailed.
Went to the Holmwood, to G. and S. Hayman`'s to lodge: an abode, to us,
of peace and comfort with much openness.

31st.--Returned to London,
and held a meeting this evening at J. Armfield`'s. Some
young men who attend Peel meeting were present by invitation.

1870+++.+++ 1st Month.--About the end of this month,
I was taken ill with a carbuncle at the back of my head;
was laid by with it for between two and three months.
It was a time of Divine favour, in which mercy was displayed to me,
and the lovingkindness of my heavenly Father was greatly manifest,
and his overshadowings were eminently sensible to me.
May I live to His praise who thus raised me up and
may I be more and more dedicated to His service.

Returning home from a business journey to the continent he writes,

6th Month 29th.--To London this morning and attended the little
meeting at +++_______+++ +++_______+++`'s where I found three assembled.
Laboured for a little bread which strengthened the inner man and was favoured with help
to administer some encouragement to the waiters upon the great Giver thereof.

10th Month 22nd.--Left home on my business journey to Ireland.

23rd.--Dublin.
Sat down to hold my meeting in my bedroom,
and was favoured with peace in wrestling for the blessing,
and the comforting assurance was given me,
"`You will keep him in perfect peace whose mind is stayed on You,
because he trusts in You.`"
I went after this to Henry and Abigail O`'Neill`'s.
Way was not made to hold a sitting in the afternoon,
but we had some comfortable conversation and I was satisfied in going.
Some young men were named to me, living in Dublin,
as holding the ancient views or not advocating the modern ones; these,
my lot was to meet in the evening,
and opportunity was afforded me to converse and explain
my views and those of the dear Friends walking with me,
as to our non-compromising the precious way of Truth by joining in with or handling
the changed discipline of the Society as now maintained by London or Dublin Yearly Meetings.
In a quiet time before leaving these young people,
in which a holy quiet not at our command, was brought over us,
I had to revive the passage of Scripture, "`Take off your shoes from off your feet,
for the ground whereon you stand is holy ground,`" signifying that nothing of our own,
or of ourselves, must be stood in,
or maintained for the furtherance of the cause of Truth, or to that effect.

26th.--Portadown.
Went to Charles and Ann Wakefield`'s to breakfast, and was very cordially welcomed.
Was engaged after reading with the opening upon what had been read by A. W.,
"`except your righteousness exceed the righteousness of the Scribes and Pharisees:`"
I was much impressed that the "`exceeding`" must be in the inward not in the outward,
and that first must be made clean the inside of the cup
and platter and then the outside will be clean also;
was strengthened thereon.

28th.--Returned to Belfast.

29th.--Much conflict seemed to take hold of my mind while on my bed this morning
as to the way to proceed homewards accompanied with a desire to be permitted
to go in the way of the Divine will and to be found in my right place tomorrow,
First-day, whether in Dublin, in Fleetwood or Belfast;
and while in this state it quietly opened in my mind to be still, not striving of myself,
and in this quietness Glasgow opened to me.
How useless and unavailing if I would be directed is my own toiling and planning!
O! that I may rest on the heavenly oars of faith,
and trust that I may be guided and know heavenly Wisdom in all my paths.
This is renewed bought experience that is good indeed to be remembered.
I accordingly went by Glasgow boat and arrived safely and peacefully.
Went to William Smeal`'s. W. S. and wife from home,
breakfasted with William Jr. and his sister.
Had my meeting in their sitting room,
they not wishing to sit with me or not putting forward to do so, which I could not,
expect they would.
Dined at Robert Smeal`'s.

[.embedded-content-document.letter]
--

[.letter-heading]
To Peleg Mitchell.^
footnote:[Peleg Mitchell was an esteemed member and elder
of Nantucket Monthly Meeting of the Society of Friends.
He was favoured in childhood with the care and training of religiously concerned parents,
and later in life, he often spoke of this as a great blessing.
When arrived at mature age, the principles of Friend, in which he had been educated,
became his own by convincement and adoption.
He was subjected to many trials,
by the diversity of views introduced at various times
into our once highly-favoured Society;
many of these being as he believed, subversive of the true and living faith.
He remained steadfast to the original principles of Friends throughout his long life,
without turning to the right hand or to the left.
He was often heard to say "`Quakerism is the same today that it
was two hundred years ago--primitive Christianity revived,
without abatement or compromise.`"
His exercise was great for the preservation of a remnant,
and his faith strong that there would be one left to uphold the ancient standard.
He died at his residence, Nantucket, Massachusetts, U.S.+++,+++
on the 1st of 8th Month, 1882, aged 80 years.]

[.signed-section-context-open]
Fritchley, 27th of 8th Month, 1870.

[.salutation]
My Dear Friend,

It is very pleasant to see again your handwriting.
I believe that communication in this way does tend
to the stirring up of the pure Life within us,
when it springs from the right ground.
Yes, it quickens and increases that bond of union in the fellowship
of the Gospel of Christ which the brethren and children of the
same Lord and Master do feel so cementing and strengthening,
the fellowship which is in the Truth.
I can quite comprehend your feeling of being oftentimes
incapacitated for doing more than must be done,
and this is not likely to diminish with you or such as have attained to your age.
But I can verily believe the Truth is very dear to you and this +++[+++love]
I believe will not diminish, though not so often, it may be,
expressed in the way of letter-writing.

It is a comfort to know that it was a memorable time, your last Annual Meeting,
and I trust there will be from time to time that
drawing nigh to the Fountain of all our strength,
as that it may be again and again experienced that
the good hand of our God is with you of a truth.
And though you may not, nor I, live to see many years of prosperity in the land,
yet we may, and I believe you do,
earnestly desire that the younger generation may witness that there is a going
forward and adding to the number as well as a growth in the Truth.

It is comforting to contemplate and think of all
the dear friends whom I know on your side the water,
or any where who are treading or endeavouring to
be found walking with the Master wherever He leads,
and I desire to be one with you.
Surely it must be in a great measure for lack of knowing
the preciousness of the truth as it is in Jesus,
who is Lord and Master,
that so few comparatively either come to our solemn feasts
or seem to be able to handle the bow to the honour thereof.
Yet, as surely, may we not believe,
that if obedience were yielded to the manifestations of the true Teacher,
there would come therewith, even in the obedience, a true knowledge of Him,
so as to be enamoured with Him, and a desire to know Him more and more.

Our band is a little one,
though we do know that the Lord of the harvest can
raise up more labourers into his harvest.
What a melancholy state of things abroad, the war raging between the two countries,
thousands falling by the sword and when it will end, or how, we know not!
It depicts, to my mind, the antichristian state of mankind in these nations.
The French nation seems to be one very void, in the general, of religion,
and those (of it) who make the most appearance as
to religion or what would be called religious observations,
are in fetters to the priests.

I will now bid you farewell and am affectionately,
your very nearly united friend in the best of bonds,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Peleg Mitchell.

[.signed-section-context-open]
Fritchley, 15th of 5th Month, 1871.

[.salutation]
My Dear Friend,

I recur with interest to the time when we met.
Much has transpired since then, much to remind us that we have no continuing city here,
and enough truly to incite to seek more earnestly, as we advance on our pilgrimage,
one to come, whose maker and builder is God.
We have to bear in mind, for a little allowable help to the tribulated mind,
that others have and do pass through a tribulated
path to the blessedness of the everlasting rest,
which may indeed be abundantly testified of, +++[+++as being]
joy and peace in the Holy Spirit.

With this I send you the Epistle from our General Meeting.
We are but a poor people, few in number,
but as the Lord`'s power may be magnified in the few as in the many,
we may I believe be incited to trust that He who does all things well,
will work to the promotion of his own glory, and in whomsoever He may please;
while we would not judge those who are not called to the path we walk in,
but leave judgment to Him who judges rightly.
I believe it can be said of a truth the Lord did own us
together by the manifestation of Himself among us,
and that we have need to be thankful and encouraged thereby, and you too, dear friends;
for the outward separation does not obstruct his blessed appearance
among all those who meet together in desire to be found where He
would have us to be whether in your land or ours.

We have been informed of the decease of a dear friend on
your side the water S. J. G. Her loss is to be felt,
but all that are gathered home into the arms of everlasting
mercy there is cause to rejoice for,
and not to mourn, striving ourselves also that we may be so gathered,
and that nothing by us may be lost to others, during our stay here,
but that we may be enabled to war a good warfare and that others seeing
and feeling the earnestness of our spirits may also follow on and gain
a crown of righteousness and everlasting glory that fades not away.

[.signed-section-closing]
Your friend in the love of the Truth,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James D. Otis.

[.signed-section-context-open]
Fritchley, 18th of 8th Month, 1871.

[.salutation]
Dear Friend,

We are favoured from time to time, I believe I can truly say,
with a little renewed evidence that it is good to have come away from
that which is changed--and I trust we shall continue so to feel,
and with you grow stronger and stronger,
as there is no lending of the hand to that which hinders our progress heavenward,
under the holy banner of Truth and the unchangeable Name of Him who is the Truth.
We had a visit awhile back from a committee or part of one,
(for some did not come) appointed by the Quarterly Meeting to visit us; why,
you may suppose--on the ground of our non-attendance of their meetings,
the marriages +++[+++at our meetings] etc.
Their visit +++[+++was]
a superficial one--no going down by them to the root of the matter,
neither did they want to know much of that which
we felt constrained to give them from the bottom,
for we felt we had not to do with the surface of the matter,
but to go down where the complaint they came with, had its rise.

O how beautiful (and how goodly) are your tents, O Jacob, and your tabernacles O Israel!
This can be said in our day, for there is a people who are serving the Lord,
and these are goodly indeed to look upon with the spiritual eye--may all such be preserved,
(and will they not?) as the apple of His eye,
if they turn not aside in their hearts from the true fear of Him, who we are told,
and can and do believe, is the same yesterday, today and forever;
therefore put on strength, "`put on your beautiful garments,
O Jerusalem!`" seems to be the encouraging language held out.
Surely we have some of us,
felt enough and seen enough with our spiritual eye of what belongs
to the Kingdom to desire it for our habitation continually,--a
heavenly place "`wherein shall go no galley with oars,
neither shall gallant ship pass thereby.`"

It is with me to believe that you, among the number,
are striving to know more and more of this for yourself,
as well as to desire it for others,
even Jerusalem the quiet habitation (as described)
a "`tabernacle that shall not be taken down.`"
What a crown this is, when man is humbled,
and all that is of him is slain and laid in the dust.
I feel that I am writing this to one who knows and enjoys of the heavenly substance,
the true riches.
May all your trials (your trials) work together for a furtherance in the same
heavenly knowledge and undoubtedly it will if there is a standing maintained,
by the Master.

[.signed-section-closing]
From your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

1871+++.+++ 10th Month 8th.--At Lille.
First-day: Have had my times of waiting and labouring, I trust I may say,
for the Bread which comes down from heaven and gives life unto the world,
as I believe it is written and as +++[+++it]
is individually experienced.

Have been favoured with some precious openings in the Truth while out on this journey
and enabled in conversation to declare to others something of the way of Life and salvation,
to my peace of mind.
O! how good it is to serve the Lord in the way that He is pleased to choose for us.
On the day when our Monthly Meeting was being held at Bakewell,
I was twice engaged in this way in the openings of Truth
to my mind while in conversation with individuals,
in French, and found peace in so doing:
but it feels hard to nature to pass along here so much laughed at,
for my singular appearance in the garb of a Friend.
It is hard also to use the plain language,
but the plural number to one individual I must not use.
To some, I explain my motive and religious conviction.
There is indeed peace in well-doing--in doing the Master`'s will.

10th Month 12th.--Fritchley.
Have cause for thankfulness,
to the great Preserver and Helper in this journey who has enabled me to return in peace.

[.embedded-content-document.letter]
--

[.letter-heading]
From W. Hodgson.

[.signed-section-context-open]
Philadelphia, 2nd of 12th Month, 1871.

[.salutation]
My Dear Friend,

Your allusion to the young people among you re-awakened a feeling
of interest in their welfare which I often feel for them,
and I do hope that in the Lord`'s time you may be comforted in beholding
one here and another there submitting to the power of the cross and thus
preparing to be fellow-helpers in the good work and cause.
I trust there is a favourable prospect in that respect
in these parts and among our friends in New York,
if no blast from the wilderness comes over them to destroy the tender plants,
and the world and its allurements are duly kept under foot.
But O, what a people we are called upon to be!
Who is sufficient for these things?
Truly our sufficiency is of the Lord alone.

It was interesting to hear that you had been called
upon by a committee of the lapsed Society.
Their own standing is what they ought to see to in the first place.
Their position is too hollow to enable them to reach forth any true hand of help to you.
I should have no objection to hear of their having pretended to disown you:
it is all a pretence and mere matter of form,
the spirit of Truth and of the discipline having
been departed from by them in their schismatic course

With dear love to you all, I am your friend and brother,

[.signed-section-signature]
W+++.+++ Hodgson.

--

12th Month 11th.--A public meeting for worship was held in the Mill which was well attended.
It was Matilda Rickman`'s concern to hold it for the inhabitants of Fritchley,
and was a favoured time.
It felt a weighty matter to my poor mind,--the first
public meeting called by our little company,
for which M. R. was liberated by our Monthly Meeting.
I felt very poor and as if nothing would be required of me therein.
M+++.+++ R. we believed, was much helped, to the relief of her mind:
this seemed to relieve my mind,
but I felt constrained to rise and give expression to the Scripture
that "`no king is saved by the multitude of a host,
neither is a mighty man delivered by much strength,`" and was helped.
The impression upon my mind was that if no king or mighty
man is delivered from his enemies by the strength of man,
neither can any of us be delivered from our spiritual enemies by anything that is of man.
I felt peace afterwards and was relieved.
The meeting felt a solemn time, and the people (perhaps 150), were quiet and orderly,
and we may trust some good seed was sown in ground that
will bring forth fruit to the praise of the great Husbandman.

[.embedded-content-document.letter]
--

[.letter-heading]
To Peleg Mitchell.

[.signed-section-context-open]
Fritchley, 25th of 12th Month, 1871.

[.salutation]
My Dear Friend,

Were love measured by space of time between our communications,
we might seem at times to have but little for our friends.
I feel I am in your debt in this way and would have written long ago,
but you know there are times we feel so poor, so empty and so barren,
that it seems best to abstain;
nevertheless I do acknowledge that sometimes we have need of an arousing.
How I would like to look in upon you and greet you with a holy kiss, the kiss of Truth,
that inward acknowledgment of Truth`'s dictating,
which is stirred up when kindred spirits meet together.

These instances +++[+++alluding to some who had been united to us by convincement]
of young people coming along in a giving up to the great Shepherd of his sheep,
are truly encouraging and we trust there will yet
be an ingathering and that his work will go forward,
if those of us who have known Him remain faithful and hold on in faithfulness.
"`Surely God is good to Israel;`" truly He is so.
I can believe it must be cheering to you to know of the young, or any,
coming into the ranks, embracing the Truth in the love of it,
and I feel if there is anything that I can desire for you more than another, it is this,
that before you bow your head in the laying down of this tabernacle,
you may know to the gladdening of your heart, sons and daughters of the precious Truth,
gathered into the fold of Him who has declared Himself to be the Way, the Truth,
and the Life everlasting;
and may the burden bearers of our day be spared till more of this is known,
even an establishment upon the Rock,
of those who as yet are not far on their way in the spiritual life.
However, this we know, that the Lord can raise up children unto Abraham,
though the fathers be taken away; and all his decrees are right.

At our last Monthly Meeting dear M. Rickman laid before us a concern
to hold a public meeting for the inhabitants of Fritchley,
which she was liberated for, and I think I may say we had a favoured time,
and a quiet company.
May fruit abound to his praise who not only lays a weight upon
the shoulders but also enables to cast it off to his honour,
if there be faithfulness and a watching to the pointing of his heavenly finger.

I will now bid you farewell in the love of the Gospel which is the unchangeable Truth,
and am your friend,

[.signed-section-signature]
John G. Sargent.

--

1872+++.+++ 1st Month 18th.--A public meeting was held
at Monsal Dale in the house of +++_______+++ Shaw:
a good meeting: help was vouchsafed to minister to a great company.
It was held at dear M. R.`'s request.
After she had spoken at some length I soon felt it required of me to stand with
the words "`I know that my Redeemer lives,`" which opened to my understanding
as that it is precious to have this acquaintance with God,
the Lord and Saviour,
and to feel that because "`He lives I live also,`" as I think it is in Scripture.
We cannot know this unless we feel that He lives in us.
