== Chapter V.

[.chapter-synopsis]
* A Religious Visit to Friends in Different Parts of the United Kingdom
* Memoranda of a Continental Business Journey
* Letter From P. Mitchell
* Letters to T+++.+++ Drewry
* D. Pickard
* W. Hodgson
* J. D. Otis
* P. Mitchell
* One of his Sons
* G. E.
* J. P. Crisp
* W. Waring
* One of his Daughters
* Priscilla Pitt

1872+++.+++ 2nd Month 1st.--At our Monthly Meeting held today at Fritchley
I laid before Friends a prospect which had long been before me,
to visit in the love of the Gospel as way may open,
some of those of the old organization in their families,
who are alive to the state of the Society,
but are lingering on and mingling with them in worship and discipline.
We were favoured with a solemn covering over the meeting from its
commencement and help was vouchsafed to minister therein.
My dear wife also expressed her willingness to accompany me,
which she was left at liberty to do.
The clerk was directed to furnish us with the minute
expressive of sympathy and unity with the prospect.

5th.--Left home in company with my dear wife to perform the engagement before me,
arriving in Birmingham between three and four p.m. and went to William
Watkins`' where we were pleasantly received and invited to lodge.
After tea we had a sitting together on my communicating the object of
the visits and relief was in due time afforded me to my admiration.

6th.--Left W. W.`'s for R. C.`'s,
where we were made partakers of the Lords`' presence to our comfort.
Afterwards, to John Sykes`' and dined--had a sitting with him and wife and son,
in which help was extended after some time of labour.
Then to Thomas Tinnions`'--were kindly received and openness manifested
so that we came away with thankfulness for this opportunity.
Next to W. L.`'s where,
Oh! the spirit that pervaded,--a struggle to go forward,--yet
gave up to apprehended duty,
but had much to feel, and that the seed, if sown, had not entrance.

7th.--Set out for William Graham`'s. The family were ready to receive us,
and after explaining the object of the visit, a quiet calm came over us,
and I was enabled to get down so as to hear what was proclaimed
and was mercifully and eminently helped to my admiration,
coming off with thankfulness and peace.
Afterwards we went to King`'s Heath to sit the little
meeting with William and Caroline M`'Cheane.
A comfortable season together, and my heart was melted in a sense of the Lord`'s goodness.
Dined and left for J. and E. W.`'s. Here help was marvellously extended to declare
unto them the way of peace and salvation to their never dying souls.
After taking tea with them we left Birmingham for London.

8th.--Went first to James Jackson`'s and sat with him and his wife and their daughter.
Afterwards J. J. walked with us as far as J. W.`'s where we attended the little meeting;
was helped therein.
Proceeded after dinner to Joseph Armfield`'s and had a sitting with them and their family,
their eldest son only being absent.
Went next to Tottenham: called upon Mary Stacey.
Sat with Edward May and afterwards with Mary Aggs where we took tea,
and left again with thankfulness of heart for London.
Found our way to Henry Darby`'s, sat with him and proceeded with him to our hotel.
Have cause to be thankful for this day`'s help,
and for a renewal of hope that help will be vouchsafed to do the whole will of Him,
whom I desire to serve fully and faithfully.
Give ear, O my soul, to every word which proceeds out of his mouth,
and obey it fully though it may be as a sword within you to slay the unrighteous seed,
wheresoever it be found, in man, woman or child.

9th.--Our first call was a return to Joseph Armfield`'s
under a feeling of necessity in obedience and for peace.
Here, I had, what were indeed, to me, hard words to utter,
but my peace consisted in not withholding what was required of me to utter,
"`His words were smoother than butter, yet war was in his heart;
his words were softer than oil,
yet were they as a drawn sword;`" cautioning him against
warring against the camp of the little ones of the Lord:
left in peace.
Proceeded next for Dalston to call upon M. A. Bayes,
but to my sorrow she rejected the object of our visit,
and was set in her mind against any testimony,
so none was given for her more than to tell her, her words were bitter words,
and after a little while we left her, she enquiring if any had received us about there.

Next we returned to London for Croydon; called first upon Thomas Ashby,
and had a uniting time with him and his wife and sister.
We found much openness and brotherly kindness,
and took tea after having a relieving opportunity with them.
T+++.+++ Ashby walked with us to John F. Marsh`'s,
where also I was much favoured with ability to relieve my mind: but,
before going to J. F. M.`'s, T. A. went with us to P. M.`'s. Here we sat down together.
I expressed a concern that he would arise from off a bed of sloth and ease, etc.;
but there felt to be too much of the natural man in him to arise out of himself.

10th.--After breakfast we went to Thomas Beach`'s,
and sat with him and his wife and daughter; were cordially received.
Then to Mitcham.
Were made welcome by G. and P. Pitt.
Relieved my mind: not much entrance felt, but no open rejection:
their mother (Pitt) present.
Next we went to Dorking and had a relieving time with Thomas W. Marsh;
afterwards to John and Ann Marsh`'s, where we took tea and were made welcome;
the feeling prevalent, their day`'s work nearly done.
Then to the Holmwood,
feeling contrited with the certainty in our experience that
the good Hand has been with us all along since we left home,
ordering all things well for us to our admiration,
filling our hearts with gratitude and praise, and the language arising,
"`Return unto your rest O my soul, for the Lord has dealt bountifully with you.`"

11th.--It felt cause for gratitude that we had been so nicely cared
for and our steps ordered so as to arrive here last evening.
Sat the little meeting here at Sarah Hayman`'s this morning.
After dinner went to John Dale`'s at Aldhurst, about four miles,
and had a favoured opportunity with him and his wife.
Two little children present, one rather unsettled,
but on the Power coming over us all was quiet, and relief afforded,
in withholding nothing that was given for utterance.
Had to entreat them to have nothing to do with the idols which the people had set up,
which having eyes could not see, nor ears could they hear,
nor with their mouths could they speak, etc.
Whether any fruit be found, the Master only knows.
Sat the little meeting held at five o`'clock, in which ability was given to minister,
and gave expression to the language in the words which impressed my mind,
"`I asked of Him life,
and He gave me length of days forever and ever,`" and declaring that it mattered
little the number of days or years we live--if so be we have the Life everlasting.
It was a comforting time in the solemnizing power of Heavenly love spread over us.

12th.--Had a favoured time this morning with S. Hayman and the
two young women after reading a part of the xviii chapter of Ezekiel,
and left this quiet resting place for Horsham on our way to S. M.`'s,
about four miles from the station.
Felt I left a warning there:
relieved my mind fully and left for John Cheal`'s near Crawley.
How is heavenly help extended!
Arrived at Crawley in the p.m. and walked to J. Cheal`'s. Went out first to Charlwood,
Mary Cheal accompanying us.
Sat with S. S., the widow of John Standing +++[+++and afterwards]
with the two young people Joseph and Mary Standing:
soon a solemnity spread over my mind and utterance was given.
Returned to J. Cheal`'s and after supper we drew into quietness and the words sprang up,
"`In my haste, I said all men are liars,`" but signified that God was a God of truth,
and gave truth unto his faithful little dependent ones,
and discernment between thing and thing,
between that which serves Him and that which serves Him not.
Encouraged the heads of the family to be strong and not flinch
from going forward and holding up the banner committed unto them,
that it might be displayed because of the Truth.

13th.--Left J. C.`'s with a peaceful mind for Brighton.
Proceeded first for Daniel P. Hack`'s, and accepted an invitation to dine.
Called at Mary B. Brown`'s, who gave us a welcome,
and upon my making her acquainted with the object of our visit we settled into
stillness and a good covering came over us and I found relief to my mind.
Then returned to D. P. H.`'s. The visit was well
received by D. P. and E. H. We then left for Lewes,
and first went to Richard P. Rickman`'s, finding him and his daughter at home.
Our visit was received kindly; the language,
"`Not by works of righteousness which we have done, but by his mercy He saves us,`" etc.,
was expressed and spoken to in the opening as it followed:
a precious covering came over on my making known the object of our coming,
and the words alluded to soon came before my mind.
Came away relieved, and feeling that indeed He has done great things for us,
to the removing of great mountains.
Truly He is to be praised and served in faithfulness in all that He requires at our hands.
We then proceeded for Wellingham, to Rachel and Sarah H. Bickman`'s; sat down together,
and soon way opened for my communicating why we were there, upon which,
as in other places, Truth spread over us and we were quiet, the words presenting,
and which remained with me for an offering, "`There is a river,
the streams wherof make glad the whole heritage of God,`" and relief was afforded me,
so that I came off in the end clear, not having any weight upon my mind,
and retired peaceful, for the night`'s rest.

14th.--We left Wellingham with our two friends R. and S. H. R.,
they going into Lewes to their meeting and we going to Croydon,
from there to Charlbury by way of Reading.
At Charlbury found our aunt Jane Sargent ready to receive us:
a feeling of thankfulness on going to rest closed the day.

15th.--Before rising this morning a song of thanksgiving and praise seemed
to fill my heart in overflowing gratitude to the Author of all good,
the dear Lord and Master, for the wonderful works He has done for me.
Made a call after breakfast upon Charles Bissell,
and we were asked upstairs into his wife`'s chamber where she was sitting up in bed.
We soon drew into silence, and were much favoured with the dear Master`'s presence.
Communication flowed freely and encouragement was handed to both to stand firm and not
to bow down to any of the idols which this once highly favoured people have set up,
nor bow down to any graven image formed in their
own minds by Satan or in the minds of others,
which they (the people) were serving as if of the Lord.

It was a melting time.
I had to encourage to stand against the angry blast
which might beat against the wall of their defence,
for that it could not prevail against the faithful who trust in the arm
of the Lord alone for deliverance from every dart of the enemy.
C+++.+++ Bissell communicated a little which left a good savour.
They appear to be under proving.
We next called upon Joseph and Lydia Tyler; help was given to relieve my mind.
It was a tendering time and we parted under a feeling of good,
for the Master had been with us.
We next called at cousin John M. Albright`'s where I expected
to have nothing in a ministerial capacity to offer,
but was made sensible I must not come away without leaving what was commissioned,
feeling that a solemn covering was breaking in upon us as I was about to rise to leave,
so giving up thereto I found that I must be faithful.

After dinner had a sitting with dear aunt Jane and Ann Durran together.
The words accosted my mind in reference to the former,
"`They that turn many to righteousness shall shine as the stars
forever and ever,`" and that it may not be in Infinite Wisdom that
his servants should know their usefulness in this respect,
but that in keeping close to Him and walking with Him in
the Light they may be thus instrumental without words spoken,
or to that effect, which I expressed.
Something also seemed given for A. D. and help in the expression
of my concern that we be not bowing down to any graven image or
idol set up either in our own minds or those of the people.

Left in the evening for Gloucester,
called upon William Bellows and had a sitting with him and his wife.
The words were revived for communication, "`The stone which the builders rejected,
the same is become the head of the corner,`" and I was helped to testify thereto,
I believe in the authority which Truth gives.
It was a refreshing opportunity showing that the wise builders
of our day in this Society have set up another building,
not of living stones, but of stones of man`'s own invention and forming.

16th.--Went again to W. L. B.`'s with a view to meeting his son John.
J+++.+++ B. soon came and we had a melting opportunity.
Help was given to give expression and cast off what arose for him,
to the relief of my mind, and we parted under mutual feelings of tenderness.

We left this place for Leominster and went to Samuel Alexander`'s. An opportunity
was soon afforded for informing of the object of our call and relief found,
a holy covering being spread over us.
"`The Lord is not slack concerning his promises to his faithful
dependent little ones,`" were the opening words,
or to that effect,
and I was led to encourage to faithfulness and against bowing
down to the graven images and idols which this people,
once highly favoured, are setting up.
It was a favoured opportunity; their son S. was addressed,
entreating him to watch and abide in the camp unless he was sent out,
and not to run as they run, who think they are serving God, but are not sent.
S+++.+++ A. took us to Henry Beck`'s where much help was afforded,
and we had a comfortable time together, H. B. being contrited in the opportunity.
How remarkable it has seemed our finding all we go to, at home, or as in this case,
and in another also, on their way home, as Henry was, when we were wanting him.

16th.--Arrived at Rugby tonight.
What a favour that we are so kindly and bountifully cared for!
We may indeed say,
Great and marvellous is your lovingkindness O Lord! and set up our Ebenezer and say,
Hitherto the Lord has helped me.
He has indeed done marvellously for us in preparing
the way before us in the hearts of those we go to.
May we remember this for our good,
that we may indeed put our trust in Him upon all occasions.

17th.--Left Rugby for Kettering and had a sitting with Francis E. Wright and wife;
dined and came away relieved.
Then to Eliza Wright`'s and sat with her and Ann Standing.
Next we went forward to Leicester and had a relieving
and comfortable time with Peter Taylor.
We then left for Nottingham, and had a sitting with Sarah Knott,
which was to our satisfaction.
After taking tea with S. K. we left for home,
thankfully feeling that we had been helped to our admiration on this journey,
so that indeed we may renew our trust in Him in whom we have believed.
True it is that sheaves of peace are given to them that labour for the
heavenly blessing and seek none other but Him and to do his will.

18th.--A comfortable and peaceful serenity covers my mind
and an inward acknowledgment that the Lord is good.
In meeting this morning I had to testify to his lovingkindness and the wonders
that He does for those that serve Him and seek no other God but Him.
"`Our fathers have told us what work You did in their days,`"
and it is the experience of his servants now.
We reckon we travelled in this journey about 750 miles and had 53 sittings,
having been from home 13 days, including the day we left it.

[.offset]
+++[+++After remaining at home one week the diary proceeds:]

2nd Month, 26th.--To William Bingham`'s, Chesterfield.
Sat with him alone:
encouraged him not to rest in past experiences of the wonders performed,
but to look unto the fresh revelations of the Divine will,
and that if there be enemies yet left in the land, his land,
he may ask for help to subdue them, or to that effect.
Next we called at John Wood`'s and had an opportunity with him of a searching kind;
well received by him.
Then with Thomas Gilbert, encouraging him not to form any graven images in his mind,
to do or leave undone according to the imagination of the natural mind or understanding,
but to follow the intimations of the Divine will,
and according to the pattern shown him in the mount.

Then to Handsworth Woodhouse, and had a sitting with Benjamin Le Tall and wife;
seemed led to encourage to the observance of every jot and tittle of the law,
and not to put their hands to anything they are not led into,
not worshipping the gods the people have set up,
nor bowing down to any but the one only God and Christ Jesus in their hearts;
was strengthened to deliver all that I believed was given me.
Had a little opportunity with their son, W. J.:
"`keep the law and the testimony`" with a little more, was spoken.
We next went to Peter France`'s, and found his sister A. Dix at home.
P+++.+++ F. came after we had taken tea, when an opportunity was afforded with them.
"`Drink deep,`" were the words spoken in my mind`'s ear, and utterance given to them,
encouraging them to go down deep,
for that the well is deep and the Saviour requires
us to draw the living water from the living well,
that our souls may be refreshed and live;
and matter flowed freely with exhortation to bow down to the one living God,
and not to the idols of the land which the people of this Society had set up.
It was a favoured time, and I was enabled to come away with peace in my bosom.
Next we went for York and arrived after 10 p.m.

27th.--Called upon Jemima Spence.
Had an open reception and in our little sitting matter flowed freely.
The case of the little captive maid came before me,
as descriptive of the state of this dear friend,
who felt to me as one led away captive into a strange
land as regards her position in life,
having about her much of that which hinders a close
keeping and faithful walking with God.
Oh! the many things that stumble and hinder the going forward.
What I had to communicate was well received.
Had also a testimony after dinner with her daughter and was much helped therein,
as well as again in what was of more general import.
We left this house with grateful hearts for the help manifested.

+++[+++Called on W. and E. Briggs,]
were received with cordiality and helped in a sitting with them.
Then we left for Knaresboro and had a sitting with
William and Sarah A. Needham to our comfort;
simple and open-hearted people.
Next we went to Harrogate and after a call at Philip
Darbyshire`'s we went to a hotel to lodge.
Again we have cause to bless the Lord, and to acknowledge that hitherto He has helped us.

28th.--Called first at P. Darbyshire`'s and on to Thomas and C. Hurtley`'s. Here
we had a welcome and open reception much to the tendering of our minds,
especially dear T. H. was tendered and broken,
telling me I was sent to him and that the words I had spoken, "`The Way,
the Truth and the Life`" had been much on his mind lately and that he had not given up,
also telling us these words that morning had been on his mind,
that "`stubbornness is as idolatry,
and rebellion as the sin of witchcraft,`" either the part or the whole of it.
Next we went to the Darbyshires`' again;
there we had an opportunity and left with peaceful minds in having been faithful,
also at our next place of calling, Holman Shepherd`'s; not much openness or freedom here.
At Samuel Pickard`'s where we went next, I had to revive the words,
"`He that sows to the flesh shall of the flesh reap corruption,
and he that sows to the spirit shall of the spirit
reap life everlasting;`" no entrance seemed manifest,
but left him clear.

28th.--From there we went to Leeds; first called at Samuel Evens`',
where we were cordially received; then to Daniel Pickard`'s;
no willingness to receive a visit.
I was then liberated to catch a train for Manchester,
and we went to Hannah Buckley`'s to lodge.

29th.--Had an open opportunity after the Scripture reading this morning.
We then visited Thomas Davidson.
Had a sitting with Richard Southall;
afterwards went to David Burton`'s who gave us a welcome;
next to Lower Broughton to the Reynolds`' and to lodge again at H. B.`'s.

3rd Month 1st.--To E. S.`'s to sit with D. M. P. Next to
Charles Thompson`'s and had a sitting with him in his office,
and afterwards with Charles Elcock.
Not finding William Irwin at his office we took train for Warrington
and on to James Darbyshire`'s. He inquired if I had a minute.
After a sitting I showed him the minute from my Monthly Meeting,
but he did not mind about it; and we parted, I believe, in the love of the Gospel.
We then visited John Rayner at Bostock Green who gave us a very open reception:
his daughter, an open-hearted, kind young woman made us truly welcome.
Her two brothers came in in the evening and we had a sitting together.
They were none of them members,--the father, we believe, walking by his faith,
and loving the principles held by us.
We lodged there and were very hospitably entertained.

2nd.--Left Bostock Green this morning for Liverpool, and went to Henry Albright`'s,
where we dined and had a sitting afterwards,
with him and his daughter Sarah,--a relieving opportunity.
We then went to George Glover`'s but not finding him or his wife at home,
nor likely to be till late this evening, we left for Fleetwood,
looking to this as a resting place till second-day.
Had a sitting with Thomas Drewry and his wife,
her mother and M. E. K. before going to rest.

3rd.--Held our meeting at T. D.`'s with them all in the
fore and afternoon and had some relieving opportunities.
Went in to Samuel Hope`'s in the evening and was much helped to relieve my mind there,
and openness seemed manifest to receive what was left there,
addressing both him and his wife,
the latter feeling to be a woman of a meek and quiet spirit.

4th.--Left Fleetwood for Preston.
Dined and had a sitting with William Clemesha, his son and daughter;
were encouraged in this visit, and went forward to Roger Preston`'s at Yealand.
Here we were made truly welcome and engaged to lodge,
going soon to Warton to John Marsden`'s where we were comforted
in finding his young wife one of the open-hearted ones.
After a sitting with them we returned to Yealand,
and finding a young man and his wife of the name
of Bragg coming to spend a little time with us,
we had a sitting with them.
What I had to communicate was as addressing a state of outward dependence on human learning,
and revived the language addressed by Festus to Paul,
"`Much learning does make you mad.`"
My mind was first impressed with the words, "`Jerusalem is a quiet habitation.`"

5th.--We left Yealand this morning and proceeded to Kendal, to visit Charles Prince, who,
we were told, has been received into membership.
Made a call before leaving Kendal, upon Mary Ann Simpson,
who with her husband received us, and parted with us in a feeling manner.
We then went to Allithwaite to William Nash`'s. Were invited to lodge
and had a relieving time with him and his son William and his wife.
W+++.+++ N. Jr. took us to Holker to visit G. E.; had an open time with him,
and went next to Ulverston.

6th.--Had a sitting with John Chapman and wife.
"`Sanctify the Lord of Hosts,
and let Him be your fear and let Him be your dread:`" came away relieved.
Left for Whitehaven.
Isaac Dickinson poorly: did not see him, but had an opportunity with his wife,
and their son and his wife.
Next we called upon Mary Miller as an old acquaintance and friend:
was helped with a little for her: she remarked it was a brook by the way.

7th.--Called this morning early upon John Walker, who seemed truly glad to see us:
I had somewhat close things to offer here.
Arrived at Cockermouth, and after dinner took conveyance to William Robinson`'s,
Whinfell Hall.
Had an opportunity with him and his wife and three of the family,
after which we went to John Alderson`'s, Beech Hill, and took tea there:
an open opportunity with him.
Left for Josiah Thompson`'s at Eaglesfield: sat with him and his wife.
Returned to Hannah Robinson`'s to lodge,
calling in the evening upon Henry T. Wake and Joseph and
Jane Adair,--opportunities affording relief to my mind.

8th.--After an opportunity with H. Robinson and her
brother we made a call upon Mary Simpson,
and left Cockermouth for Wigton.
Took a conveyance to Waverton and had a comfortable and relieving
time with Richard Hall and wife and three of his family,
after which we went forward to Park Gate.
A hard time here, feeling strong opposition in the head of the family,
who was much disposed for reason and argument.
Left for Carlisle and went to Richard Brockbank`'s
and had an opportunity with him and his wife.
He was in the spirit of contest as to our being wrong in separating from such as themselves,
but it seemed best to relieve our minds on this head and bear his rebuts.
He stood in the reasoning of man in opposition to us.

9th.--Left Carlisle for Edinboro.
Had a relieving time with Helenus Gibbs.
Called upon Jane Wigham, then left for Dundee.

10th.--Went to Hector Macgregor`'s and had a sitting with him.
Sat down for meeting at eleven o`'clock.
James C. Steele sat with us.

11th.--We left for Glasgow.
Had a sitting with William and Margaret Smeal and then with Robert and
Mary S. and had a relieving time with both the above named heads of families.
Left for Greenock to go by steamer to Belfast.
Had rather a rough passage, arriving about two hours after time.

12th.--Our first call was upon Forster Green:
went out to see him and met him a little way from the house on horseback.
He went back and we had a sitting with him, his sister-in-law being present.
He went with us, riding before the cab,
to show the way to Ann Gardner`'s where I relieved my mind and felt thankful.
Then we called upon Robert Gouch and had a sitting with him;
after which we left for Lisburn, and had a little time with Harriet Green at the School.
Next we went to Hillsboro`' to William Green`'s and lodged.
Had a sitting with him and his wife, and after breakfast left for Portadown.

13th.--Felt confirmed by W. G.`'s own remarks that
our steppings in our withdrawal were right for us,
but the crown of all was the precious covering I felt over
my mind that morning before leaving our room,
which prepared and solemnized my mind for anything, and help was again vouchsafed,
so that I was enabled to depart in peace for our next visit which was to Portadown,
to James Green`'s. Did not find him at home; I relieved my mind to his wife,
and left for Richhill where we found James Creeth;
we were comforted in finding him one of those who
see and feel the present state the Society is in.
He told us he does not rise in meetings to the kneeling of the unsound ones,
and that the meeting would not receive his certificate of removal
to this place on account of his bearing this testimony.

We returned to Portadown and had a sitting with Charles and Ann Wakefield,
and I was much helped therein to set the truth before them quoting the words
"`Jerusalem is a quiet habitation,`" and to encourage them to unflinching faithfulness
to what is made manifest in them to be the will of the Lord concerning them,
whether in the doing or the leaving undone, that he might be glorified by and in them.
They received us kindly and we parted friendly.

14th.--We left Portadown for Bessbrook, Newry and Dublin.
Went to Henry O`'Neill`'s and had an opportunity to my relief before parting.

15th.--This morning we went to see George A. Milne.
Called upon Henry Scarnell, employed at Edmundsons`',
in Capel St. Had a sitting with him and afterwards with the housekeeper S. C.:
felt comfort in these visits.
Had a sitting with Robert Chapman; a tendering time to him.
We then went to G. A. Milne`'s to dinner.
Had an opportunity with him and his wife: a relieving time.
We next went to the Bakers`' and W. and E. Wardell`'s. Had a time at both houses.
Then we went to meet with John Gough and had a time with him.
Then to Robert and H. Bowles`': it was an open opportunity; a welcome manifested.

16th.--We left this morning for Enniscorthy,
Went to J. Morrison`'s who had no unity with our withdrawal from the meetings.
I relieved my mind there and went next to R. Copeland`'s and had a sitting with him,
who received us pleasantly and feelingly.
Called to see T. Chapman,
but not sufficient openness was manifested to make way for a time with him.
We left Enniscorthy for Wexford, feeling it a favour to get there,
and settled in comfortably.
(Hardness experienced today.)

17th.--First-day.
Had our meeting at the hotel this forenoon and again in the afternoon,
after which we went out to find Thomas Purvis and
were agreeably impressed with our visit,
and returned to the hotel to lodge.

18th.--Breakfasted with T. and S. Purvis and afterwards called upon Hannah Thompson,
an aged Friend: it was comforting to meet with her,
and we parted in a feeling beyond words.
Truly we have been helped on our way hitherto and been mercifully cared for.
O! the tender dealings of the dear Master with us in leading us
along safely and enabling to set up our Ebenezer and say,
Hitherto He has helped us.
How wonderful are his ways and past finding out,
so that we may confide in Him as our Leader and Preserver.
On arriving at the station at Carlow I perceived a young man coming to the train,
and thought it might be Richard Williams whom we were going to see, and found it was so:
he was going with an invalid friend to Dublin.
Though disappointing,
yet it was relieving not to have to go further on his account and thus
we were enabled to take a train coming up a few minutes after for Waterford,
instead of having to wait until tomorrow, having nothing further to do here.
In this we perceived Divine leading, which is again cause to adore and trust at all times.
We reached Waterford in the evening and made our first call upon Charles J. Hill.
Had an opportunity with him, which seemed rightly timed.

19th.--Made calls this morning upon T. Barrington, John Adair, Rachel Barnes,
Joshua W. and Elizabeth W. Strangman; after which we went for the train to Clonmel.
Our first call there was to see Eliza Malcomson, and sat with her and her two sisters,
and afterwards to the three sisters Moore.
We then went to the hotel to lodge and left in the morning for Limerick,
and soon found the way to Joshua Jacob`'s. He received us pleasantly and showed openness,
his wife also.
We had a sitting with him and his wife, and afterwards with a young man, not a member,
who is drawing to Friends`' views:
an open opportunity and it has seemed good we came here.
J+++.+++ J. saw us off by train for Cork.
Feel as if there was not much if any way here.

21st.--This morning it opened,
after learning about the boats that it might be well to leave for
Plymouth by steamer advertised to leave at 12 o`'clock,
instead of waiting till tomorrow, and feeling nothing to detain,
we embraced the opportunity, and prepared accordingly,
first calling at John B. Haughton`'s which also afforded
an opportunity of some expression with two other individuals,
Phebe Cook and H. Abbot; we then seemed ready to leave Cork for own shores.
How wonderful to us have been the leadings of our heavenly Shepherd,
even bringing us on to a hair`'s breadth in the way that has seemed,
(when afterwards we have looked at the path taken) the best way for proceeding,
in order to carry out the prospect I had, from the time it was opened to my mind,
until now.
May this ever be remembered for my encouragement and trust in the best of Leaders,
and not to look far forward for the accomplishment, but rather day by day,
for the manifestation in the Light;
for truly my own plannings and arrangements will not work the thing required
anything like unto the Master`'s begettings unfolded to view in his own time,
which is the best time.
(Written on board the _Upupa_ steamboat off the coast of Falmouth.)

22nd.--Reached this place (Plymouth) thankful in heart to have been brought here,
in the feeling it is right.
Marvellous are your works, Lord God Almighty, and that my soul knows right well,
seems to be the language of the heart at this time.
We went to William and Catherine Brown`'s, where I relieved my mind,
but was not refreshed.
We then called upon Ann Balkwill, and had a time of interesting converse,
nothing more feeling required.

23rd.--We left early for Redruth and proceeded to George Cornish`'s,
and found a true welcome; a favoured contriting opportunity with him:
here we had cause to say, Hitherto the Lord has helped us, and to bless his holy hand,
in doing so much and so marvellously for us.
We left this place on our way back towards Plymouth, stopping at "`St`" Austell,
where we visited James Veale, his wife and a sister being present.
Our next visit was in company with J. V. to his brother Andrew Veale,
where I had something to communicate and some conversation
on the subject of our withdrawal from their meetings,
in which I felt best help.
We next went to Richard Veale`'s where Samuel Veale met us.
Here I was brought into a strait place, but best help I believe, was near,
and I came away feeling that such a one in earthly greatness is not congenially situated,
and that such a way of living stands greatly in the way of a progress in the Divine life.
"`How hard it is for such as have riches to enter the kingdom.`"
We then went to +++_______+++ an aged man.
Here I found great openness in a feeling of his being in a humble state of mind:
it felt good to make the visit and we parted in true love.
He is not a member, but attends meetings.

24th First-day.--Left for Exeter; here we have had our two quiet sittings,
and are again and again led to express how marvellously we are cared for every way,
so that our faith is confirmed and renewed in Him in whom we have believed.
May we in low seasons remember his past lovingkindness
and condescending goodness to us throughout this journey.

25th.--We left Exeter this morning for Wincanton
and found dear Susan E. Bracher ill in bed.
Had a comfortable sitting with her by her bedside, to her encouragement she said.
We took train to Bath arriving at Catherine Williams`' to lodge.
Had a laborious time with her and F. Trimmer who was with her, before going to rest.

26th.--This morning left for Bristol.
On arrival went to Hannah B. Smith`'s where we had a tendering opportunity.
We left this place for Chipping Sodbury, where cousin Jane Parker kindly made us welcome.

27th.--We left this morning for the station,
but not feeling easy without going to Kingrove to see Jane
Douding we went there much to the relief of my mind,
and visited this solitary one as regards fellow members.
Had a relieving time with her,
and I again felt how good it is to attend to that which makes for true peace.
Had a little time also with her nephew, who appears to be in a decline.
Encouraged him to go down deep in the secret of his soul
and wait upon the Lord that he might find a stay there,
and to be resigned to the Lord`'s will as to death or life of the tabernacle.
Left for Worcester and had, at our cousins here,
a solemn time of favour in the feeling that the Wing of ancient Goodness was over us,
to which I had to bear testimony and was again helped in the renewings
of Life to declare of the way of Life unto all men,
standing in the obedience of faith to the manifestations of the Divine will to us,
whatsoever the requiring or command may be, whether in the doing or the leaving undone.
This offering left on my mind a solemn, peaceful feeling,
which may it be remembered with thankfulness of heart to the Author of all good,
and may my heavenly Preserver stimulate me to a perseverance
in whatsoever He may show me is his holy will.

We were favoured to reach our comfortable home and those we had left,
in a peaceful feeling of gratitude to our great Benefactor.

5th Month 14th.--Left this evening for Dover on my +++[+++business]
journey to the Continent.

19th.--Gand.
Sat down in my room in the forenoon and evening to hold my meeting,
and trust my desires were accepted, though much wading was my experience,
the mind running to the morrow.

20th.--Alost.
Sitting at the station, my mind turned towards those probably now assembled in London,
of the Ministers and Elders of the "`Society,`" my heart indites the language,
"`Spare your people, O Lord,
and give not your heritage to reproach!`" but Oh! the probability
is that many of those met together are not of the Lord`'s anointing,
but of man`'s choosing and appointment, who run in their own wills and are not sent.

26th.--Lille.
Sat down for waiting upon the Lord and Master,--poor, but peaceful in so doing.
In the evening again endeavoured to draw into inward
silence before Him whom it is good to serve,
and to worship in all things, keeping close and walking in his fear.

29th.--Arrived at my brother`'s in Paris.

30th.--After breakfast this morning, +++[+++my sister]
Lucy read, and my mind was visited with the words,
"`The fear of the Lord is the beginning of wisdom,
a good understanding have all they that keep his commandments,`"
addressing the two dear children and partly,
towards the end of the communication, the parents.
This giving up afforded relief to my mind and in
the feeling of help vouchsafed I felt tendered.
I trust the opportunity may be remembered by us to profit.

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 20th of 7th Month, 1872.

[.salutation]
My Dear Friend,

It is brought to my remembrance that "`the fire will
prove every man`'s work of what sort it is.`"
This we may believe,
and may the language of my heart ever be "`that which I know not teach me.`"
Would that we could be at peace with all men, and that all men would be at peace with us,
but this does not seem practicable throughout,
only as much as in us lies we have to endeavour to be so.
How have I desired that all who see eye to eye in doctrinal points,
might harmonize together, be of one mind and keep out all differences.

I think you know this has been my mind and it continues so to be,
and I believe I can say the craving of my heart to the Creator of all good is,
that the time might come comparable to that when "`the wolf shall dwell with the lamb,
and the leopard shall lie down with the kid.`" Isaiah 11:6.
What a notable time this would be,--no differences! and
I sometimes query whether we are sufficiently alive to the query (not
just among ourselves but in a more extended sense) "`when differences
arise is due care taken to endeavour speedily to end them.`"
It is a hard matter sometimes, but perhaps we are not prayerful enough.
Farewell.

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Daniel Pickard.

[.signed-section-context-open]
Fritchley, 27th of 10th Month, 1872.

[.salutation]
Dear Daniel,

I felt a response to your communication of the 24th, relative to the help afforded us,
on the day we met;
having believed that there was cause for gratitude and praise to the Giver of all good,
that his power was manifestly over us chaining down under its influence that which opposes
itself to the work of God in the heart and melting into that pure love which is of Christ.
Greatly have I desired that this may be permanent,
although a difference of action we believe, is called for at our hands,
and I do sincerely hope and trust that that charity
does exist towards each other which "`bears all things,
believes all things, hopes all things,
endures all things`" and "`never fails,`" and that it may exist with us to the end.

With regard to your remark offered to myself in particular
I desire to stand open to the sincerity of all my friends,
and remain in a feeling of true love,

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 19th of 11th Month, 1872.

[.salutation]
My Dear Friend,

I received the document +++[+++disownment of J. G. S. by the (so called) Friends]
and this morning your letter, which was acceptable.
Your remarks respecting appealing are quite in unison with my own view.
I have not seen that it would be consistent with my withdrawal,
or that it would accord with the ground for which I withdrew,
to appeal to either Quarterly or Yearly Meeting; the ground being that it,
London Yearly Meeting,
is a lapsed body and consequently the meetings that are subordinate thereto.

I trust I may be helped to see what is required at my hand for the clearing of Truth,
for it (the document) has untruth in it.
It is a favour to feel unmoved and lifted above their insinuations,
and the desire of my heart is that this act on their part,
and close keeping to best Wisdom on mine,
may tend to the confirming of our testimony on behalf of the Truth,
and to the honour of the Great Name,
which I can truly say it is my desire on all occasions to advocate.

[.signed-section-closing]
With love I am your friend sincerely,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To W. Hodgson.

[.signed-section-context-open]
Fritchley, 5th of 1st Month, 1873.

[.salutation]
My Dear Friend,

Since I last wrote there have been occurrences which I may now allude to.
One is my own disownment by "`Chesterfield Monthly Meeting,`" which is stated to be
on account of taking a prominent part in two marriages solemnized in our meetings,
and the non-attendance of their meetings.
Their testimony of disownment is a weak document, as might be expected;
untrue and contradictory as well as expressing their belief +++[+++merely]
that I have erred, not that I have erred.
The Clerk of their meeting who brought it, believed, as he said,
that both they were right and we were so too, and told me not to read it.
It seemed a burden to him, but I viewed it best for him to read it to me.
I may thankfully acknowledge it has not moved me,
and that I have been mercifully favoured with the
comforting owning of the Shepherd of his sheep,
to an unusual degree of its abiding influence,
which has indeed been strengthening and encouraging under the more
than usual provings of faith which have just lately come upon me.

I wrote a letter to the Clerk (not to the meeting) thinking it best to let him thus know,
(and requesting him to show it to all who had been concerned in the matter,
and those who had visited me) that it,
(the document) was untruthful and not straightforward,
as well as that it admitted a doubt of error, and that it would not bear the Light.
He has since informed me that my letter was read in the Monthly Meeting,
and that he had handed it to each of the Quarterly
Meeting`'s Committee who were on the appointment.

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James D. Otis.

[.signed-section-context-open]
Fritchley, 16th of 3rd Month, 1873.

It feels right to work in the daytime, while it is day with us,
for the night comes wherein no man can work; and to do the work faithfully,
that is given us to do.
May we all, who feel the dear Master lay anything upon us, bow to it,
though the weight thereof may seem heavy,
for assuredly He requires nothing of any one of us, which He does not,
and will not give the ability to perform to his praise and our everlasting good.
May we be faithful and not let the opportunities go by, for these will cease,
and there is neither work, nor device,
nor knowledge nor wisdom in the grave where each one of us goes.
How many are the lawful earthly things which sometimes rise up in a heap before us,
and cast down under their weight to our hindrance,
unless we look unto Him who helps through, and so press through them all.

[.signed-section-closing]
I am your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James D. Otis.

[.signed-section-context-open]
Fritchley, 2nd of 5th Month, 1873.

[.salutation]
My Dear Friend,

Your acceptable letter was received when some of our dear
friends were with us to attend our General Meeting.
It was very pleasant to have your brotherly salutation and I can say my heart is made
glad in a feeling of that true unity which is the badge of Christ`'s followers:
may this continue, and I believe it will increase in the cementing which knows no end.
Our General Meeting was held yesterday and our Monthly Meeting the day before.
I know of nothing to boast of as respects these gatherings
but while feeling that of ourselves we can do nothing,
a sense has been given of Israel`'s unslumbering Shepherd being mindful of us,
and his outstretched wing to be over us, blessed be his holy Name

Our dear friends from Norway, Anders and Sikke Evertsen were with us.
It has felt comforting to have their company.
Anders had something to say in our meeting yesterday, his wife interpreting.
The nearness I have felt with him and his wife is precious.
Well for us it is that we can testify to help vouchsafed,
and as it is written (I think) he that is forgiven much loves much,
so he that is helped through straits and difficulties (and especially in an endeavour
for the cause of Truth) has cause to love much Him that helps him.

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 17th of 8th Month, 1873.

[.salutation]
My Dear Friend,

Our little company hereabouts, are, I trust, holding on their way,
though feeling at times low and lacking; but the Good Master does condescend at seasons,
to feed us with a crumb (to be truly thankful for,) of the living Bread.
But times and seasons we know are not at our command;
we must watch and wait that we may be fed.
Our opposers continue our opposers,
those who think we are wrong in leaving them who remain in the larger body;
and yet should we join them and do as they do, they would undoubtedly rejoice in us,
as bearing testimony for the Truth in the way they would have us to do,
but we do not hear the Master say go with them, but, follow me, is, I believe,
what we must give heed to.

I was talking the other day with one of the larger
body who considers there must be a reaction,
that they will soon have gone so far away from the original
principles of Friends as to see where they are and return.
I told him I looked for no such thing, it seems a delusive thought with some,
who deplore much that is done, and they, are we may believe,
lulled to sleep in this expectation that something will be done for them and
so work deliverance without their previously withdrawing from wrong things.
The individual I have alluded to does not I believe,
oppose us in our action (for ourselves) but does not come beyond where he is.
He thinks we have not stepped right nevertheless in holding birthright membership,
and so do some others who say if we did not admit birth members they would join us.

I can say love flows towards the dear Friends about you
as well as elsewhere on your side the great Atlantic,
"`There is a river the streams whereof make glad the heritage of God.`"
Is it not so?
This stream gladdens the hearts of those, all those who partake thereof,
which flows from the living Fountain.
And whether we are outwardly together or far separated,
drinking thereof we are alike refreshed, comforted and strengthened, yes,
comforted and strengthened in our God and one in another in Him the Lord.
So let our hands wax strong through Him and in his holy Name; so shall we do valiantly,
yes, one shall chase a thousand, and two put ten thousand to flight,
this I believe remains as true as ever;
and though at times the way seems dark and gloomy
and we be troubled as under clouds of darkness,
yet may we trust in our heavenly Leader, for we do know my dear friend and brother,
that He does and will bring us out into a large place
where indeed we can set up our Ebenezer and say,
"`hitherto the Lord has helped us.`"

If our reliance was upon our numbers where alas should we be?
but there is a stronghold where Satan`'s darts cannot enter or pierce,
and in Him we can have confidence.
The Light shines through the dark clouds and assures us He is there,
though when obscured we behold Him not.
Let us then be of good courage and He will strengthen our hearts.
Only let us have patience, the patience of the saints,
them that have feared God before us,
and them that still fear and love his adorable name throughout the earth.
My love flows to you my beloved brother in the unchangeable Truth.
Let us trust on to the end,
"`be of good courage and he will strengthen your heart,`"--this
belongs to Israel now as it did of old.

What a trial it must feel +++_______+++`'s daughter being engaged to one not a Friend.
I am sorry it is so,--would that there had been faith! that faith which
removes mountains and wherein the decree of the Most High is established,
that He will never leave nor forsake them that trust in Him;
and are we not to believe that if this is so He will provide in
his own time helpmates for his children in a safe enclosure,
and of such as will be blessed to them; the one unto the other.
I can sympathise with the parents.
"`Without faith we cannot please God;`" this language revives with me while I am writing.
If therefore there be not faith in Him in a matter
of so great importance as that of marriage,
how can it be but that we displease Him in stepping without it?
and this dear young woman must I do believe,
be acting to the grief of her exercised parents, who are devoted I believe to his fear,
both of them.
Well the Lord does bless and He also does blast.
May he work in his mercy and bring in to Himself through great tribulation.
It is through great tribulation we enter his kingdom, if we enter it;
and some by one sort and others by another,
and his ever blessed hand gets Him the victory.

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Peleg Mitchell.

[.signed-section-context-open]
Fritchley, 18th of 10th Month, 1873.

[.salutation]
My Dear Friend,

Truly how pleasant it is for brethren to dwell together in unity,
and whether they be present or absent one from another, to live in unity;
and this we know, that if we live in Him,
we shall know unity in the Life one with another; O! it is a precious thing, Unity.
Well, my dear friend, I believe if it rests with you,
your love for the Truth and its reigning over all will keep up the unity,
(as far as you are concerned) and I believe the desire for its
maintenance among you will continue to the end of time with you.

We have had an acceptable visit from our dear friends W. C. and L. D. Meader
and we trust they are now not far from their native land.
Their labours have tended to encourage and stir up to seek a better country and inheritance,
and we trust will not be in vain in the Lord.
They paid an acceptable visit in Norway, and William and I felt encouraged,
in finding a few yet alive in the south of France and in Germany,
so that it felt to us good that we went there.
It is a favour that amidst all the degeneracy which overspreads the countries,
the Shepherd has his sheep and that his voice is known;
and we may believe He will still have a seed to serve Him in the way of his requirings,
doing his commandments.

I have not much to report respecting our little companies in this land,
but that we are favoured from season to season to feel the Lord`'s sunshine to
warm our hearts and invigorate to the renewing of fresh desires to serve Him.
O! that we and you may feel weighted down by the tokens of his love, his holy presence,
so as to continue in his love and grow in the knowledge
of Him and his will concerning us;
and thus I am persuaded we shall know more and more of the
excellency of his strength and the seasoning of his power,
to bring all into dominion unto Him who alone is the Life of his people,
and He will have a people I believe to the end of time,
whatever name (outward name) they may go by.

It feels to me that if we are deep enough,
we must know all barriers and hindrances to the Divine
Life flowing from vessel to vessel subdued,
and the precious substance to be ours,
that in which there is no jarring and nothing that
disqualifies for the blessed unity of God`'s people;
may we, may we all, seek this more and more for our experience.

We have lately lost by death a very dear friend, John F. Marsh, in his 85th year;
one who loved the Truth and was a father in it, to some of us, in years gone by.
But he did not see his way out of the old organization,
and we did not judge him therefor,
feeling we must leave all judgment with Him who judges
righteously and knows how to lead us along,
and commits unto each one their portion of work for Himself.
Our place is to do it faithfully,
but although we judge not our dear friends who do not see
with us in our stand in withdrawal from the larger body,
yet we have to feel something of a lessening of that same
freedom of fellowship one with another which once existed;
this we can but lament,
but if we are faithful our Lord and Master will carry
us through to our own peace and consolation in Him.

[.signed-section-closing]
In much love to you both from your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Sons.

[.signed-section-context-open]
Fritchley, 24th of 12th Month, 1873.

[.salutation]
My Dear +++_______+++,

Inclination and more than inclination induces me to take
the pen to let you know that you have been in remembrance,
as well as others of our dear family, and in thinking of tomorrow, the 25th,
commonly called "`Christmas day,`" when all but Friends, I believe, close their shops,
I have been led to ponder upon our different allotments and the opportunities given us,
some greater some less, of showing forth our allegiance unto our Lord.
It is indeed a privilege to feel that we can own the Truth,
and in any measure display the standard because of it, and in so doing,
acknowledging the Lord in all our ways,
we gain strength and a footing or establishment in the everlasting Truth, which none do,
but those who take up the cross to their own inclinations
and prefer the ways of Zion to the ways of the world,
or even of professors merely, who abide in the outer court.

Do, my dear son, endeavour to come into Wisdom`'s ways in all things,
and bow your neck to the yoke of Christ, unto that, it may be,
little despised thing which the Lord by his Holy Spirit requires of each one of us;
that we should walk worthy of his Name.
It will be a comfort to your parents, and I believe your true friends,
to know that you have had some faith in exercise on tomorrow in regard
to keeping your warehouse open as Friends have been accustomed to do,
as a testimony of their allegiance to the King of kings and Lord of lords.
I believe you will feel true inward peace if you do,
so let nothing hinder your faithfulness to that in you which makes for peace.
Dear love from us.

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To G. E.

[.signed-section-context-open]
Fritchley, 1st of 7th Month, 1874.

[.salutation]
Dear Friend,

I would have liked to reply sooner to your letter lately received,
but much occupation of mind and body has prevented
my putting pen to paper to address you.
I believe I can say that we sympathise with you under the trials you are brought into,
owing to the lapsed state of the Society which still claims the name of Friends, without,
it would seem, being able to see (being so blinded as a body) the state they are in,
or to know that blindness has come over them,
and the back-sliding which has befallen them.
I would say in these conflicts and under this baptism,
"`Be still and know that I am God,`" which language,
applicable to the children of the true Israel in our day,
is comforting when received into the spiritual understanding.
We can do nothing of ourselves; but to wait upon God in these straits,
that we may be endued with power from on high is, I believe,
the sole remedy for the afflicted ones; then, when this is received,
we can do whatever He commands us to do,
because He pours out of his spirit upon us and our understandings are enlightened,
then are the angry elements stilled at his bidding,
and his love and power are proclaimed in our hearts to his praise.

I believe there is no other way for you,
but to be fully persuaded in your own mind by attention to the
Word nigh you--and you know in what you find true peace,
whether it be to sit alone,
or go to the other meetings--this do (that which makes for peace) and leave the other.
I believe it is not for us to prescribe the one for the other;
nor to look unto man but to faithfully mind the true Teacher--for the promise is,
He will lead us into all truth,
and this indeed is worth coveting after that we may know it.
I think you have wearied your mind long enough with these things,
which may be taken into the reasoning part which is that part in man that belongs to him.
Do not so, but seek for that only which is of God, and this will be the way to find rest,
the true rest to your soul.

Weary not yourself with what you shall do; but what you find concerns your peace,
that do, and do it with your might, embracing all the faith you have,
whether little or much.
Seek not to counsellors, but look for the true Counsellor and wait for his appearing.
He will be more to you when He has made Himself known to you in secret,
than all the ways you may choose can be,
if chosen because of the appearance of the thing.
If you have a testimony for God, bear it whensoever He may lay it upon you,
and this I believe will stay your mind.
Do not be tried with me if I do not answer your queries--I
want to draw you off from them,
believing they (the many queries that present to your mind)
have a drawing off or outward in their effects upon you.
We are pleased nevertheless to hear from you, and to know how it fares with you.

[.signed-section-closing]
With love, I remain your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One Of His Sons.

[.salutation]
My Dear +++_______+++,

Since I left home my thoughts have at different times turned to you,
in desire that if there should be anything as a duty from
a father to his son remaining to be done by me towards you,
I might see it, and be enabled to do it.
I have in my sitting this morning,
felt such cravings to arise in my heart for your best welfare and future happiness,
that I feel best satisfied to let you know it.
I think you must know,
from your past life and experience that we (your parents) to whom you have been
committed for bringing up to the best of our knowledge under the leadings of
our Heavenly Father and Saviour have had this in view for you,
and that we do earnestly desire your good every way.

We cannot therefore reconcile anything on your account,
which we feel to be contrary to the pure guidance of the Spirit of Truth,
which does lead its followers into all Truth,
whereby they become increasingly acquainted with God;
and also with the many snares which are laid by our unwearied adversary for their feet,
that they may not walk in the way of Life and salvation,
but turn into the crooked ways of Satan,
"`the broad way which leads to destruction,`" and become his servants
and followers to their everlasting unhappiness and eternal misery,
which surely commences here,
though our enemy takes care so to blind the spiritual eye and to delude,
that he may win over and captivate to final destruction.

Let me, my dear boy, once more earnestly entreat you to look narrowly, yes,
very closely at the "`path of your feet;`" ponder it well,
(read Proverbs 4 ch.) Strive to get into the quiet,
out of all excitement of the creature or natural man, the passions which are but,
as it were for a moment, and look up unto God, our God--your father`'s God,
and the God of the fathers in the everlasting and unchangeable Truth,
who have gone before us, who are inheriting enduring bliss;
and consider well what is a little pleasure in this
world which endures (comparatively) but for a moment!
Look at your lasting happiness which we do earnestly desire for you.

But if you will walk in the way of your own choosing,
without regard to the desires of those who are not serving a hard Master,
then what can we do for you?
All that remains for us to do is to continue our prayers for you,
that you may have Light and our merciful heavenly Father and Benefactor may continue
his striving with you (though we read his Spirit "`shall not always strive with
man.`") And may you come to the knowledge of God so as to put your trust in Him,
who, if you "`lean not to your own understanding`" (which is the exhortation of Holy
Scripture) will lead you along safely and provide for you in his wisdom,
so that you also, shall "`lack no good thing`" that he sees is fitting for you.

Do my dear--take this to heart;
incline your heart to seek his ways for yourself
and let Him choose your inheritance for you.
So says my heart and soul,
while I can assure you I do feel all desire that you may
be provided for in his time with a true helpmate,
that shall be able to strengthen you in that which is good,
counsel you in difficulties and warm your heart with the
love which is begotten of and has its spring from God.
In dear love and earnest solicitude for your welfare as already expressed,

I am your affectionate and truly well-wishing father,

[.signed-section-signature]
J+++.+++ G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Jane P. Crisp.

[.signed-section-context-open]
Fritchley, 17th of 5th Month, 1875.

[.salutation]
Dear Friend,

You will perhaps remember me by name, as living near 30 years ago at Kimberley.
Since that time I do not remember having heard of you,
till lately on reading a piece in _The British Friend_ signed J. P. C.^
footnote:[See [.book-title]#The British Friend# for 1875, Vol.
33, page 100.]
The query was raised who this could be, and your name was mentioned,
I think by our friend Matilda Rickman who lives in this village, L. E. Gilkes with her.
It was very interesting to me, your name being brought up,
and it raised a desire to know something concerning you,
now in this day of turning aside from the ancient testimonies of Friends,
by the lapsed Society (as a body) consequent upon their falling away from the living
principles of Truth and embracing other doctrines than those our early Friends espoused,
and all true Friends must now do,
if they will be followers of Him who is the great Leader into all Truth,
as faithfulness is abode in to the discoveries He makes manifest.

We are desirous of sending you by post a book or two,
which are deeply interesting to such as retain the ancient Principle,
and good perhaps for others to read who have not yet seen,
so as to distinguish to whom belongs "`the living child,`"
nor yet bowed the neck to the Christian yoke,
that all in them that is contrary to its cleansing
and sanctifying nature may be rooted out.
I shall be pleased to have a letter from you, if you will post me ever so few lines,
that I may know your proper address,
and with unfeigned love in that which has no change (I trust I can say),

[.signed-section-closing]
I subscribe myself,

[.signed-section-closing]
Your friend sincerely,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Jane P. Crisp.

[.signed-section-context-open]
Fritchley, 5th of 6th Month, 1875.

[.salutation]
Dear Friend,

Your letter to hand this morning is cause of comfort to me and my dear wife.
We have perused it as coming from one of the Lord`'s followers,
as the day dawns upon her heart.
If we are faithful to what is made manifest,
the Lord is our shield and exceeding great reward, as He was unto Abraham.

It is cause for rejoicing to us that you have felt called to show
your allegiance to the King of kings and Lord of lords,
by making some stand against the sorrowful departures and innovations in the Society;
and it may be the steps you have already taken have
been all that the Lord has hitherto required of you;
but He that leads along step by step safely does
also so anoint the eyes of his little dependent ones,
that from time to time, as such are enabled to bear it,
He makes fresh discoveries to them and fresh requirements also.
O that we may each one of us bow unto his will in these, whatsoever they may be,
and (I am writing to one who knows these things) our peace does then flow as a river,
the streams whereof do, we are assured, make glad the city of God.

I am intending to send you by this post a valuable work
written by a Friend with whom I am personally acquainted.
Another work has just come out,
[.book-title]#The Society of Friends in the 19th Century,# an interesting historical account.
I am well acquainted with the author.
I have been much engaged since the receipt of your first letter,
or would I expect have written to you again before this.
I think I may say, and without any breach of charity,
that our friends with whom we have been accustomed to go together to worship,
one of whom I think has been your communicant,
do not give us credit for our endeavour to be found walking in the Truth,
or according to Truth`'s leadings,
because of the view they take that we ought to remain with them and help them.

This, in my apprehension, is not watching unto prayer that we may be led by Him,
who in our day, as well as of old time, is the Leader of his people everywhere,
of those that will be gathered by Him, and feed in his pastures of Life: but if I,
or any other do choose for ourselves, where I shall work for Him,
and what shall be the work that I shall do, then I do greatly err,
and am not the Lord`'s servant.
It is not a light thing to come away from those we love;
but "`Him only shall you serve,`" and though this Society be as father or mother to us,
yet our love for Him who has begotten us in the Truth and is greater than it +++[+++the Society],
urges us to obey his call, though it be to forsake all.
You remind me in your letter to us of a dear friend now deceased,
who joined our little company to his great comfort and peace,
not very long before he died.
He clung to his meeting where he had so long been accustomed to go,
but he was given to see that that was his idol and
he must come away and sit down in his cottage.
This was George Hayman: he belonged to Capel Meeting in Surrey.

We feel we have nothing to do with resigning our membership any of us,
inasmuch as we have membership with the Society of Friends of the ancient faith,
holding those precious testimonies also,
as required of us in our day as a part of Truth`'s requirings
of his followers as in the days of our fathers.
London Yearly Meeting has become a seceding body,
and Friends who have not departed with it cannot be said to have membership therewith,
and have therefore nothing to resign.

I may just inform you that I have been up to London twice,
under a weight of exercise to attend some of the meetings for worship,
held during the Yearly Meeting, with the feeling sympathy of my dear friends here.
I attended five sittings, at Devonshire House in the two houses,
Westminster twice and Stoke Newington,--the two last on last First-day.
One of our men friends went first with me and to the two last my dear wife.
I was favoured with ability to relieve my mind and
returned home with the rich reward of peace.
Let us be encouraged to faithfulness.
"`Be faithful unto death and I will give you a crown of life.`"

[.signed-section-closing]
I am your sincere and sympathising friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Peleg Mitchell.

[.signed-section-context-open]
Nantucket, 21st of 7th Month, 1875.

[.salutation]
Dear Friend,

In my last if I remember right, I alluded to the subject of birthright membership.
I have never had any other feeling that I can remember,
but that the introduction of that institution among us was in the ordering of Truth,
adopted by those ancient worthies whose eyes were anointed
by the Spirit to see its adaptation and its usefulness;
and that in a day when there was more of a necessity felt, as I apprehend,
to look inward for direction than has been too much
the case with many in more modern times.

It seems to me the greater our exercise to continue to hold fast to that inwardness
and weight of spirit for which our worthy predecessors were distinguished,
the greater will be our concern that no inroad be made upon the ancient landmarks.
In some instances when it has fallen to me to bestow labour with some young people
in time past who have claimed that they were not members by their consent,
I have felt it right briefly to allude to the foregoing view of its origin,
and that they thus being members in the ordering of Truth,
in that the discipline was adopted under its influence,
there was a great responsibility resting upon them, on that account.
My own experience in my youth was that it was a hedge about me,
and especially so as my dress was even then in a good degree of conformity thereunto,
and how have I craved that this badge of our profession should be closely kept up.
Oh, this looking outward, which has so much prevailed,
how obvious are the sad effects of it in latter time.

I conclude, I hope, in that which changes not,

[.signed-section-signature]
Peleg Mitchell.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. Crisp.

[.signed-section-context-open]
Fritchley, 26th of 7th Month, 1875.

[.salutation]
Dear Friend,

Your letter much interested us,
and your position is one that demands living very close to the Master,
and the ear to be diligently kept open to his voice.
We know that none can teach as He teaches, nor speak as He speaks,
though the enemy we do know can feign resemblances so near and so like his teaching,
that we are only safe when with true fervour and humble
waiting we listen to Him alone and obey his voice,
in the quiet that He commands to and in the waiting soul.
Unity is very precious and counsel flowing from Wisdom`'s book is good indeed,--but
in these times we have especial need to remember for our warning,
how it was with the young prophet who had received the word of the Lord,
and had he obeyed it instead of leaning to the old prophet,
his life would have been spared, would have been continued unto him,
but this failing to do, it was his destruction.

This incident has been brought to my recollection in reading your allusion
to some "`whose shields have been anointed and who counselled to abide
the pressure upon us and let those alone who were violating our principles.`"
Dear M. A. Bayes alludes "`to being inwardly separated from the unfaithful ones.`"
This, I can believe, but it may not be sufficient for the carrying out of His purpose,
to restore Israel to their former dwelling-places.
These, undoubtedly, have been forsaken by this people: and nothing,
nothing but individual faithfulness, to what?--to the Master himself,
can I believe bring back again into Him, the living Vine:
so that we must not lean one upon another (I fully believe you will say with me);
and the language "`Trust not in a friend,`" has to
be verified in the experience of the Lord`'s little,
dependent ones, his sheep and the lambs of his fold,
who know not the voice of the stranger and therefore will not follow him,--and
all such are strangers to those who in any way turn in themselves,
or turn others from the voice of Him who speaks from Heaven.

We are much interested, deeply so, I may say and feel,
in your and the little company`'s position with you--and I believe you
can acknowledge with me that anything you may imagine you can do for them,
to keep them together, and in Him,
if it varies from the teaching in your own mind which comes from Him, so far,
though it might look like the best course to take,
so far their and your own safety will be endangered.
This I feelingly believe you can subscribe to,
and I also believe that when our hearts lean to Him who
is Almighty and the desire is kept alive to follow Him,
who is the Truth and the Way as well as the Life,
we shall be kept as in the hollow of his hand and none of
the hurtful things will be permitted to harm us.

I have written you rather a long letter perhaps with but little worth:
but it is I believe well we should speak one with another,
and I incline to believe we shall have at some time,
perhaps not far distant to meet also.
Whatsoever we do at any time, may it be to the glory of God.
I am pleased with your little note of corrections of error.
How clean is the Truth and Truth`'s orderings and commands to us in our hearts,
that we may bring no reproach thereon! and what is
more cementing than a love for the Truth?
truly Truth is known and felt in all and by all who love Him and obey his dictates.

[.signed-section-closing]
Sincerely your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Peleg Mitchell.

[.signed-section-context-open]
Fritchley, 15th of 8th Month, 1875.

[.salutation]
My Dear Friend,

Your letter of the 21st of last month was received acceptably by me, and we were deeply,
I think I may say, interested in what was communicated.
What an unexpected dismissal from mortality was that of the dear friend
R+++.+++ S. N.! Another instance that we have no continuing city here:
and in these troublesome times are we not to believe
it to be and to receive it as a favour,
that such are gathered home to the celestial habitation of peace and eternal rest.
Let us look on the bright side of this, another summons,
may we not say from earth to heaven.

Many indeed have been the calls from your little company within the last few years!
and seeing the Lord and Maker of all is not dependent upon us for his own work,
may we not look upon this calling away from works to rewards as a token
of his mercy and lovingkindness towards the departed from earth,
and also towards those He is pleased to leave for a little time longer?
For being deprived of those we loved and with whom we walked together in unity,
are we not more closely driven to depend upon Him,
who is the Helper of all who trust in Him?
Yes truly, if the heart is set aright towards God.

There seems to be a shaking among you in New England, as well as elsewhere,
and can we believe that it is not needed?
No! let us hail it as a means of sifting in each one the
chaff-like ingredients of nature from that which is to remain;
for this sifting is not to be only in an outward sense, or always in the outward,
but the dross in our hearts must be cleared away and that
is more than we can do by any outward separation merely;
but He that knows how, can work and who shall hinder it.
I believed and still believe that that among you in New
England which has hindered the blessed Master`'s own work,
in a leaning too much, by some, upon man, though not appearing to them so,
has required a conflict,
and may this be consummated in the true humbling
and the acknowledgment which then must follow,
that the Lord He is God, and there is none like unto Him.
Oh! what sad work it does make when there is a leaning of man upon man in any of us!
How does it draw down the indignation of the Almighty, and frustrate his work!
So that there is not under such bondage,
the liberty in the Truth which Truth gives to all her devoted children.

We have had some conflicts, something to travel through,
but who of the Lord`'s people have not, and if we come off victorious through and by Him,
are we not the better prepared to magnify his hand of power?
Numbers we must not look to, but His power in a few,
may be what we may have to stand by while you and some of us have our time allotted here.

[.signed-section-closing]
With much love I conclude,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Thomas Drewry.

[.signed-section-context-open]
Fritchley, 19th of 8th Month, 1875.

My love please to your uncle +++[+++Samuel Evens, then of Leeds.]
Too great a sign may be, and no doubt is often, looked for,
and that by many--but simple faith to move on (or in) is sometimes needed,
and the only remedy.
I hope he will not miss what was or is designed for him, by seeking after a sign,
or looking for too great things before he makes a decided step in that boldness
of the right and true authority which Truth gives only to the little ones.
It is they that will get the battle or gain the victory,
as their Master works now as formerly He did, by the few;
those who move as blind in themselves, yet eyeing the Captain of their Salvation,
seeing all that is needful for them.
The little captive maid said "`would that my lord were with the prophet that is in Samaria.`"
And he came down from his lordly height--and did as this little maid desired he would do,
and great was the result! the result of becoming little, which all of us must do,
in other words, humble and lowly, stooping to the little thing made manifest,
which will assuredly grow and become in us a great tree, because (or when) it is allowed,
in our humility and feeling lack of all things, to do so.
I believe your uncle has useful talents committed to him, but they must also be given up,
as any that we possess have to be, that they may be sanctified to the good Master,
for his use not our own.

[.signed-section-closing]
Much love to you all,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James D. Otis.

[.signed-section-context-open]
Fritchley, 7th of 2nd Month, 1876.

[.salutation]
My Dear Friend,

Your letter was very acceptable, and on re-perusing it,
it feels to draw us close together in that which
comes from above and has its spring in Divine Love.
I trust we do feel, sympathy with you in your afflictions,
the loss from your midst from time to time of late, of some dear relative or friend.
But how true it is, the great "`I Am`" knows best how to dispose of any of us;
whether it be to gather unto Himself into a place prepared
in one of his many mansions of everlasting bliss,
or to continue awhile under affliction for the Gospel`'s sake,
in this life of trial and probation, thus and by these means preparing and fitting,
by hewing and squaring, stones for the building;--stones which indeed need much labour,
and repeated strokes of the hammer and chisel.

But the Master Builder knows,
in the greatness of his wisdom and understanding which is infinite,
just how much of labour or afflictive dispensation, from his holy hand,
whether immediate or mediate, to bestow or permit to come to pass for this end.
Therefore, my beloved friend, let us hope unto the end,
though it may seem sometimes as if hoping against hope, and our trials be very many.
The crown is at the end of the race,
which is not to the swift of foot but to the sure-footed ones,
to those whose feet are established and their minds stayed upon the Rock, Christ Jesus.

It is a favour to be helped to pass along unhurt, in labours for the good of the cause,
and undoubtedly that dwelling which is in the secret
place of the Most High does thus preserve,
and keeps in the hollow of the Divine Hand,
so that we need not fear the storm which drives heavily about us,
thereby showing to us and making us to feel the necessity to keep inward.
May we each and all of us who are sincerely desirous of keeping with the Master,
watch and strive that nothing may hinder us on our heavenward journey;
and as we journey onward, keeping with Him and with one another, by the way,
we also shall know what it means, the burning of our hearts within us,
as did those of the disciples of old.

[.signed-section-closing]
I remain your friend as ever,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. P. Crisp.

[.signed-section-context-open]
Fritchley, 19th of 2nd Month, 1876.

[.salutation]
Dear Friend,

I do feel a love kindled in my heart towards the
faithful followers of the Shepherd of his sheep.
Love for Him begets true love for one another,
and I might have written sooner since your last,
but for a desire to carry out what I felt would be a pleasant undertaking,
to come and see you and those who meet together on a First-day evening in your house.
However, the right time I have apprehended does not yet appear,
and the future is hid from our view.

I cannot but believe your steadfast sitting down together in another sense
than one (than that of the outward sitting down) must be blessed to you.
O how precious is that lowliness of mind which brings
us to behold the Saviour where He is;
even to sit at his feet, and hear the gracious words which flow forth from his lips,
strengthening and encouraging us to hold on our way,
though thick clouds and dark ones intervene to the obscuring for awhile,
it may be to the dismay of the little ones.
But that there is cause to trust and not to be afraid we are enabled sometimes
to prove in own experience,--that the lifter-up of the head is again with us,
even to the calling forth of a song of praise inwardly,
to the glory of his ever excellent Name.

I hope you will not think I do not value your letter because I make no remark
on some of its details--I can assure you I have felt much interested in them,
and my hope and trust is,
that we may live so near the Fountain of our strength and right
ability to do anything acceptably for our Lord and Master,
as that we may be each one found travelling towards Zion and working for the
Lord according to his good pleasure and where our appointed place is,
in the vineyard of the Lord of hosts, who is the Lord of hosts still.

"`Mind your calling,
brethren,`" is the watchword especially needed in
this our day,--to mind our calling each one.
We serve not a hard Master,
but One who liberally rewards with holy sustenance and strength,
pouring in the oil and wine when it is most needed,--when
without it we should faint by the way and give up the contest.
To keep the eye single, we are assured by Him who now speaks from Heaven,
is the way to have the body full of light--no part dark;--this being our favoured experience,
or when it is so, we need not fear that we shall stumble.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Waring.

[.signed-section-context-open]
Fritchley, 21st of 5th Month, 1876.

[.salutation]
Dear Friend,

With a little salutation of love from a poor friend, yet I trust a brother in the Truth,
I send you our General Meeting`'s Epistle to yours.
A feeling of pure love does, I believe,
go forth to our dear Friends who are separated from us by
the great Atlantic,--truly not separated in the Life,
which flows from vessel to vessel, whether we see one another with the outward eye,
or not.

We had a comfortable meeting, and the company of some individuals who feel near to us.
Whether they will come so near to us as to join eventually,
in membership remains unknown to us; but of this we may be assured,
that if faithful to the precious discoveries of the unchangeable Truth,
the Truth will make them one with us, in Him, we also abiding with Him, the Vine.
I cannot write to you a glowing account of matters with us in these parts:
the Lord sees us as we are, and can deal unto each one,
the "`food convenient`" and necessary for our further refinement.
God sees not as man sees; therefore we must sink into nothingness before Him.
He will be exalted in the earth, and this may be brought about in, by, and through us,
in a way very different from the way we would choose.
What then, is there for poor finite man to do, but to trust in the Lord,
watching unto prayer and waiting patiently for Him,
and his appearance to us in the way that He shall choose?

[.signed-section-closing]
I remain your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 9th of 7th Month, 1876.

[.salutation]
My Dear Friend,

I have not felt more any removal by the stroke of
death in your land than that of dear James D. Otis,
whom I loved for the Truth`'s sake.
A father in the Truth I believe he was,
who desired to follow his heavenly Master in all
his leadings and discoveries of the waymarks thereof.
How many calls away you have had, so that we may query, who will be the next?
These are warnings for us also to be ready.
And dear aged Solomon Lukens whom I well remember, he also is gathered,
and may we not say as a shock of corn fully ripe!

We have been kindly informed of our dear friend and brother Daniel Koll
being about to visit this land again and some parts of the continent,
and Ireland.
I trust the Master will be with him all the way,
and that he may experience as at former times, when in his service, strength to do,
and a manifestation of His holy will in all his movings.
May the Lord be with us and direct to a hair`'s breadth,
that none of us may enter upon that which is not called for at our hands,
as well as to be faithful, obediently faithful,
to all that He is pleased to require of us.

I do desire to hold myself willing and ready as the Lord may direct at any time,
but I also believe that if called to any service for Him, away from home,
that He will enable to put my house in order and to leave all in his hands,
who does at all times well.
It is indeed a favour to know at any time that He cares for us,
and takes our cares into his own hand by giving ability to cast all upon Him.

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 3rd of 9th Month, 1876.

[.salutation]
My Dear Friend,

I feel that something is due to you,
by way of information respecting our and your dear friends,
who are over here from your shores.
Daniel Koll and Caleb B. Cope are now in Ireland,
accompanied by Thomas Drewry who met them at Belfast,
after we had parted with them at Kilmarnock in Scotland to return to our home;
Mary J. Koll accompanying us, not feeling it was required of her to cross to Ireland.

I may inform you with thankfulness that way was made remarkably for us,
and Truth prevailed in the minds of some in our journey into Scotland,
where Daniel felt drawn to attend the General Meeting
held at Aberdeen on the 21st of last month.
I had no expectation of being at liberty to go into Scotland,
my business demanding a journey from home.
However, in a remarkable manner my leaving home on that account was overruled.

At Aberdeen, Truth had dominion,
though there were those who withstood and prevented that
full openness in every respect that could be desired;
nevertheless we did not look for the way being made as it was,
and it was very extraordinary that no public "`Friends`"
of the "`larger Body`" were there as is usually the case,
this was quite an exception;
so there was more room in every sense of the word for our little company,
and Daniel was much favoured among them in meetings,
two on First-day and the one preceding that for business on Second-day morning,
as well as helped in a call or two socially while in the town.
Some young men and others quite drew towards us in
a manifestation of their unity with us;
but a contrary spirit we fear did at Glasgow in some
degree have place in the minds of some,
through (probably) evil report, such as our "`separating from the Society.`"
But the Master makes way for his people and we must not look for great things.
There is cause nevertheless on our part to be very
thankful and we left with peaceful minds.

From Aberdeen we went to Dundee.
We next proceeded to Dalguise.
A public meeting was held at Dunkeld, +++[+++in Perthshire]; not a large meeting,
but we may trust and hope that good may come of it.
Our next stop was at Glasgow where we spent First-day the
28th and attended their morning and evening meetings.
We were very kindly received there and entertained at two Friends`'
houses William and Margaret Smeal`'s and James and Margaret M`'Nish`'s.
W+++.+++ Smeal is very infirm and does not often get out to meeting;
much openness was felt by our dear friends there.

We have had a comforting account of dear D. K.`'s labours and their
reception in Belfast by Forster Green +++[+++who accompanied them to]
Ballinderry meeting to which Jacob Green belonged,
also to Hillsboro`' where William Green lives.
It is remarkable how way has opened for them so far in Ireland in the hearts of some,
and we may trust this will continue to be as faithfulness
is abode in and the Lord alone is exalted where they go.

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
John.
G+++.+++ Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Charlbury, 9th of 6th Month, 1877.

[.salutation]
My Dear Friend,

What a sorrowful state the "`larger body,`" as a body is in.
They, the active ones therein,
are going further and further from the principles of our profession,--the
leadings of Truth believed in by us as a people.
It does appear as if all must go:
nevertheless the great Husbandman can gather out from among them,
disciples to follow Him as of old and there may yet be among them
such as have "`not bowed the knee to Baal nor kissed his image.`"
We may, I believe, hope this is the case, though few be the indications to us.

Some of the greatest opponents to our views of the simplicity
which Truth requires and the holding up of our acknowledged
testimonies thereunto seem to be from your side the Atlantic,
who are ever active in knocking them down and introducing new things
(or the old which have been come out of) among this people.
Happy for those who escape the snare,
but the leaven seems spread from the head to the foot,
that there seems no hope if we judge thereby.

How many have been removed from among you!
Their loss to the gathered Church upon earth feels to be great;
but the good Master knows what He is doing.
It is not for us to judge, but it would appear as if the stripping would bring low indeed.
There is the greater call for faithfulness on the part of those who remain,
and the Lord can gather by the few as well as show forth his marvellous works by them.
He has a purpose in the earth, and if He is glorified and exalted therein,
what is this to us,
though we do mourn that so few come to our solemn
feasts and we would that all should be gathered.
It is a time of dearth, yet the Lord is known in the earth,
and in the earthen vessels who seek Him with the whole soul and
are not satisfied with anything short of his pure leadings,
wherein they know Him and his holy will concerning them.
So then we may and do rejoice at times under his banner which we feel to be that of love,
his love who begat us by the visitations of his love and mercy to us.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To +++_______+++ +++_______+++.

[.signed-section-context-open]
Belfast, 1st of 7th Month, 1877.

[.salutation]
Dear Friend,

Since we met in the train last Fourth-day my mind
has turned towards you with solicitude on your account,
and as you told me you had been recorded a minister, on the account also of others.
Do, dear friend, peruse the two publications I enclose for your acceptance,
with your mind turned deeply inward,
that you may rightly understand and be benefitted thereby; for in them both, there is,
I believe, something you stand in need of,--the food convenient.

It is, I believe, a great mistake, recording those who speak,
and those who kneel in meetings, so soon as is oftentimes done; before they are enough,
or truly baptized by the Spirit for the work,
and I believe it to be a very great mistake for individuals
to take upon themselves to set others to work.
This subject we spoke somewhat upon when we were together.
What is needed in the meetings for worship of this day, is more indwelling,
and love for silence, on the part, I believe, of most who speak,
and of most of those who are silent.
What is to be compared to the presence of the Master!
And words when they are given as prayers or preaching,
if they are not in the Life (and to be so they must emanate from the Life) are disturbers,
and do not build up.
On the contrary, they lay waste and hurt a meeting when the Life has arisen therein.

What I have written is sent in love.

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Daughters.

[.signed-section-context-open]
Fritchley, 29th of 7th Month, 1877.

[.salutation]
My Beloved Daughter,

I hope you will not think any that do not write to you do not think of you,
in your absence personally from us.
Such is not the case; I have not written but my mind is often, I hope I may say,
with you as well as that of those who salute you with a letter.
We have today +++_______+++ and +++_______+++ with us, they are very affectionate and cordial,
but would that they were more likeminded with us in bearing
testimony in some things they do not.

I am thinking while writing that the nearer we are to the Master,
the more we must find ourselves assimilating in those things, which, as a people,
it has been found of old there must be a walking in,
whereby we are known to those outside as well as within our borders,
to be one and a peculiar people, zealous of good works, those works which are good,
as emanating from the one Law and Lawgiver who testifies to man what is in man,
and how we must forsake all and be followers of Him!
And does He call that one people, by His pure Law in their hearts,
to go so far opposite in their allegiance to Him,
as for the one to deny (by their lives) that to be a testimony for the Truth,
which the other feels His Law in them requires them to conform to?
I believe not!

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
John G. Sargent.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Hodgson.

[.signed-section-context-open]
Fritchley, 6th of 11th Month, 1877.

[.salutation]
My Dear Friend,

You query about Ireland.
I often find great openness where I go, both there, on the Continent and in this country,
to receive what opens on my mind in discourse,
and opportunities are afforded of true refreshment mutually I believe,
and the heart is made glad, more so than with corn,
wine or oil (as we read) in a sense of the goodness and
lovingkindness of Him who opens and none can shut,
and shuts and none can open.
Now and then I feel it right for me to go into other meetings,
some of the "`larger body,`" and the penny is given to me.
But on these occasions it is not in any feeling of bitterness towards any, but in love,
as to the children of the same great Parent; When this call to go among them is heard,
I believe it is good to obey;
but the time has not seemed come when we are required to do much or to conform to much,
as a body, but each one to be faithful in and to our callings, I believe.

It feels that it will be a favour to get well to the end of the race,
which truly is not to the swift of foot,
nor the battle to the strong who are in their own strength,
warring to do something and know not what it is to become so weak as to be made
strong in the strength of Him who is the great Captain of our salvation,
and leads forth his little ones who know no strength but his, that they can war with.
Now my dear friend and elder brother, farewell in the Truth and in the Life,
which I believe is very dear to you.
And may all of yours also inherit the blessings of heavenly goodness and mercy and Truth.

[.signed-section-signature]
J+++.+++ G. S.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Priscilla Pitt.

[.signed-section-context-open]
Fritchley, 4th of 12th Month, 1877.

[.salutation]
My Dear Friend,

Although I have not written to you since the departure
of your dearly loved parent to her everlasting rest,
as it may be consolingly believed, yet I have not been forgetful of the solemn event,
and in this we may rejoice,
while on the other hand to lose from our midst one who feared God and eschewed evil,
and who completed for a long time past the comfortable family circle,
leaves a great blank, more perhaps to be realised now than at the time it took place.

We can hardly, I apprehend, appreciate fully the blessing there is,
in having to believe without a doubt that a dear one is gathered home,
no more to buffet with the waves of time, which do sometimes sorely cast down.
So then there is a bright side; all is not dark.
I trust you, your dear G. and self, do feel this,
and whatever was worthy in her example to follow,
it may rest as a concern for you to follow; for, of a truth, she and your beloved father,
were patterns of no common kind,
and I believe (and can believe no otherwise) they were made so
by Him who frames and fashions us and all to his own design,
if we will be subject.

This, then, is the work for us, to subject our wills to his will,
that we may be well pleasing unto Him.
Then may we move along and wear a smile upon our faces,
a smile of heavenly-mindedness which is truth and in it there is no alloy,
because the alloy is of this world.
While writing,
I am thinking of our worthy forefathers in the blessed
Truth who trod the way before any of us.
They were valiant for the Truth upon earth,
and could wear no other armour than that which they had proved, like David, who,
though he essayed to go forth in Saul`'s armour, yet he found this would not do,
and by keeping to that which he had proved before,
he was enabled to go forth in the name of the Lord, who was with him.
But of this we may be assured that if we are fervent in spirit serving the Lord,
we shall reap the reward, through Him who died for us,
and ever lives and makes intercession for us.

[.signed-section-closing]
Your and your sincerely affectionate friend,

[.signed-section-signature]
John G. Sargent.

--
